### ISSUE TITLE
Course builder: On lesson creation, if the server timeouts you might end up having N duplicates of the lesson.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1003]
I don't have standard reproduction steps for this, I can force this, so...

+ force a timeout after a lesson is created, but before any response is returned to the ajax call, e.g. adding a php delay (`sleep`) here:
https://github.com/gocodebox/lifterlms/blob/3.37.4/includes/admin/class.llms.admin.builder.php#L911
(of course the delay must be so that the server timeouts :P so it depends on your server settings)
+ go in the course builder and create a lesson
+ click on Save changes, and wait for a response
+ after a bunch of time (server timeouts settings) you'll see this error popping out in the course builder, while the Saving changes spinner continues to spin:
![Schermata 2019-12-06 alle 20 27 02](https://user-images.githubusercontent.com/7689242/70350347-e40cdb00-1866-11ea-9ae6-2cab3420e61c.png)

As long as you stay with the course builder open new lessons will be created in the background: the number of the lessons created, I guess, is a function of the heartbeat time, the server timeout settings and the time you stay with the course builder open.

(Of course the timeout might even happen before the lesson is created, or after the lesson is created but before its post metas are set, but in that case there's not that much we can do... I think)

### System Information

LifterLMS 3.37.4

### Browser, Device, and Operating System Information

n/a

reported on HS-105610

**Comment by thomasplevy** [comment]
If an error of any kind is received should kill the autosave mechanism, prevent saving from being attempted manually, and pop a notice informing the user they should reload the page to continue

we could possibly also store the current course outline data in local storage and make a comparison on reload to see what was actually saved (and what was only locally saved) and provide an option to restore the difference so no work is lost.

**Comment by brianhogg** [comment]
We've changed this to not be on auto-save by default.
