### ISSUE TITLE
Warning: Invalid argument llms.functions.notice.php on line 107

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1005]
**This issue has been reported on wp.org:**
https://wordpress.org/support/topic/invalid-argument-llms-functions-notice-php-on-line-107/
and on hs # 107502

### Reproduction Steps

+ make sure you have the debug enabled
+ make sure one of your courses has a **Sales Page Content** option set to **Redirect to WordPress Page** and a redirection page set 
+ as "visitor" (also make sure you have cleaned your cookies: __wp_session_) directly visit the course of the previous bullet.

### Expected Behavior

+ I would expect to be redirected without any PHP warning

### Actual Behavior

+ I see a PHP warning in my logs

### Error Messages / Logs

```
PHP Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/functions/llms.functions.notice.php on line 107
```

### System Information

LifterLMS 3.37.6
WordPress 5.3.1
PHP 7.3

### Browser, Device, and Operating System Information

n/a

### Considerations
This issue has been recently introduced: https://github.com/gocodebox/lifterlms/commit/3d1a8cc80c5d002a077c46c57040dca6b4b85e1b
part of https://github.com/gocodebox/lifterlms/pull/984
But the real issue is here:
https://github.com/gocodebox/lifterlms/blob/3.37.6/includes/functions/llms.functions.notice.php#L99

As you can see the `LLMS_Session::get($key)` has no "default value" parameter:
https://github.com/gocodebox/lifterlms/blob/3.37.6/includes/class.llms.session.php#L110

so `$all_notices` retrieved as follow:
`$all_notices = LLMS()->session->get( 'llms_notices', array() );`
if `llms_notices` key doesn't exist, it will be `false` and not `array()`, hence generating the warning above.

Since there are several lines in llms.functions.notice.php assuming this default value param exists, I think we can add it as optional parameter to the `LLMS_Session::get()` method signature, and it'll be `false` by default.

In the wp.org ticket case, though, the issue becomes more "importante" because of the server settings:
1) PHP set to not use the output buffering (e.g. `output_buffering = Off`) => this can generate the headers already sent issue if you output something before http headers are sent.
2) PHP (or WordPress) set to display the errors/warnings => this will display the warning above in the page, before the http headers are sent (because of when the warning is generated), hence generating the headers already sent issue because of 1.

**Comment by eri-trabiccolo** [comment]
Also reported in another hs ticket: # 107394

**Comment by thomasplevy** [comment]
@eri-trabiccolo this dropped off my radar, sorry. I'll include and build a release tomorrow.
