### ISSUE TITLE
PHP 7.4 compatibility: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/abstracts/abstract.llms.admin.table.php on line 526

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1008]
### Reproduction Steps

+ Edit a course, for instance

### Expected Behavior

+  no php warning

### Actual Behavior

+ got php deprecation warning

### Error Messages / Logs

[17-Dec-2019 17:24:08 UTC] PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/abstracts/abstract.llms.admin.table.php on line 526

### System Information
LifterLMS 3.37.6
WP 5.3.1
PHP 7.4

### Browser, Device, and Operating System Information

n/a

From a rapid search that seems to be the only one place where the swap occurs.

**Comment by thomasplevy** [comment]
Probably just a transposition typo, easy enough fix.
