### ISSUE TITLE
Restrict site by membership level, redirect to a WordPress page produces infinite loop

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1023]
### Reproduction Steps

1. Create a Membership
2. on the Restrictions tab select Redirect to a "WordPress page" for Restricted Access Redirect
3. Select a WordPress page
4. leave the other settings as they are by default (Display a Message and Restricted Content Notice)
5. navigate through your dashboard -> LifterLMS (Settings) -> Membership
6. as Restrict site by membership level search and set the just created membership
7. save
9. as visitor, in front, navigate to whatever singular except the Membership created above (which is excluded by this restriction) and the selected WordPress page (which should be excluded as well)

### Expected Behavior

+ I would expect to be redirected to the selected WordPress page and see its content.

### Actual Behavior

+ I'm redirected to the selected WordPress page, which is still restricted, and then produces another redirect to itself and so on...

### Error Messages / Logs

n/a

### System Information

LifterLMS 3.37.9
WordPress 3.5.3

### Browser, Device, and Operating System Information

n/a

WIP: https://github.com/eri-trabiccolo/lifterlms/tree/membership-redirection
needs (unit) tests

**Comment by thomasplevy** [comment]
WIP looks pretty good.

While you're there -- unrelated -- the privacy policy page should be whitelisted too.
