### ISSUE TITLE
bbpress forum is cleared out of course when quick edit is used

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1034]
### Reproduction Steps

Inside editing a course, add a bbPress forum and save

view COURSES list. 

Click "Quick Edit" and check a box next to another Category, then click Update.

When you go back into the course and select the bbPress tab. The forum previously saved is now gone.

### Expected Behavior

Quick edit should not affect saved bbPress forums inside courses.

### Actual Behavior

Using quick edit unsets the forum. 

HS-107288

**Comment by thomasplevy** [comment]
@nrherron92 fixed in 3.37.11, please update related HS tickets. Thanks
