### ISSUE TITLE
Conditionally Hide Menu Pages Based on Membership

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1035]
**Describe the solution you'd like**
It would be great to hide specific pages in menu depends on your memberships level. Something similar to the menu conditional plugin where you can set what menu items are seen based on loggedin/logged out status. Or I'm pretty sure the WP Fusion integration does this but he's looking for something in the default when building menus.

HS-113004

**Comment by thomasplevy** [comment]
This feature request has been moved to the feature request system.
