### ISSUE TITLE
WooCommerce causing LifterLMS password reset looping

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1037]
### Reproduction Steps

Turn on LifterLMS and WooCommerce.
Do not install or turn on LifterLMS WooCommerce integration.
Set LifterLMS Dashboard to its own dashboard page.
Set WooCommerce my account to its own my account page.
From the logged out LifterLMS Dashboard click password reset and run through the process.
With WooCommerce active, even with no crossing of my account page/dashboard settings or shortcodes LifterLMS password reset loops back to the original password input page.

### Expected Behavior

LifterLMS password reset should operate as expected.

### Actual Behavior

It loops back to the input email page instead of going to the new password input page.

### System Information

LifterLMS
WooCommerce

HS-111422

**Comment by eri-trabiccolo** [comment]
This doesn't occur in https://github.com/gocodebox/lifterlms/tree/3.38.0 (while still occurs with #1092 applied).

**Comment by thomasplevy** [comment]
I was not trying to fix this in #1092

**Comment by eri-trabiccolo** [comment]
@thomasplevy Yeah I know, was just a note for me, sorry <3
