### ISSUE TITLE
Quotes encoded in some engagement's emaill inputs (text) 

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1038]
### Reproduction Steps

+ In Engagements -> Emails add a new Email
+ Add a string with some quotes as Email Subject and as Email Heading
+ Trigger an engagement

### Expected Behavior

+ The email Subject and Heading text should show the quotes

### Actual Behavior

+ The email Subject and Heading text show the encoded (single) quotes: `&#39;`: the option value is encoded before saving and displayed/used as it is.

### Error Messages / Logs

n/a

### System Information

LifterLMS 3.37.11

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-104612

This issue has been, most likely, introduced in version 3.37.0, and it's similar to:
https://github.com/gocodebox/lifterlms/issues/967

We could follow a similar approach, or, we can just keep the sanitization before inserting the value in the DB as it is - so with the quotes encoded - but then decode it before using, exactly like we do with the engagement's `email_from_name` here:
https://github.com/gocodebox/lifterlms/blob/3.37.11/includes/emails/class.llms.email.php#L371

**Comment by thomasplevy** [comment]
@eri-trabiccolo thanks

Do you have time to write up a PR?

**Comment by eri-trabiccolo** [comment]
Sure!

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Look that also the:
- Achievement title
- Achievement content (this is a textarea actually...)
- Certificate title

are now sanitized with the `FILTER_SANITIZE_STRING` (with no specific flags) before saving.
Even if they don't produce any visual issue as these values are displayed in "html contexts", I think we should ask ourselves how do we want these data to be saved once for all :D

I'm not going to touch them for now, but let me know and I'll integrate the PR.

**Comment by thomasplevy** [comment]
See my note on #1040

**Comment by thomasplevy** [comment]
@eri-trabiccolo included in 3.37.12
