### ISSUE TITLE
PHP Notice when entering Appearance -> Menus IF a student dashboard endpoint has been cleared

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1041]
### Reproduction Steps

from your wp dashboard
+ go to LifterLMS -> Settings -> Accounts
+ clear the **View Achievements** endpoint
+ save 
+ navigate to Appearance -> Menus

### Expected Behavior

+ Nothing weird

### Actual Behavior

+ PHP Notice

### Error Messages / Logs

```
[03-Mar-2020 19:51:23 UTC] PHP Notice:  Undefined index: url in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/class.llms.nav.menus.php on line 157
```

### System Information

LifterLMS 3.37.11

### Browser, Device, and Operating System Information

n/a

### Related User Information

HS-104008

**Comment by thomasplevy** [comment]
@eri-trabiccolo fixed in 3.37.12
