### ISSUE TITLE
Revisions in Gutenberg within Lifter lessons

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1043]
**Describe the solution you'd like**
In the Gutenberg editor for posts and pages there is a setting you can click to see revisions added to the post or page. The customer would like for this to also be accessible in LifterLMS lessons and courses.

HS-113325

**Comment by thomasplevy** [comment]
Courses, lessons, and memberships should all support revisions. I'm not sure why they don't. It may be an oversight dating back to the initial release of LifterLMS which no one has noticed / asked about before.

**Comment by thomasplevy** [comment]
@nrherron92 released in 3.37.12
