### ISSUE TITLE
Payment "integrations" chaotic simulation tests failing on CI (but rarely locally)

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1053]
These "Chaos" tests are built on random numbers. This is likely a big mistake to add randomization to a test but it maybe kind of worked to help us randomly encounter weird niche scenarios where our schedulers are failing.

In any event this is a list of failing tests collected in a single place to help us figure out the common links between the failures and then we can use that to find the issue in the code and fix the bugs (if this is a bug in the code and not in the tests):

https://app.circleci.com/jobs/github/gocodebox/lifterlms/3713
https://app.circleci.com/jobs/github/gocodebox/lifterlms/3710
https://app.circleci.com/jobs/github/gocodebox/lifterlms/3714

https://app.circleci.com/jobs/github/gocodebox/lifterlms/3733

https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1012/workflows/96ea3aa0-fb5a-4c2f-bc48-f32ab52689fa/jobs/3777
https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1012/workflows/96ea3aa0-fb5a-4c2f-bc48-f32ab52689fa/jobs/3777

https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1017/workflows/8513bbb8-e87d-489a-a6fc-857ea349df79/jobs/3817
https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1017/workflows/8513bbb8-e87d-489a-a6fc-857ea349df79/jobs/3819

https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1021/workflows/a20ce800-2523-48c6-b2ad-586398814ada/jobs/3844
https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1021/workflows/a20ce800-2523-48c6-b2ad-586398814ada/jobs/3845

https://app.circleci.com/pipelines/github/gocodebox/lifterlms/1039/workflows/53e5ee13-996d-4b98-8415-2431e9d69b81/jobs/3965

Local:

```
1) LLMS_Test_Payment_Gateway_Integrations::test_recurring_lifecycle_for_month_plan_with_chaos
Month Payment #96: Got 2028-03-02 23:58:08 and expected 2028-03-01 03:20:29 ( $chaos_hours = 12 | $chaos = 12141 )
Failed asserting that 1835654288 matches expected 1835493629.
```

```
1) LLMS_Test_Payment_Gateway_Integrations::test_recurring_lifecycle_for_year_plan_with_chaos
Year Payment #68: Got 2088-02-28 23:33:17 and expected 2088-03-01 03:02:27 ( $chaos_hours = 12 | $chaos = 12550 )
Failed asserting that 3728849597 matches expected 3728948547.
```

**Comment by eri-trabiccolo** [comment]
Thomas found it to be due to something actually expected with `strtotime( +n months )` because months haven't the same number of days.
We've found this is not critical so we decided to only accommodate the tests in the commit below:
https://github.com/gocodebox/lifterlms/commit/4e245fc0986f7ebe3366ee4220a171ae15f1129b

**Comment by pondermatic** [comment]
### Steps to Reproduce

1. Apply the following changes to `tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php`.
    ```diff
	diff --git a/tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php b/tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php
	index 2f681c24d..35d8605c8 100644
	--- a/tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php
	+++ b/tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php
	@@ -166,7 +166,7 @@ class LLMS_Test_Payment_Gateway_Integrations extends LLMS_UnitTestCase {
	                        $next_payment_time = $order->get_date( 'date_next_payment', 'U' );
	
	                        // Run the recurring payment randomly between 12 hours before and 12 hours after the scheduled payment time.
	-                       $chaos = rand( 0, HOUR_IN_SECONDS * $chaos_hours ) * ( rand( 0, 1 ) ? -1 : 1 );
	+                       $chaos = HOUR_IN_SECONDS * ( $i - $chaos_hours - 2 );
	
	                        // Time travel.
	                        llms_mock_current_time( $next_payment_time + $chaos );
	@@ -463,6 +463,7 @@ class LLMS_Test_Payment_Gateway_Integrations extends LLMS_UnitTestCase {
	         */
	        public function test_recurring_lifecycle_for_month_plan_with_chaos() {
	
	+               llms_tests_mock_current_time( "2023-07-01" );
	                $order = $this->setup_order( 'month' );
	
	                // Reinitialize the order for assertions.
    ```
1. Apply the following changes to `includes/models/model.llms.order.php`.
    ```diff
	diff --git a/includes/models/model.llms.order.php b/includes/models/model.llms.order.php
	index c1982382d..dd2818910 100644
	--- a/includes/models/model.llms.order.php
	+++ b/includes/models/model.llms.order.php
	@@ -663,6 +663,7 @@ class LLMS_Order extends LLMS_Post_Model {
	                                'ping_status'    => 'closed',
	                                'post_author'    => 1,
	                                'post_content'   => '',
	+                               'post_date'      => llms_current_time( 'mysql' ),
	                                'post_excerpt'   => '',
	                                'post_password'  => uniqid( 'order_' ),
	                                'post_status'    => 'llms-' . apply_filters( 'llms_default_order_status', 'pending' ),
    ```

## Result

`Month Payment #21: Got 2025-03-28 18:00:00 and expected 2025-04-01 01:00:00 ( $chaos_hours = 12 | $chaos = 25200 )`

**Comment by pondermatic** [comment]
[`LLMS_Test_Payment_Gateway_Integrations->do_n_charges_for_order`](https://github.com/gocodebox/lifterlms/blob/dev/tests/phpunit/unit-tests/class-llms-test-payment-gateway-integrations.php#L189) expects that that the next payment time is always based on the last transaction time. However, [`LLMS_Order->calculate_next_payment_date()`](https://github.com/gocodebox/lifterlms/blob/dev/includes/models/model.llms.order.php#L281) can base the next payment time on the previous payment time **or** the last transaction time.
