### ISSUE TITLE
Nginx Helper 

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1073]
### Reproduction Steps

Make sure the Nginx Helper plugin is installed.
Try to add a lesson to a section.
The save button rolls for a while and brings the error "1. Undefined(0 Timeout)"

### Expected Behavior

Should work as appriopriate

### Actual Behavior

The save button rolls for a while and brings the error "1. Undefined(0 Timeout)"

### Error Messages / Logs

+ Include any relevant error messages or log files

![lifterlms-course-builder-error](https://user-images.githubusercontent.com/62220599/77662198-d85f3480-6f7b-11ea-9910-29a19ad6f10a.png)

### System Information

<details>
<summary>System Report</summary>
  
```
<!-- Paste your System Report below this line -->

```

</details>

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

HS-114483

**Comment by thomasplevy** [comment]
While I can recreate this issue after about 45 minutes of debugging I cannot figure out why this is happening. I don't know if this is something that we'll be able to fix from within LifterLMS.

**Comment by thomasplevy** [comment]
It appears that what's happening is that PHP is timing out as a result of the cache purging performed by the plugin

**Comment by thomasplevy** [comment]
@toyinogunseinde I've opened an issue on the nginx-helper GitHub. Could you please direct the customer to this issue over there and ask if they'd consider reaching out directly to the developers of the plugin for assistance. After a review I'm really not sure what LifterLMS can do here to fix this. We could probably solve it with some custom code.

A "workaround" I could propose would be to disable automatic purging in the plugin settings and then manually clearing the cache. This would enable the plugin to still be used without affecting LifterLMS. It's not idea but it's the best I can come up with.

**Comment by thomasplevy** [comment]
@toyinogunseinde we're checking back in on this issue and the issue I opened on their GitHub has had no movement on it. Is this ticket still open? Has the customer had any success reaching out to the developers?

**Comment by toyinogunseinde** [comment]
@thomasplevy The ticket is closed but I've got another customer with the same issue as well. HS-116652

**Comment by thomasplevy** [comment]
@toyinogunseinde please have the customer's reach out to the developers of the nginx plugin directly. This isn't something that we're going to be able to fix but I'd like to leave the issue open for now

**Comment by thomasplevy** [comment]
Closing as unfixable -- all attempts to communicate with the plugin developers have been unsuccessful.
