### ISSUE TITLE
Student Dashboard Notifications endpoint displaying email preferences instead of notifications

### ISSUE THREAD

**Issue by vertika1** [gocodebox/lifterlms#1075]
After upgrading to 3.37.15, the student dashboard notifications endpoint is displaying email preferences instead of notifications.

<img width="685" alt="Capture" src="https://user-images.githubusercontent.com/62865899/78060645-8179a680-7351-11ea-9379-42e2600f2786.PNG">

I believe it is due to these lines, specifically 693:
https://github.com/gocodebox/lifterlms/blob/29a23f074b2a79f4af02b3c3d4de29485bc68a50/includes/functions/llms.functions.templates.dashboard.php#L691-L693

The condition is comparing `$view` against the literal string `'views'` when it should be checking for `'view'` (without the 's')

### System Information

+ WP 5.3.2
+ LifterLMS 3.37.15

**Comment by eri-trabiccolo** [comment]
Thanks @vertika1 yeah that `s` it's a typo indeed!
