### ISSUE TITLE
Emails Not Sending After Failed Email for Deleted Course

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1088]
HS-116009

It looks like there's a notification that was sent for a course that's been deleted so the notification is failing to send and there's like 30 notifications in the queue with no new notifications being sent.

Any emails related to LifterLMS Courses/Memberships/Purchases do not seem to send though a password email reset has sent and a notice of manual enrollment has been sent.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I haven't had time to look into this, can you have a closer look if you have some time.

I thought I had some way to recreate it but it didn't work

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Short answer: I will.
Long:
I actually tried to reproduce this issue, but with no luck. I need to take another look into this, I wonder if there's something else blocking... and what is actually blocked: the email sending or the scheduled process (in this case other processes could be as well).

**Comment by thomasplevy** [comment]
https://github.com/gocodebox/lifterlms-assignments/pull/35/files

**Comment by thomasplevy** [comment]
@eri-trabiccolo did some detective work and found that this is happening as a result of a "notification" post type in the user's database (so a plugin conflict) coupled with a bug in the LifterLMS Assignments plugin causing the `LLMS_Notification` class to attempt to be constructed via `llms_get_post()`

This particular issue will actually be resolved by several updates from both the core and the assignments add-on
