### ISSUE TITLE
Access plan Checkout Redirect to Custom URL fails

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1095]
### Reproduction Steps

Create an access plan on a course.
Change checkout redirect to Custom URL and put the URL
When checking out, it takes you to thedomain.com/wp-admin

### Expected Behavior

Meant to redirect to the specified URL

### Actual Behavior

Redirects to thedomain.com/wp-admin

HS-117227

**Comment by thomasplevy** [comment]
@toyinogunseinde looks like the issue is actually a regression introduced in version 3.34.0 and occurs only when redirecting to a domain other than than the current site's domain.

PR #1101 should get merged in and released in next 48 hours
