### ISSUE TITLE
Change the currency in sales reporting tab

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1096]
### Reproduction Steps
Change your currency to something else apart from Dollars
Go to Reporting >> Sales
It still stays at Dollars
![image](https://user-images.githubusercontent.com/62220599/79052754-8fbca200-7c30-11ea-95e2-2e7b3ff2db1c.png)

### Expected Behavior
Supposed to change the currency to the currency in settings

### Actual Behavior

Still remains at Dollars

**Comment by thomasplevy** [comment]
Duplicated reported in #1372 (HS-137401)
