### ISSUE TITLE
Reporting is not captured for mobile users

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1103]
### Reproduction Steps
Enroll for a course on your phone.
Watch the first few lessons.
Check reporting tab on LifterLMS

### Expected Behavior

Either Desktop or mobile, it should record the progress of the student

### Actual Behavior

Not recording progress from mobile. Only records via desktop/laptop

HS-117743

**Comment by eri-trabiccolo** [comment]
@toyinogunseinde 
what do you mean with "watch the first few..."?
I guess, "complete the first few lessons". Right?

Also, is it something you've been able to reproduce?

**Comment by toyinogunseinde** [comment]
@eri-trabiccolo Yes, I meant complete few lessons.
I was able to reproduce this on my test site and I found same issue

**Comment by eri-trabiccolo** [comment]
thanks @toyinogunseinde ! <3

**Comment by eri-trabiccolo** [comment]
@toyinogunseinde I'm not able to reproduce this.
Have you already cleaned the Student Progress Cache under Status -> Tools ?

**Comment by toyinogunseinde** [comment]
@eri-trabiccolo That was the issue. Thanks a lot!! :)
