### ISSUE TITLE
User registration for user with apostrophe in email results in 403 Forbidden Error

### ISSUE THREAD

**Issue by ericnicolaas** [gocodebox/lifterlms#1104]
### Reproduction Steps

1. In WordPress dashboard, go to Users > Add New. 
2. Add anything for the username.
3. Make the email address something with an apostrophe in the local-part. i.e. `eric's@test.dev`
4. Submit user.

### Expected Behavior

The user should be created normally.

### Actual Behavior

You get a 403 Forbidden Error if LifterLMS is enabled; with core WP, it works as expected. 

Likely related to https://github.com/gocodebox/lifterlms/issues/591

**Comment by thomasplevy** [comment]
@ericnicolaas I'm not seeing this issue, that doesn't necessarily mean it's not a legitimate issue but we're going to need some more information from you to move forward.

Could you please confirm this happens with only LifterLMS and a default theme (say twentytwenty) installed (and no other plugins).

Could you also post a copy of your LifterLMS System Report for us to have a look at


Thanks

**Comment by thomasplevy** [comment]
@eri-trabiccolo when you have a free moment can you attempt recreation steps and let me know if you're seeing this issue or not.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
cannot reproduce either mmm

**Comment by thomasplevy** [comment]
@ericnicolaas please let us know if you can provide the additional information requested above and we'll reopen.

**Comment by ericnicolaas** [comment]
My apologies — I've since tested this on a blank install with just Lifter and it works there, so must be something else in our environment causing the issue.

**Comment by thomasplevy** [comment]
@ericnicolaas glad to hear you figured it out
