### ISSUE TITLE
The course page of one course displays other course information

### ISSUE THREAD

**Issue by wpp-github** [gocodebox/lifterlms#1114]
In a course page, when the mouse continues to slide, the page information of other courses will be loaded automatically. How to solve this problem

**Comment by thomasplevy** [comment]
@wpp-github 

The information in the issue template is absent from your issue, could you please edit your issue and add the requested information from the template 

Posting a video of your issue would help a lot. I'm note sure what you're describing here.

**Comment by wpp-github** [comment]
http://47.96.7.125/index.php/test-0416-page/
If you enter the details page of a course，for example http://47.96.7.125/index.php/course/face-rec/, not only the course information will be displayed, but also the information of other courses will appear when the mouse continues to scroll
