### ISSUE TITLE
Fatal when downloading a certificate if mbstring PHP module not installed/enabled

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1118]
The mbstring PHP module is optional, so I think we need a fall back. 

### Reproduction Steps

+ On a server where the mbstring PHP module is not installed/enabled download/save a certificate
+ Check the error log

### Expected Behavior

+ I expect to download the certificate without any issues

### Actual Behavior

+ Cannot download the certificate

### Error Messages / Logs

```
Fatal error: Uncaught Error: Call to undefined function mb_convert_encoding() in /home/***/public_html/wp-content/plugins/lifterlms/includes/class.llms.certificates.php:228 Stack trace: #0 /home/***/public_html/wp-content/plugins/lifterlms/includes/class.llms.certificates.php(188): LLMS_Certificates->modify_dom(‘<!DOCTYPE html>…’) #1 /home/***/public_html/wp-content/plugins/lifterlms/includes/class.llms.certificates.php(105): LLMS_Certificates->get_export_html(‘2064’) #2 /home/***/public_html/wp-content/plugins/lifterlms/includes/class.llms.certificates.php(161): LLMS_Certificates->generate_export(‘/home/***/…’, ‘2064’) #3 /home/***/public_html/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.certificates.php(149): LLMS_Certificates->get_export(‘2064’) #4 /home/***/public_html/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.certificates.php(111): LLMS_Controller_Certificates->download(‘2064’) #5 /home/***/public_html/wp-includes/cla in /home/***/public_html/wp-content/plugins/lifterlms/includes/class.llms.certificates.php on line 228
```

### System Information
(redacted)
<details>
<summary>System Report</summary>
  
```
WordPress
-------------------------------------------

Home Url: https://---.com.au
Site Url: https://---.com.au
Login Url: https://---.com.au/wp-login.php
Version: 5.4
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#12) [https://---.com.au/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes
Server
-------------------------------------------

Mysql Version: 5.7.29
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 8 MB
Php Memory Limit: 256M
Php Post Max Size: 8M
Php Soap: No
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.2.27
Software: Apache
Wp Memory Limit: 40M
Theme
-------------------------------------------

Name: Astra
Version: 2.4.2
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes

Plugins
-------------------------------------------

Astra Hooks: 1.0.2
Astra Pro: 2.4.0
Classic Editor: 1.5
Contact Form 7: 5.1.7
Elementor: 2.9.7
Elementor - Header, Footer & Blocks: 1.4.1
LifterLMS: 3.37.18
Really Simple SSL: 3.3.1
Starter Templates: 2.2.1
Ultimate Addons for Gutenberg: 1.14.8
Under Construction: 3.75
WPForms Lite: 1.5.9.5
Yoast SEO: 13.5

Integrations
-------------------------------------------

BbPress: No
BuddyPress: No

Template Overrides
-------------------------------------------
```

</details>

### Browser, Device, and Operating System Information

n/a

### Related User Information

https://wordpress.org/support/topic/certificate-download-error/

---

I couldn't find an equivalent "non-mb" for `mb_convert_encoding()`, but from several sources, e.g. https://stackoverflow.com/a/11978382
looks like 
`htmlspecialchars_decode(utf8_decode(htmlentities($htmls, ENT_COMPAT, 'UTF-8', false)));`
is a good alternative (fall back in our case) for:
`mb_convert_encoding( $html, 'HTML-ENTITIES', 'UTF-8' );` that we use here:
https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.certificates.php#L228

**Comment by eri-trabiccolo** [comment]
@thomasplevy I'm still documenting about that, I'm not sure `htmlspecialchars_decode(utf8_decode(htmlentities($htmls, ENT_COMPAT, 'UTF-8', false)));`
is the correct solution here.
I'm seeing different approaches in WP, e.g. using a symfony polyfill .

given the fact that as far we know we only have 1 user affected by that and that he fixed the issue by asking his hosting provider to enable the multibyte strings support, I think we can postpone it.

Do you agree?

**Comment by thomasplevy** [comment]
@eri-trabiccolo if the affected user is under control let's move this to future and investigate further when we have more reports or some additional breathing room.

If you could post a link to the polyfill as used in the WP core that would be cool so we don't lose it too, please!

**Comment by eri-trabiccolo** [comment]
sorry, meant WP world, e.g. Caldera Forms, Back WP Up use it:
https://github.com/inpsyde/backwpup/tree/master/vendor/symfony/polyfill-mbstring

**Comment by thomasplevy** [comment]
ah okay
