### ISSUE TITLE
Add reveiews manually

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1119]
### Reproduction Steps
I know reviews can be added from the frontend of the course but you can't select the course the review is for at the backend.

Go to Courses >> Reviews >> Add new.
There's no option to map the review to a course.

### Expected Behavior

There should be a checkbox or Course field option

### Actual Behavior

No course field option

HS-118735

**Comment by thomasplevy** [comment]
Please add this as a feature request on the Trello board
