### ISSUE TITLE
Fatal when downloading a certificate if mime_content_type PHP function not available.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1120]
### Reproduction Steps

+ On a server where the PHP function `mime_content_type()` is not available download/save a certificate

### Expected Behavior

+ I expect to download the certificate without any issues

### Actual Behavior

+ Cannot download the certificate due to a fatal error

### Error Messages / Logs

It should be a classic PHP fatal for non existent functions.

### System Information

same as #1118 

### Browser, Device, and Operating System Information

n/a

### Related User Information

https://wordpress.org/support/topic/certificate-download-error/

We should take into account the non availability of this function (e.g. jetpack and several others do it), a simple but nice solution would be something of the sort:
https://github.com/inpsyde/backwpup/blob/master/vendor/inpsyde/backwpup-shared/src/File/MimeTypeExtractor.php

**Comment by toyinogunseinde** [comment]
Any news on this yet? HS-119399

**Comment by eri-trabiccolo** [comment]
@toyinogunseinde not yet.

**Comment by toyinogunseinde** [comment]
@thomasplevy @eri-trabiccolo This is the third time the customer is sending an email to check-in. It seems urgent to him. Thank you :)
