### ISSUE TITLE
Enrollment End date rule is not obeyed

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1121]
### Reproduction Steps

On a course, Go to Restrictions
Put any start date
Put an end date(like yesterday or two days ago)

### Expected Behavior

Should not allow users enroll for the course.

### Actual Behavior

Users can still enroll even after enrollment date has lapsed.

### Error Messages / Logs

HS-119283

**Comment by thomasplevy** [comment]
@toyinogunseinde 

Is the access plan that's allowing enrollment a *free* access plan?

**Comment by toyinogunseinde** [comment]
@thomasplevy Yes, it's a free plan

**Comment by thomasplevy** [comment]
This logic here: https://github.com/gocodebox/lifterlms/blob/bd78c8c04aaa20073b649c64d93834de9d53491d/templates/product/pricing-table.php#L20

Allows free access plans to bypass enrollment restrictions.


This logic (of allowing free) is intended to allow free access plans to be purchased without any access plans enabled, however it's creating this issue while fixing that one.

**Comment by thomasplevy** [comment]
This is a pretty easy fix, I should have it reworked in a few hours

**Comment by thomasplevy** [comment]
@toyinogunseinde this is fixed in LifterLMS 3.38.0
