### ISSUE TITLE
Post Excerpt doesn't get updated(either deleted or removed)

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1122]
### Reproduction Steps

Open up a course.
Type an excerpt to the right sidebar(not the one below the editor)
Click on update. 

### Expected Behavior

Meant to either remove or update to the latest excerpt on it

### Actual Behavior

If there was an excerpt before, it won't get deleted and if there was none before and you add one, it'll get deleted

### Error Messages / Logs

HS-119283
https://www.loom.com/share/898e1d74d43d41578fa42084520befa0

**Comment by thomasplevy** [comment]
@toyinogunseinde I see Elementor is enabled. Have you ruled out plugin conflicts yet?

**Comment by toyinogunseinde** [comment]
Likely to be a plugin conflict. Just tried on a fresh site and it worked!

**Comment by thomasplevy** [comment]
@toyinogunseinde 

Do you have time to determine the conflicting plugin and then get back to me so we can determine if we can fix it in the core?

**Comment by toyinogunseinde** [comment]
@thomasplevy  I'm working on that already. I Will let you know as soon as I'm able to get something. Thanks

**Comment by thomasplevy** [comment]
@toyinogunseinde can I get an update on whether or not we've determined if this is in fact a plugin conflict or not?

**Comment by toyinogunseinde** [comment]
@thomasplevy For some reason, it doesn't update on the Default LifterLMS course but it does for other courses. I just tried this on my test site. Also, if you clone a course from the Default LifterLMS course, it does the same thing.

**Comment by eri-trabiccolo** [comment]
@toyinogunseinde no other plugins active?

**Comment by toyinogunseinde** [comment]
@eri-trabiccolo Yeah, No plugins or add-ons available. Just LifterLMS core

**Comment by thomasplevy** [comment]
> @thomasplevy For some reason, it doesn't update on the Default LifterLMS course but it does for other courses. I just tried this on my test site. Also, if you clone a course from the Default LifterLMS course, it does the same thing.

That's an interesting observation and will help out a bit. Knowing this can you relay this to the customer so we can de-prioritize knowing that it does actually work and more than likely the issue lies in metadata on the course import?

**Comment by toyinogunseinde** [comment]
@thomasplevy Customer has been updated with this information.

**Comment by toyinogun** [comment]
HS-129308

**Comment by toyinogun** [comment]
HS-131999

**Comment by nrherron92** [comment]
HS-130470

**Comment by nrherron92** [comment]
I bumped the severity due to the frequency we've now heard about this issue.

**Comment by thomasplevy** [comment]
This is a regression resulting from the block editor exposing the "excerpt" field. Excerpts on a course are managed via the sales page "content" field in the course options metabox..

So what's happening is the data posted in the "Excerpt" area is being overridden by the empty data found in the metabox.

I believe a solution would be to keep those two fields in sync or to simply disable the excerpt field.

https://developer.wordpress.org/reference/functions/register_post_type/#supports
