### ISSUE TITLE
Divi doesn't recognize LifterLMS quizzes as a custom post type

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1135]
### Reproduction Steps

Install Divi
Customize your header and styles.
Launch course builder and insert a quiz into a lesson.

### Expected Behavior

When you launch the quiz, it's meant to still take the global header settings and not go to default header settings

### Actual Behavior

Goes to default header settings.

This is the header that has been customized

[image removed]

When you click on "Take Quiz" it reverts to this:
[image removed]

HS-120130

**Comment by thomasplevy** [comment]
@toyinogunseinde from my perspective this is not really a bug in LifterLMS or DIvi and while the behavior is obviously not ideal it's not like #1079 where LifterLMS + Divi is unuseable as a result of the conflict.

At this moment we're not going to change the LifterLMS core to support this. I'm not sure why Divi isn't recognizing quizzes but it's not. It's not our responsibility to make sure every feature of Divi works with our plugin. Divi can choose to add support for us here or the user could use a child theme that has native LifterLMS support.

We have a few recommended Divi child themes that may consider adding this support

In the future *maybe* we can add this to our labs divi integration, however at this moment it's going to be extremely low priority.

I suggest the customer work with a theme developer to get this level of compatibility.
