### ISSUE TITLE
PHP Warning when deleting a quiz attempt

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1142]
### Reproduction Steps

+ From LifterLMS -> Reporting -> Quizzes visit the Attempts screen (so you need at least a quiz with an attempt)
+ Click on a quiz attempt
+ Delete the attempt

### Expected Behavior

+ Attempt deleted with no warnings

### Actual Behavior

+ Attempt deleted but with warnings

### Error Messages / Logs

```
[12-May-2020 12:14:29 UTC] PHP Notice:  Undefined index:  in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php on line 614

```

### System and Environment Information

```
Php Version: 7.2.29-1+ubuntu18.04.1+deb.sury.org+1


LifterLMS 3.38.1
```

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by eri-trabiccolo** [comment]
I'm actually working on #1116 and unless you have something against it I will ship a fix for this in the PR for that issue.

**Comment by thomasplevy** [comment]
@eri-trabiccolo sounds good
