### ISSUE TITLE
Certificates printing: they can be shifted in an undesirable way

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1163]
### Reproduction Steps
This is something I've been able to reproduce under pretty specific circumstances but the issue itself is generic, that's why I report this here and not in LaunchPad where I've been (and our customer is) able to reproduce it.

+ With the LaunchPad theme
+ Create a certificate with an image with the following size: 1123(w)x794(h)px - which should be the size in pixels of the A4 paper in horizontal mode at 96dpi.
+ To speed up testing do not generate a new thumbnail for this size, just go in Settings -> Engagements and check the Legacy Compatibility option under the Certificate Settings
+ View the certificate
+ Open the print preview, with chromium based browsers, clicking on the Print button would be enough :P
+ Make sure you removed the (printed) page margins

### Expected Behavior

+ I would expect the certificate to take the whole page in horizontal orientation with basically no gaps

![Schermata 2020-05-26 alle 17 32 06](https://user-images.githubusercontent.com/7689242/82920040-15917400-9f77-11ea-8146-bd0aa8ca4c1f.png)

### Actual Behavior

+ The certificate is shifted on the right, and doesn't even take the whole height:
![Schermata 2020-05-26 alle 17 21 25](https://user-images.githubusercontent.com/7689242/82919114-e3cbdd80-9f75-11ea-801e-2fc084c369fc.png)

### Error Messages / Logs

```
n/a

```

### System and Environment Information

```
Plugins: LifterLMS: 3.38.2
Theme: LifterLMS LaunchPad 2.4.6
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-121920

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

since the issue here, I'm pretty certain, is the print-area margins that are automatically added how do you propose we "fix" this issue without also creating a lot of issues for users who don't have their image set to the full margin-less width/height of an a4 piece of paper?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
The problem is the `.container` element in LP, that wraps the certificate container element, and has a width set to less than 100% (80%). This element's position is `relative`, so the certificate container elements, whose position is absolute in `print` media, refers to it and it's shifted on the right by 10% of the page's width. 

My proposal is just that that we reset the `.container` width (set it to 100%) in `print` media, for the certificates.
