### ISSUE TITLE
LifterLMS 4.0.0 3rd Party Compatibility

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1174]
This issue serves as a way for us to track confirmations of 4.0.0 compatibility with 3rd party plugins, integrations, and themes.

+ [x] [AffiliateWP](https://lifterlms.com/product/affiliatewp/)
+ [x] [Astra](https://lifterlms.com/product/astra/)
+ [ ] [Beaver Builder + LifterLMS](https://lifterlms.com/product/beaver-builder-lifterlms/)
+ [ ] [BuddyBoss for LifterLMS](https://lifterlms.com/product/buddyboss-for-lifterlms/)
+ [ ] [ConsultPress](https://lifterlms.com/product/consultpress/)
+ [ ] [Course Maker Pro](https://lifterlms.com/product/course-maker-pro/)
+ [ ] [Course Scheduler](https://lifterlms.com/product/course-scheduler/)
+ [ ] [Divi + LifterLMS](https://lifterlms.com/product/divi-lifterlms/)
+ [ ] [iDevAffiliate](https://lifterlms.com/product/idevaffiliate-integration/)
+ [ ] [Elementor + LifterLMS](https://lifterlms.com/product/elementor-lifterlms/)
+ [ ] [Emerson](https://lifterlms.com/product/emerson-child-theme-for-divi-lifterlms/)
+ [ ] [GamiPress](https://lifterlms.com/product/gamipress/)
+ [ ] [GroundHogg](https://lifterlms.com/product/groundhogg/)
+ [ ] [Gutenberg + LifterLMS](https://lifterlms.com/product/gutenberg-lifterlms/)
+ [ ] [Larry](https://lifterlms.com/product/larry/)
+ [ ] [Lifter Elements](https://lifterlms.com/product/lifter-elements/)
+ [ ] [LifterLMS BadeOS](https://lifterlms.com/product/lifterlms-badgeos/)
+ [ ] [LifterLMS EDD](https://lifterlms.com/product/lifterlms-edd/)
+ [ ] [LifterLMS Quiz Import/Export](https://lifterlms.com/product/lifterlms-quiz-import-export/)
+ [x] [MonsterInsights](https://lifterlms.com/product/monsterinsights/)
+ [ ] [Neve](https://lifterlms.com/product/neve/)
+ [ ] [OceanWP](https://lifterlms.com/product/oceanwp/)
+ [ ] [Rebrand LifterLMS Pro](https://lifterlms.com/product/rebrand-lifterlms-pro/)
+ [ ] [Sage](https://lifterlms.com/product/sage/)
+ [ ] [Simply Schedule Appointments](https://lifterlms.com/product/simply-schedule-appointments/)
+ [ ] ~[The Core](https://lifterlms.com/product/the-core/)~
+ [x] [Uncanny Automator](https://lifterlms.com/product/uncanny-automator/)
+ [ ] [Ventura](https://lifterlms.com/product/ventura/)
+ [ ] [WP Fomify](https://lifterlms.com/product/wpfomify/)
+ [ ] [WP Fusion](https://lifterlms.com/product/wp-fusion-integration/)

**Comment by uncannyowlryan** [comment]
I can confirm Uncanny Automator worked as expected with the beta we tested.

**Comment by thomasplevy** [comment]
@uncannyowlryan thanks so much!

**Comment by premanshup** [comment]
@thomasplevy Thanks for the heads up. We can confirm that Astra is working without any issues with the beta version. :-)

**Comment by thomasplevy** [comment]
@premanshup thank you!
