### ISSUE TITLE
Minor bug. Notice: Trying to get property 'post_content' in Course listing page

### ISSUE THREAD

**Issue by liveaspankaj** [gocodebox/lifterlms#1176]
Course listing page: 
https://www.screencast.com/t/95Y27FYRKiT

Message: Notice: Trying to get property 'post_content' in Course listing page

**Comment by thomasplevy** [comment]
@liveaspankaj could you update your issue to include the information asked for in our issue template at https://github.com/gocodebox/lifterlms/issues/new?template=Bug_Report.md

**Comment by thomasplevy** [comment]
@liveaspankaj closing due to insufficient information. Please reply by following the issue template and we'll reopen.

Thanks
