### ISSUE TITLE
llms notices not displayed on Checkout page (e.g. Payment gateway errors) when Slim SEO plugin enabled.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1181]
### Reproduction Steps

+ Install and activate the plugin [Slim Seo](https://wordpress.org/plugins/slim-seo/)
As not logged in user:
+ Reach the checkout page, e.g. by clicking on the Enroll button of the LifterLMS sample course
+ Fill all the required fields making sure to use an email address of **an already existing user**, e.g. your admin email.
+ Click on the checkout form submit button
+ The page reloads and..

### Expected Behavior

+ I would expect to see an error printed at the top of the checkout form, saying:
**An account with the email address "{your_already_existing_user_email}" already exists.**

### Actual Behavior

+ No error printed at the top of the checkout form.

### Error Messages / Logs

n/a

### System and Environment Information

<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.4.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: fr_FR
Multisite: No
Page For Posts: Not Set
Page On Front: home-ok (#12477) [[removed]/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.38.1
Db Version: 3.38.1
Course Catalog: Not Set
Membership Catalog: Membership Catalog (#7) [[removed]/memberships/]
Student Dashboard: Tableau de bord (#9) [[removed]/tableau-de-bord/]
Checkout Page: Acheter (#8) [[removed]/acheter/]
Course Catalog Per Page: 12
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: 8
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Conditions d’utilisation (#13432) [[removed]/conditions-dutilisation/]
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: required
Registration Phone: optional
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: CA
Currency: USD
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: Académie Canadienne de Management et de Technologie (Canada-academy.com)
Email Header Image:
Cert Bg Width: 900
Cert Bg Height: 1216
Cert Legacy Compat: no


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: yes
PayPal Order: 0
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manual: Disabled
Manual Logging:
Manual Order: 2


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 8000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 512M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.2.30
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad Child
Version: 1.1.0
Themeuri: https://lifterlms.com/product/launchpad/
Authoruri: https://lifterlms.com
Template: lifterlms-launchpad
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Duplicate Page: 4.2
Elementor: 2.9.8
Elementor Pro: 2.9.4
Header and Footer Scripts: 2.2.1
HurryTimer PRO: 2.2.27
LifterLMS: 3.38.1
LifterLMS Labs: 1.5.3
LifterLMS PayPal Gateway: 1.1.3
LifterLMS Stripe Payment Gateway: 4.3.4
Loco Translate: 2.3.4
Monkeyman Rewrite Analyzer: 1.0
Slim SEO: 3.3.1
Title Remover: 1.2.1
WebP Converter for Media: 1.2.5
WP Fastest Cache: 0.9.0.6


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

content-certificate.php (ver: 3.18.0): /home/[redacted]/public_html/wp-content/themes/lifterlms-launchpad-child-master/lifterlms/ (ver: 3.18.0)
certificates/preview.php (ver: 3.14.0): /home/[redacted]/public_html/wp-content/themes/lifterlms-launchpad-child-master/lifterlms/ (ver: 3.14.0)
course/lesson-navigation.php (ver: ): /home/[redacted]/public_html/wp-content/themes/lifterlms-launchpad-child-master/lifterlms/ (ver: )
```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Info
HS-122446

### Workaround
Define a manual description (via plugin settings) for the checkout page - or an excerpt.

### Thoughts
The issue happens because the plugin, in order to set the description automatically - when not manually defined - parses the post_content, and "does" the shortcodes in it, hence the notices are print at that time and the notices queue is flushed.

The same would happen with Slim SEO and WooCommerce, BUT, the plugin has a specific integration:
https://github.com/elightup/slim-seo/blob/3.3.2/src/Integrations/WooCommerce.php
that wouldn't be too much different from the one needed for us.

**Comment by thomasplevy** [comment]
Is there any way to reproduce this with the manual gateway? Maybe by trying to checkout with an existing username / email address? Would we encounter the same issue that way?

**Comment by eri-trabiccolo** [comment]
@thomasplevy yeah you can reproduce it either that way, or even by trying to login (so filling the login form in the checkout page) with a non existing email+pw.
Well I wanted to present the user's case (even because a payment error not shown is more important I think). :)

**Comment by thomasplevy** [comment]
I'm asking about other ways to recreate it (without an add-on) in order to propose that we open an issue in the Slim SEO repo reporting this issue with an offer to submit a PR in order to fix this issue as we could do almost exactly what their current WC integration does in order to fix this

**Comment by eri-trabiccolo** [comment]
Yes yes I got it man :)
I know you have a reason if you ask about something.
I just added my reason about proposing only one case.
I had to add the other ways to reproduce the issue in Thoughts :D

**Comment by thomasplevy** [comment]
@eri-trabiccolo can you update reproduction with non-stripe steps also please, I'll reach out to the devs a bit later

**Comment by eri-trabiccolo** [comment]
@thomasplevy edited the reproduction steps.

**Comment by eri-trabiccolo** [comment]
proposed a PR https://github.com/elightup/slim-seo/pull/16

**Comment by thomasplevy** [comment]
PR Merged, closing!
