### ISSUE TITLE
LifterLMS 4.0.0 Beta - not possible to start a quiz

### ISSUE THREAD

**Issue by annrra** [gocodebox/lifterlms#1184]
### Reproduction Steps
Create a course with lesson and quiz inside
Try to start the quiz

### Expected Behavior
User should be able to start taking the quiz

### Actual Behavior
Take Quiz button loads empty quiz page without quiz content and questions listed

**Comment by thomasplevy** [comment]
Thanks @annrra !

**Comment by thomasplevy** [comment]
Resolved in 4.0.0-beta.2: https://github.com/gocodebox/lifterlms/releases/tag/4.0.0-beta.2
