### ISSUE TITLE
Importer does not import images from the post_content or custom fields (except featured images)

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1196]
### Reproduction Steps

+ Create a course with images in a course, lesson, quiz, etc... post_content or in any custom fields designed for an image (image question types, for example)
+ Export the course
+ Import the course into another site

### Expected Behavior

+ The images would imported into the media library of the site where the course is imported (how like the featured images are)

### Actual Behavior

+ Images are not imported and will instead be loaded from the original site's media library (hotlinked)

### Error Messages / Logs

N/A

**Comment by toyinogun** [comment]
HS-135185
