### ISSUE TITLE
Deprecated entities to be removed in 5.0

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1198]
I open this to track of all the deprecated files/functions/etc. that should be removed in 5.0

- [x] [`class LLMS_Processor_Table_To_Csv`](https://github.com/gocodebox/lifterlms/blob/3.40.0/includes/processors/class.llms.processor.table.to.csv.php) deprecated since 3.28.0
- [x] Methods deprecated in #1511 should be removed from the codebase. See https://github.com/gocodebox/lifterlms/commit/54e736cf125fd291e4b6a7733f87d3015060f67d & https://github.com/gocodebox/lifterlms/commit/e4bff7c9afcf06030342a812d376f49195c0ed40

**Comment by thomasplevy** [comment]
Updated to include methods deprecated in #1511
