### ISSUE TITLE
4.0.0-beta3 db update: missing callbacks

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1202]
### Reproduction Steps

+ Update to 4.0.0-beta.3 (you can downgrade and then upgrade)
+ run the db update by clicking on the notice shown in admin
+ look at the updater log

### Expected Behavior

+ I expect the update going smooth, and the updater log showing no issues

### Actual Behavior

+ The updater log shows that an action callback is missing

### Error Messages / Logs

+ Include any relevant error messages or log files
```
06-12-2020 @ 10:51:37 - Queuing 4.0.0-beta.3 - llms_update_400_clear_wp_session_manager_data
06-12-2020 @ 10:51:37 - Queuing 4.0.0-beta.3 - llms_update_400_update_db_version
06-12-2020 @ 10:51:39 - Could not find llms_update_400_clear_wp_session_manager_data callback
06-12-2020 @ 10:51:39 - Running llms_update_400_update_db_version callback
06-12-2020 @ 10:51:39 - Finished llms_update_400_update_db_version callback
06-12-2020 @ 10:51:39 - Update complete

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
LifterLMS: 4.0.0-beta.3

LifterLMS Social Learning: 1.2.1

LifterLMS WooCommerce: 2.0.15

WooCommerce: 4.2.0

```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information
n/a

**Comment by thomasplevy** [comment]
I cannot for the life of me figure out how this function was removed, did I never add it to the migration stack?

**Comment by eri-trabiccolo** [comment]
I don't know what we did on this :(

**Comment by thomasplevy** [comment]
I must have refactored the update functions to each have a single purpose, updated the function tests, and then never updated the callback list... I was just trying to figure out if i botched a merge.
