### ISSUE TITLE
Preview management wp-admin menu icon uses old logo

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1236]
### Reproduction Steps

+ Log in as an admin
+ Visit the frontend of course
+ Look at the "View as" menu on the top right of the WP Admin bar

### Expected Behavior

+ See the "new" logo as the icon

### Actual Behavior

+ The old icon is visible

**Comment by eri-trabiccolo** [comment]
That's used in the merge code buttons too (see #1241).
In the "View as" menu on the top right of the WP Admin bar we could use https://github.com/gocodebox/lifterlms/blob/4.1.0/assets/images/lifterlms-icon.png it fits quite nice.
But we cannot use it in the merge code buttons, as it's white and has very low contrast with the button's background, which is a light grey.

**Comment by thomasplevy** [comment]
@eri-trabiccolo could you open a new issue for the other issue referenced in your comment please.
