### ISSUE TITLE
Deprecate LLMS_Quiz::get_lessons

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1238]
https://github.com/gocodebox/lifterlms/blob/4.1.0/includes/models/model.llms.quiz.php#L252

It relies on a `LLMS_Lesson` post meta we don't use anymore `_llms_assigned_quiz`, and on the fact that a quiz could be associated with more than one lesson, which is not the case anymore as well.

**Comment by thomasplevy** [comment]
See commit: https://github.com/gocodebox/lifterlms/commit/ad0e8bf06e527d4f5c1984953fcb8bb64b7c4be2

**Comment by thomasplevy** [comment]
Closed in #1517
