### ISSUE TITLE
Limit Attempt Switch-Number is a text field

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1239]
### Reproduction Steps

+ Open a quiz lesson in the builder 
+ Look at the CSS structure for Limit Attempts

### Expected Behavior

+ I guess it should be a number field?

### Actual Behavior

+ it's a text field that accepts numbers just fine.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

HS-128036  Customer attached a screenshot.

**Comment by thomasplevy** [comment]
@nrherron92 thank the customer, inform them this is a development oversight and will be resolved in a future release, however, since this is __very__ low severity ask the customer to kindly use numbers (as is intended).

**Comment by nrherron92** [comment]
@thomasplevy will do
