### ISSUE TITLE
Live Theme Preview Causing Error

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1251]
### Reproduction Steps

+ Switch into Twenty-Twenty Theme
+ Attempt a live preview of another theme

### Expected Behavior

+ You can live preview.

### Actual Behavior

+ There's an error thrown on a white screen of doom

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Stack trace:
#0 Web/fresh/wp-includes/class-wp-hook.php(287): LLMS_Twenty_Twenty::add_inline_styles('')
#1 Web/fresh/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 Web/fresh/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 Web/fresh/wp-includes/general-template.php(2884): do_action('wp_head')
#4 Web/fresh/wp-content/themes/astra/header.php(26): wp_head()
#5 Web/fresh/wp-includes/template.php(723): require_once('/Users/natalie/...')
#6 Web/fresh/wp-includes/template.php(672): load_template('/Users/natalie/...', true)
#7 Web/fresh/wp-includes/general-template.php(41): locate_template(Array, true)
#8 Web/fresh/wp-content/themes/astra/page.php(20): get_header in /Users/natalie/Web/fresh/wp-content/plugins/lifterlms/includes/theme-support/class-llms-twenty-twenty.php on line 72



```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

HS-128860

**Comment by thomasplevy** [comment]
@nrherron92 fixed in 4.3.0
