### ISSUE TITLE
Make the plan length in the Access plans a free text field or accomodate more months/years

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1255]
**Is your feature request related to a problem? Please describe.**
A user wants a payment plan of 48 payments of $x every month but the access plan cap is 24 months. This means the customer can't do this access plan.

**Describe the solution you'd like**
Perhaps a free text in the plan length for months/years

**Describe alternatives you've considered**
N/A

HS-128786

**Comment by thomasplevy** [comment]
https://github.com/gocodebox/lifterlms-gateway-paypal/issues/30

**Comment by thomasplevy** [comment]
In order to make this as compatible as possible with multiple gateways we cannot allow an unrestricted field here. This will not be implemented.
