### ISSUE TITLE
JQMIGRATE: 'ready' event is deprecated

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1268]
### Reproduction Steps

+ Open browser's console in front

### Expected Behavior

+ No warnings logged

### Actual Behavior

+ Warning logged

### Error Messages / Logs

+ Include any relevant error messages or log files
```
JQMIGRATE: 'ready' event is deprecated
migrateWarn @ jquery-migrate.js?ver=1.4.1:45

```

### System and Environment Information

```
LifterLMS 4.3.0
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### What to do
First of all let's look at the jQuery doc:
https://api.jquery.com/ready/

> 
> jQuery offers several ways to attach a function that will run when the DOM is ready. All of the following syntaxes are equivalent:
> 
```
$( handler )
$( document ).ready( handler )
$( "document" ).ready( handler )
$( "img" ).ready( handler )
$().ready( handler )
```
> As of jQuery 3.0, only the first syntax is recommended; the other syntaxes still work but are deprecated. This is because the selection has no bearing on the behavior of the .ready() method, which is inefficient and can lead to incorrect assumptions about the method's behavior. For example, the third syntax works with "document" which selects nothing. The fourth syntax waits for the document to be ready but implies (incorrectly) that it waits for images to become ready.
> 
> There is also $(document).on( "ready", handler ), deprecated as of jQuery 1.8 and removed in jQuery 3.0. Note that if the DOM becomes ready before this event is attached, the handler will not be executed.

Now considering that the built-in WordPress jQuery version is 1.12 (at the moment), I don't think we should really worry about what will happen in 3.0, but since we're here, we could just replace, occurrences of deprecated once with:
`$(handler)
`

**Comment by thomasplevy** [comment]
This has been a wild 5 hours... Got kind out of hand but PR is incoming.
