### ISSUE TITLE
Legend is truncated when viewing the charts in the reporting section

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1269]
### Reproduction Steps

Go to LifterLMS >> Reporting >> Enrollments and see the screen there
![image](https://user-images.githubusercontent.com/62220599/89317138-e1bc8400-d674-11ea-97f3-75870256a7f5.png)

### Expected Behavior

The legend should be fully written out

### Actual Behavior

Seems truncated

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
N/A

```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)
HS-129505

**Comment by thomasplevy** [comment]
Potential solution: https://stackoverflow.com/a/17338269/400568

Hovering over the label shows the full label as an alternative in the meantime
