### ISSUE TITLE
Update sample course import file

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1276]
+ [x] Provide export file from sandbox site (assigned to @chrisbadgett)
+ [x] Review Kadence theme (assigned to @nrherron92)
+ [x] Strip author information from file
+ [x] Replace file in core plugin

**Comment by chrisbadgett** [comment]
~Github does not support json file attachments. The course is here: [redacted]~

[LifterLMS-Quickstart-Course_20200805.zip](https://github.com/gocodebox/lifterlms/files/5029757/LifterLMS-Quickstart-Course_20200805.zip)

**Comment by thomasplevy** [comment]
@chrisbadgett 

Due to the prevalence of the Kadence theme in this course I am not going to ship this until @nrherron92 and @toyinogunseinde have had a chance to review (and approve) the theme through our 3rd-party integrations process.

**Comment by chrisbadgett** [comment]
This issue has been merged here: https://github.com/gocodebox/lifterlms/issues/1305

**Comment by thomasplevy** [comment]
Reopening to keep issue scope small

**Comment by thomasplevy** [comment]
Import files will be served from an API hosted at academy.lifterlms.com, closing this.
