### ISSUE TITLE
Predictable class file paths

### ISSUE THREAD

**Issue by szepeviktor** [gocodebox/lifterlms#1303]
Could e.g. `LLMS_Achievement_User` class live in `includes/achievement/class-llms-achievement-user.php` instead of `includes/achievements/class.llms.achievement.user.php` ?

@thomasplevy What do you think?

**Comment by szepeviktor** [comment]
BTW I've just released the WPCS-compliant autoloader.
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/wordpress-autoloader.php
Although class files in unpredictable directories are impossible to find 🔎

**Comment by thomasplevy** [comment]
Yes, it's difficult to rename filenames because these are technically backwards incompatible changes. We want to be safe and ensure that we don't cause 500 errors if 3rd parties or custom code are referencing files in our codebase.

We planned to rename all the files in 4.0 but decided to push that back for a later future release.

See #638 for original issue

**Comment by szepeviktor** [comment]
Thank you @thomasplevy!

Could you give me the first example that pops into your head?

**Comment by szepeviktor** [comment]
I cannot imagine one! 🤯 
Class names wouldn't change.

**Comment by thomasplevy** [comment]
File names change and any plugin or theme that calls an include to the now non-existent file creates a 500 error

**Comment by szepeviktor** [comment]
Okay-okay.
But what is the use case?
Martians land in our garden? Maybe I have limited imagination.

**Comment by szepeviktor** [comment]
`LLMS_Loader` loads **everything**.

**Comment by thomasplevy** [comment]
> `LLMS_Loader` loads **everything**.

Do you do any amount of support or development for a WP plugin or theme?

That doesn't matter. Someone somewhere is loading something for no good reason and if we change the location there will be a crashed website and we will be held responsible.
