### ISSUE TITLE
Course importer does not allow usage of reusable blocks

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1326]
### Reproduction Steps

+ Create a course that utilizes a reusable block editor block in course or lesson content
+ Export the course
+ Import the course into a different site

### Expected Behavior

+ The reusable block will be imported into the site with the course import

### Actual Behavior

+ The reusable block will render as "Unavailable" in the new site

### Additional details

A reusable block is stored as a `wp_block` post type, when used in a post's content, the reusable block is stored as a reference that looks like this:

```html
<!-- wp:block {"ref":562} /-->
```

The ref is a reference to the `wp_block` post's post ID.

### Proposed solution

When generating an export, post types that support the block editor should include a property of reusable blocks contained within the post's content That looks something like this:

```json
{
  "id": 123,
  "embeds": {
     "blocks": {
          "456": {
              "title": "Block Title",
              "content": "block content",
          }
      }
 }
}
```

During an import we can read all the reusable blocks included in an export and duplicate them into the import site, and, after importing it, we can update the reference(s) in the post's content.

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment]
@eri-trabiccolo I came across this bug today and in light of your comments regarding exporting images as an array in favor of parsing images (comments in review on #1324) I'm proposing that we add an "attachments" array member during exports. We can attach "images" here as well as reuseable blocks. Working on a WIP that we'll discuss tomorrow in greater detail.

**Comment by eri-trabiccolo** [comment]
@thomasplevy ok, but I would use a different name since "attachment" has a meaning in wp, what do you think?

**Comment by thomasplevy** [comment]
I was thinking "embeds" but that has a different meaning too. Attachments didn't feel quite right but I didn't spend too much more time thinking about it.

Any suggestions on what it should be called?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Mmm maybe we just should keep it simple and consistent, let's remove the 'embeds' and just go with first level:
'blocks'
'attachments'
'images' (which are not attachments, and, in fact I see it as an array of URLs). 
Otherwise, something like 'include/require'?
