### ISSUE TITLE
Event session start not recorded on sign-on

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1349]
### Reproduction Steps

+ Perform a login
+ Check the `wp_lifterlms_events` table in your db.

### Expected Behavior

I would expect to see two new records with approximately the same date, referring to the same user id:
+ a session start event
+ a sign-on event

### Actual Behavior

Only the sign-on event is recorded.

This is because the sign-on event is recorded when the `'wp_login'` action hook is fired, but then current user id is not set yet, so the session start doesn't occur because of this:
https://github.com/gocodebox/lifterlms/blob/4.4.4/includes/class-llms-sessions.php#L415-L418

The solution would be to pass the user_id parameter to `LLMS_Sessions::start()` method, which will continue to fall back on the current user id if the user_id is not provided.

### Error Messages / Logs

```
n/a

```

### System and Environment Information

```

LifterLMS 4.4.4
WordPress 5.5.1
```

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
If you're fine I'm going to fix this, #1350 and #1351 in the open sessions events optimization I'm working on:
https://github.com/eri-trabiccolo/lifterlms/tree/events-open-sessions

**Comment by thomasplevy** [comment]
@eri-trabiccolo yea sounds good. My guess is you've stumbled upon these during your refactor and fixes so might as well include them while your head is in it.

Thanks <3
