### ISSUE TITLE
Usage of `llms_log()` for deprecated function notice should be replaced with `llms_deprecated_function()`

### ISSUE THREAD

**Issue by daniel-shuy** [gocodebox/lifterlms#1391]
While working on #1302, I realized that `LLMS_Notifications::dispatch_processors()` is using `llms_log()` instead of `llms_deprecated_function()` (which in turn uses wp core's [_deprecated_function()](https://developer.wordpress.org/reference/functions/_deprecated_function/)) to mark the function as deprecated.

**Comment by thomasplevy** [comment]
@daniel-shuy this is only a technically valid issue and while a technically valid issue is still an issue, I'd prefer that you focus your efforts on open issues instead of looking for and creating issues that can be fixed with minimum effort.

**Comment by daniel-shuy** [comment]
Sorry, I just thought it was a low hanging fruit, maybe I should've just committed it as part of #1390 without creating a new issue/PR
