### ISSUE TITLE
Drop PHP 7.2 testing & support (after 11/30)

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1415]
PHP 7.2 will reach it's official end of life on Nov 30 2020 [source](https://www.php.net/supported-versions)

+ [ ] Drop from travis testing matrix
+ [x] Raise PHP minimum version support from 7.2 to 7.3
+ [ ] Update add-on minimum supported version

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm thinking that we can schedule this to happen in early January and add a notice to the next release changelog to give users some fair warning. Does this seem acceptable to you?

**Comment by eri-trabiccolo** [comment]
@thomasplevy not sure man, hosting are not that fast... let's wait for February maybe, but start noticing in the changelog starting from the next release anyways...

**Comment by thomasplevy** [comment]
> **PHP 7.2 has reached it's official [end of life](https://www.php.net/eol.php). LifterLMS aims to support only officially supported PHP versions and our goal is to drop support for PHP 7.2 by March of 2021 at which time minimum supported PHP version will be raised to 7.3. If you're currently using PHP 7.2 please contact your host and request an upgrade to a [supported PHP version](https://www.php.net/supported-versions) as soon as possible!**

Hows that sound in the changelog of the next release? I'll review usage stats before we make the official decision to bump the version number and we can always not raise it when we hit March if we don't feel good about it?

**Comment by thomasplevy** [comment]
@eri-trabiccolo :arrow_up:

**Comment by eri-trabiccolo** [comment]
@thomasplevy I like it.
Would be good if we could add a short version of that in each next release like only:
> LifterLMS will drop support for PHP 7.2 by March of 2021, at which them time minimum supported PHP version will be raised to 7.3.

So that this important information doesn't get buried, what do you think?

**Comment by thomasplevy** [comment]
Sounds good

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I missed a typo:
>PHP 7.2 has reached it's official end of life. 

should be

>PHP 7.2 has reached its official end of life.

**Comment by thomasplevy** [comment]
Version 4.18.0 will be the final version to support 7.2, we'll be raising the minimum supported version to 7.3 with our next release.
