### ISSUE TITLE
Avoid adding 'extras' to the post toArray when parsing  data to be used in the course builder.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1427]
### Reproduction Steps

see #1426 

### Expected Behavior

+ I'd expect 'extras' to not be added to the array model

### Actual Behavior

+ 'extras' are added

I wonder if by default we should just set this filter to `false`, and only enable it on export (we don't need it on clonation at the moment, right?):
https://github.com/gocodebox/lifterlms/blob/4.7.1/includes/abstracts/abstract.llms.post.model.php#L1194

### Error Messages / Logs

n/a

### System and Environment Information

LifterLMS 4.7.1

### This issue has been recreated:

+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
> I wonder if by default we should just set this filter to `false`, and only enable it on export (we don't need it on clonation at the moment, right?):

Makes sense

**Comment by eri-trabiccolo** [comment]
fixed and released in v4.8.0
