### ISSUE TITLE
Notice: Undefined offset / Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by kjohnson** [gocodebox/lifterlms#144]
There are multiple PHP notices when viewing the last lesson in a course.

- Notice: Undefined offset: 0 in /Users/ua2/Dev/mamp/wp/wp-content/plugins/lifterlms/includes/class.llms.lesson.php on line 351
- Notice: Trying to get property of non-object in /Users/ua2/Dev/mamp/wp/wp-content/plugins/lifterlms/includes/class.llms.lesson.php on line 351

<img width="1280" alt="screenshot 2016-06-04 00 58 58" src="https://cloud.githubusercontent.com/assets/10858303/15797731/cb47c166-29ef-11e6-9054-67e46ae64d0e.png">

**Comment by thomasplevy** [comment]
@kjohnson 2.7.5 just released includes this fix, thanks again and please consider contributing again in the future.
