### ISSUE TITLE
Got error 'PHP message: PHP Warning:  in_array() expects parameter 2 to be array, string given in /lifterlms/includes/admin/class.llms.admin.notices.php on line 206

### ISSUE THREAD

**Issue by qamaruldinhamza** [gocodebox/lifterlms#1443]
### Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced
I found some warnings in my site log, those are repeating on a daily basis, those are given here

Got error 'PHP message: PHP Warning:  in_array() expects parameter 2 to be array, string given in /public_html/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php on line 206

~PHP Warning:  chmod(): Operation not permitted in /public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 173', referer: https://samanthariley.coursecommander.com/wp-admin/admin.php?page=llms-course-builder&course_id=1624~ Moved to #1445 

Both the same is happing multiple times a day.

+ Include screenshots where applicable
+ Record a video if possible (if you post a video please still include a text version of your recreation steps!)

### Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)
There should be no warning because it happens because of bad practices in coding and it also effect the processing speed of the server and took more resources and cause memory breach as well.

### Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)
There are a lot of warnings as explained above

### Error Messages / Logs

+ Include any relevant error messages or log files
```

<!-- Paste error logs / backtraces below this line -->
Got error 'PHP message: PHP Warning:  in_array() expects parameter 2 to be array, string given in /public_html/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php on line 206
```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://samanthariley.coursecommander.com
Site Url: https://samanthariley.coursecommander.com
Login Url: https://samanthariley.coursecommander.com/login
Version: 5.5.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: Yes
Page For Posts: Blog (#1145) [https://samanthariley.coursecommander.com/?page_id=1145]
Page On Front: Home (#918) [https://samanthariley.coursecommander.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 4.7.1
Db Version: 3.41.1
Course Catalog: Course Catalog (#31) [https://samanthariley.coursecommander.com/?page_id=31]
Membership Catalog: Membership Catalog (#32) [https://samanthariley.coursecommander.com/memberships/]
Student Dashboard: My Dashboard (#34) [https://samanthariley.coursecommander.com/dashboard/]
Checkout Page: Purchase (#33) [https://samanthariley.coursecommander.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-vouchers
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: weak
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: optional
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: optional
Registration Voucher: required
Registration Email Confirmation: no
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: replace@email.com
Email From Name: Samantha Riley Global
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 5 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.3.24-3+0~20201103.72+debian9~1.gbp945915
Software: Apache/2.4.25 (Debian)
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36


Theme
-------------------------------------------

Name: TotalTheme
Version: 1
Themeuri: 
Authoruri: http://wpastra.com/about/
Template: astra
Child Theme: Yes
Llms Support: Yes


Plugins
-------------------------------------------

301 Redirects: 2.53
AddFunc Head & Footer Code: 2.3
Admin Menu Editor Pro: 2.12.4
Advanced Database Cleaner PRO: 3.1.6
AffiliateWP: 2.6.1
AffiliateWP - Lifetime Commissions: 1.4.2
AffiliateWP - PayPal Payouts: 1.2.1
AffiliateWP - Recurring Referrals: 1.7.2
All-in-One WP Migration: 7.28
All-in-One WP Migration FTP Extension: 2.60
All-in-One WP Migration Multisite Extension: 3.97
Astra Pro: 2.6.4
Beaver Builder Plugin (Agency Version): 2.4.0.6
BLITZ - WP Ultimo: CartFlows Integration: 1.0.16
Checkout Page Builder Module: 1.1.0
Classic Editor: 1.6
Cloudflare DNS Settings: 1.0
Custom Fonts: 1.2.5
Customizer Search: 1.1.6
Filester - File Manager Pro: 1.4.1
Gravity Forms: 2.4.21
Gravity Forms Quiz Funnel: 1.0.0
Gravity Forms Webhooks Add-On: 1.4
Hide Notices: 1.0.0
Hide Wp Editor For BB: 1.0
LifterLMS: 4.7.1
LifterLMS Labs: 1.5.3
LifterLMS Stripe Payment Gateway: 5.1.0
Login or Logout Menu Item: 1.2.0
Post SMTP: 2.0.15
Premium Starter Templates: 2.3.8
PRO Theme: 1.1.5
Really Simple SSL: 3.3.5
Rebrandit New: 1.3.0
SEOPress: 4.0.3
SEOPress PRO: 4.0.1
Tawk.to Live Chat: 0.4.3
Ultimate Addons for Beaver Builder: 1.28.9
UpdraftPlus - Backup/Restore: 2.16.41.24
User Shortcodes Plus: 2.0.2
W3 Total Cache: 0.15.2
Webcraftic Robin image optimizer: 1.4.6
Wordfence Security: 7.4.12
WordPress Toolbar Editor: 1.3.4
WP Admin Pages PRO: 1.8.3
WP Crontrol: 1.8.5
WPfomify: 2.2.0
WP Fusion: 3.35.4
WP Fusion - Abandoned Cart Addon: 1.6.1
WP Marketing Pages: 4.1.4
WP Ultimo: 1.10.12
WP Ultimo Widgets for Beaver Builder: 1.0.5


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ * ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
on All browsers
+ Operating System name and version
Mac, Windows, and Ubuntu, on all it's same
+ Device name and version (if applicable)
N/A

**Comment by thomasplevy** [comment]
@qamaruldinhamza 

Thanks for your bug report.

Can you help me out with a few more details:

1) Can you provide me with the string that's being passed into `in_array()`. It feels like it's possible for that to be an empty string but I cannot see how that could happen without someone heading into the database and deleting manually entering a string (even an empty string) into the option value.

Of course, we can fix this even if that's the case but I'm curious what the string is that you're seeing so I can figure out if I can actually recreate this through code we've written. As of this moment the only way I can recreate is by forcing a string into a field that the LifterLMS codebase would never save a string directly to.

I think.

2) The `chmod()` is coming from a WP core function and I think it's probably an unrelated issue. For the sake of making all our lives less complicated I'm copying the contents of this issue into a new issue and going to isolate that as a separate issue. I have some questions about it but I'll ask you over there.

**Comment by thomasplevy** [comment]
@qamaruldinhamza in case you missed it I'm requesting some additional information from you to move this forward. Thanks <3

**Comment by toyinogun** [comment]
HS-145203
