### ISSUE TITLE
llmd_calculate_course_data causing DDOS

### ISSUE THREAD

**Issue by DonavanMartin** [gocodebox/lifterlms#1448]
### Reproduction Steps

It looks to happen randomly. 

![Capture d’écran, le 2020-12-01 à 14 56 05](https://user-images.githubusercontent.com/7544240/100790117-5d40fe80-33e5-11eb-9ee9-f0c464023f50.png)

When those cron task are added at the same time in the cron tasks queue, the site response become very slow...
<img width="784" alt="Capture d’écran, le 2020-12-01 à 14 56 46" src="https://user-images.githubusercontent.com/7544240/100790298-937e7e00-33e5-11eb-99ca-de4b09d0bd6e.png">

### Expected Behavior
Limit calculation.

### Actual Behavior
DDOS

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

Wordpress 
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

All

**Comment by thomasplevy** [comment]
@AlgoSolu 

Throttling is built into the background processor that processes the data in question. Perhaps given the resources available to your server the default settings are too high, you can reduce these as needed with the filters found here:

https://github.com/gocodebox/lifterlms/blob/d5dbbfae38e2970baefce5fc3ce9e3da0b9977b9/includes/processors/class.llms.processor.course.data.php#L175-L177

Try lowering the max students throttle to 200 or 500 or a number that suits you best.

The second filter allows you to determine the frequency with which the calculations are run when throttled, by default, 4 hours.

Best

**Comment by thomasplevy** [comment]
Woops I didn't mean to close it, I'll let you review and close if you're satisfied!

**Comment by DonavanMartin** [comment]
@thomasplevy I forgot to mention that we have a performant server only for this site... 
64GB DDR4 SDRAM
2 x SSD
Intel Xeon Gold 6130 - 16 Total Cores
Ubuntu 18.04 LTS 64-bit

I saw those settings in your LifterLMS documentation but the four hours settings don't looks like with our case... 
![Capture d’écran, le 2020-12-01 à 15 37 10](https://user-images.githubusercontent.com/7544240/100794104-1f46d900-33eb-11eb-9942-3f13114bf45e.png)


Ok, so I'm currently changing it to max 500 users with frequency = every hour.
I'll keep an eye on this. And I will reopen this number if it reappears.
