### ISSUE TITLE
LifterLMS Add-Ons screen - a couple of style issues

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1456]
### Reproduction Steps

+ Go to your wp dashboard - LifterLMS -> Add-ons & more
+ Make sure your viewport's width is around 2205px
+ Look at the cards

### Expected Behavior

+ Cards should be organized in 3 columns
+ Also we should be able to see the full description in each card

### Actual Behavior

+ The Advanced Videos card is misplaced
+ Cannot see the author nor the version of any add-on. This actually happens when your viewport's width is > 679px
(I think this might have a reason back in the past, not sure why though)

![Schermata 2020-12-04 alle 18 27 33](https://user-images.githubusercontent.com/7689242/101208121-f97f3580-3671-11eb-9b1c-1c1ec02b7adc.png)

### Error Messages / Logs
n/a

### System and Environment Information

LifterLMS 4.10.0

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information
n/a

**Comment by zackkatz** [comment]
I was just about to create an issue for this as well: with a very wide viewport (2560px), the add-ons no longer show descriptions and the images become too large:

Normal:

![add-ons screen for normal viewport](https://i.gravityview.co/yVvtJR+)

Wide:
![add-ons screen for wide viewport](https://i.gravityview.co/HnV13G+)

**Comment by thomasplevy** [comment]
@zackkatz I'm not seeing the issue you're reporting on our `dev` branch (where the fix for the initial issue reported by @eri-trabiccolo has been merged). Your issue seems somewhat related but not entirely the same.

If you'd like us to track your issue separately could you have a go at the `dev` branch and, if you're still seeing this issue, could you open a new bug report for us please.

Thanks

**Comment by eri-trabiccolo** [comment]
actually I found another issue introduced by #1457 
see LifterLMS Settings screen:
![Schermata 2020-12-08 alle 19 01 44](https://user-images.githubusercontent.com/7689242/101522675-da411a80-3987-11eb-80c6-0f74612568e0.png)

I think we can just get rid of that CSS rule which sets the minimum height of those cards.
