### ISSUE TITLE
Possible Fatal when deleting a product (course/membership) related to a (recurring) manual payment

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1463]
### Reproduction Steps
(a way to reproduce it)
+ as admin
+ create a course with an access plan with recurring payments
+ buy the access plan with manual payment gateway
+ go to the backend and delete (permanently) the course
+ edit the pending order and record a manual transaction so that the next recurring payment is scheduled
+ go to LifterLMS->Status->Scheduled Actions
+ run the pending action llms_charge_recurring_payment related to the just generated order

### Expected Behavior

+ no errors

### Actual Behavior

+ error generated/logged
+ you cannot see the list of the orders or any other post type, so basically you cannot even easily delete the order, at least not with that user (admin and buyer).

This is kinda an edge case but raises some questions:
1) what should we do with recurring payments related to a deleted product?
2) is it normal that the basic notification is instantiated in admin (edit.php)?
3) why do we "parse" merge codes that are not part of the content of the notification? The basic notification for the manual payment, by default, doesn't contain the merge code that produces that error, so I wouldn't expect it to be parsed at all.

### Error Messages / Logs

```
[15-Dec-2020 18:36:04 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_customer_name() on null in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.manual.payment.due.php:193
Stack trace:
#0 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(584): LLMS_Notification_View_Manual_Payment_Due->set_merge_data('{{CUSTOMER_NAME...')
#1 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(627): LLMS_Abstract_Notification_View->get_merged_string('A payment is du...')
#2 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/notifications/processors/class.llms.notification.processor.email.php(62): LLMS_Abstract_Notification_View->get_subject()
#3 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/libraries/wp-background-processing/wp-background-process.php(270): LLMS_Notification_Processor_Email->task(38)
#4 /sh in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.manual.payment.due.php on line 193
```

### System and Environment Information

```
LifterLMS 4.10.1
Theme: TwentyTwentyone
WordPress: 5.6
```

### This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-144708

**Comment by thomasplevy** [comment]
> 1. what should we do with recurring payments related to a deleted product?

I believe that when a product is deleted the related orders should be marked as cancelled (and we should probably create a "lock" mechanism so that it can't be edited after that happens) and the order data, when viewing it, should likely display something like "[Deleted]" so we don't run into errors referencing IDs that no longer exist.

This should likely happen during DELETION not trashing though, right?

> 2. is it normal that the basic notification is instantiated in admin (edit.php)?

Yes, I believe so. But I haven't looked at this code in a very long time (and I haven't reveiwed it today either). I believe that the notifications are generated and stored to be displayed later. If the action that caused the notification to be generated happens on the admin panel then the notification would be generated there (and then displayed on the frontend later). There aren't many notifications that would happen in this way but in this particular scenario it's happening as a result of the manual running of the action, I think. Normally this would happen during a background process.

> 3. why do we "parse" merge codes that are not part of the content of the notification? The basic notification for the manual payment, by default, doesn't contain the merge code that produces that error, so I wouldn't expect it to be parsed at all.

It never occurred to me to reduce the list of potentially used merge codes down to a list of actually used merge codes. 

A find & replace is run on the content of the merge code, the find is populated with the list of possible merge codes and the replace array with all the merged data.

You're correct that we can optimize this to prevent the merged data that is never used from being populated and instead search for all the merge codes actually used in the notification content and then run the find an replace requiring us to only ever populate what is needed.

This feels like a separate issue to me though which is only showing itself because we don't properly handle item 1

**Comment by eri-trabiccolo** [comment]
> > 1. what should we do with recurring payments related to a deleted product?
> 
> I believe that when a product is deleted the related orders should be marked as cancelled (and we should probably create a "lock" mechanism so that it can't be edited after that happens) and the order data, when viewing it, should likely display something like "[Deleted]" so we don't run into errors referencing IDs that no longer exist.
> 
> This should likely happen during DELETION not trashing though, right?

I see, mmm it seems to make sense yeah.

> > 2. is it normal that the basic notification is instantiated in admin (edit.php)?
> 
> Yes, I believe so. But I haven't looked at this code in a very long time (and I haven't reveiwed it today either). I believe that the notifications are generated and stored to be displayed later. If the action that caused the notification to be generated happens on the admin panel then the notification would be generated there (and then displayed on the frontend later). There aren't many notifications that would happen in this way but in this particular scenario it's happening as a result of the manual running of the action, I think. Normally this would happen during a background process.

Have to investigate why the notice is instantiated in wp-admin/edit.php and not in wp-admin/settings.php for instance...

> > 3. why do we "parse" merge codes that are not part of the content of the notification? The basic notification for the manual payment, by default, doesn't contain the merge code that produces that error, so I wouldn't expect it to be parsed at all.
> 
> It never occurred to me to reduce the list of potentially used merge codes down to a list of actually used merge codes.
> 
> A find & replace is run on the content of the merge code, the find is populated with the list of possible merge codes and the replace array with all the merged data.
> 
> You're correct that we can optimize this to prevent the merged data that is never used from being populated and instead search for all the merge codes actually used in the notification content and then run the find an replace requiring us to only ever populate what is needed.
> 
> This feels like a separate issue to me though which is only showing itself because we don't properly handle item 1

Yes this is also a separate issue.

**Comment by eri-trabiccolo** [comment]
HS-172724

**Comment by thomasplevy** [comment]
@gocodebox/engineering I think we should start working on this. I've moved into the "active" backlog.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I'm thinking more about this and I think that we shouldn't do this:

> I believe that when a product is deleted the related orders should be marked as cancelled (and we should probably create a "lock" mechanism so that it can't be edited after that happens) and the order data, when viewing it, should likely display something like "[Deleted]" so we don't run into errors referencing IDs that no longer exist.
> 
> This should likely happen during DELETION not trashing though, right?

If a product is deleted I think the order should still be there and not be cancelled, why should we cancel it...?!
I just think we should just remove the links to the product and append the a `[DELETED]` string to the product name in order screens.
The only fatal I can see when the product is deleted is produced by the notifications, so we have to fix that.

**Comment by thomasplevy** [comment]
> If a product is deleted I think the order should still be there and not be cancelled, why should we cancel it...?!

The student is now effectively paying for a subscription to content that doesn't exist...

**Comment by eri-trabiccolo** [comment]
That's true but I thought it was "legitimate" selling something that lasts 3 months, allowing you to pay it in 12 months.
But actually we unschedule recurring payments when access plan expires so... (and orders are set to "expired" ).
I think this is what we have to do mmm.
When products are permanently deleted access plans should 'expire' before being deleted. How does it sound?

**Comment by thomasplevy** [comment]
I mean.. deleting the course is different than a user's agreed-to plan ending

Also... there's payment plans and access expiration... these are similar but different. If something is deleted and the user no longer has access that doesn't matter to me but if something is deleted and someone *has access and are still on a subscription they're paying for* I think that it should stop...

However... who knows... people do weird stuff and maybe they'd consider this a bad practice...

That said... I feel like a user *might expect* for their users to stop paying for stuff they're deleting, but maybe not.... Maybe we *shouldn't do anything* and we just inform the user that there's active subscriptions to a course on deletion and they can decide to manually cancel them if they choose

**Comment by eri-trabiccolo** [comment]
> If something is deleted and the user no longer has access that doesn't matter to me but if something is deleted and someone has access and are still on a subscription they're paying for I think that it should stop...

Yeah what I meant is that we already have code in place that stops recurring payments and set the order as expired when the access plan expires (access expiration). If when deleting the course/membership which the access plan belongs to we also trigger the access plan expiration, which semantically makes sense to me, we can leverage the already existing code.

> That said... I feel like a user might expect for their users to stop paying for stuff they're deleting, but maybe not.... Maybe we shouldn't do anything and we just inform the user that there's active subscriptions to a course on deletion and they can decide to manually cancel them if they choose

That was my initial concern, you mean a pop-up?
We can even do that we show up a alert saying "Be aware that permanently deleting courses/memberships will cancel active subscriptions".

**Comment by thomasplevy** [comment]
A pop-up is going to be convoluted to implement since there's a few different places to delete courses from but yes, I think that would probably make the most sense...

Can you look into what WC subscriptions does when a product is deleted that has active subscriptions? Now that we're this far in I'm curious how they handle this scenario...

**Comment by eri-trabiccolo** [comment]
Yeah looking into that was my plan :) as wc alone doesn't do anything for normal orders on products deletion.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
It doesn't allow you to permanently delete a subscription product until you permanently delete the parent order, even if the subscription (order) was already permanently deleted.
With a simple wp blank + "You're not allowed to delete this item" kind of message... weird. Not ideal I think.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Mmm... hooking into the the actions run before a course/membership post is deleted or trashed *may* be a descent way to handle this though. If we identify connected subscriptions during the pre-delete hook then we can return false and prevent the deletion.

Ignoring the action run when deleting from the posts table list and when deleting via the classic editor and focusing on deleting from within the block editor we have a single entry point to deletion (through the WP Core rest API). We can prevent the deletion and then run another hook to modify the rest response (error) message to say something like "There are active subscriptions connected to this course. These subscriptions must be cancelled before deleting this course." (Or something like that)

We'd want to also make sure our REST endpoints work identically to this (since the block editor uses the wp/v2/... endpoint in favor of our API.

We could backport a solution to the classic editor or make a choice that classic was supposed to be deprecated by 2022 and "accept" that this is a "known issue" when using classic. I'd be okay with writing documentation about this and allowing it to be in the hands of the site owner.

We'd need to add a handler from deleting from the post table but it should be possible to use the same logic above just with different handler for customizing the error message.

**Comment by eri-trabiccolo** [comment]
> @eri-trabiccolo
> 
> Mmm... hooking into the the actions run before a course/membership post is deleted or trashed _may_ be a descent way to handle this though. If we identify connected subscriptions during the pre-delete hook then we can return false and prevent the deletion.
> 
> Ignoring the action run when deleting from the posts table list and when deleting via the classic editor and focusing on deleting from within the block editor we have a single entry point to deletion (through the WP Core rest API). We can prevent the deletion and then run another hook to modify the rest response (error) message to say something like "There are active subscriptions connected to this course. These subscriptions must be cancelled before deleting this course." (Or something like that)
> 
> We'd want to also make sure our REST endpoints work identically to this (since the block editor uses the wp/v2/... endpoint in favor of our API.
> 
> We could backport a solution to the classic editor or make a choice that classic was supposed to be deprecated by 2022 and "accept" that this is a "known issue" when using classic. I'd be okay with writing documentation about this and allowing it to be in the hands of the site owner.
> 
> We'd need to add a handler from deleting from the post table but it should be possible to use the same logic above just with different handler for customizing the error message.

@thomasplevy:
The thing is that the block editor only allows you to trash, the permanent deletion is still performed via the post table.
You'd say... "yeah but if we disallow the trashing via the post editor...". I see what you mean but this seems a bit weak to me.
Also cannot see how to prevent the deletion via REST API if not acting on the capability.
So the idea here would be to prevent permanent deletion this way:
1) when "doing rest" leverage the [`'user_has_cap'`](https://developer.wordpress.org/reference/hooks/user_has_cap/) filter
so to remove the `delete_*` cap on the the "product" with active subscriptions
1a) [filter the rest response](https://developer.wordpress.org/reference/hooks/rest_request_after_callbacks/) so to alter the error message to give a proper information about the error.
This will work both with wp and our rest apis.
2) when "not doing rest" hook to [`'before_delete_post'`](https://developer.wordpress.org/reference/hooks/before_delete_post/) performing the same checks as above and call `wp_die()` with a relevant message. This because if we leverage the capabilities in non-rest context WordPress will die with the default message `'Sorry, you are not allowed to delete this item.'` with no real way to alter it.

What do you think about this approach?

**Comment by thomasplevy** [comment]
This sounds like a solid plan. We should be able to call `wp_die()` with a more useful error message here though, right? Something like "Sorry, you are not allowed to delete a course with active subscriptions."

**Comment by eri-trabiccolo** [comment]
yeah:

> 2. when "not doing rest" hook to 'before_delete_post' performing the same checks as above and call wp_die() with a relevant message.

that's what I meant :D

**Comment by eri-trabiccolo** [comment]
@thomasplevy can you take a look at #1759 
I went for a simpler solution.
(I'm not blocked, working on the logic to determine whether a product has an attached active subscription so...)

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
so wc-subscription prevents the product deletion if connected to an existing subscription, even if canceled/refunded etc, while I was thinking to prevent the deletion only of products tied to an 'active' subscription, like that any other status allows the deletion, but, on the other hand it should be impossible then to switch the status of a recurring order related to a deleted product to 'active'. What do you think? Too much?

**Comment by thomasplevy** [comment]
I hadn't thought about this but now...

I think that we should prevent deletion of products connected to active, on-hold, and pending-cancel... Active & pending cancel both still allow users to access the content and on-hold means there's a missed payment and there's a *possible* retry scheduled which would allow them to regain access once they pay current.

For all other statuses I agree that we should *lock* status switching if connected to a deleted product. We can do that by adding a check on the metabox and preventing the change there, right?

**Comment by eri-trabiccolo** [comment]
@gocodebox/engineering 
When #1759 will be merged it'll be impossible to delete products with existing subscriptions, but what do you think we should do about recurring payments running for deleted products?
E.g. a product directly deleted from the DB for any reasons, or products deleted prior to this PR being merged?
Seems reasonable to me that when processing the recurring payment we check on the product existence, and if it doesn't exist we just block the payment and unschedule the next recurring payments.

What do you think?

**Comment by pondermatic** [comment]
@eri-trabiccolo, that sounds logical to me.

**Comment by thomasplevy** [comment]
@eri-trabiccolo thumbs up from me too
