### ISSUE TITLE
Some js texts are missing from translation

### ISSUE THREAD

**Issue by alaa-alshamy** [gocodebox/lifterlms#1464]
### Reproduction Steps

+ Open "Course builder" of any course
+ Edit any lesson
+ Hover over the tool tip of "Free lesson" for example
+ The text of the tool tip is not translatable ( because it's not exist in translation template(pot) to be translated )

see this screenshot:
![Screenshot from 2020-12-21 10-57-00](https://user-images.githubusercontent.com/2883734/102753053-997bd500-437b-11eb-8b49-cb055b9be5e3.png)

### Technical description

After some investigation i figured that those texts are not added to the POT file because they are not added to the "get_strings" function in this line:
https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.l10n.js.php#L38

and this file actually compiled automatically via the gulp as described in the head

```
<?php
/**
 * Localize JS strings
 * This file should not be edited directly
 * It is compiled automatically via the gulp task `pot-js`
 * See the lifterlms-lib-tasks package for more information
 *
 * @package  LifterLMS/Classes/Localization
 * @since    3.17.8
 * @version  4.7.0
 */
```
And i think the gulp script not adding them because those texts used in double quote in this line:
https://github.com/gocodebox/lifterlms/blob/trunk/assets/js/builder/Schemas/Lesson.js#L39

and the gulp script expect them to be in single quote in this line:
https://github.com/gocodebox/lifterlms-lib-tasks/blob/master/tasks/pot-js.js#L28

So if you searched about `LLMS.l10n.translate( "` you will find all those texts i mean

### Expected Behavior

+ It should be added to the POT file to be translated

### Actual Behavior

+ it's not exist in the POT file

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by alaa-alshamy** [comment]
The possible solutions:

- Fix the gulp script to make it expect the texts being in double quotes
- Change those texts to be in single quote

but i don't know what you prefer

**Comment by thomasplevy** [comment]
@alaa-alshamy 

Thanks for reporting this, we'll work on getting this fixed in a future version

**Comment by alaa-alshamy** [comment]
@thomasplevy Any news here ?

**Comment by thomasplevy** [comment]
@alaa-alshamy I've prioritized this as a future update and haven't begun work on it yet. Once we start working on it it'll be moved out of the "Future" milestone and assigned to one of us.

Thanks for your patience.

**Comment by kimcoleman** [comment]
There were just three strings that used the double quotes, so we reworded them slightly to not need an apostrophe. This will be resolved when this feature branch is merged and released: https://github.com/gocodebox/lifterlms/commit/fa84d1bc36f4519bdb82378e65a3a7ea48829847
