### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by jurasjo** [gocodebox/lifterlms#147]
Polish translation in proggress
https://github.com/jurasjo/lifterlms_pl

**Comment by thomasplevy** [comment]
@jurasjo,

Glad to see you're interest and enthusiasm for LifterLMS and I'm very excited to have you contribute translations but we don't manage translations via GitHub, instead, please head over to [GlotPress](https://translate.wordpress.org/projects/wp-plugins/lifterlms) and submit translations for your locale via the GlotPress translation interface.

This ensures the translations are accurate as they are verified by locale-specific translation editors.

Additionally, once a language in 95% translated the language packs are automatically downloaded and updated when updating LifterLMS via the WordPress Admin panel.

While we might, periodically add translation files to the LifterLMS core we'll include them by downloading the files from GlotPress after translations have been verified and approved by a translation editor.

You can read our full guidelines [here](https://lifterlms.com/docs/how-can-i-contribute-translations-to-lifterlms/) and learn more about translating WordPress in general [here](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/)

Thanks again!
