### ISSUE TITLE
PHP Notice when trying to retrieve next lesson from an empty sibling section

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1479]
### Reproduction Steps

+ Create a course with a section and a lesson
+ Then create another section, but do not add any lessons to it
+ Visit the first lesson on front (assuming it shows the lessons navigation).

### Expected Behavior

+ I'd expect to only see the Back to the Course button in the lessons navigation and no warnings.

### Actual Behavior

+ I see the  the Back to the Course button but also a PHP notice is logged.

(discovered this because of a rest-api test failing)

I introduced this in https://github.com/gocodebox/lifterlms/pull/1467

### Error Messages / Logs

```
[07-Jan-2021 10:56:54 UTC] PHP Notice:  Undefined offset: 0 in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/models/model.llms.lesson.php on line 926
```

### System and Environment Information

```

LifterLMS 4.10.2
```

### This issue has been recreated:

+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
> I introduced this in #1467

*We introduced this

**Comment by eri-trabiccolo** [comment]
Yeah we as a team, but I wanted to highlight the fact that the bug wasn't in the first version of the PR, the one that you implemented. :D

**Comment by thomasplevy** [comment]
Ahhh, I assumed that I introduced it and you we're being kind <3
