### ISSUE TITLE
Quiz score circle 

### ISSUE THREAD

**Issue by jurasjo** [gocodebox/lifterlms#148]
Quiz score circle is always red. Maybe it could be better if colour is green if quiz is passed?

**Comment by thomasplevy** [comment]
@jurasjo if you'd like to change the color, please consider using some custom CSS.

If you need help writing CSS please open a support ticket at https://lifterlms.com/my-account/my-tickets or at https://wordpress.org/support/plugin/lifterlms.

Take care,

**Comment by jurasjo** [comment]
I meant conditional colour changing depending on settings in quiz menu.

**Comment by thomasplevy** [comment]
@jurasjo in that case please submit a feature request at https://lifterlms.com/contact -- as per our [guidelines](https://github.com/gocodebox/lifterlms#support) this is not a support or feature request forum

Thanks,
