### ISSUE TITLE
Add a Database Indices to Improve Performance of Frequently-Running Queries

### ISSUE THREAD

**Issue by reedhewitt** [gocodebox/lifterlms#1484]
The short version: adding a few new indices on a couple of database tables made one of the often-running background processes in LifterLMS run seven times faster.  I'm posting it here in case it helps anyone else and in case it can be included in a future release of LifterLMS.

**Is your feature request related to a problem? Please describe.**

We noticed that LifterLMS was always running some variation of the following query (and by “always”, I mean these queries were literally running 24/7), and it appeared to be triggered by the cron event “llms_calculate_course_data”:

```sql
SELECT
    SQL_CALC_FOUND_ROWS u.ID AS id,
    (
      SELECT
          meta_value
        FROM
          wp_lifterlms_user_postmeta
        WHERE
          meta_key = '_status'
          AND user_id = id
          AND post_id IN (274)
        ORDER BY
          updated_date DESC LIMIT 1
    ) AS status,
    (
      SELECT
          updated_date
        FROM
          wp_lifterlms_user_postmeta
        WHERE
          meta_key = '_status'
          AND user_id = id
          AND post_id IN (274)
        ORDER BY
          updated_date DESC LIMIT 1
    ) AS `date`,
    m_last.meta_value AS last_name,
    m_last.meta_value AS first_name
  FROM
    wp_users AS u JOIN wp_usermeta AS m_first
      ON u.ID = m_first.user_id
    AND m_first.meta_key = 'first_name' JOIN wp_usermeta AS m_last
      ON u.ID = m_last.user_id
    AND m_last.meta_key = 'last_name'
  HAVING
    status IS NOT NULL
    AND status IN ('enrolled')
  ORDER BY
    date DESC,
    status ASC,
    last_name ASC,
    first_name ASC,
    id ASC
  LIMIT 0, 100
```

The limit number and post_id would change periodically as the batch job progressed.  Our WordPress instance has over 34,000 users, so it would take a long time to cycle through them all in sets of 100.  Also, the query shown above would take over 40 seconds to run, even on a big server (64GB RAM and 16 CPU cores) without much other load at the time.  Basically, one of our CPU cores was dedicated to running that query all day every day.

Looking in the LifterLMS Status > Tools & Utilities page, I saw an option to clear all the pending batch processes.  There were over 100,000 of them pending.  It appears that the batch processes were being initiated faster than they could be completed, and the queue was just getting deeper over time.

**Describe the solution you'd like**

I added a couple of indices to the table `wp_lifterlms_user_postmeta` in our database:
* Index on `meta_key`
* Composite index on `user_id`, `post_id`, and `meta_key`

That brought the query time down from an average of 46 seconds to 14 seconds.

Then I added a composite index in `wp_usermeta` on the columns `user_id` and `meta_key`, since the joins relied on those two.  (I’m sure a lot of other common WordPress queries will benefit as well — that index should exist by default).  That dropped the query time down to about 7 seconds on average.

The server still had a massive backlog of batch processes to run, so I cleared those in the Tools & Utilities page.  As far as I can tell, the query is now fast enough to keep up and we are not accumulating a backlog.

**Describe alternatives you've considered**

Thank you to @thomasplevy for pointing out that these queries can be throttled via filters: https://github.com/gocodebox/lifterlms/blob/3acc83349f82e2b6c7ab7477bc48454031b1a397/includes/processors/class.llms.processor.course.data.php#L175-L177

We don't need the reporting in our dashboard to be updated as frequently as the default, so we can use those filters to make these batch processes run less frequently.

**Comment by thomasplevy** [comment]
@reedhewitt 

After adding the indices on your site did you see any side effects (aside from the performance improvements)?

I'm mainly interested in knowing if the indices had any notable impact on the size of the tables in your DB. 

While I'm not opposed to some table alterations, I'm a bit hesitant to deploy a change without understanding the full scope of impact.

Additionally, we've identified some ways to improve the query in question without making any changes to the database tables. I'm thinking these changes (to code, not the database) will actually have a greater impact on this particular query without any potential (negative) side effects.

I should have something to look at pushed tomorrow after I get some tests written. Maybe you'd be interested in running a fork on a testing site and sharing some benchmarks?

In any event, thanks for bringing this to our attention and we'll stay in touch as we work on this.

**Comment by thomasplevy** [comment]
@reedhewitt Version 4.12.0 (now released) introduces some improvements to the queries in question here. I believe these are some pretty significant improvements that may "close" the issue you initially raised. Any feedback greatly appreciated.

I'm going to leave this open for the time being as we may yet add additional indices as you've suggested in the future

**Comment by reedhewitt** [comment]
@thomasplevy Thank you!  I will definitely check it out and report back here.

**Comment by reedhewitt** [comment]
@thomasplevy Here's what I've found with the latest version (4.13.0):

The data processor queries don't show up in the MySQL slow query log anymore, even with the threshold set to 2 seconds.  I'm also not seeing any noticeable CPU usage by MySQL when there are no active users on the website.  (We have WP cron triggered by a server cron, not by visitor activity, so background processes would still be running.)  I removed the database indices that I added previously on `wp_lifterlms_user_postmeta` to confirm that the updates are resolving the performance issue even without those in place.

I did just notice something else related to my original post.  In some places, such as when opening the editor page for a membership, there is a query very similar to what I was seeing before in the background process.  It takes over 50 seconds to run without the indices that I created, and it takes about 2 seconds to run with those indices.  Here are the details from the MySQL slow query log without the indices:

```SQL
# Query_time: 53.318933  Lock_time: 0.000209  Rows_sent: 20  Rows_examined: 2800483
# Rows_affected: 0  Bytes_sent: 791
SET timestamp=1611848923;
SELECT SQL_CALC_FOUND_ROWS u.ID as id, ( SELECT meta_value
                                FROM wp_lifterlms_user_postmeta
                                WHERE meta_key = '_status'
                                  AND user_id = id
                                  AND post_id IN ( 145118 )
                                ORDER BY updated_date DESC
                                LIMIT 1 ) AS status, m_last.meta_value AS last_name, m_first.meta_value AS first_name
                        FROM wp_users AS u
                        JOIN wp_usermeta AS m_first ON u.ID = m_first.user_id AND m_first.meta_key = 'first_name' JOIN wp_usermeta AS m_last ON u.ID = m_last.user_id AND m_last.meta_key = 'last_name'
                        
                        HAVING status IS NOT NULL AND status IN ( 'cancelled','enrolled','expired' )
                        ORDER BY last_name ASC, first_name ASC, id ASC
                        LIMIT 0, 20;
```

And with the indices:

```SQL
# Query_time: 1.734853  Lock_time: 0.000143  Rows_sent: 20  Rows_examined: 165262
# Rows_affected: 0  Bytes_sent: 791
SET timestamp=1611849068;
SELECT SQL_CALC_FOUND_ROWS u.ID as id, ( SELECT meta_value
                                FROM wp_lifterlms_user_postmeta
                                WHERE meta_key = '_status'
                                  AND user_id = id
                                  AND post_id IN ( 145118 )
                                ORDER BY updated_date DESC
                                LIMIT 1 ) AS status, m_last.meta_value AS last_name, m_first.meta_value AS first_name
                        FROM wp_users AS u
                        JOIN wp_usermeta AS m_first ON u.ID = m_first.user_id AND m_first.meta_key = 'first_name' JOIN wp_usermeta AS m_last ON u.ID = m_last.user_id AND m_last.meta_key = 'last_name'
                        
                        HAVING status IS NOT NULL AND status IN ( 'cancelled','enrolled','expired' )
                        ORDER BY last_name ASC, first_name ASC, id ASC
                        LIMIT 0, 20;
```

The only difference between those two is that I added an index in `wp_lifterlms_user_postmeta` on `meta_key` and a composite index on `user_id`, `post_id`, and `meta_key`.  I know it is not just the result of caching the query because I added and removed the indices several times and got consistent results.

I checked on the size difference of the index before and after.  For 185 MB of source data, the index grew from 600 MB to 811 MB with those new indices.

With the indices in place it is working great for us and we don't mind the extra index size.  So this isn't a problem per se, but I just wanted to pass along what I found.

**Comment by thomasplevy** [comment]
@reedhewitt 

I realized I never responded to this.

At the moment I'm going to leave this for future development as the query in question will be quite difficult to improve given what's needed to pull the information found in the metabox. There's a lot of alternative solutions and I'm really hesitant to add the indicies as you've identified due to the increase in size. Users who aren't having any problems may start having issues (with their shared host telling them their DB is too big). 

Users who do need an index can add one as you have.

I'm always super hesitant to make potentially large changes without having information from at least a few users having a problem like this. If I was getting reports of this kind of slowness every day or even once a month I'd jump on the change but as of now I think we're going to create more complaints than we'll resolve. So we'll have to wait.

**Comment by reedhewitt** [comment]
Thanks for the reply.  That all makes sense about not including the indices by default.
