### ISSUE TITLE
Access Plans not displaying on imported course template

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1490]
### Reproduction Steps

+ Import Course Template
+ Notice 3 access plan boxes are visible on the backend but not on the front end 

<img width="1453" alt="Course_Template_–_A_LifterLMS_Sandbox" src="https://user-images.githubusercontent.com/12163552/104776025-60027380-5747-11eb-82db-8011e6f1877f.png">

### Expected Behavior

+ Access plan should be visible on front end

### Actual Behavior

+ Access plan isn't visible

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

Wordpress
-------------------------------------------

Home Url: https://proud-violet.myliftersite.com
Site Url: https://proud-violet.myliftersite.com
Login Url: https://proud-violet.myliftersite.com/wp-login.php
Version: 5.6
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes

Settings
-------------------------------------------

Version: 4.11.0
Db Version: 4.11.0
Course Catalog: Course Catalog (#5) [https://proud-violet.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#6) [https://proud-violet.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#8) [https://proud-violet.myliftersite.com/dashboard/]
Checkout Page: Purchase (#7) [https://proud-violet.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no

Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1

Server
-------------------------------------------

Mysql Version: 5.7.32
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.26
Software: Apache/2.4.46 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M

Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Theme
-------------------------------------------

Name: Kadence
Version: 1.0.11
Themeuri: https://www.kadence-theme.com/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No

Plugins
-------------------------------------------

LifterLMS: 4.11.0

Integrations
-------------------------------------------

BbPress: No
BuddyPress: No

Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 4.4.0): /srv/users/manager/apps/proud-violet/public/wp-content/themes/kadence/lifterlms/ (ver: 3.19.2)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/proud-violet/public/wp-content/themes/kadence/lifterlms/ (ver: 3.24.0)

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ x] On a staging site
+ [ ] On a production website
+ [x ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@chrisbadgett 
It could happen when you have no payment gateway set: in that case only free access plans are visible.

Either enable e.g. the manual payment or set up a free access plan...

Can be that?

**Comment by thomasplevy** [comment]
@chrisbadgett

LifterLMS automatically prevents plans from being displayed when there is no payment gateway available to "support" the checkout process for the gateway.

So if you have no payment gateways enabled, paid access plans can't be viewed.

**Comment by chrisbadgett** [comment]
Thanks! I did not realize that was the case. I must have skipped the manual gateway option in the setup wizard (which I usually don't) so that must have been my mixup.
