### ISSUE TITLE
Missing stylesheets in saved certificates, when serving them (stylesheets) trough a CDN.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1509]
### Reproduction Steps
Edit:

What I said below, while it's technically true, doesn't take into account the fact that, because of this line:
https://github.com/gocodebox/lifterlms/blob/4.13.0/includes/class.llms.certificates.php#L263-L265
we totally skip external stylesheets, and remove them later:
https://github.com/gocodebox/lifterlms/blob/4.13.0/includes/class.llms.certificates.php#L285-L289

~~This is more a guess based on the code and on something I could actually reproduce.
Basically I theorized this when handling the ticket HS-151532 
I suggested to disable the CDN and that very issue seemed to be resolved, so I'm quite sure my guess was good.
Also because I verified that retrieving one of those stylesheets hosted on the CDN with `file_get_content()` on my machine - with `fopen_wrappers` disabled - was working fine, so it _shouldn't_ be a problem related to the CDN settings/firewall. All these are guesses at this stage.~~

~~So let's go with reproduction steps.
(implies [fopen_wrappers](https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) are disabled).~~

+ Use CDN for your stylesheets :D
or
+ for testing purposes, you can just enqueue some external stylesheet
+ save a certificate 
+ Inspect the html

### Expected Behavior

+ I'd expect the style to be correctly inlined

### Actual Behavior

+ You'll not see the "external" stylesheet enqueued no

The problem is that I think we "assume" that all the stylesheets are local here:
https://github.com/gocodebox/lifterlms/blob/4.13.0/includes/class.llms.certificates.php#L263-L265

Also we need to keep in mind that if we just avoid that skip we can still have problems retrieving external stylesheets via `file_get_contents()`.
https://github.com/gocodebox/lifterlms/blob/4.13.0/includes/class.llms.certificates.php#L268-L269

We know that we just can't assume `file_get_contents()` will work when using URLs, so I think that when we get an external URL we should go with curl (or `wp_remote_get()`).

The idea is to keep skipping some external sylesheets: e.g. fonts cdn (with a filterable blocklist); but to retrieve remote ones.

### Error Messages / Logs

n/a

### System and Environment Information

LiferLMS 4.13.0

</details>

### This issue has beeb recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information

HS-151532

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
on a further analysis I see that we don't "inline" external images as well, but in this case we leave them in the certificate document as they are: with the original external src.

I think we should apply the same principle: use `wp_remote_get()` for external images too.

**Comment by thomasplevy** [comment]
Sounds good

**Comment by nrherron92** [comment]
Can we bump priority for this issue? Our user is still very interested in a solution and has been asking for updates

**Comment by thomasplevy** [comment]
@nrherron92 thanks for the update, this is now on @eri-trabiccolo task list for this week, our hope is to ship a fix later this week.

In the meantime we noticed that the customer was told to reenable the CDN, if the CDN is enabled this problem will *continue* to happen. So they should probably be advised that they were advised to reenable the CDN in error. In short: since we have a problem working with CDNs at the moment CDNs should be disabled for the cert.

Any questions let me know.

**Comment by nrherron92** [comment]
@thomasplevy when he has CDNs off he sees the errors on the course catalog (edit: not the course catalog the student dashboard my courses) screen and the certificate without trying to save. If we have him turn it off again is there a way to hide those errors?

**Comment by thomasplevy** [comment]
@nrherron92 I have no idea what's causing those. Sorry I didn't see that I just saw you say "Turn back on the CDN" and didn't read any further.

Ignore my above message. I'm not going to get roped into debugging that too right now. We'll just fix the CDN issue and carry on.
