### ISSUE TITLE
Enroll in membership auto-enroll courses "on demand" instead of all at once

### ISSUE THREAD

**Issue by reedhewitt** [gocodebox/lifterlms#1516]
@thomasplevy, we talked on Slack about the idea of postponing student enrollment in all the auto-enroll courses for a membership level.  On our large site with a lot of courses (43 in our main membership level), the auto-enrollment was bogging down the server because it happened immediately when customers completed checkout to purchase a membership.  If we had any significant number of checkouts happening at the same time, the auto-enrollment activity would bring our server to a crawl.

Here’s an update on my experiment with the “enrollment on demand.”  I was able to add a few filters so that a student does not immediately get enrolled in a membership's auto-enroll courses, however the student will be automatically and seamlessly enrolled in any of those courses at the moment when they try to view them.  There is only one code modification in a LifterLMS file to make this possible: I added a filter named `courses_shortcode_get_post__in` which is described with the last code block below.

I started by looking into `llms_page_restricted`, which you recommended, but I didn't end up adding the filter there because `$student->is_enrolled( $restriction_id )` gets called right before the filter is applied, so it was just a little too late.  The following three filters are what worked for us.

The first filter hides the auto-enrollment list from `LLMS_Student::add_membership_level()`.  The only way I could do it was to filter `get_post_meta`, but a more specific filter could be added within `LLMS_Student::add_membership_level()`.

```php
// If the auto_enroll list is checked while adding a membership level, ignore that
// request by returning an empty array. This is how we avoid doing the auto-enrollment
// immediately at checkout when the customer gets assigned a membership level.
function maybe_hide_llms_auto_enroll($value, $object_id, $meta_key, $single){
    if(!empty($meta_key) && $meta_key == '_llms_auto_enroll'){
      
      // Use the backtrace to see if this was invoked by LLMS_Student::add_membership_level().
      $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
      
      foreach($backtrace as $function_call){
        if(
            isset($function_call['function'])
            && isset($function_call['class'])
            && $function_call['function'] == 'add_membership_level'
            && $function_call['class'] == 'LLMS_Student'
          ){
          // Return an empty array wrapped in an array, because the get_post_metadata
          // filter always expects the return value to be wrapped in an array.
          return [[]];
        }
      }
      
      // If this meta lookup was not initiated by LLMS_Student::add_membership_level()
      // then we want to return the real value.  We must remove the current filter
      // to do that so we don't enter an infinite loop.
      remove_filter('get_post_metadata', 'maybe_hide_llms_auto_enroll', 10);
      $value = [get_post_meta($object_id, $meta_key, true)];
      add_filter('get_post_metadata', 'maybe_hide_llms_auto_enroll', 10, 4);
    }
    
    return $value;
}
add_filter('get_post_metadata', 'maybe_hide_llms_auto_enroll', 10, 4);
```

This next filter is the thing that actually does the enrollment.  It happens at the point when a student’s enrollment status is being checked.  If the check initially says that the student is not enrolled, the this function looks at the student’s membership levels and determines if the course is in the auto-enroll list for one of those memberships.  If so, it does the enrollment.  The function goes on to return an accurate value for `$is_enrolled`, taking into account the “all” or “any” value of `$relationship` and any other courses that are being checked at the same time.

```php
// Enroll a student in a course at the time enrollment is checked if they have
// access via there membership auto-enroll settings.
function enroll_on_demand($is_enrolled, $student, $product_ids, $relation, $use_cache){
  // Only do additional checking if the student is not enrolled.
  if(!$is_enrolled){
    // We'll need all the student's memberships.
    $memberships = $student->get_memberships([
      'limit'   => 1024,
      'status'  => 'enrolled'
    ]);
    
    // An array that will use the contents of $product_ids as keys.
    $enrollment_statuses = [];
    
    foreach($product_ids as $product_id){
      $course_id = null;
      $post_type = get_post_type($product_id);
      
      if($post_type == 'course'){
        $course_id = $product_id;
      } elseif($post_type == 'lesson'){
        $lesson = new LLMS_Lesson($product_id);
        $course_id = $lesson->get_parent_course();
      }
      
      // If we are working with a course, then see if the course is one of the "auto-enroll"
      // courses for one of the student's memberships.
      if($course_id){
        foreach($memberships['results'] as $membership_id){
          $auto_enroll_course_ids = get_post_meta($membership_id, '_llms_auto_enroll', true);
          foreach($auto_enroll_course_ids as $auto_enroll_course_id){
            // If we found an auto-enroll course ID that matches the current course ID...
            if($course_id == $auto_enroll_course_id){
              // Temporarily remove this filter so it doesn't cause an infinite loop when
              // called from inside the $student->enroll() method.
              remove_filter('llms_is_user_enrolled', 'enroll_on_demand', 10);
              
              // Enroll the student in this course.
              $student->enroll($course_id, 'on-demand-via-membership');
              
              // Add this filter back in place.
              add_filter('llms_is_user_enrolled', 'enroll_on_demand', 10, 5);
              
              $enrollment_statuses[$product_id] = true;
            } else {
              // If this course did not appear in the auto-enroll list, either use a true value
              // from a previous membership check, or use the get_enrollment_status() method.
              $enrollment_statuses[$product_id] = !empty($enrollment_statuses[$product_id]) || ('enrolled' === strtolower($student->get_enrollment_status($course_id, $use_cache)));
            }
          }
        }
      } else {
        $enrollment_statuses[$product_id] = ('enrolled' === strtolower($student->get_enrollment_status($product_id, $use_cache)));
      }
    }
    
    if($relation == 'all'){
      // For "all", $is_enrolled is reset to true because it can be made false by any single product.
      $is_enrolled = true;
      foreach($enrollment_statuses as $id => $status){
        $is_enrolled = $is_enrolled && $status;
      }
    } elseif($relation == 'any'){
      // For "any", $is_enrolled is reset to false because it can be made true by any single product.
      $is_enrolled = false;
      foreach($enrollment_statuses as $id => $status){
        $is_enrolled = $is_enrolled || $status;
        if($is_enrolled){
          break;
        }
      }
    }
  }
  
  return $is_enrolled;
}
add_filter('llms_is_user_enrolled', 'enroll_on_demand', 10, 5);
```

The final filter allows a user to see courses that are displayed by the `[lifterlms_courses]` shortcode when it is set up to only display courses that are “mine” (enrolled and available).  To make this work, I had to add a filter to `lifterlms/includes/shortcodes/class.llms.shortcode.courses.php` on line 89.  I put a filter on the return value of `get_post__in()` like this: `return apply_filters('courses_shortcode_get_post__in', $ids, $student, $mine);`.  This is the only change I made to a LifterLMS plugin file.  I couldn’t find any other way to insert the membership auto-enroll course IDs into the list that are considered “mine”.

```php
// When the [lifterlms_courses] shortcode checks to see what courses are "mine",
// include courses that my membership gives me access to, even if I haven't been
// auto-enrolled in them yet.
function add_courses_accessible_to_student_via_membership($ids, $student, $mine){
  if(!is_object($student) || !method_exists($student, 'get_memberships') || ($mine != 'any' && $mine != 'enrolled')){
    return $ids;
  }
  
  $additional_ids = [];
  $memberships = $student->get_memberships([
    'limit'   => 1024,
    'status'  => 'enrolled'
  ]);
  
  foreach($memberships['results'] as $membership_id){
    $auto_enroll_course_ids = get_post_meta($membership_id, '_llms_auto_enroll', true);
    $additional_ids = array_merge($additional_ids, $auto_enroll_course_ids);
  }
  
  if(!empty($additional_ids)){
    $ids = array_unique(array_merge($ids, $additional_ids));
  }
  
  return $ids;
}
add_filter('courses_shortcode_get_post__in', 'add_courses_accessible_to_student_via_membership', 10, 3);
```

With these filters in place we noticed a major reduction in server load during an event that brought a lot of customers to the checkout at the same time.  We handled about twice as many customers as our previous major event with about half the server load.

This solution is working well for us at the moment.  It would be great to see the filter `courses_shortcode_get_post__in` added to the LifterLMS source code.

**Comment by thomasplevy** [comment]
@reedhewitt 

Makes sense.

I'd be happy to have this filter, [PRs are welcome](https://github.com/gocodebox/lifterlms/blob/trunk/.github/CONTRIBUTING.md#contributing-code)!

**Comment by thomasplevy** [comment]
Oh... and two notes:

1) pulling autoenrollment courses via the method `LLMS_Membership::get_autoenroll_courses()` is probably preferable to pulling the metadata directly.

This will first off guarantee an array if the metadata isn't set (which is possible!) and will also ensure filters are applied. The core doesn't use the filter anywhere but, you know, things could change and this helps with forward compatibility.

Source: https://developer.lifterlms.com/reference/classes/llms_membership/get_auto_enroll_courses/

2) You might actually prefer to use `LLMS_Membership::get_associated_posts()`

This method is used, currently, only by add-ons (Groups) but in the future will likely be used internally also as we enhance membership capabilities to do some of what I'm sure you'd like LifterLMS to do on it's own (but doesn't currently).

In addition to including the autoenrll courses, it will also automatically pull in data from any course that is associated with the membership through a members-only access plan. Based on your use case this may not matter in which case using item 1 would be better.

Source: https://developer.lifterlms.com/reference/classes/LLMS_Membership/get_associated_posts/

**Comment by reedhewitt** [comment]
Thanks for the tips!  I'll look into those two methods.  I'll also submit a pull request with the filter.

**Comment by thomasplevy** [comment]
Leaving this open, if you do decide to submit a PR we'll close when it gets merged or, if you don't, we'll close it when we do so internally (and merge)

Thanks!
