### ISSUE TITLE
Text Editor Visual Editor Won't Switch

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1553]
### Reproduction Steps

+ Create a course with a custom sales page
+ Add content to the custom sales page in the text editor
+ try to switch to the visual // save and switch to visual

### Expected Behavior

+ The content will show up under the visual editor

### Actual Behavior

+ the visual editor is blank and cannot be clicked into to edit
+ if the visual editor is not blank it still cannot be clicked into to edit. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

HS-156151

**Comment by thomasplevy** [comment]
@eri-trabiccolo you're saying you can reproduce 8/10 times but I can't reproduce at all. Any clarification would be helpful!

**Comment by thomasplevy** [comment]
I can't reproduce with `define( 'SCRIPT_DEBUG', true )` but pretty reliably reproducible without this.

Possibly related: https://core.trac.wordpress.org/ticket/19173

**Comment by thomasplevy** [comment]
I fixed this. PR incoming.
