### ISSUE TITLE
Delete empty (malformed) admin notices

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1560]
### Reproduction Steps

This is something I've found when troubleshooting a customer's issue.
They needed to use the Reset Automatic Payments Status tool in order to re-enable the recurring payments feature.
The problem was that the notice which prompts the user to choose whether to re-enable them or not was not shown.
I've investigated and found that the reason was that the notice was already present in the db (so it was not re-added) but it was empty (I couldn't find the reason why it was empty, nor I could reproduce it on the customer's website after removing and re-generating it). This prevented it to be shown, but also to be re-added.

### Expected Behavior

+ I'd expect that an empty notice is deleted so it can be added again.

### Actual Behavior

+ The empty notice is not shown but not deleted so it cannot be re-added. This is particularly bad for the recurring payments feature as that notice is the only way (via UI, so excluding the definition of constants) to toggle the feature.

We already treat a similar case here:
https://github.com/gocodebox/lifterlms/blob/4.19.0/includes/admin/class.llms.admin.notices.php#L306-L308

but we don't account for a totally empty notice :(
Also, we should return after deleting the notice...

### Error Messages / Logs

```
n/a
```

### System and Environment Information

```
LifterLMS 4.19.0
WordPress 5.7.0

```

### This issue has been recreated:

+ [ ] Locally 
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information

HS-158371

**Comment by thomasplevy** [comment]
@eri-trabiccolo

By a "totally empty" notice do you mean it's like `array()`? Or something like this?

We do "handle" that above

https://github.com/gocodebox/lifterlms/blob/6ae53c607594768f9d70f4e2b94507e6fd211f8b/includes/admin/class.llms.admin.notices.php#L300

but you're right that it's not deleted like these malformed notices you reference. I think we can probably combine these two conditions into one and delete them when found (and, return early, as you've noted)

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Yeah I know we handle the "totally empty" case, we just don't handle as we should :) : delete the empty notice before returning.
