### ISSUE TITLE
LifterLMS 5.0.0 Beta Testing and Feedback

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1573]
## Add-on Compatibility

+ [x] Social Learning - Edit account page has custom fields added via the pre 5.x API
+ [x] Groups - Open Registration should continue to work with a custom registration form
+ [x] Formidable Forms (with user reg / account edit)
+ [x] Gravity Forms (with User Registration / account edit) 
+ [x] Ninja Forms (with user reg / account edit)
+ [x] WP Forms (with user reg)

## Pre 5.x API Code Snippets

+ [x] Ensure code snippets with the pre 5.x API continue to work as expected (they should, but we need to run some explicit tests)

## Theme Compatibility

We should test compatibility with themes we [recommend](https://rel-500-a2.myliftersite.com/purchase/?plan=16&llms-view-as=visitor&view_nonce=3e4b67da94)

Where possible, we should enlist the assistance of theme developers to help us test compatibility

+ [x] Astra
+ [ ] Authority Pro
+ [x] BuddyBoss
+ [ ] Course Maker Pro
+ [x] Divi
+ [ ] Emerson
+ [x] Genesis
+ [x] Kadence
+ [ ] Magazine Pro
+ [ ] Monochrome Pro
+ [x] Neve
+ [x] Ocean WP
+ [ ] Page Builder Framework
+ [ ] Revolution Pro
+ [ ] Sage
+ [ ] Ventura

## Internal Q&A / Testing / Etc...

Each of the following team members will test 5.0.0 functionality and report bugs / issues / feedback

+ [ ] @chrisbadgett 
+ [ ] @nrherron92 
+ [ ] @toyinogunseinde 
+ [ ] @willmiddleton-lifterlms

**Comment by thomasplevy** [comment]
:heavy_check_mark: Social Learning

Editing profile fields works as expected

We have to remove the (now redundant) "display name" field though: https://github.com/gocodebox/lifterlms-social-learning/issues/48

**Comment by thomasplevy** [comment]
:heavy_check_mark: Groups

Editing profiles & open registration work as expected

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm assigning you to this issue to assist with testing against our form add-ons please <3

**Comment by eri-trabiccolo** [comment]
I'd say
✔️ Forms add-ons

I just checked the forms were correctly replaced, and pushed PR to make it happen when they didn't.
