### ISSUE TITLE
[5.0.0] Password Length is not validated on form submission (via PHP)

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1574]
### Reproduction Steps

+ This is only easy to see by faking submitted form data (thanks to html5 validation), however, we should be validating the password length via PHP anyway

### Expected Behavior

+ A password that is too short for the selected min length should return an error

### Actual Behavior

+ The password is accepted

**Comment by magicemilymiddleton** [comment]
I'm not sure if this is a related issue or a new issue, on this site, my password always is 'very weak':

https://will-video.myliftersite.com/purchase/?plan=474

<img width="1302" alt="Screen Shot 2021-04-30 at 11 13 44 AM" src="https://user-images.githubusercontent.com/76497148/116723427-262b4500-a9a5-11eb-8ef8-fb44729eb8fa.png">

**Comment by thomasplevy** [comment]
@willmiddleton-lifterlms this was fixed in
https://github.com/gocodebox/lifterlms/pull/1478/commits/4f568a7ad2da47b2b4e92e498c6758870bc0c59d
Not released yet though
