### ISSUE TITLE
[5.x] UX for forms missing required fields

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1589]
Currently we apply "validation" within the block editor when the User Email field is deleted/removed from a form. An error notice is added to the editor with an action button to restore the required field. This *basically* works but it's a little hacky and I think a server-side solution should be applied as well.

In the event that a required field is missing from a form, I think we should add the field dynamically (with base settings) via PHP on page load.

This will ensure that if there's any amount of monkeying the forms will continue to function.

Additionally, I'm not sure whether or not we should define the user password field as required as well.

I had initially wished to build a passwordless registration flow which would allow users to remove the password creation and trigger a password reset email after account creation. This is a not uncommon registration flow:

1. Enter email
2. Receive an email
3. Click the link
4. Add your password
5. Login

If we keep password as an "optional" field we need to add a handler to fire off the reset email upon account creation. Currently it's broken if password is ommitted.

Finally, on the account edit screen I think we should *force* email AND password to always be editable but allow users to determine what other fields they want on their account edit form. This means that we'll likely need to add some conditional behavior to determine what fields are required based on the form location.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I did the basic fix in #1688 meaning that I add the email field via PHP on checkout/registration form.

What about this instead?
> In the event that a required field is missing from a form, I think we should add the field dynamically (with base settings) via PHP on page load.
> 
> This will ensure that if there's any amount of monkeying the forms will continue to function.

I don't even understand what this means :D a required field is missing from a form, if it's missing how can it be required?
Can you elaborate with a use case?
Thanks <3

I also think that both the two below should be addressed in another issue. what do you think?

> Additionally, I'm not sure whether or not we should define the user password field as required as well.
> 
> I had initially wished to build a passwordless registration flow which would allow users to remove the password creation and trigger a password reset email after account creation. This is a not uncommon registration flow:
> 
> Enter email
> Receive an email
> Click the link
> Add your password
> Login
> If we keep password as an "optional" field we need to add a handler to fire off the reset email upon account creation. Currently it's broken if password is ommitted.
> 
> Finally, on the account edit screen I think we should force email AND password to always be editable but allow users to determine what other fields they want on their account edit form. This means that we'll likely need to add some conditional behavior to determine what fields are required based on the form location.

**Comment by thomasplevy** [comment]
@eri-trabiccolo Your solution in #1688 looks pretty solid to me (with minor changes I noted in my review)

I think that for a password-less registration we can handle that entirely separately, yes
