### ISSUE TITLE
[5.x] Logged in Enrollment

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1594]
### Reproduction Steps

+ Log into an account on the site
+ Go into a course or membership and attempt to enroll with an access plan

### Expected Behavior

+ Since the account is already logged in the email address should be pulled from the user's account and not be a required field.

### Actual Behavior

+ The check does not go through because it requires an email address field

![image](https://user-images.githubusercontent.com/47434271/114738889-0261d100-9d0e-11eb-8143-30376a23f88a.png)

### Error Messages / Logs

+ Include any relevant error messages or log files

This shows up in the console logs:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-He578RhxGHfIAZJusM5BQ02z9lVgRg1l9EFI7m/QpyM='), or a nonce ('nonce-...') is required to enable inline execution.

```

### System and Environment Information

https://natalie-5-testing.myliftersite.com/purchase

**Comment by thomasplevy** [comment]
@nrherron92 for the time being so you can continue testing add the email address field as a *visible* field for all users (not just logged out) and we'll get this fixed in the next prerelease

**Comment by thomasplevy** [comment]
I haven't confirmed it but the logic seems sound that the field requirment checks aren't looking at the field's visibility settings

**Comment by nrherron92** [comment]
@thomasplevy will do! I'm nearly done with testing I'm just waiting to hear back from divisoup about access to those themes

**Comment by thomasplevy** [comment]
Fixed in beta.4
