### ISSUE TITLE
process_course_data arguments in multiple llms_background_process_course_data_batch rows

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#1602]
### Reproduction Steps

I'm not sure of the steps to reproduce this issue.

It appears that it is possible for `LLMS_Processor_Course_Data->dispatch_calc()` to add a new task with a course ID and page number to an existing batch, which is then saved as a new batch. So now there are multiple batches that contain the same task.

### Expected Behavior

When `LLMS_Processor_Course_Data->dispatch_calc()` is called, a new batch is saved containing tasks for only the given course ID.

### Actual Behavior

In the wp_options table, I have
```
llms_background_process_course_data_batch_49929a7ab6937b11bad017 = a:1:{i:0;a:5:{s:7:"post_id";s:5:"12926";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}}

llms_background_process_course_data_batch_2bd6ccdf7c02c959dac0d0 = a:2:{i:0;a:5:{s:7:"post_id";s:5:"12926";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}i:1;a:5:{s:7:"post_id";s:5:"13076";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}}

llms_background_process_course_data_batch_ec0b0ed1824c59b8a2e09d = a:3:{i:0;a:5:{s:7:"post_id";s:5:"12926";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}i:1;a:5:{s:7:"post_id";s:5:"13076";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}i:2;a:5:{s:7:"post_id";s:5:"13083";s:8:"statuses";a:1:{i:0;s:8:"enrolled";}s:4:"page";i:1;s:8:"per_page";i:100;s:4:"sort";a:1:{s:2:"id";s:3:"ASC";}}}
```

etc.

This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On two production websites
+ [ ] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment]
@pondermatic 

Are you certain that this isn't a side effect of #1598 and / or #1600 ?

I'm struggling to recreate this on my local...

**Comment by thomasplevy** [comment]
> ### Expected Behavior
> When `LLMS_Processor_Course_Data->dispatch_calc()` is called, a new batch is saved containing tasks for only the given course ID.

I'd also like to note that having multiple courses in the same batch isn't unexpected behavior. This can happen if you're enrolling a user into a membership that causes the user to be enrolled into multiple courses.

We shouldn't be seeing multiple batches in that scenario though, you'd see a single batch with multiple courses.

**Comment by pondermatic** [comment]
I've struggled to find the steps to reproduce this issue for many months. Usually, I give up and use the "Delete processor batches" LifterLMS tool. But I'm worried that I'm causing calculated data to be stale.

**Comment by pondermatic** [comment]
> Are you certain that this isn't a side effect of #1598 and / or #1600 ?

I am not certain.

**Comment by pondermatic** [comment]
I believe this issue can be reproduced by calling `dispatch_calc()` twice with different course IDs.

Here is a unit test I'm working on.
```php
	/**
	 * Test dispatch_calc() with multiple courses to make sure that tasks are not duplicated in other batches.
	 *
	 * @since [version]
	 *
	 * @return void
	 */
	public function test_duplicate_batch_tasks() {

		$course_ids[] = $this->factory->post->create( array( 'post_type' => 'course' ) );
		$course_ids[] = $this->factory->post->create( array( 'post_type' => 'course' ) );
		foreach ( $course_ids as $course_id ) {
			$this->factory->student->create_and_enroll_many( 5, $course_id );
		}
		$this->logs->clear( 'processors' );

		$handler = function ( $args ) {
			$args['per_page'] = 2;

			return $args;
		};
		add_filter( 'llms_data_processor_course_data_student_query_args', $handler );

		$expected_logs = array();
		foreach ( $course_ids as $course_id ) {
			$this->main->dispatch_calc( $course_id );
			$expected_logs[] = "Course data calculation dispatched for course {$course_id}.";
		}
		// Logged properly.
		$this->assertEquals( $expected_logs, $this->logs->get( 'processors' ) );

		foreach ( $course_ids as $course_id ) {
			$batch = LLMS_Unit_Test_Util::call_method( $this->main, 'get_batch' );

			// Test data is loaded into the queue properly.
			foreach ( $batch->data as $i => $student_query_args ) {
				$this->assertEquals( $course_id, $student_query_args['post_id'], 'course_id' );
				$this->assertEquals( 2, $student_query_args['per_page'], 'per_page' );
				$this->assertEquals( array( 'enrolled' ), $student_query_args['statuses'], 'statuses' );
				$this->assertEquals( ++ $i, $student_query_args['page'], 'page' );
			}

			// Simulate handling of queued batched tasks.
			LLMS_Unit_Test_Util::call_method( $this->main, 'delete', array( $batch->key ) );
		}

		remove_filter( 'llms_data_processor_course_data_student_query_args', $handler );
	}
```
It is similar to `test_dispatch_calc_success()` but uses two courses.

**Comment by pondermatic** [comment]
Here is the processor log after I run this code.
```php
$processor = new LLMS_Processor_Course_Data();
$processor->schedule_calculation( 50 );
$processor->schedule_calculation( 87 );
```
```
2021-04-19 14:06:25 - Course data calculation triggered for course 50.
2021-04-19 14:06:25 - Course data calculation scheduled for course 50.
2021-04-19 14:06:25 - Course data calculation triggered for course 87.
2021-04-19 14:06:25 - Course data calculation scheduled for course 87.
2021-04-19 14:07:30 - Course data calculation dispatched for course 50.
2021-04-19 14:07:31 - Course data calculation task called for course 50 with args: {"post_id":50,"statuses":["enrolled"],"page":1,"per_page":100,"sort":{"id":"ASC"}}
2021-04-19 14:07:31 - Course data calculation task completed for course 50 with data: {"students":1,"progress":100,"quizzes":0,"grade":0}
2021-04-19 14:07:31 - Course data calculation completed for course 50.
2021-04-19 14:07:31 - Course data calculation dispatched for course 87.
2021-04-19 14:07:32 - Course data calculation task called for course 50 with args: {"post_id":50,"statuses":["enrolled"],"page":1,"per_page":100,"sort":{"id":"ASC"}}
2021-04-19 14:07:32 - Course data calculation task completed for course 50 with data: {"students":1,"progress":100,"quizzes":0,"grade":0}
2021-04-19 14:07:32 - Course data calculation completed for course 50.
2021-04-19 14:07:32 - Course data calculation task called for course 87 with args: {"post_id":87,"statuses":["enrolled"],"page":1,"per_page":100,"sort":{"id":"ASC"}}
2021-04-19 14:07:32 - Course data calculation task completed for course 87 with data: {"students":1,"progress":100,"quizzes":0,"grade":0}
2021-04-19 14:07:32 - Course data calculation completed for course 87.
```
Course 50 is needlessly processed twice. Under light loads, this is not a big deal. But on busy sites, the tasks pile up and never finish.

**Comment by eri-trabiccolo** [comment]
Very interesting, I wonder if with 3 courses the even the second course is processed twice, and the first triple...
and if this happens only when the `$processor` instance is the same one..., and or if it happens even when schedule the calculations in different sessions.

**Comment by thomasplevy** [comment]
mmm thanks @pondermatic I think this actually highlights an issue that would occur when bulk enrolling users into courses associated with a membership. This is the only way I could see this happening. Just to put my mind at ease does it seem like this could be the entrypoint for this bug presenting itself on your site?

I've lifted your test and I'm including it in a PR in a moment to fix the issue. Thanks for that, it helped me clarify how you could be seeing what you're seeing <3

**Comment by pondermatic** [comment]
> I think this actually highlights an issue that would occur when bulk enrolling users into courses associated with a membership. This is the only way I could see this happening. Just to put my mind at ease does it seem like this could be the entrypoint for this bug presenting itself on your site?

We aren't using the LifterLMS bulk enroll feature, but are likely doing something similar. On two of our sites, we have a feature that enables enrolling in all courses assigned to a course category when a user is enrolled in a special course that points to the category.

**Comment by pondermatic** [comment]
Thanks @thomasplevy. Emptying out the `$this->data` array in `LLMS_Abstract_Processor->dispatch()` seems to do the trick. Both the unit test and the test code that schedules calculations work as expected. I wasn't sure if changing the batch array before adding tasks to it was a safe thing to do or not.

**Comment by thomasplevy** [comment]
> We aren't using the LifterLMS bulk enroll feature, but are likely doing something similar. On two of our sites, we have a feature that enables enrolling in all courses assigned to a course category when a user is enrolled in a special course that points to the category.

Gotcha.

Yea this would make sense to cause this to happen then, thanks for explaining.

Since there's only a single instance of the processor running on a given request the *data must* be cleared otherwise we'll see this behavior you've reported.

I looked a little deeper into the way the membership works and we actually *intentionally disable* the processor until after bulk enrollment is completed and then trigger the processor manually. However, this is still problematic behavior (how it was working before this PR). Thanks for raising this and helping out so we could improve it a bit

Best
