### ISSUE TITLE
Number of enrolled users displayed of newly cloned course is the same as the the old course

### ISSUE THREAD

**Issue by yewzy** [gocodebox/lifterlms#1604]
### Reproduction Steps

In the courses page, click 'clone' on an old course. Then publish the course.
Head to LifterLMS -> Reporting -> Courses. Number of enrolled students shown in cloned course in incorrect.

### Expected Behavior

The number of enrolled students should be 0.

### Actual Behavior

When a course is cloned and published, the number of currently enrolled students in the reporting page (/wp-admin/admin.php?page=llms-reporting&tab=courses) is also transferred, ie. the new (cloned) course is showing the number of currently enrolled students the old course have. 

The number of students enrolled all-time is accurate.

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by yewzy** [comment]
Looking at #1564, maybe this is due to the number being cached, and cross-linked? If that's the case, a potential solution might be to allow admins to force recalculate student data.

**Comment by thomasplevy** [comment]
Thanks for the report @yewzy

I'm going to close this in favor of #1532 (duplicate)

Any else to add please add it there
