### ISSUE TITLE
200 parsererror when editing section & lesson with the latest version of Redux plugin

### ISSUE THREAD

**Issue by soydiloreto** [gocodebox/lifterlms#1610]
### Reproduction Steps

1. Enter in courses in any site in my wordpress implementation (multisite).
2. Enter in "Builder"
3. Edit anything or create anything.
4. 200 parsererror appear in screen.

Plase see this error in image https://azure.conosur.tech/wp-content/uploads/sites/18/2021/04/2021-04-24_19-09-59.png

### Expected Behavior

I want to edit or create new sections & lessons.

### Actual Behavior

An error appear in screen.

### System and Environment Information

<details>
<summary>System Report</summary>

Wordpress
-------------------------------------------

Home Url: https://azure.conosur.tech
Site Url: https://azure.conosur.tech
Login Url: https://azure.conosur.tech/wp-login.php
Version: 5.7.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: es_AR
Multisite: Yes
Page For Posts: Publicaciones (#5494) [https://azure.conosur.tech/publicaciones/]
Page On Front: Home (#9) [https://azure.conosur.tech/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes

Settings
-------------------------------------------

Version: 4.21.0
Db Version: 4.21.0
Course Catalog: Not Set
Membership Catalog: Not Set
Student Dashboard: Estudiantes (#396) [https://azure.conosur.tech/estudiantes/]
Checkout Page: Not Set
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: mis-cursos
Edit Endpoint: 
Lost Password Endpoint: recuperar-contrasena
Vouchers Endpoint: 
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: hidden
Registration Email Confirmation: no
Account Names: required
Account Address: hidden
Account Phone: hidden
Account Email Confirmation: no
Confirmation Endpoint: confirmar-pago
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: conosur@conosur.tech
Email From Name: ConoSur.Tech
Email Footer Text: --
Equipo de ConoSur.Tech
Email Header Image: 5446
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no

Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined

Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1

Server
-------------------------------------------

Mysql Version: 8.0.23
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 8 MB
Php Memory Limit: 512M
Php Post Max Size: 8M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.4.15
Software: Microsoft-IIS/10.0
Wp Memory Limit: 64M

Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4474.0 Safari/537.36 Edg/92.0.867.0

Theme
-------------------------------------------

Name: Vlog | Shared By VestaThemes.com
Version: 2.2.3
Themeuri: https://mekshq.com/theme/vlog/
Authoruri: https://mekshq.com/
Template: 
Child Theme: No
Llms Support: No

Plugins
-------------------------------------------

Comments Widget Plus: 1.1.0
Contact Form 7: 5.4
Countdown Timer Ultimate: 1.4
Custom Login Page Templates: 1.0
Custom Sidebars: 3.31
Embed Any Document: 2.6.1
Events Manager: 5.9.11.3
Hola Simpsons: 1.2.4
iThemes Security Pro: 6.8.4
LifterLMS: 4.21.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.14
LifterLMS Assignments: 1.1.12
LifterLMS Customization for vLog in ConoSur.Tech: 1.0.1
LifterLMS Helper: 3.2.0
LifterLMS PDFs: 1.0.0
Mailjet for WordPress: 5.2.6
MultiSite Clone Duplicator: 1.5.3
Multisite Enhancements: 1.6.1
My Sites Sort and Filter: 1.1.1
Network Posts Ext: 7.4.7
NS Cloner - Site Copier: 4.1.5.3
Redirection: 5.1.1
Redux: 4.1.26
Remove Dashboard Access: 1.1.3
Site Kit by Google: 1.30.0
Table of Contents Plus: 2002
Under Construction / Maintenance Mode From Acurax: 2.5.9
User Menus: 1.2.5
Widget Options: 3.7.8
WP Dark Mode: 2.0.5
wpDiscuz: 7.2.0
WPM User Sync: 1.1.1
Yoast Duplicate Post: 4.1.2
Youtube Channel Gallery: 2.4

Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes

Template Overrides
-------------------------------------------

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

Any browser, any OS.

**Comment by thomasplevy** [comment]
Hey there @pablodiloreto 

Would you kindly confirm that this is is occurring with only LifterLMS and a default theme (twenty-twenty one, for example)

If this is happening only when a certain plugin(s) is activated please help narrow it down so we can determine if it's a conflict we can fix.

Could you also provide me with a copy of the AJAX response that's being returned from the server?

Thanks!

**Comment by soydiloreto** [comment]
Hello @thomasplevy ! Thanks for your reply. I checked it with twenty twenty and no error here. It only happen with vLog theme activated. I use LifterLMS with vLog from several month ago (12 months) and this error never happen.

In the AJAX XHR tab in my browser, when I activate vLog Theme no response appear from server. If I change to Twenty Twenty, this response appear (and everything is right):

`{"llms_builder":{"status":"success","message":"\u00c9xito","updates":{"sections":[{"lessons":[{"id":125,"title":"A\u00f1adir nueva lecci\u00f3n","type":"lesson","order":2,"parent_course":95,"parent_section":122,"edit_url":"","view_url":"","content":"","audio_embed":"","has_prerequisite":"no","require_passing_grade":"yes","require_assignment_passing_grade":"yes","video_embed":"","free_lesson":"","points":1,"assignment":[],"assignment_enabled":"no","quiz":[],"quiz_enabled":"no","orig_id":"temp_49"}],"id":122,"orig_id":122}]}},"wp-refresh-post-lock":{"new_lock":"1619315168:41"},"wp-auth-check":true,"server_time":1619315168}`

Maybe you can help me with the "headers" tab from my AJAX XHR when the error appear:

```
Request URL: https://template.conosur.tech/wp-admin/admin-ajax.php
Request Method: POST
Status Code: 200 
Remote Address: 52.170.148.171:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 0
content-type: text/html; charset=UTF-8
date: Sun, 25 Apr 2021 01:48:48 GMT
server: Microsoft-IIS/10.0
x-powered-by: PHP/7.4.15
x-powered-by: ASP.NET
:authority: template.conosur.tech
:method: POST
:path: /wp-admin/admin-ajax.php
:scheme: https
accept: application/json, text/javascript, */*; q=0.01
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8,pt;q=0.7
content-length: 1024
content-type: application/x-www-form-urlencoded; charset=UTF-8
cookie: _ga=GA1.2.430892913.1615817583; __gads=ID=cf69f606f4f558ea-229a04ca35b9008e:T=1615817583:RT=1615817583:S=ALNI_MZiR51JYyiQLp5i8Z57MAtptWhf6A; wp-settings-41=libraryContent%3Dbrowse; wp-settings-time-41=1617473890; thing_sec_33245928665fb1047c02177be6760cb4=pablodiloreto%7C1619366092%7CeafkxdyPVYFYMxFgziW9tCDEOu923trwtfBjKouKenS%7C3874ce327d55c11eb02a32298854044360f13f44279de166b43895a7f82c986e; thing_logged_in33245928665fb1047c02177be6760cb4=pablodiloreto%7C1619366092%7CeafkxdyPVYFYMxFgziW9tCDEOu923trwtfBjKouKenS%7Cf955bf76a5eb1e01ef15d91ddaa7ed1711fa73f294c97475a69e4213dc5e3253; wp_llms_session_33245928665fb1047c02177be6760cb4=41%7C%7C1619333738%7C%7C1619330138%7C%7C9f83ab9c1e729f03b378ecab4b8f61ef; llms-tracking={%22nonce%22:%22414d9fe228%22}
origin: https://template.conosur.tech
referer: https://template.conosur.tech/wp-admin/admin.php?page=llms-course-builder&course_id=95
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Microsoft Edge";v="92"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4474.0 Safari/537.36 Edg/92.0.867.0
x-requested-with: XMLHttpRequest
data[wp-refresh-post-lock][post_id]: 95
data[wp-refresh-post-lock][lock]: 1619315315:41
data[llms_builder]: {"detach":[],"trash":[],"updates":{"sections":[{"lessons":[{"id":"temp_58","title":"Añadir nueva lección","type":"lesson","order":3,"parent_course":95,"parent_section":122,"edit_url":"","view_url":"","content":"","audio_embed":"","has_prerequisite":"no","require_passing_grade":"yes","require_assignment_passing_grade":"yes","video_embed":"","free_lesson":"","points":1,"assignment":{},"assignment_enabled":"no","quiz":{},"quiz_enabled":"no"}],"id":122}],"id":95},"id":95}
interval: 15
_nonce: acceb60aa9
action: heartbeat
screen_id: admin_page_llms-course-builder
has_focus: true
```

Thank you.

**Comment by soydiloreto** [comment]
Hello @thomasplevy ! I find the following: the problem is not with vLog, the problem is with "Redux Framework plugin".
If I have the vLog plugin activated, but if I deactivate the "Redux Framework plugin", everything works fine.
Is any possibility to help this issue?

**Comment by soydiloreto** [comment]
Another information about this issue: if you rollback the "Redux Framework Plugin" to 4.1.24 (the last update is 4.1.26) LifterLMS works fine. From yesterday, I am using Redux with 4.1.24 as workaround.

**Comment by eri-trabiccolo** [comment]
Hi @pablodiloreto 
since this is something introduced by that plugin update might be worthwhile to open an issue on the plugin's GitHub repository (?!): https://github.com/reduxframework/redux-framework-4

Also could you also check that the issue occurs both with the auto-save and the manual saving?
https://lifterlms.com/docs/using-course-builder/#manual-saving

**Comment by soydiloreto** [comment]
Thank you @eri-trabiccolo ! I will check to open the github case in redux. In addition, I confirm that the problem is also found in both cases: manual saving & auto-save. Regards.

**Comment by eri-trabiccolo** [comment]
@pablodiloreto 
Thanks for the feedback.
That's really interesting as I can reproduce the issue with the auto-save (user) option enabled, but not when it's disabled and I save the changes manually.

**Comment by thomasplevy** [comment]
@eri-trabiccolo does this look like something that's fixable or is this something that needs to be addressed from the Redux side?

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I don't know honestly, I can't see any error logged anywhere when the issue occurs, so it would require some digging into their code.
What I get, in JS, is a response with status 200 and no "content".

**Comment by thomasplevy** [comment]
@pablodiloreto at this time I'm going to leave this as a plugin conflict and when time allows we'll do some deeper investigation.

The fact that you've confirmed that this is an issue apparent only in a recent version of another plugin which used to work fine leaves me to hope that you can notify them of this recent issue and that they could adjust accordingly to play nice with our plugin.

My guess is this has something to do with shared usage of the WP heartbeat API if, as @eri-trabiccolo has stated, using manual save works.

In the worst case scenario you can switch to using manual saving (https://lifterlms.com/docs/using-course-builder/#manual-saving)

We also welcome contributions from you or the community to resolve this from our side (if possible).

**Comment by soydiloreto** [comment]
Hello Team! Thank you @thomasplevy and @eri-trabiccolo for your responses. I opened a new issue in redux (https://github.com/reduxframework/redux-framework-4/issues/215) 

As a workaround, I will use LifterLMS with manual saving.

Thank you!

**Comment by thomasplevy** [comment]
Resolved redux at https://github.com/reduxframework/redux-framework-4/commit/5a44d6d9af677bf47d255724b0075c9351e1e991
