### ISSUE TITLE
[5.x] Field Title Change UX & Clarify Reusable Block Options Confirmation Step

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1616]
**Is your feature request related to a problem? Please describe.**
First time users need help understanding the choice they have here

**Describe the solution you'd like**
Helper text

###

1. I changed "City" field title to "Zone"
2. I like the "dot" on the update button after I did that. It Dre my attention
3. I clicked update
4. It looks like I'm presented with this "Reusable Block" confirmation step
5. It does not make sense that it says "there are no changes" under  "Are you ready to save" because I just made a change
6. As a power user, it looks like I have a choice to apply this change globally via the Reusable block, but a first time user would need more context. Why are you making me focus on an optional checkbox? I need some helper text about the checkbox, for example: Leave this box checked to apply these changes across all forms using the fields yo made changes on. If you uncheck the box, changes made will only happen on this form.

![Edit_Post_‹_A_LifterLMS_Sandbox_—_WordPress-2](https://user-images.githubusercontent.com/12163552/116757076-5ab9f380-a9db-11eb-97e9-6d5c020ad83b.png)

###

**Describe alternatives you've considered**
Don't give them this choice maybe?

**Comment by thomasplevy** [comment]
This is WP core functionality. I'm not going to endeavor to change this default WP functionality within LifterLMS. I do, however agree with your feedback. It's confusing. User s are going to have to learn.
