### ISSUE TITLE
[5.x] Free Course Lead Magnet and BuddyBoss

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1622]
### Reproduction Steps

+ (note: I found this in the 5.0 but this happens in our current version too)

+ Import the Free Course Lead Magnet course template
+ Activate BuddyBoss at the theme 
+ Check the course

### Expected Behavior

+ The emojis are emoji sized

### Actual Behavior

![image](https://user-images.githubusercontent.com/47434271/117343063-8ae51480-ae69-11eb-901f-f4b5f24c58de.png)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 Thanks for this... I think that BuddyBoss is (intentionally?) removing Emoji "support" via something like this

`remove_action( 'wp_head', 'print_emoji_styles' );` but I'm not entirely positive.

This isn't a LifterLMS core issue, if you go to a regular BB page and add an emoji you'll see the same kind of behavior.

I'll drop a note to BB in case they're interested in knowing about this
