### ISSUE TITLE
[5.x] Clarify 3 default form Titles

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#1627]
The form title defaults should use consistent language with location so they easily map in the users mind to the same place

![LifterLMS_Forms_‹_A_LifterLMS_Sandbox_—_WordPress](https://user-images.githubusercontent.com/12163552/117495017-1ed6df00-af43-11eb-9274-acb3760e51c8.png)

Suggested edits to titles:

- Checkout Form
- Registration Form
- Edit Account Form

**Comment by thomasplevy** [comment]
@chrisbadgett these titles are the physical titles displayed on the frontend of the website so changing these as suggested I don't believe makes sense.

Previously it was impossible to edit this kind of thing (in version 4.x and lower) but now users can customize language. The form "title" was the simplest way I could think of to make this possible.

I cannot exactly understand the exact reason why this would need to change though... Can you help me understand what the "problem" you're identifying is? Do users see "Billing information" and not know what that means? Or is it that the "location" (in the right column) differs? Is the information displayed on screen actually causing confusion (in favor of reducing it)?

What can we do here to meld your feedback with the functionality enabled by allowing the title to be customized?

**Comment by chrisbadgett** [comment]
Ah now that I know it displays on the frontend, that makes sense. 

Leave as is.
