### ISSUE TITLE
[5.x] When changing to a Country with no States, previous State's value is no cleared.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1633]
### Reproduction Steps

+ Register with Country US and State AR
+ Edit your account
+ Change your country to something that has no states, e.g. United States Minor Outlying Islands
+ the States select field will disappear
+ Save
+ Look at your profile in admin (or through reporting)

### Expected Behavior

+ I'd expect the state to be empty

### Actual Behavior

+ The state is still AR
(we should not disable the field, but rather empy it and send it over anyways, right?)

### Error Messages / Logs

n/a

### System and Environment Information

```
LifterLMS 5.0.0-alpha.6
```

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
> * (we should not disable the field, but rather empy it and send it over anyways, right?)

Yes... there's logic to disable the field if it's not required and perhaps we can hook into that same logic to empty the field in this scenario
