### ISSUE TITLE
5.0 rc-2 Declare Action Schedule 3.2.0 conflict

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1673]
### Reproduction Steps

HS-169185

+ Conflict is with the plugin WP Mail SMTP: 2.8.0
+ wp-mail-smtp declares Action Scheduler 3.1.6
+ LifterLMS 5 to declares Action Scheduler 3.2.0.

### Expected Behavior

+ I can't figure out how to reproduce this, but it is causing a fatal error on the user's staging site and this is what he's reported

### Actual Behavior

+ when activating lifterlms 5.0 rc-2 the site crashes

### Error Messages / Logs

+ Include any relevant error messages or log files
```
E_COMPILE_ERROR was caused in line 10 of the file /wp-content/plugins/lifterlms/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler.php.
Error message: Cannot declare class ActionScheduler, because the name is already in use

```

### System and Environment Information

<details>
<summary>System Report</summary>

We don't have the system report for the staging site he tested this on, and he won't/can't give us logins

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
hey hey hey we're having fun already!

**Comment by thomasplevy** [comment]
@nrherron92 looking at the rest of the information provided it seems this is a conflict between the version included by WP Mail SMTP and version 3.2.0 (which was included in RC.2). However, we upgraded to 3.2.1 (just released) in 5.0 (stable): https://github.com/gocodebox/lifterlms/commit/b863b5fa41aef197bc1110e270e0490bf26a8cb6

I just ran a test with the current (public stable) 5.0 & latest WP Mail SMTP and I don't see any errors here.

Looking at the code there shouldn't be.

Could you notify the customer and see if they could update to the 5.0 stable on the stage and confirm this does indeed fix it?

Thanks

**Comment by nrherron92** [comment]
@thomasplevy replied to user!

**Comment by thomasplevy** [comment]
Looks like we're good here @nrherron92!
