### ISSUE TITLE
Setting All Billing information to view to only logged out users

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1678]
### Reproduction Steps

+ Go into _LifterLMS->Forms->Billing Information_
+ Set all of the content of the form to display _only_ to logged out users
+ (I found this is easiest to test if you just remove the billing information and use a free course/membership with the email field set to logged out only users but it works the same if you set all of the billing fields to logged out only and use a paid course/membership)
+ Go into a course or membership as a logged in user and attempt to purchase/enroll

### Expected Behavior

+ I think this behaves _exactly_ as I would expect it to. If only logged out users can see required fields then of course if a logged in user tries to purchase but can't fill out billing information the purchase will fail
+ However, where I think think maybe this could be confusing is when logged in users enroll in a free course/membership. Since you don't technically go to the purchase page for this since the logged in information autofills. Though, I understand it could not be autofilling because that field is not avaliable for logged in users so the information bounces. 

### Actual Behavior

+ There is missing information that the user doesn't have access to so can't fill out to login. 
+ Of course the fix to this is set that information to display to everyone.
+ Maybe this is just an issue of documentation that you can't hide required billing fields from users? I just feel like there's a gap here that we've had one user encounter already.  Or maybe we should make it so if a field is required it default displays to everyone and the user can't change it?

**Comment by thomasplevy** [comment]
Basically you're identifying #1589

Also Related: #1607 

I think this *can* be addressed with documentation although I'd prefer to address it with programming so that even if users don't read the docs they won't have broken forms. The documentation could *explain* why fields they wish to hide are displaying anyway or something...

**Comment by thomasplevy** [comment]
I had intially figured both these above issues would be things we could deal with in the next few weeks but I guess since we're having issues on day one already we should expedite that
