### ISSUE TITLE
Lessons being replaced

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1699]
### Reproduction Steps

+ HS-169442
+ I'm not sure this is replicable the users are not sure what is happening to cause this to be able to reproduce it. 
+ The issue is happening with the course titled "Gesprächsführung für Praxisanleiter*innen" the lesson that should be the second lesson in the course is "Vom Problem zur Lösung" however it has been replaced with "Anleitungsmethoden & Lerntheorien"
+ According to the user the lesson "Anleitungsmethoden & Lerntheorien" has never been part of the "Gesprächsführung für Praxisanleiter*innen"
+ Vom Problem zur Lösung is currently just dissociated from any course
+ However, it's possible that "Gesprächsführung für Praxisanleiter*innen" was cloned from the course: Anleiten und Coachen which I believe is probably the case. 
+ There are two Anleitungsmethoden & Lerntheorien lessons that were created 8 hours apart on the same day. One Anleitungsmethoden & Lerntheorien is correctly associated with the Anleiten und Coachen course and the other is the one that replaced the Vom Problem zur Lösung lesson in Gesprächsführung für Praxisanleiter*innen
+ The first time this happened the user restored a back up of the database, but apparently the switch is happening before any database updates are happening
+ The site has never been migrated and does not currently have staging -- though i just asked for one to be set up for us

### Expected Behavior

+ the assigned lesson should be on the course

### Actual Behavior

+ The assigned lesson is being swapped out for an unrelated lesson

### Error Messages / Logs

+ Include any relevant error messages or log files
+none that I could find but debug log is enabled
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.7.2
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: de_DE_formal
Multisite: No
Page For Posts: Not Set
Page On Front: Start (#96) [[removed]/]
Permalink Structure: /%postname%
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.21.3
Db Version: 4.21.3
Course Catalog: Kurs Katalog (#38) [[removed]/courses]
Membership Catalog: Mitglieder Katalog (#39) [[removed]/memberships]
Student Dashboard: Mein Konto (#41) [[removed]/my-courses]
Checkout Page: Anmeldung (#40) [[removed]/purchase]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: meine-kurse
Edit Endpoint: konto-bearbeiten
Lost Password Endpoint: passwort-vergessen
Vouchers Endpoint: eingeloeste-gutscheine
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: DE
Currency: EUR
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manuell: Enabled
Manuell Logging: no
Manuell Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.60
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 64 MB
Php Memory Limit: 268435456
Php Post Max Size: 67108864
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.28
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.54


Theme
-------------------------------------------

Name: DiviChild
Version: 1.0
Themeuri:
Authoruri:
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

amr users: 4.55
BackWPup: 3.8.0
Child Theme Generator: 2.2.7
Cookie Notice & Compliance for GDPR / CCPA: 2.0.4
Fast Flow: 1.2.6.2
Fast WooCredit Pro: 1.3.1.7
Germanized for WooCommerce: 3.4.8
Health Check & Troubleshooting: 1.4.5
Import and export users and customers: 1.17.5.6
LifterLMS: 4.21.3
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Customizations: 1.0.0
LifterLMS Labs: 1.5.3
LifterLMS WooCommerce: 1.3.2
Loco Translate: 2.5.2
Login Logout Register Menu: 2.0
Magic Action Box: 2.17.2
NinjaFirewall (WP Edition): 4.3.4
Order / Coupon / Subscription Export Import Plugin for WooCommerce: 2.4.9
Page Links To: 3.3.5
Peter's Login Redirect: 2.9.9
Preferred Languages: 1.7.0
WooCommerce: 5.3.0
WooCommerce Colors: 1.0.7
WooCommerce PayPal Checkout Gateway: 2.1.1
Yoast Duplicate Post: 4.1.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
After reviewing all of this I can't help but wonder if this is an accidentally self-created issue..

I simply cannot imagine a way in which the content of a course (or the video of a lesson) is "swapped" and stored into another course with absolutely no explanation. I just don't see it being the least bit realistic that LifterLMS is suddenly this broken that the content of a course flows from one place to another without explanation.

I do see that the user reporting the issue is reporting this second hand based on something their client has relaid to them... Is there any world in which this is simply user error? Someone accidentally editing the wrong course and not realizing and when a student realizes the content is wrong they haven't realized they made a mistake in content management? This seems implausible also but I just simply cannot explain how content would just jump courses with no explanation.

Additionally: there is a DB search and replace plugin installed on the site (but inactive). Is it possible that faulty search and replaces have been run causing data to be assigned to the wrong place unintentionally?

**Comment by thomasplevy** [comment]
@eri-trabiccolo can you have a brief look at this and see if I'm being insane or dense? I can't find any reason how this could happen.

**Comment by eri-trabiccolo** [comment]
@thomasplevy I had a look, I cannot see any reason for that to happening.
I just cannot see how... all of a sudden, **without anyone doing anything**?!
We know it's impossible for this to be happening without any "admin" action...

Let's wait for a staging website...

**Comment by nrherron92** [comment]
@eri-trabiccolo @thomasplevy I also noticed another weird thing while I was getting back to them. The course they're saying where the lesson is being replaced has only 1 section with 4 lessons. However, the settings from the detached lesson show that it was part of "Section 2". So what happened to that section? I think this is coming down to a miscommunication between the site owner and the dev.

**Comment by thomasplevy** [comment]
@nrherron92 at this moment I'm not sure what else we can do here -- even with a staging site since we don't know what events have to transpire to cause this to happen.

**Comment by nrherron92** [comment]
@thomasplevy So he had some updates...he added a new lesson (7) and it became detached from the course but also spawned another new lesson (8) that he never made.... 

Someone else is working on this site it has to be, because the next update was that all the lessons and new quizzes made were correctly attached... I'm just not sure how to address this ticket in a way that doesn't sound like we're just throwing out hands up


oh we also have a staging site now...

**Comment by thomasplevy** [comment]
@nrherron92 Can you work on this with @willmiddleton-lifterlms. I don't know what else to do here... There's nothing malfunctioning as far as I can tell. I can't prove someone is doing this but no one can help me prove that there's a bug either... Stuff just doesn't *detach* and or get created for no discernible reason.

**Comment by magicemilymiddleton** [comment]
I could make this specific issue happen where I think the lesson doesn't know what section to attach to if the section hasn't yet been saved: https://www.loom.com/share/329165d843ff467195d4b9874ee446cc

Recreation steps:
- Create a course
- Enter the course builder
- Create a 3 or 4 lesson course
- Wait for that to save
- Then add a new section and move a lesson to it before the section has a chance to save
- That should abandon the lesson

(if you give the section time to save before moving a lesson in, this problem doesn't happen)

This doesn't explain all the user's reports but was something I thought of as a possible issue to bring up when Natalie mentioned a lesson was a part of a section that doesn't exist.

**Comment by thomasplevy** [comment]
@willmiddleton-lifterlms what does "abandon" the lesson mean, exactly? I haven't tried this but based on way things are programmed the lesson should be saved to the section on the next save. Are you *exiting* the builder after the last step you provided?

**Comment by thomasplevy** [comment]
@nrherron92 can you relay this potential bit of information @willmiddleton-lifterlms has provided to the customer and see if this could be what's happening on their site?

**Comment by magicemilymiddleton** [comment]
@thomasplevy by abandon, I mean it doesn't have a section to associate with.

I don't know how the functions technically work, but it seems like the section doesn't exist until the next save and if there's a lesson that's looking for that section as a parent, the lesson won't have a parent section to identify with because that parent section is being saved at the same time the lesson is updating as well to look for it.

https://www.loom.com/share/da09d2742ced46fa8b8f7e51abd5105f

I'm not leaving the builder, it just doesn't seem to register a change has been made so the 'Save' option doesn't light up again.

**Comment by eri-trabiccolo** [comment]
@willmiddleton-lifterlms 
This is interesting, thanks for reporting this!
Although I think this is a different issue (that I'm about to open), as the customer talks about lessons being replaced with other lessons, not just missing...
