### ISSUE TITLE
Causing issue in course builder by doing a bunch of things very quickly

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#1710]
### Reproduction Steps

Video of this:
https://www.loom.com/share/ea6ca692c2b147d7ac0d87e77501193d

I'm not sure if this one is a known issue -> If you do a bunch of things very quickly in the course builder, you can trigger an error I don't understand.
The easiest way to trigger this is to:
- create a quiz
- create a question
- duplicate the question a bunch
- delete a bunch of questions
- just keep duplicating and deleting until the course builder tries to save automatically
- the 'save' button will infinitely spin and none of your future changes will be saved (until you reload the page and start again)

### Error Messages / Logs

From the Inspector Console:

 
```
<!-- Paste error logs / backtraces below this line -->
 at Sync.js:460
    at Function.dr (underscore.min.js?ver=1.8.3:2)
    at u (Sync.js:448)
    at Sync.js:439
    at Function.dr (underscore.min.js?ver=1.8.3:2)
    at u (Sync.js:438)
    at Sync.js:469
    at Function.dr (underscore.min.js?ver=1.8.3:2)
    at Sync.js:468
    at Function.dr (underscore.min.js?ver=1.8.3:2)
</details>
```

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment]
Possibly related to https://github.com/gocodebox/lifterlms/issues/1003 and gocodebox/lifterlms-assignments#47
