### ISSUE TITLE
Implement usage of traits

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1746]
LifterLMS is long overdue to use PHP traits. I often wish to add a trait for something but don't want to include the required "prework" in the related bugfix / feature PR.

+ Trait classes should follow the naming convention `LLMS_Trait_{$trait}`, eg: `LLMS_Trait_Singleton`.
+ Trait files should follow the naming convention `llms-trait-{$trait}.php`: eg: `llms-trait-singleton.php`
+ Trait classes should be stored in their own directory at `includes/traits`
+ Traits should be autoloaded via the `LLMS_Loader::autoload()` method

An initial singleton trait can be included and singleton classes in the core can remove their singleton methods and properties and be replaced with the new trait.

+ A singleton trait exists in the lifterlms-rest library: https://github.com/gocodebox/lifterlms-rest/blob/trunk/includes/traits/class-llms-rest-trait-singleton.php. I believe this can be lifted into the core (and ultimately replaced in the rest lib as the core's singleton could then be used).

+ the sales page redirect methods "shared" (duplicated) across courses and memberships (see #1743) can be converted into a "sales page" type trait containing these methods that can then be mixed into the course and membership models.

+ Audio and video embed code is similarly copied between courses and memberships

This would be a good start. There's lots of other potential areas where we could replace duplicated code with traits too but these jump out at me immediately.

+ Existing tests should continue to pass if traits are implemented properly.
+ When creating new traits I feel the best practice would be to instantiate a mock (anonymous?) class that uses the trait and write tests against the mock. However, for the purposes of ensuring the traits "integrate" properly having redundant tests for some traits *might* make sense. The sales page / redirect trait might benefit from having course/membership model tests AND having tests against an anonymous class that uses the trait out of the "intended" context

**Comment by thomasplevy** [comment]
@pondermatic how's this sound to get working on?

**Comment by pondermatic** [comment]
I was thinking this exact same thing when I worked on the sales page functions in memberships and courses. Your plan sounds perfect.
