### ISSUE TITLE
Fatal error on clean install (beta 3.0)

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#179]
receiving fatal error while installing 3.0
![image](https://cloud.githubusercontent.com/assets/4434724/18334616/94fba62a-752d-11e6-89a8-e2438e8371a9.png)

### The full error message:

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home4/larpoon/public_html/loralee.ca/lifterlms/wp-content/plugins/lifterlms-3.0.0-beta.5/lifterlms.php on line 29

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/php56/lib/php') in /home4/larpoon/public_html/loralee.ca/lifterlms/wp-content/plugins/lifterlms-3.0.0-beta.5/lifterlms.php on line 29

### WordPress Environment
Wordpress Version: 4.6.1
Wordpress Memory Limit: 256 MB
Wordpress Language: en_US

### Server Environment

Server Info: Apache
PHP Version: 5.6.24
PHP Max Post Size: 64 MB
Max Upload Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
Default Timezone is UTC: 
MySQL Version: 5.5.48
GZip: 
DOMDocument: 
SoapClient: 
fsockopen/cURL: 
Multibyte String: 

### Active Plugins
none

### Current Theme

Theme: Twenty Sixteen
Theme Version: 1.3

**Comment by BurlesonBrad** [comment]
@Loralee : 
It looks like you downloaded straight from Github & then uploaded the downloaded .zip file directly to WordPress.  Is that correct @Loralee ?

If you're wanting to run a version that's well ahead of what's on WordPress.org, then.... **first of all** 
:clap: :fireworks: :tada: :balloon: :+1: :clap: :fireworks: :tada: :balloon: :+1: :clap: :fireworks: :tada: :balloon: :+1: :clap: :fireworks: :tada: :balloon: :+1: :clap: :fireworks: :tada: :balloon: :+1: 

# **_GO YOU!_**

You'll want to follow these instructions right here: 
https://github.com/gocodebox/lifterlms#installing-for-development
That will load all the dependencies and packages needed to pull from a LifterLMS version that is not currently pushed to WordPress.org/plugins/lifterlms.  

[Currently the stable version of LifterLMS is 2.7.11](https://wordpress.org/plugins/lifterlms/developers/) and of course you can always download it directly from your own site's dashboard! _(from what I can see from the error logs above, if you are currently logged into your own site @Loralee , **~great news!~** the link below should be the simplest way)_
http://loralee.ca/wp-admin/plugin-install.php?s=lifterlms&tab=search&type=term

I hope that helps @Loralee :smile:

**Comment by Loralee** [comment]
Thanks for all the awesome emoticons Brad @BurlesonBrad ... Made my night! :+1: 

I should have mentioned that I'm part of the beta testing team for version 3.0... I'll remember to do that when I post again (Thomas asked us to post on github if we felt comfortable doing so, during the beta testing phase). 

Should I take a closer look at the zip file Thomas sent, to see if maybe it needs to be unzipped before uploading it?

**Comment by BurlesonBrad** [comment]
Well.... I'm not sure exactly _**which**_ .zip file 'ya got, but...  See up yonder where your error message is mentioning line 29 of ```lifterlms.php```?

Now shimmy on over to that line **[HERE](https://github.com/gocodebox/lifterlms/blob/master/lifterlms.php#L29)** and you'll see this
```
require_once 'vendor/autoload.php';
```

That little fellah right there tells this repo to run all the _**dependencies**_ that makes LifterLMS actually create / make / load all other functions and files.

Now, those _**dependencies**_ are only going to auto**_load_** when you're running from a shell or command line ~ not from within WordPress _(...on it's own)_

https://github.com/gocodebox/lifterlms/blob/master/composer.json#L33

So, unless you're running something like https://github.com/Varying-Vagrant-Vagrants/VVV on your computer, those .zip files ain't gonna behave correctly :disappointed: 

_....and if you attempt to load VVV on a Windows10 machine, you're in my prayers!_

**Comment by thomasplevy** [comment]
@Loralee I attached the wrong .zip file (the raw source without compiled dependencies), my apologies, you'll want this one: https://drive.google.com/open?id=0Bw2pzOxBity2YUg0V0gwWGxzekE

**Comment by Loralee** [comment]
Thanks @thomasplevy I'm getting a new error on activation

Fatal error: Call to undefined function llms_create_page() in /home4/larpoon/public_html/loralee.ca/lifterlms/wp-content/plugins/lifterlms-3.0.0-beta.5/includes/class.llms.install.php on line 350

![image](https://cloud.githubusercontent.com/assets/4434724/18358035/1030de4e-75a8-11e6-8f2c-0a98a57cec69.png)

**Comment by thomasplevy** [comment]
@Loralee i see the issue... working on it now will have an update in the next hour or so, I messed some things up by adding the setup wizard and I very stupidly ran no activation tests in my haste to get the beta testing started...

**Comment by Loralee** [comment]
totally understand - no need to rush on my account :)

**Comment by thomasplevy** [comment]
@Loralee 

Resolved via [beta.6](https://github.com/gocodebox/lifterlms/releases/tag/3.0.0-beta.6)

Direct download: https://drive.google.com/open?id=0Bw2pzOxBity2N19MeC1fV3FVbGs

**Comment by thomasplevy** [comment]
@Loralee since you've reported a new issue I'm assuming this issue is resolved please let me know if I'm wrong and I'll reopen and keep working at it.

**Comment by Loralee** [comment]
:+1:  You're absolutely right! 6 did the trick :)  Thanks again Thomas
