### ISSUE TITLE
`llms_bulk_update_user_postmeta()` inserts rows with different `updated_date` values

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#1793]
**Is your feature request related to a problem? Please describe.**
When [`llms_bulk_update_user_postmeta()`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L199) is used to insert or update many database rows, there is a chance that their `updated_date` values may be different if the current time is near a second, e.g. `01:02:03.999` for the first row and `01:02:04.001` for the second row.

This occasionally causes unit tests to fail.
https://app.travis-ci.com/github/gocodebox/lifterlms/jobs/538224179

**Describe the solution you'd like**
[`llms_bulk_update_user_postmeta()`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L204) calls [`llms_update_user_postmeta()`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L151), which sets [`updated_date`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L175) to the current time.

I'd like for [`llms_bulk_update_user_postmeta()`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L204) to pass the current (mockable) time to [`llms_update_user_postmeta()`](https://github.com/gocodebox/lifterlms/blob/5.3.1/includes/functions/llms.functions.user.postmeta.php#L151).

**Describe alternatives you've considered**
Have `llms_bulk_update_user_postmeta()` set the current time on each iteration.

**Comment by pondermatic** [comment]
Instead of allowing `llms_bulk_update_user_postmeta()` to pass the `updated_date` to `llms_update_user_postmeta()`, `test_llms_get_user_postmeta()` was changed to allow a 2 second delta variation between dates.

**Comment by thomasplevy** [comment]
Unreleased as of yet (it's staged on `dev`)
