### ISSUE TITLE
LLMS.wait_for should give more information on the dependency

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1797]
Currently (LifterLMS 5.3.1) this util only prints to messages:
`waiting...` while waiting for a condition to be met
`could not load dependency...` when the condition is still not met after 30 seconds.

When this happens we have no information on what's missing.

The idea would be to add a third (optional) param (`dep`) to `LLMS.wait_for` which is a string representing the condition to be met.

what do you think @gocodebox/engineering

**Comment by pondermatic** [comment]
I like the idea of calling `LLMS.wait_for()` with a string that is logged to the console if the dependency could not be loaded.

Another option, although not as good, is to have the `test` functions return `true` | `string`.

**Comment by thomasplevy** [comment]
Opinions on my PR, #1800

**Comment by toyinogun** [comment]
HS-176373
