### ISSUE TITLE
Latest achievement in dashboard/my-grades might be empty depending on the number of posts set in wp->settings->reading

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1803]
### Reproduction Steps

+ In your wp dashboard -> Settings -> Reading, set the number of posts to show to 1.
+ Create a Course with two lessons
+ Create 2 Achievements
+ Create two Engagements (respect this order):
-- for the **first lesson** completion, assign the first achievement
-- for the course completion, assign the second achievement
+ Enroll a user in the course
+ As this user:
-- complete lesson 1
-- head to the dashboard's my-grades for the new course

### Expected Behavior

+ I'd expect to see the lesson 1 completion achievement

### Actual Behavior

+ the Latest Achievements reads "No achievements"

The reason why this happens is because the query to get the achievements (engagements) related to a post (e.g course) doesn't specify a specific `posts_per_page` param, which is then inherited by the global wp option (in settings/reading) - which is 1, in this case; the order is by default `post_date` `DESC` hence the importance of following the engagementes creation order as in the reproduction steps.

So I'd say that by default we could set a `posts_per_page` to 100 here:
https://github.com/gocodebox/lifterlms/blob/5.3.2/includes/class.llms.achievements.php#L115

As this method is only used in my-grades (and groups) reports - nothing else will be affected by this change.

### Error Messages / Logs

n/a

### System and Environment Information

```
LifterLMS 5.3.2

```

### This issue has been recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

see also https://github.com/gocodebox/lifterlms-groups/issues/164 (and related HS ticket.)

**Comment by eri-trabiccolo** [comment]
@thomasplevy priority?

**Comment by thomasplevy** [comment]
I'd say we should take care of this since we have a customer who encountered the issue, we told them we fixed it, and we didn't actually fix it

**Comment by eri-trabiccolo** [comment]
We fixed what we could reproduce :D 
there were two issues... :P

**Comment by thomasplevy** [comment]
A nuance that matters to us but I doubt matters to the customer
