### ISSUE TITLE
"Back to" links on lesson page points to current page (bug)

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#181]
Possible bug with meta information at top of each lesson

### Expected behavior: 
When viewing a new lecture there is a "Back to:--lesson--" hyperlink near the top of the page that returns the user to the previous lesson. 

### What I'm experiencing:
The link points to the existing lecture (see screenshot)

### To reproduce issue:

- proceed to at least the 2nd lesson in any given course
- view the "back to" hyperlink
- verify that it's pointing to the previous lecture, not the current one.

### Screenshots / examples

In the example below, the page/lesson I'm viewing is called "why automate", after completing the "introduction" lesson. The hyperlink points to "why automate", when it should point to "introduction"
![image](https://cloud.githubusercontent.com/assets/4434724/18369644/ed0e2bd6-75db-11e6-94cc-1b78be095872.png)

@thomasplevy  let me know if this style of reporting potential bugs works for you, or if you prefer a different format?

**Comment by thomasplevy** [comment]
@Loralee this is a perfect format and I would be so lucky if everyone would follow your lead! It almost seems like you may have read the info at https://github.com/gocodebox/lifterlms#reporting-a-bug!! Thank you

as for the issue itself it is legitimate and reproducible and I'll have a fix for it in the next beta release. Probably tomorrow sometime.

**Comment by Loralee** [comment]
too funny! I didn't see the bug reporting section, but I'm sure I've scrolled past it before... I'll modify it to that exact method for next time :)

**Comment by Loralee** [comment]
@thomasplevy I've made a quick template version for myself, and thought it might be helpful to share it. Feel free to make a edit or make a copy to share with other beta testers
https://docs.google.com/document/d/1DX3_iCwcoU6mwTg5kpn3fSE3adQGfpvxIP0_MvU4tbs/edit?usp=sharing

**Comment by thomasplevy** [comment]
resolved in [beta.7](https://github.com/gocodebox/lifterlms/releases/tag/3.0.0-beta.7)
