### ISSUE TITLE
Username created from email address with + sign creates error

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#182]
## Brief summary of issue
When creating a new account with a + sign, a username error is returned

## Reproduction Steps
- Create a new purchase with a new email address, using a plus sign 
- Click the "buy now' button

## Expected Behavior
The option to select my own username, or for the system to create a username based on the info created during signup (even if it includes a +)

##What I'm experiencing
When I entered an email address with a + sign, I see this error message

> The username "loralee+test" is invalid, please try a different username.

Using the + sign is commonly used to help with creating filters in email programs like gmail. 

## Other notes 

- I attempted to use another handy email address admin@ and that threw back another similar error
- password needs to be added again in both fields when these errors occur (may especially be frustrating for mobile users)

##Screenshots or video
![image](https://cloud.githubusercontent.com/assets/4434724/18373519/9c0f30c2-75f9-11e6-8481-a3770f9b7d99.png)

## Server Details
**Server Info:** Apache
**PHP Version:** 5.6.24
**PHP Max Post Size:** 64 MB
**Max Upload Size:** 64 MB
**PHP Time Limit:** 30
**PHP Max Input Vars:** 1000
**MySQL Version:** 5.5.48

## Browser, Device, and Operating System
**Browser:** Chrome 52
**Operating system:** Windows NT 10.0
**Javascript enabled** Yes
**Cookies enabled** Yes
**Flash version** 22.0.0
**Java version** Not installed
**Websockets supported** Yes
**Browser size** 1263 x 595
**Screen size** 1280 x 720 (Retina)
**Color depth** 24 bit

**Comment by thomasplevy** [comment]
resolved in [beta.7](https://github.com/gocodebox/lifterlms/releases/tag/3.0.0-beta.7)
