### ISSUE TITLE
Registration form creates user without proper email address

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1829]
### Reproduction Steps

+ HS-177727
+ create a registration form that has email, username required and nothing else (no password field)
+ Go to register a new user
+ type in an incomplete email address for example: thisisnotcomplete@notcomplete
+ complete registration

### Expected Behavior

+ The user should not be registered on the site because the email is invalid.
+ so there would be no way for the user to set their password

### Actual Behavior

+ the account is created on the backend 
+ but the user is not logged in on the front end and there is no warning the page just refreshes

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.4.0
Db Version: 5.4.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Purchase (#37) [https://natalie-test-site.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.31
Software: Apache/2.4.51 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.7.3
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 5.4.0
LifterLMS Stripe Payment Gateway: 5.3.2
Manage User Columns: 1.0.3
User Switching: 1.5.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@nrherron92 
I'm a little confused about this:
> create a registration form that has email, username required and nothing else (no password field)
If you remove the password field, it is automatically added, isn't so?

**also**

> Actual Behavior:
> but the user is not logged in on the front end and there is no warning the page just refreshes
I don't seem to be able to reproduce this: in my tests the user is logged in on the front end.

@thomasplevy 
the problem here is that we:
- [check the required fields](https://github.com/gocodebox/lifterlms/blob/5.4.0/includes/forms/class-llms-form-handler.php#L370) are present (and the email field is present) 
- [sanitize the fields](https://github.com/gocodebox/lifterlms/blob/5.4.0/includes/forms/class-llms-form-handler.php#L390) (sanitizing an email like `hey@hey` results in an **empty string**).
- [validate the fields](https://github.com/gocodebox/lifterlms/blob/5.4.0/includes/forms/class-llms-form-handler.php#L392) (we skip fields with [empty values](https://github.com/gocodebox/lifterlms/blob/5.4.0/includes/forms/class-llms-form-validator.php#L395-L397))

So the thing is that, and it makes sense to me, we should not sanitize before validating, but rather do the opposite.
Additionally, I wonder if we should do another check on the required fields just after the sanitization, but I guess that would just be paranoid.

**Comment by nrherron92** [comment]
@eri-trabiccolo you can make a registration form with no password: 
![image](https://user-images.githubusercontent.com/47434271/138099053-a2b59921-c282-4f16-b86c-7fe8ffa0a55f.png)

**Comment by eri-trabiccolo** [comment]
@nrherron92 do you have a website where I can check this?

**Comment by nrherron92** [comment]
@eri-trabiccolo yeah! I'll send you the password link to my lifterlms site

**Comment by eri-trabiccolo** [comment]
@nrherron92 
thanks!
So you can have a registration form with no password field if you removed the password field from the form and from the password reusable block (which becomes empty). Aside from the fact that this is not related to this very issue, we must decide whether, a password field can be removed from the password reusable block - I guess it shouldn't.
In any case when re-adding the minimum required fields (email, password) to a form which is missing them we should make sure the reusable blocks are containing the actual fields we need...
