### ISSUE TITLE
User account creation requires complex password (beta 3.0) possible bug

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#183]
## Brief summary of issue
new user account required a very complex password (I was able to get in with a 16 character)

## Reproduction Steps
- purchase a new course as a new user
- enter a password with 7 or 8 characters

## Expected Behavior
The instructions include choosing a six plus character password with numbers and letters.

##What I'm experiencing
When creating a new test user account I used an 8 character password with one capital letter, two numbers and an apostrophe. I was presented with the error message below (see screenshot)

## Other notes 
I thought there might be an issue with some of the security plugins I use, but then I remembered I was using a clean install, and the only plugin is lifterlms, so I believe it's tied directly into lifter

##Screenshots or video
![image](https://cloud.githubusercontent.com/assets/4434724/18373472/389027f4-75f9-11e6-81d4-83915d35ba01.png)

## Server Details
**Server Info:** Apache
**PHP Version:** 5.6.24
**PHP Max Post Size:** 64 MB
**Max Upload Size:** 64 MB
**PHP Time Limit:** 30
**PHP Max Input Vars:** 1000
**MySQL Version:** 5.5.48

## Browser, Device, and Operating System
**Browser:** Chrome 52
**Operating system:** Windows NT 10.0
**Javascript enabled** Yes
**Cookies enabled** Yes
**Flash version** 22.0.0
**Java version** Not installed
**Websockets supported** Yes
**Browser size** 1263 x 595
**Screen size** 1280 x 720 (Retina)
**Color depth** 24 bit

**Comment by thomasplevy** [comment]
@Loralee check out settings for password strength under LifterLMS -> Accounts

You can disable password strength requirements entirely or lower the strength via the options available there

This is not a bug

If you feel the default strength should be lowered I will consider that if other testers agree that a default "Strong" is too strong

also, for what it's worth, we're leveraging WordPress core password stength functions, not our own overly complex systems. WooCommerce has also recently enforced password strength on account creation too. We're not coming out of nowhere with this feature, we're following a WP trend

**Comment by Loralee** [comment]
@thomasplevy - just wanted to quickly follow up with this one - my only concern about this one is that the message below the password strength meter says that it should be 6 characters. Is that also a WP message? Or is it text delivered from lifterlms?

**Comment by thomasplevy** [comment]
@Loralee,  6 characters is a limit I added, again, if you want to allow really weak passwords, just disable password strength all together!
