### ISSUE TITLE
both enrolled and unenrolled information is displayed after signup

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#184]
## Brief summary of issue
after payment confirmation user is returned to the top of page, with the original course information. The "confirmation" message is displayed farther down the screen, inbetween the info for unenrolled and enrolled users.

(at least I believe this is what I'm experiencing - it's possible this should be filed as 2 separate issues)

## Reproduction Steps

1. Ensure course has information in both the enroll and unenrolled fields (see screenshot)
2. Enroll in course 
3. Look for confirmation of purchase message

![image](https://cloud.githubusercontent.com/assets/4434724/18374855/44fae1d0-7605-11e6-9415-d93eb945c025.png)

## Expected Behavior
I thought the page would refresh, and display the enrolled user information (not both), with the confirmation message near the top of the page

##What I'm experiencing
I needed to scroll down past the non-enrolled info. The confirmation message is in the middle (In my test example, it's presenting duplicate information - similar information for enrolled and non enrolled)

## Other notes 
It's possible this is more than one issue (the presentation of the confirmation message, and displaying of both fields), but I thought I'd combine them together.

##Screenshots or video
![image](https://cloud.githubusercontent.com/assets/4434724/18374771/83245f8c-7604-11e6-9b6e-3e346558d6f9.png)

##WordPress Environment
**LifterLMS Version:** 3.0.0-beta.6
**Wordpress Version:** 4.6.1

## Server Details
(can copy and paste from your lifterlms installation at 
**Server Info:** Apache
**PHP Version:** 5.6.24
**PHP Max Post Size:** 64 MB
**Max Upload Size:** 64 MB
**PHP Time Limit:** 30
**PHP Max Input Vars:** 1000
**MySQL Version:** 5.5.48

## Browser, Device, and Operating System
**Browser:** Chrome 52
**Operating system:** Windows NT 10.0
**Javascript enabled** Yes
**Cookies enabled** Yes
**Flash version** 22.0.0
**Java version** Not installed
**Websockets supported** Yes
**Browser size** 1263 x 595
**Screen size** 1280 x 720 (Retina)
**Color depth** 24 bit

**Comment by thomasplevy** [comment]
appears to be a twenty sixteen issue... theme outputs the the non-enrolled stuff at the top automatically b/c we store it in the excerpt...

**Comment by thomasplevy** [comment]
lets give this a shot: https://lifterlms.com/docs/content-for-unenrolled-students-displays-for-enrolled-students-when-using-the-twenty-sixteen-theme/

I considered adding this code directly to the core but I feel dirty about doing that, especially if another plugin or a child theme is already plugging the function... This will get the job done on a case by case basis when the theme is being used
