### ISSUE TITLE
SEOPress Conflict

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1865]
### Reproduction Steps

+ HS-180585 -- I'll get y'all credentials
+ Enable SEOPress and Query Monitor 
+  Query Monitor, reports LifterLMS calls go up from 24, when SEOPress is deactivated, to 544 with SEOPress activated. This is to the exact same page and repro's 100% of the time.
+ single call to LLMS_Course::get_sections results in 27 extra database queries with SEOPress activated, as compared to with SEOPress deactivated.

### Expected Behavior

+ The calls presumably shouldn't expand like that with SEOPress on

### Actual Behavior

+ A massive increase in calls.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
`SELECT SQL_CALC_FOUND_ROWS wp_posts.*
FROM wp_posts
INNER JOIN wp_postmeta
ON ( wp_posts.ID = wp_postmeta.post_id )
INNER JOIN wp_postmeta AS mt1
ON ( wp_posts.ID = mt1.post_id )
WHERE 1=1
AND ( wp_postmeta.meta_key = '_llms_order'
AND ( ( mt1.meta_key = '_llms_parent_section'
AND mt1.meta_value = '2875' ) ) )
AND wp_posts.post_type = 'lesson'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'acf-disabled'
OR wp_posts.post_status = 'xlwctydisabled'
OR wp_posts.post_status = 'llms-completed'
OR wp_posts.post_status = 'llms-active'
OR wp_posts.post_status = 'llms-expired'
OR wp_posts.post_status = 'llms-on-hold'
OR wp_posts.post_status = 'llms-pending-cancel'
OR wp_posts.post_status = 'llms-pending'
OR wp_posts.post_status = 'llms-cancelled'
OR wp_posts.post_status = 'llms-refunded'
OR wp_posts.post_status = 'llms-failed'
OR wp_posts.post_status = 'llms-txn-failed'
OR wp_posts.post_status = 'llms-txn-pending'
OR wp_posts.post_status = 'llms-txn-refunded'
OR wp_posts.post_status = 'llms-txn-succeeded'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
ORDER BY wp_postmeta.meta_value+0 ASC
LIMIT 0, 500`

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Website

[removed]

Admin Credentials

Email:
Password:

System Report

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: /logon
Version: 5.8.2
Debug Mode: No
Debug Log: No
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: PerfectBee: To Your First Beehive and Beyond (#5865) [[removed]/]
Permalink Structure: /%category%/%postname%
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 4.21.3
Db Version: 4.21.3
Course Catalog: Course Catalog (#7) [[removed]/courses]
Membership Catalog: Membership Catalog (#8) [[removed]/memberships]
Student Dashboard: Dashboard (#1419) [[removed]/?page_id=1419]
Checkout Page: Purchase (#9) [[removed]/purchase]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my_account
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 256 MB
Php Memory Limit: 512M
Php Post Max Size: 500M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 240
Php Version: 7.4.25
Software: nginx/1.19.3
Wp Memory Limit: 512M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53


Theme
-------------------------------------------

Name: Twenty Twenty
Version: 1.8
Themeuri: https://wordpress.org/themes/twentytwenty/
Authoruri: https://wordpress.org/
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Advanced Custom Fields PRO: 5.11
Advanced Scripts: 2.3.3
AeroCheckout: Custom WooCommerce Checkout Pages: 2.7.2
Akismet Anti-Spam: 4.2.1
Category Order and Taxonomy Terms Order: 1.5.7.7
Custom Post Type UI: 1.10.0
Discourage Search Engines Notifier: 1.9
Fatal Error Notify: 1.4.4
Favicon by RealFaviconGenerator: 1.3.22
Flexible Shipping: 4.10.0
Flexible Shipping PRO: 2.9.1
Fluent Forms: 4.2.21
Fluent Forms Pro Add On Pack: 4.2.0
FluentSMTP: 2.1.0
Groundhogg: 2.5.5
Groundhogg - Advanced Email Preferences: 1.0.8
Groundhogg - Advanced Features: 2.2.8
Groundhogg - Conditional Funnel Logic: 1.0.6
Groundhogg - WooCommerce Integration: 2.4
Hydrogen Pack: 1.3.5
ImageInject: 1.17
Judge.me Product Reviews for WooCommerce: 1.3.11
LifterLMS: 4.21.3
LifterLMS Advanced Quizzes: 1.1.1
MainWP Child: 4.1.8
Metorik Helper: 1.5.1
NextMove Lite - Thank You Page for WooCommerce: 2.14.2
Oxygen: 3.6.1
Oxygen Elements for WooCommerce: 1.3
PerfectBee Utilities: 3.14
Perfmatters: 1.8.1
Permalink Manager Pro: 2.2.14
PixelYourSite PRO: 8.4.3
PixelYourSite Super Pack: 2.1.9
Product Catalog Feed Pro by PixelYourSite: 5.1.2
Query Monitor: 3.7.1
Redirection: 5.1.3
Redis Object Cache: 2.0.21
Safe SVG: 1.9.9
SearchIQ: 3.8
ShortPixel Image Optimizer: 4.22.6
TaxJar - Sales Tax Automation for WooCommerce: 4.0.0
UpdraftPlus - Backup/Restore: 2.16.63.25
User Role Editor: 4.60.2
WooCommerce: 5.9.0
WooCommerce Advanced Bulk Edit: 4.5
WooCommerce Shipment Tracking: 1.6.29
WooCommerce Stripe Gateway: 5.8.0
WooCommerce Subscriptions: 3.1.6
Woo Discount Rules: 2.3.10
Woo Discount Rules PRO 2.0: 2.3.9
WP-Discourse: 2.3.4
WP All Export - ACF Export Add-On Pro: 1.0.3
WP All Export - WooCommerce Export Add-On Pro: 1.0.3
WP All Export Pro: 1.7.2
WP Data Access Premium: 5.0.0
WP Fusion: 3.36.11
WP Fusion - Logins Addon: 1.2.4
WP Google Maps: 8.1.18
WP Rocket: 3.8.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 an initial review of this issue shows that there are the same number of queries on a course page with SEOPress activae and inactive.

I'm looking deeper into the plugin's settings to see if I can find a way to "add queries" via a setting or something...

The user mentions there's a specific page on the site where this is happening, I'd like to know what page this is to see if I can find anything on that page that might explain what's happening here.

**Comment by thomasplevy** [comment]
I can't find anything with LifterLMS and SEOPress itself... I've looked through all the SEOPress settings and I can't get the queries on a course page to increase by having SEOPress enabled (it increases by 2, there's two option queries run by SEOPress).

I see that the Oxygen Builder plugin is enabled and the customer's course pages seem to not use our default syllabus (where the query referenced in the ticket comes from). I'm wondering if the builder has something to do with this. It would be interesting to have the customer disable all other plugins except LifterLMS and SEOPress and see if they have the same findings as I have

**Comment by nrherron92** [comment]
@thomasplevy We finally got access to the test site. It looks to me like the queries are coming from Oxygen. When I turn oxygen off it drops, but I wasn't seeing any difference between SEO on and off. 

Do we still have access to the Oxygen builder that I can test locally from that other issue we had come up with them?

The link to the staging site is on the ticket with an autologin code. The only thing he asked is that we don't turn off FluentSMTP but I don't think that's doing anything.

**Comment by thomasplevy** [comment]
@nrherron92 here's the issue from the Oxygen issue. @eri-trabiccolo worked on it not me so I don't have a copy of Oxygen but maybe he does or maybe the initial ticket still has the plugin?

https://github.com/gocodebox/lifterlms/issues/1841

I'm not sure if there's much more for us to do though if the combination of Oxygen and SEOPress are creating the increase in queries what would we do about this? The query that was cited *does* come from LifterLMS but that query is *expected* to run. 

I'm not familiar with Oxygen in the least but my guess here is that some sort of page builder post preview thing is being run which is causing SEOPress to load SEO data for each instance of the "sub page" being displayed via the builder... If this is the case while it may be happening on a LifterLMS page it's not really a LifterLMS problem... Though maybe I'm incorrect as I'm guessing.

**Comment by nrherron92** [comment]
He's taking it up with oxygen and seopress. We're good to close!
