### ISSUE TITLE
Dev-600: Cannot award a certificate to a specific student, if using the block editor

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1889]
### Reproduction Steps
1)
+ from your wp dashboard -> Engagements -> Awarded Certificates
+ click on Award Certificate
+ select a student different from yourself :D
+ save
+ reload the page
+ look at the Student select
2)
+ from your wp dashboard -> LifterLMS -> Reporting
+ click on a user email
+ click on the certificates tab
+ click on the Award Certificate button
+ look at the Student select

### Expected Behavior

1) I'd expect the student to be the one I chose.

2) I'd expect the student to be the one of the reporting.

### Actual Behavior

1)
+ the student who awarded the certificate is actually you
+ and you can find it in your reporting -> certificates
+ Also the student's link points to the user's profile, while it should point to the student's reporting.

2)
+ the student select shows you

**Comment by thomasplevy** [comment]
This is fixed by #1887 right?

**Comment by eri-trabiccolo** [comment]
Nope it's not.
