### ISSUE TITLE
Add @pondermatic as a contributor via wp.org readme frontmatter

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1895]
https://github.com/gocodebox/lifterlms/blob/trunk/.wordpress-org/readme/01-header.md

@pondermatic let me get your WordPress.org username and we'll get you added as a contributor :+1:

**Comment by pondermatic** [comment]
@thomasplevy, my wordpress.org username is `pondermatic`.

**Comment by thomasplevy** [comment]
@pondermatic thanks, also added to .org repo as a support rep in case you ever need to post something there you'll have a flag on your name (or something, I think)
