### ISSUE TITLE
Dev 600: Legacy Template label might be confusing?

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1903]
When looking at the awarded certificate list table, there can be some items with the label "Legacy Template", plus this items have the action link "Migrate Template", no matter whether they were manually awarded or they actually had a "certificate template". 
I think this might be a bit confusing, not sure how to call that though, but Legacy Template doesn't refer to the awarded certificate's parent (certificate template), as well as the Migrate Template action link, will allow you to migrate the awarded certificate not its template.

What do you think?

**Comment by thomasplevy** [comment]
What do you suggest?

**Comment by eri-trabiccolo** [comment]
just "Legacy" for the label and "Migrate legacy certificate" for the action link?

**Comment by thomasplevy** [comment]
Sounds good to me <3
