### ISSUE TITLE
Metaboxes transition to 3.x api & look towards gutenberg compat

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#191]
includes/admin/post-types/class.llms.meta.boxes.php

**Comment by thomasplevy** [comment]
Metaboxes should be refactored to be forward compatible to gutenberg: https://wordpress.org/gutenberg/handbook/extensibility/meta-box/

**Comment by actual-saurabh** [comment]
This was added in https://github.com/gocodebox/lifterlms/tree/3.25.0
