### ISSUE TITLE
LifterLMS 6.0.0 Prerelease Testing & Feedback

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#1935]
## General Feedback

Testing a prerelease of LifterLMS 6.0.0 and have feedback? Let us know your thoughts below

## Theme Compatibility

We should test compatibility with themes we [recommend](https://lifterlms.com/recommended-resources/#themes)

We will consider a theme to be compatible if no obvious visual issues are seen when viewing a certificate on screen or in the print preview dialog when trying to print the certificate. We're not very concerned with checking compatibility of legacy certificates at this point (since nothing's really changed there) but we would like to know about issues on new certificates created with the block ed.

Where possible, we should enlist the assistance of theme developers to help us test compatibility

See below: https://github.com/gocodebox/lifterlms/issues/1935#issuecomment-1021392014

## Internal Q&A / Testing / Etc...

Each of the following team members will test 6.0.0 functionality and report bugs / issues / feedback

+ [ ] @chrisbadgett 
+ [ ] @nrherron92 
+ [ ] @toyinogunseinde 
+ [ ] @willmiddleton-lifterlms

**Comment by nrherron92** [comment]
+ [x] Astra
+ [x] Authority Pro
+ [x] BuddyBoss - issue open
+ [ ] Course Maker Pro
+ [x] Divi - issue open
+ [ ] Emerson
+ [x] Genesis - fix pending
+ [x] Kadence
+ [ ] Magazine Pro
+ [x] Monochrome Pro
+ [x] Neve
+ [ ] Ocean WP - fix pending
+ [x] Page Builder Framework
+ [x] Revolution Pro
+ [ ] Sage
+ [ ] Tribe
+ [ ] Tutorque
+ [ ] Ventura

Additionally we should ensure compatibility with recent WP core default themes:
+ [ ] Twenty Twenty - issue opened
+ [x] Twenty Twenty-One
+ [ ] Twenty Twenty-Two

**Comment by thomasplevy** [comment]
@nrherron92 any updates on this list, how are you feeling generally about theme compat and 6.0?

**Comment by nrherron92** [comment]
@thomasplevy I think it works pretty solidly with any well built theme! The only thing I still want to teat is with the PDF integration. I think I had an issue open before that we needed to wait for the update on?

**Comment by thomasplevy** [comment]
@nrherron92 We'll have another version out by end of the week fixing the kadence issue but the pdfs 2.0 beta is now available :+1:
