### ISSUE TITLE
[6.0] Divi Removes Default Content in Certificates

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1949]
### Reproduction Steps

+ Install Divi
+ Create a new certificate
+ Choose the default editor to build the certificate in Gutenberg as expected

### Expected Behavior

+ You see our default template settings to edit or keep. 

### Actual Behavior

+ Divi's removed all of our default content
https://www.loom.com/share/10d0f2facf4c41789d8eceb228e4b16c

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-alpha.3
Db Version: 5.7.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Authorize.Net: Enabled
Authorize.Net Test Mode: Enabled
Authorize.Net Logging: no
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Enabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.36
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.33
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.14.7
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-alpha.3
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.17
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS ConvertKit: 2.1.2
LifterLMS Custom Fields: 2.0.2
LifterLMS Formidable Forms: 1.0.4
LifterLMS Gravity Forms: 2.1.2
LifterLMS Groups: 1.0.0-beta.17
LifterLMS MailChimp Add-on: 3.2.0
LifterLMS Ninja Forms: 1.1.1
LifterLMS PayPal Gateway: 1.3.0
LifterLMS PDFs: 1.0.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.4.0
LifterLMS Stripe Payment Gateway: 5.4.0
LifterLMS WooCommerce: 2.2.1
LifterLMS WPForms: 1.1.1
User Switching: 1.5.8
WooCommerce: 6.1.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: Yes
LifterLMS Groups: Yes
LifterLMS Formidable Forms: No
LifterLMS Gravity Forms: No
LifterLMS Ninja Forms: No
WooCommerce: Yes
LifterLMS WPForms: No
LifterLMS MailChimp: Yes
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 that "content" you're missing is the default certificate block template. Which is helpful as a starting point but not *essential* to build certificates. Can you let me know if you can actually build a certificate (just add some content, doesn't have to be pretty) and check the frontend output after saving.

Ideally, the option to use the divi builder on certificates *won't* exist... Although I'd be interested to know what happens when you try to build it using the divi builder (does it work at all?)

This will help me form an opionon on how to proceed with divi compat here

**Comment by nrherron92** [comment]
@thomasplevy oh yeah you can build a custom one and it works just the same as any other theme for display and print

the divi builder does work! you can use their builder but it get wonky when you try to print, but essentially if you use the Divi builder it will switch you back to legacy certificates

**Comment by thomasplevy** [comment]
Okay thanks @nrherron92 I'm going to leave this open... if we can find some time to investigate compatibility more closely we will, otherrwise if it *works* but is a "little wonky" I'm going to call that good enough for Divi for launch. I don't want to have to add custom theme support internally for every theme but for this one we might have to.

I'm not opposed to letting divi users switch over to divi and fight with print compat on their own but we could probably figure out how to make it work. Though I think the ideal would be to *force off* the divi builder entirely... if possible

**Comment by thomasplevy** [comment]
Though Divi users will hate me for saying that probably

**Comment by eri-trabiccolo** [comment]
@thomasplevy @nrherron92 
I did a clean install of Divi, and as far as I can see, the Divi Builder is not enabled by default for the Certificate Templates and Awarded Certificates post types. 
If they want to use the builder there they have to go in Divi -> Theme Options -> Builder -> Post Type Integration -> Enable Divi Builder On Post Types 
and select the aforementioned post types.
If they do that it's up to them I guess. The problems with the print depend on the Divi CSS, not on us, it's about the _spacing_ of their elements, the columns sizing and responsiveness, etc.
Forcing them not using the Divi builder, on the other hand, raises another issue: customers might have used it in the past, so they might have some certificate templates built with the Divi builder, so we should force not using the Divi builder only on new items (and on old ones that already didn't use it).
I'm not sure this is worthwhile to be honest, since:
1) the Divi Builder is not the def editor for certificates
2) customers can opt it out and ideally reset the certificate templates to the default ones

**Comment by thomasplevy** [comment]
@eri-trabiccolo Good points on all fronts. I think we'll leave it as is and return in the future should more information is revealed (likely in the form of a lot of complaints)
