### ISSUE TITLE
Skipping the setup wizard....how to get back to it?

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#195]
I decided on skipping the setup wizard.
Now how do I get back to it....

I first tried the installed plugin screen to see if LifterLMS plugin linked beside Deactivate I Edit I Settings. I clicked Settings and thought that the top area of the settings would give me a notification asking me if I wanted to continue with the setup wizard. Hmm not there...

There needs to be a logical place for the user to continue the setup wizard.

**Comment by thomasplevy** [comment]
@paaljoachim i have yet to write documentation on this, it's on my todo list for prerelease and will be covered in docs

head to LifterLMS -> Settings and scroll down -- hit the "Return to Setup Wizard" button
