### ISSUE TITLE
[6.0] Pop Up Mini Certificate Oversized

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1950]
### Reproduction Steps

+ create a certificate
+ complete the trigger or assign the certificate to a user
+ view the pop up for the certificate awarded on the front end

### Expected Behavior

+ You can see the pop up and click the option to view the full certificate
![image](https://user-images.githubusercontent.com/47434271/150574349-1b6b93b1-368c-46b9-b516-cd3977df13d2.png)

### Actual Behavior

+ In Divi the mini certificate takes up the whole screen and you can not click the view full certificate
+ It also hides any other pop ups that come at the same time
![image](https://user-images.githubusercontent.com/47434271/150574080-dcd63553-4b08-4d71-a165-466cafad8646.png)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-alpha.3
Db Version: 5.7.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Authorize.Net: Enabled
Authorize.Net Test Mode: Enabled
Authorize.Net Logging: no
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Enabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.36
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.33
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.14.7
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-alpha.3
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.17
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS ConvertKit: 2.1.2
LifterLMS Custom Fields: 2.0.2
LifterLMS Formidable Forms: 1.0.4
LifterLMS Gravity Forms: 2.1.2
LifterLMS Groups: 1.0.0-beta.17
LifterLMS MailChimp Add-on: 3.2.0
LifterLMS Ninja Forms: 1.1.1
LifterLMS PayPal Gateway: 1.3.0
LifterLMS PDFs: 1.0.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.4.0
LifterLMS Stripe Payment Gateway: 5.4.0
LifterLMS WooCommerce: 2.2.1
LifterLMS WPForms: 1.1.1
User Switching: 1.5.8
WooCommerce: 6.1.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: Yes
LifterLMS Groups: Yes
LifterLMS Formidable Forms: No
LifterLMS Gravity Forms: No
LifterLMS Ninja Forms: No
WooCommerce: Yes
LifterLMS WPForms: No
LifterLMS MailChimp: Yes
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------





```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
This is actually happening on other themes too and isn't a divi-specific issue as far as I can tell

**Comment by nrherron92** [comment]
yeah I just noticed it does this on twenty-twenty one too

**Comment by thomasplevy** [comment]
@gocodebox/engineering @gocodebox/success @chrisbadgett 

Thoughts on this as a potential solution to the problem identified here...

https://user-images.githubusercontent.com/1290739/152448592-b387730d-8fed-491b-a57b-83444fea5612.mp4

The current strategy creates "mini" certificate by stripping most html / styles (except text) and putting htem in a little frame.

With certificates now having much more complex HTML in the block editor this strategy doesn't really work.

This proposed solution replaces everything except the certificate title with placeholder shapes with a little "sweeping" image we're used to seeing in web apps (facebook, twitter, etc...). It's not technically loading anything so maybe this doesn't make sense. But it looks okay, I think....

Thoughts??

**Comment by eri-trabiccolo** [comment]
Is "Welcome" the actual certificate title?
Anyways I like this solution. I'm with you.

**Comment by nrherron92** [comment]
I like this solution! This looks super slick. It also looks like it's "loading up" the certificate for you to go see!

**Comment by thomasplevy** [comment]
> Is "Welcome" the actual certificate title?

Yes, that was the title of this cert. Very inventive.

**Comment by thomasplevy** [comment]
> I like this solution! This looks super slick. It also looks like it's "loading up" the certificate for you to go see!

Is that problematic though? Since it won't ever actually load it there... I figure since the notification is auto-dismissed it's okay but I don't want users to feel like it's *supposed* to be loading and it's just taking too long because "LifterLMS is slow" or whatever...

**Comment by nrherron92** [comment]
Oh yeah good point. I feel like because it is auto dismissed it is fine. To me, it seems like you should click on it to see the certificate fully loaded. I like that it seems like it's baking. But you're right, some people will probably think that it's an indication of a lag or their site loading slow if it dismisses before it fully loads... maybe we could have the other information like under a blur where it's not the real information but looks like it is filled out but you need to click on it to see the whole thing?

**Comment by eri-trabiccolo** [comment]
Maybe old users can think that but... not sure. I don't think it's something we should really care about. What if we just remove that sweeping effect?

**Comment by chrisbadgett** [comment]
I like the placeholder solution. Looks cleaner. I also agree to not have the loading/sweeping effect as I was staring at it waiting it to load some content.
