### ISSUE TITLE
[6.0] Twenty-Twenty Makes Everything Huge

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1954]
### Reproduction Steps

+ Twenty-Twenty Theme + Make a Certificate (Note: twenty-twenty two does the same thing)
+ If you just do the default and publish you get a certificate that looks like this:
![image](https://user-images.githubusercontent.com/47434271/151054177-a1926cef-15a5-422a-9c0d-09c99ecea522.png)

+ If you go ahead and remove the default spacers there is still some oversized spacing where there shouldn't be there.
![image](https://user-images.githubusercontent.com/47434271/151055169-29f2975f-f746-41d4-8488-33557b8a305e.png)

### Actual Behavior

+ Everything is oversized. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-alpha.3
Db Version: 5.7.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Authorize.Net: Enabled
Authorize.Net Test Mode: Enabled
Authorize.Net Logging: no
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Enabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.36
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.14
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty
Version: 1.8
Themeuri: https://wordpress.org/themes/twentytwenty/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-alpha.3
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.17
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS ConvertKit: 2.1.2
LifterLMS Custom Fields: 2.0.2
LifterLMS Formidable Forms: 1.0.4
LifterLMS Gravity Forms: 2.1.2
LifterLMS Groups: 1.0.0-beta.17
LifterLMS MailChimp Add-on: 3.2.0
LifterLMS Ninja Forms: 1.1.1
LifterLMS PayPal Gateway: 1.3.0
LifterLMS PDFs: 1.0.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.4.0
LifterLMS Stripe Payment Gateway: 5.4.0
LifterLMS WPForms: 1.1.1
User Switching: 1.5.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: Yes
LifterLMS Groups: Yes
LifterLMS Formidable Forms: No
LifterLMS Gravity Forms: No
LifterLMS Ninja Forms: No
LifterLMS WPForms: No
LifterLMS MailChimp: Yes
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 Twenty Twenty doesn't look like this at all for me
![Screenshot_2022-02-03_15-50-37](https://user-images.githubusercontent.com/1290739/152442465-0d86382b-f5f6-4613-8ed2-7aa9a17c3a19.png)

I see you're on 1.8, the latest version is 1.9... I can't imagine that has too much of an impact but can you double check what you're seeing for me?

What I'm seeing is a bit under sized but I think that's okay for default content in this scenario, spilling over isn't great though. If it's too small I'm going to ignore it and move on.

**Comment by thomasplevy** [comment]
@nrherron92 :arrow_up:

**Comment by nrherron92** [comment]
@thomasplevy sorry I missed this before.... but I still see the issue?

https://www.loom.com/share/9c139abd058241f880390cf9c274e19b

**Comment by eri-trabiccolo** [comment]
It looks very big here too, I'm with Natie

**Comment by thomasplevy** [comment]
I had added bootstrap to my site to debug something with PDFs (via an enqueue via an MU plugin) and it was causing everything to render real small (on every theme) and I simply didn't realize it cause I'm a dumbie.

**Comment by thomasplevy** [comment]
It looks like the twentytwenty theme doesn't include the same editor styles as it does frontend styles... This may have to do with changes in the block editor apis since the theme was released and since it's an oldish theme now I'm guessing updates weren't released to the theme to accommodate since, in most circumstance, the visual discrepencies between the editor and the frontend are going to have negligible impact... I can't come up with a descent way to address this other than adding CSS specific to the theme to our twentytwenty compat file. Mostly this includes reducing margins on header elements.

I'm going to drop this off me and leave it up to either @eri-trabiccolo  or @pondermatic to pickup and workout some CSS rules to address the visual issues identified here on the frontend.

I don't think we're ever going to achieve 100% theme compatibility with this update unless we completely remove all theme styles from certificates and do a full CSS reset and only load our styles. I don't think this is a good idea especially since we're late in the release cycle of 6.0
