### ISSUE TITLE
[6.0] Return to (student) Dashboard (from certificate screen)

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1959]
**Is your feature request related to a problem? Please describe.**
Students no longer see the header or menu on certificates and will want a way to go back to their dashboard or other content that isn't the back button 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/47434271/151581823-d4fc8b3e-a546-4264-ad00-a993252de95a.png)

**Comment by eri-trabiccolo** [comment]
jeez, she's right. dammit!
