### ISSUE TITLE
LifterLMS Settings as well as other screens - too much space between letters.

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#196]
The letters in 
General - Catalogs and the other words are too far from each other. They almost lose each other. Push them a little closer to each other.

![screen shot 2016-09-14 at 20 12 31](https://cloud.githubusercontent.com/assets/5323259/18524161/986cff90-7ab7-11e6-91cc-6ad23654505b.png)

My suggestion:

![lifterlms-settings-top-bar](https://cloud.githubusercontent.com/assets/5323259/18524337/43ff28ce-7ab8-11e6-962b-cd38c8238ead.jpg)

At the same time get rid of the grow shrink thing on hover. It looks cheesy. It is more then enough that the background light blue changes to the dark blue.

The above also relates to other screens as well. I am looking at Catalogs section right now and am also seeing large distances between letters in subtitles here. Likely the same goes for other screens as well.

Btw
![screen shot 2016-09-14 at 20 38 55](https://cloud.githubusercontent.com/assets/5323259/18525064/50fb488e-7abb-11e6-80ce-f85eac65935b.png)

**Comment by thomasplevy** [comment]
@paaljoachim thanks for the feedback, our menus have been like this since v1.0.0 and while I don't necessarily disagree with you I don't necessarily agree either.

Going to leave this open and possibly revisit when we do some visual upgades on the admin panel (we have a much needed css & js refactoring project ahead of us).

Thanks

**Comment by thomasplevy** [comment]
updated in 3.0

**Comment by paaljoachim** [comment]
I am hoping to finally get around to testing your plugin realtime as I create WordPress tutorials.
