### ISSUE TITLE
[6.0] Reset to Default in Certificate Builder

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1960]
**Describe the solution you'd like**
A reset to default button in the certificate builder like what we have for forms, so if something breaks or the user does too many weird changes they don't like we can get it back to the default easily to fix the issue!

**Comment by thomasplevy** [comment]
Useful method: https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#gettemplate

**Comment by eri-trabiccolo** [comment]
~@thomasplevy 
Shall we do that with legacy certificates too?~
stupid trabiccolo, there's no default template for legacy certificates.
