### ISSUE TITLE
[6.0] display controller sync errors

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#1962]
[`LLMS_Controller_Certificates::sync_awarded_certificate()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/controllers/class.llms.controller.certificates.php#L195) adds a `WP_error` object instead of a string to the meta box errors array. [`LLMS_Admin_Metabox::output_errors()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/abstracts/abstract.llms.admin.metabox.php#L297) can't handle `WP_Error` objects.

[`LLMS_Controller_Certificates::maybe_handle_awarded_certificates_sync_actions()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/controllers/class.llms.controller.certificates.php#L143) and the related sync methods all return `WP_Error` objects, but don't seem to have a way to display the errors on the admin pages.

**Comment by thomasplevy** [comment]
@pondermatic is something you can cleanup in your current project since you're already working on some refactoring of these syncing mechanisms?

Seems like you can just change the WP_Error to an error string an move on. But I'm wondering if I'm missing something bigger here...?

**Comment by pondermatic** [comment]
Yes, I can clean this up.

The unit tests need WP_Error because they are looking for specific codes. I'll teach [`LLMS_Admin_Metabox::output_errors()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/abstracts/abstract.llms.admin.metabox.php#L297) how to output the message from WP_Error.

**Comment by eri-trabiccolo** [comment]
@pondermatic 
This looks an oversight from me :) 
I think you can safely turn this:
https://github.com/gocodebox/lifterlms/blob/dev-600/includes/controllers/class.llms.controller.certificates.php#L214-L221
into 
```php
					sprintf(
						__( 'Sorry, the awarded certificate #%d has a not valid certificate template.', 'lifterlms' ),
						$cert_id
					),
```

About 

> LLMS_Controller_Certificates::maybe_handle_awarded_certificates_sync_actions() and the related sync methods all return WP_Error objects, but don't seem to have a way to display the errors on the admin pages.

Yeah, I actually added those wp error returns just for testing purposes, didn't mean to display nothing to the user.

**Comment by pondermatic** [comment]
@eri-trabiccolo 
I've updated [`LLMS_Admin_Metabox::output_errors()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/abstracts/abstract.llms.admin.metabox.php#L297) to handle WP_Error objects, so now we can test for an error code and still output a string on the admin pages.

**Comment by pondermatic** [comment]
@gocodebox/engineering 
I'm thinking that all of the new sync errors generated in [`LLMS_Controller_Certificates`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/abstracts/abstract.llms.admin.metabox.php) should be run through `LLMS_Meta_Box_Award_Engagement_Submit::add_error()` so that they are displayed on the admin pages. It doesn't looks like they are displayed right now.

**Comment by eri-trabiccolo** [comment]
Yeah they're not, see my:

> Yeah, I actually added those wp error returns just for testing purposes, didn't mean to display nothing to the user.
above.

I honestly don't think those errors are for the end user. Do we usually tell the user the nonce is invalid or that the action requested requires an id but that id is missing? Those checks are relevant for us, to avoid processing invalid actions.
I wouldn't want to pollute the admin notifications area with them. Also they are not something users can reproduce if not voluntarily, at this point I would rather go with a `wp_die()`.
Additionally consider that, as of now, the metabox admin notice is "kinda hidden" in the block editor.

**Comment by pondermatic** [comment]
If the sync errors are not for the user, and they're currently hidden under the block editor anyway, how about we handle `llms-sync-awarded-certificate-invalid-template` the same way we do the others by returning a `WP_Error` and don't add it to `LLMS_Meta_Box_Award_Engagement_Submit::$errors`?

**Comment by thomasplevy** [comment]
I think in this scenario where the error is being added to the metabox *we do* wish to display the error message to the user.

So we can switch it from a WP_Error to a string... If we have to modify a test, modify a test.
