### ISSUE TITLE
LifterLMS Settings screen

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#197]
Looking at the LifterLMS Settings

It looks more like an ad for LifterLMS addons because of the huge banners for Pro, Launchpad, Stripe and MailChimp, ConvertKit, Boost, Turbo Boost and the 4 smaller squares below it.

Make these smaller. As they get in your face too much.
It would be good to make this important screen show importance not be an ad.

Please rework this screen to focus on settings.

A better option would be to add a Addon/Extension link to the bottom of the LifterLMS sidebar meny where you can place the various big and small squares. For users to get more information on additional products.

**Comment by thomasplevy** [comment]
@paaljoachim thanks again, I can't justify removing a few ads from a free plugin. They actually convert quite well for us and you can always ignore them.

We may do an extensions page in the future like other plugins but at this moment I don't have the capacity or interest in reworking this screen

**Comment by paaljoachim** [comment]
If the existing version works then it works.....:)
