### ISSUE TITLE
Top bar of Analytics (New) is too alive

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#198]
Hey

The top bar:

![screen shot 2016-09-14 at 20 44 24](https://cloud.githubusercontent.com/assets/5323259/18525281/1106c7ac-7abc-11e6-9e23-8e9bab30ad93.png)

Takes too much visual space and creates visual clutter.
Please cut out some of the animation effects going on. Make it plain and simple. Less space between the headings so that most of the time they are in one row.

Remove the grow/shrink on hover of: This Year, Last Month etc etc. Just go with a change in color.

Go button looks like a button. Please keep consistency. Text or button. Btw the text contains too much space again.

![screen shot 2016-09-14 at 20 47 40](https://cloud.githubusercontent.com/assets/5323259/18525389/8c30025e-7abc-11e6-8098-4481779643b7.png)

I made the screen wider and all of it came onto the lines they are supposed to be on. On a smaller screen just let some of them come closer together and still keep it on one line.

Sigh. A little smaller screen looks like this:
![screen shot 2016-09-14 at 20 51 00](https://cloud.githubusercontent.com/assets/5323259/18525488/fb9bdbb8-7abc-11e6-9463-81e147d2a40b.png)

I am very sorry to say but this is very messy.
1. Smaller distance between each letter.
2. On this size of a screen the blue banner links should still be on one line. Same goes for This year etc links right below it.
3. Black text beside Custom seems out of place.
4. Remove the button around Go. Keep the links as they are.

**Comment by thomasplevy** [comment]
@paaljoachim this screen isn't finished and is still undergoing development... also see the admin refactor note in one of my other responses, you can track our progress on the analytics at #156 

I'll keep all of this in mind as we finish the analytics overhaul

**Comment by thomasplevy** [comment]
updates coming in beta 9, thanks for all the feedback

**Comment by paaljoachim** [comment]
Your welcome Thomas!
Glad to be of help.
