### ISSUE TITLE
Password Key Invalid Issue 

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1983]
### Reproduction Steps

+ I think this is different from the WPEngine/Flywheel issue. 
+ HS-176845 (credentials in one pass)
+ Turn off all plugins but LifterLMS + LaunchPad
+ In an incognito window do a password reset

### Expected Behavior

+ Normally we see this with our resets the cookie stays even after the redirects:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/47434271/153238178-a17826fc-94ca-4582-9438-70d9b7b2cba8.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/47434271/153239095-67ba4302-0a9c-4a8d-8c17-346acb7f5f6c.png">

### Actual Behavior

+ the user's site and staging site does not keep the cookie:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/47434271/153239827-58d3b093-b62b-435c-8db0-813548073cfa.png">

and the redirect seems to wipe it out:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/47434271/153239661-b5ba26d4-c46f-4d35-8cd2-a1d7304057da.png">

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Course Catalog (#80) [[removed]/course-catalog]
Page On Front: Home page (#4) [[removed]/]
Permalink Structure: /'/%year%/%monthnum%/%day%/%postname%/'
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.8.0
Db Version: 5.8.0
Course Catalog: Course Catalog (#80) [[removed]/course-catalog]
Membership Catalog: Membership (#82) [[removed]/membership]
Student Dashboard: Account Dashboard (#86) [[removed]/account-dashboard]
Checkout Page: Checkout (#88) [[removed]/checkout]
Course Catalog Per Page: 12
Course Catalog Sorting: date,DESC
Membership Catalog Per Page: 10
Membership Catalog Sorting: title,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: weak
Terms Required: no
Terms Page: Terms and Conditions (#84) [[removed]/terms-and-conditions]
Checkout Names: required
Checkout Address: required
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: required
Registration Phone: required
Registration Voucher: hidden
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: required
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: Got questions? Hit reply. We're here for you.
Email Header Image: [removed]/wp-content/uploads/2017/02/email_header-e1486031128828.gif
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 3


Server
-------------------------------------------

Mysql Version: 5.7.23
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 516M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.33
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad
Version: 2.4.9
Themeuri: https://lifterlms.com/launchpad/
Authoruri: https://gocodebox.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 5.8.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 what's the webhost? Are there any MU or dropin plugins or server-level caching mechanisms in effect?

**Comment by nrherron92** [comment]
@thomasplevy webhost is Bluehost and they swear all server side caching is off. There was a caching plugin active on the site but it's been flushed and turned off

**Comment by thomasplevy** [comment]
Alright it looks like this has to do with trailing slashes in the URL.

I can reproduce the issue by changing my site's permalink structure from `/%postname%/` to `/%postname%`

When we generate an endpoint URL, we stick a slash on the end though, regardless of the permalink structure: 

https://github.com/gocodebox/lifterlms/blob/91177745854fca180652d70ca524efee35c51bc5/includes/functions/llms.functions.page.php#L94

As a result, the lost password url on a site without a trailing slash should be something like `whatever.com/dashboard/lost-password` but it ends up being `whatever.com/dashboard/lost-password/`

This *doesn't matter* almost at all as WordPress will strip the slash and still load the correct page... however, when we set the cookie used for the password reset we restrict the path of the cookie only to the password reset page url using data from `$_SERVER` (which will not have the slash stripped)

https://github.com/gocodebox/lifterlms/blob/91177745854fca180652d70ca524efee35c51bc5/includes/functions/llms.functions.person.php#L452

A primitive solution appears to be running the `$path` variable through `untrailingslashit()` before setting the cookie. Doing some more testing on this before committing to the solution.

**Comment by thomasplevy** [comment]
@nrherron92 a temporary workaround for this user would be to suggest switching to using a trailing slash. This shouldn't have any real effect on the functionality of the site since WordPress generally accepts URLs in either format regardless of the defined permalink structure... Although I can't promise that there will be absolutely no problems.

Or wait until a patch is issued.
