### ISSUE TITLE
Conflict with SendinBlue

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1984]
### Reproduction Steps

+ HS-185311
+ Trigger a LifterLMS email with _SendInBlue's Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue_ plugin active
+ I know the issue comes from their plugin because if it is turned off so that they are not acting as an SMTP on the site our emails send as normal, but I don't know if it is something we should fix or Sendinblue should be fixing.
+ I'm inclined to say Sendinblue should since we just use wp_mail() to queue up emails so I don't think there is anything we can change.
+ Mostly I just want to check that I'm not missing anything and be able to tell the user we did in fact talk to our engineering team to be sure there isn't an error on our side. 

### Expected Behavior

+ The email should send 
+ All of our emails send as normal with Sendinblue's plugin turned off

### Actual Behavior

+ All emails except for LifterLMS emails send
+ LifterLMS emails still queue as normal with no errors

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.8.3
Debug Mode: No
Debug Log: No
Debug Display: No
Locale: fr_FR
Multisite: No
Page For Posts: Not Set
Page On Front: ACCUEIL (#28893) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.7.0
Db Version: 5.7.0
Course Catalog: Course Catalog (#28988) [[removed]/courses/]
Membership Catalog: Membership Catalog (#28989) [[removed]/memberships/]
Student Dashboard: Dashboard (#28991) [[removed]/dashboard/]
Checkout Page: Purchase (#28990) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: CH
Currency: CHF
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 30595
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.32
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 1 Go
Php Memory Limit: 640M
Php Post Max Size: 1100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 60
Php Version: 7.4.26
Software: Apache
Wp Memory Limit: 640M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.14.7
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Advanced Dynamic Pricing for WooCommerce: 3.3.2
Advanced Order Export For WooCommerce: 3.2.2
All-in-One WP Migration: 7.53
AutomateWoo: 5.5.8
Check & Log Email: 1.0.4
Checkout Field Editor for WooCommerce: 1.5.3
Clean Login: 1.13.1
Contact Form 7: 5.5.4
Cookie Notice & Compliance for GDPR / CCPA: 2.2.1
CURCY - Multi Currency for WooCommerce: 2.1.11
Custom My Account for Woocommerce: 2.0.5
Display Price Free: 0.0.3
Facebook for WooCommerce: 2.6.9
Google Ads & Marketing by Kliken: 1.0.7
H5P: 1.15.4
Imagify: 1.10
Instant Images: 4.6.1
iThemes Security: 8.0.2
Kadence WooCommerce Email Designer: 1.4.10
LifterLMS: 5.7.0
LifterLMS Helper: 3.4.1
LifterLMS Labs: 1.6.0
LifterLMS WooCommerce: 2.2.1
LifterLMS WPForms: 1.1.1
Loco Translate: 2.5.7
Mime Types Plus: 2.03
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: 3.1.32
PDFjs Viewer - Embed PDFs: 2.1.5
Preview E-mails for WooCommerce: 2.0.1
Protect Uploads: 0.3
PublishPress Capabilities: 2.3.3
Really Simple CAPTCHA: 2.1
Site Kit by Google: 1.49.0
TablePress: 1.14
UpdraftPlus - Backup/Restore: 1.22.1
Username Changer: 3.2.2
User Switching: 1.5.8
Video Conferencing with Zoom: 3.8.16
VOD Infomaniak: 1.4.4
WooCommerce: 6.1.1
WooCommerce Menu Cart: 2.10.3
WooCommerce PayPal Checkout Gateway: 2.1.3
WooCommerce PayPal Payments: 1.6.4
WooCommerce PDF Invoices & Packing Slips: 2.12.1
WooCommerce Shipping & Tax: 1.25.20
WooCommerce SSL Seal: 2.0
WooCommerce Stripe Gateway: 6.0.0
WordPress Importer: 0.7
WordPress Users & WooCommerce Customers Import Export(BASIC): 2.1.8
WPC Grouped Product for WooCommerce: 2.9.3
WPC Product Bundles for WooCommerce: 6.0.4
WPForms Lite: 1.7.2
WP LinkedIn Auto Publish: 7.8
WP Mail Logging: 1.10.2
WP User Login Notifier: 1.0.5
Yoast Duplicate Post: 4.3
Yoast SEO: 17.9


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes
LifterLMS WPForms: Yes


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@eri-trabiccolo can you triage this for us please

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I can confirm on the production website this issue exists.
At the moment the staging website is not reachable (@nrherron92 is working on it).
I created a sendinblue (free) account and managed to reproduce the issue locally.
The problem is "simple", but it's their fault.
Basically they override `wp_mail()` they missed this piece from the original code:
https://github.com/WordPress/wordpress-develop/blob/5.9/src/wp-includes/pluggable.php#L433-L441
so that the `$to` param we pass (in the format `AAA <a@a.it>`), produces an error as the email is not valid. They expect it to be just the email address.

Now they do not provide any filter aside from `wp_mail` itself, which runs too much early... 
I confirm this conflict though.

**Comment by nrherron92** [comment]
@eri-trabiccolo is this something we can patch or do they need to talk to SendInBlue about the override?

**Comment by eri-trabiccolo** [comment]
@nrherron92 
To me it's a Sendinblue bug:
They are overriding a wp core function, `wp_mail`. The wp original function accepts as `recipients` stuff like `John Doe <john@doe.it>`, and is able to parse it. The Seninblue override, instead, doesn't account for that format, and expects the `recipients` to only be the email address `john@doe.it`.
But we're doing nothing wrong, we are correctly using a WordPress function, they're overriding it but they must ensure we can pass the same kind of data without producing any issue.

**Comment by thomasplevy** [comment]
@eri-trabiccolo can you find anyplace to report the issue to the sendinblue devs so we don't have to just tell the customer "it's their problem"

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Yesterday I already couldn't find a way to contact them aside from the wp support forum or directly at [contact@sendinblue.com](mailto:contact@sendinblue.com).
I (today) opted then for the support forum:
https://wordpress.org/support/topic/mail-not-sent-if-the-recipient-is-in-the-format-foo/
Let's see.

@nrherron92 ^

**Comment by thomasplevy** [comment]
@nrherron92 Outside of developing an integration (which I don't think would be to *fix* this issue, but maybe to clone behavior from our MC or CK integrations) I think we're safe to alert the user to the WP.org topic and close this out on our side.

Are we all in agreement?

**Comment by nrherron92** [comment]
@thomasplevy @eri-trabiccolo on it! Thanks for all the help fellas <3
