### ISSUE TITLE
Clicking Add New Course

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#199]
Create New Course modul
As one fills in the "Enter a name for your course" the background "Enter title here" also shows the new title on top of the "Enter title here" words. Just for a moment too fast for me to take a screenshot.

Why is there even a modul? What about just using the standard Add New Course seen in the background to add a name of the course.

**Comment by thomasplevy** [comment]
@paaljoachim it's the very beginning of an attempt to create a coure building tutorial that was never finished. It's a terrible reason but it is a reason, I've been considering killing it all together so thanks for the confirmation on that.
