### ISSUE TITLE
LLMS_Block_Templates::generate_template_slug_from_path() directory separator

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#2001]
### Reproduction Steps

```php
$block_templates = new LLMS_Block_Templates();
$windows_path = 'C:\WordPress\src\wp-content\plugins\lifterlms/templates/block-templates/template.html';
$template_slug = $block_templates( $windows_path );
```

### Expected Behavior

`'llms_template' === $template_slug`

### Actual Behavior

`'llms_dPress\src\wp-content\plugins\lifterlms/templates/block-templates/template' === $template_slug`

### Cause

The path is built [here](https://github.com/gocodebox/lifterlms/blob/trunk/includes/class-llms-block-templates.php#L78) with '/' between the `templates` and `block-templates` directories. However, [this line](https://github.com/gocodebox/lifterlms/blob/trunk/includes/class-llms-block-templates.php#L489) uses `DIRECTORY_SEPARATOR` instead of '/'.

### System and Environment Information

Windows 10
PHP 7.4

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
@pondermatic will replacing:
`				strpos( $path, $dirname . DIRECTORY_SEPARATOR ) + 1 + strlen( $dirname ),`
with:
`				strpos( $path, $dirname . '/' ) + 1 + strlen( $dirname ),`

fix the issue on Windows?

**Comment by pondermatic** [comment]
Yes, that will fix the issue.
