### ISSUE TITLE
[6.0] Reset to Default in Achievement Template in the Awarded Achievement Editor

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#2004]
exactly like we do with certificates, except that we'll do it in a classic metabox:
https://github.com/gocodebox/lifterlms/issues/1960

**Comment by thomasplevy** [comment]
We'll... The default template doesn't exist for achievements... What we're resetting in #1960 is the certificate's block template.

**Comment by eri-trabiccolo** [comment]
ahah <3
