### ISSUE TITLE
[6.x] certificate {sequential_id} only increments when programmatically inserting an awarded certificate

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#2021]
Currently not easily reproducible via the UI but there's a design flaw in:

https://github.com/gocodebox/lifterlms/blob/c3e2b51ad322bb6bb60ab95a642dd9ed88ec545f/includes/models/model.llms.user.certificate.php#L108-L119

If we create a new awarded certificate via the REST API and set it to have a parent, this code won't run and therefore the sequential ID won't be set properly.

Changes I'm working on for #1965 make this apparent.

I propose that this code be moved out of the model and into a controller class, probably to run here:

https://github.com/gocodebox/lifterlms/blob/c3e2b51ad322bb6bb60ab95a642dd9ed88ec545f/includes/controllers/class-llms-controller-awards.php#L143-L153

**Comment by eri-trabiccolo** [comment]
Mmm, yeah it should be moved out of the model's `after_create()` method also because the sequential_id should be set once the post is `published` not just created.

**Comment by thomasplevy** [comment]
good point
