### ISSUE TITLE
[6.0] Default Custom Certificate Size

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2029]
Create UI for a new selectable size in default certificates (LifterLMS->Engagements) that allows you to still create a custom size per certificate that way if a user wants to globally change their custom size they can do it once under their default settings.

**Comment by thomasplevy** [comment]
@gocodebox/engineering 

The idea here is to add an additional certificate image size that is customizable through a UI on the admin panel under the certificate options.

I think adding a new size (USER_DEFINED) to the list of available certificates and the width / height / unit will be pulled from this set of db options is the way to go here.

This way users can have their own custom size pre-defined and they can *still* define a specialized custom size per certificate as well.

This would be a nice addition to get in prior to the 6.0 release but not essential
