### ISSUE TITLE
[6.0] Assigned Certificates are updated to new default image

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2030]
### Reproduction Steps

+ In 5.x create a certificate and get it assigned to a user
+ Upgrade to 6.0
+ Go into LifterLMS->Reporting->Student->View previously assigned certificate

### Expected Behavior

+ The certificate will maintain the legacy settings from when it was assigned

### Actual Behavior

+ It is updated with the new default 6.0 template background (the content on the certificate remains the same)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: https://alleged-bug.myliftersite.com
Site Url: https://alleged-bug.myliftersite.com
Login Url: https://alleged-bug.myliftersite.com/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-beta.2
Db Version: 5.10.0
Course Catalog: Course Catalog (#16) [https://alleged-bug.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#17) [https://alleged-bug.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#19) [https://alleged-bug.myliftersite.com/dashboard/]
Checkout Page: Purchase (#18) [https://alleged-bug.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.15
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-Two
Version: 1.1
Themeuri: https://wordpress.org/themes/twentytwentytwo/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-beta.2
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------



```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
I think this is a bug.
Our db update routine should take care about this. Old awards, which use the default bg, should retain it.

Customers who want to have the legacy backgrounds can use this filter atm:
https://github.com/gocodebox/lifterlms/blob/88024c89140c72d31eae9d032b28cee73390f2a0/includes/traits/llms-trait-award-default-images.php#L51

But I think this should be automatic.
Also, this is, in a way, related to 
https://github.com/gocodebox/lifterlms/issues/2032

**Comment by thomasplevy** [comment]
I'd add that not only should old awards be migrated, old templates should be migrated too.

**Comment by thomasplevy** [comment]
@eri-trabiccolo or @pondermatic either of you have capacity to tackle this in the next day or three please <3

**Comment by thomasplevy** [comment]
Also of note that if people want to retain the legacy background they can grab them out of the zip file and upload them to the plugin's settings as the defaults. They *can* use the filters but for most users download + upload is a much simpler solution.

**Comment by pondermatic** [comment]
@thomasplevy wrote,
> I'd add that not only should old awards be migrated, old templates should be migrated too.

Are you saying that legacy certificates should be **automatically** migrated to the block editor? There's a manual action for that on  the awarded certificates table.

**Comment by thomasplevy** [comment]
No, I'm not.

This is about the featured image of certificates and achievements that existed prior to 6.x which did not have a specific image specified.

The database migration should update any existing award or template (achievement and certificate) to use the *old* default image (https://github.com/gocodebox/lifterlms/blob/dev-600/assets/images/optional_achievement.png and https://github.com/gocodebox/lifterlms/blob/dev-600/assets/images/optional_certificate.png) as the featured image.

Though... now that I'm thinking about this I actually think that we should *not* install the featured image into the migrated items but instead automatically configure the legacy image filter based on an option set during migration.

Based on feedback on #2032 -- that default featured images should not be stored in the db and should be pulled from the option I think that we should fix this problem by using an option set in the DB to which specifies whether or not to use the legacy image.

My thinking is that we use the existing "legacy cert option" (https://github.com/gocodebox/lifterlms/blob/cb379d36e3cad922e2da686678e35444f3d93d1f/includes/functions/updates/llms-functions-updates-600.php#L334) to determine whether or not any certificates exist and if that option is `true` we can force on the filter at https://github.com/gocodebox/lifterlms/blob/88024c89140c72d31eae9d032b28cee73390f2a0/includes/traits/llms-trait-award-default-images.php#L51

We'll need to add a legacy option for achievements as well.

Users could quickly opt-into the new image by downloading the new file and uploading it into the option *or* deleting the legacy option (via options.php)

How's that sound @gocodebox/engineering

**Comment by pondermatic** [comment]
This is the solution I'm proposing and doesn't require updating the database.
In `LLMS_Trait_Award_Default_Images::get_default_default_image_src()`,
1. call `llms_get_certificate()` to get the current post object
2. if a `LLMS_User_Certificate` object is returned, call `LLMS_User_Certificate::get_template_version()`
3. if `1` is returned, change the default value passed to the `llms_use_legacy_award_images` filter hook from `false` to `true`.
```php
		$use_legacy_award_images = false;

		$certificate = llms_get_certificate();
		if ( $certificate ) {
			$version = $certificate->get_template_version();
			if ( 1 === $version ) {
				$use_legacy_award_images = true;
			}
		}
```

**Comment by thomasplevy** [comment]
I like that solution a lot @pondermatic but it won't help us with achievements which don't have a template version...

**Comment by pondermatic** [comment]
Do users view past achievements?

**Comment by thomasplevy** [comment]
Yes, they can view them on the student dashboard (and admins can view them in reporting screens)

**Comment by thomasplevy** [comment]
Do they view them is a different question lol... but tey can

**Comment by pondermatic** [comment]
I forgot about the dashboard. I was only thinking about the admin reporting page.

**Comment by thomasplevy** [comment]
@pondermatic do you have an ETA on completion for this? I'm thinking this should be included in the first RC and I'm trying to decide if I should ship another beta or wait on this for RC.1. I want to ship *something* today.

Thank

**Comment by pondermatic** [comment]
@thomasplevy, I plan to complete this today. The update functions are coded (although not tested in any way). Now I need to write unit tests and do manual testing.
