### ISSUE TITLE
Dashboard: Coupon empty link in the order information table.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#2033]
### Reproduction Steps

+ buy a course with a coupon as a student
+ go to your dashboard/my orders
+ look at the coupon's related row

### Expected Behavior

+ I expect to see the coupon amount, the saved amount, and the coupon code with no link to anything.

### Actual Behavior

+ I do see the coupon amount, the saved amount, and the coupon code BUT the latter is a link with an empty href (for users who can edit the coupon, the href attribute will be populated with the coupon's edit link).

We just should not print any link if the current user cannot edit the coupon.

### Error Messages / Logs

n/a

### System and Environment Information

LifterLMS [6.0.0](https://github.com/gocodebox/lifterlms/tree/cdc9a8bf681f4ed1f8c074ae70747429c0deba93)

### This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
The offending line:

https://github.com/gocodebox/lifterlms/blob/8d7ea3d97b241279b0e70a18a61b29ba8f67f2cf/templates/myaccount/view-order.php#L72

This should just be changed to not be a link

I think this is probably just a copy/paste error from the coupon display on the order info area on the admin panel.

Realistically the formatting of that area could be improved. I'm thinking displaying the coupon code in a `<code>` block might be the right way to go. And maybe adding another row entirely to define that it was the coupon used or something

**Comment by eri-trabiccolo** [comment]
Yeah, there's more than one of those (read: there are two :D), see also:
https://github.com/gocodebox/lifterlms/blob/8d7ea3d97b241279b0e70a18a61b29ba8f67f2cf/templates/myaccount/view-order.php#L108
