### ISSUE TITLE
Check if user passed a quiz - helper function

### ISSUE THREAD

**Issue by UVLabs** [gocodebox/lifterlms#2038]
I'm adding more Lifter support to our theme. I'm wondering if there's a helper function to pull the past quiz attempts of a user by passing the user ID.

I can write the function but wondering if there's something already. Wasn't able to find anything that will seem to work here: https://developer.lifterlms.com/reference/

Also I tried this snippet: https://github.com/gocodebox/snippets/blob/trunk/lifterlms/llms-quiz-data.php but after completing the quiz with two user accounts it doesn't seem like any user meta is saved with that meta key. So nothing is returned

**Comment by thomasplevy** [comment]
Hey @UVLabs 

Check out this class: https://developer.lifterlms.com/reference/classes/llms_student_quizzes/

And specifically this method: https://developer.lifterlms.com/reference/classes/llms_student_quizzes/get_all/

Let me know if you need anything further direction

**Comment by thomasplevy** [comment]
Also, I've just deleted that code snippet (it was from 2016). It was invalid in the current form of LifterLMS. In version 2.x and earlier quiz data was stored as user meta, since LifterLMS 3.0 we've changed the data structure to be stored in custom tables.

**Comment by UVLabs** [comment]
Thank you @thomasplevy after some digging into the code I was able to figure it out.

In case someone else comes across this:


```
$user_id     = get_current_user_id();
$student_obj = llms_get_student( $user_id );
$student_last_quiz_attempt = $student_obj->quizzes()->get_last_attempt( $quiz_id );

if ( $student_last_quiz_attempt->is_passing() ) {
// Do thing if student passed last quiz attempt
}
```
