### ISSUE TITLE
LifterLMS PDF 2.0 composer dependency require a PHP version ">= 8.0.2"

### ISSUE THREAD

**Issue by yewzy** [gocodebox/lifterlms#2050]
### Reproduction Steps

1. Install LifterLMS PDF 2.0.0
2. Activate the plugin

### Expected Behavior

Plugin successfully installed

### Actual Behavior

The whole site is unable to be accessed due to a Fatal Error:
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.19. in C:\laragon\www\lifter-test\wp-content\plugins\lifterlms-pdfs\vendor\composer\platform_check.php on line 24`

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.19. in C:\laragon\www\lifter-test\wp-content\plugins\lifterlms-pdfs\vendor\composer\platform_check.php on line 24`

</details>


This issue has be recreated:
+ [/ ] Locally
+ [ /] On a staging site
+ [/ ] On a production website
+ [ /] With only LifterLMS and a default theme

**Comment by yewzy** [comment]
Apparently symfony/css-selector requires php 8.0.2
https://packagist.org/packages/symfony/css-selector

**Comment by thomasplevy** [comment]
@yewzy thanks for bringing this to our attention. We're shipping a hotfix as we speak. I'm assuming you are able to recover from the error in the meantime but if you need any assistance with how to recover your site from a  fatal error please open a support request at lifterlms.com/my-account/my-tickets

**Comment by yewzy** [comment]
Thanks @thomasplevy for the quick response! No worries, I've disabled the LifterLMS PDF plugin through FTP.

**Comment by thomasplevy** [comment]
@yewzy LifterLMS PDFs 2.0.1 includes dependencies suitable for use on PHP 7.4, https://make.lifterlms.com/2022/03/08/lifterlms-pdfs-version-2-0-1/

My apologies for this oversight and my appreciation for bringing this to our attention promptly <3
