### ISSUE TITLE
Database Update Won't Complete

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2060]
### Reproduction Steps

+ HS-188815
+ Rollback LifterLMS to 5.10 and then update to 6.0
+ Run the database updater

### Expected Behavior

+ The database updates and restores legacy certificates.

### Actual Behavior

+ The update doesn't complete.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: 
Site Url: 
Login Url: 
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: zh_CN
Multisite: No
Page For Posts: Course Catalog (#4) 
Page On Front: 主页 (#672) 
Permalink Structure: /post/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 5.10.0
Course Catalog: Course Catalog (#4) 
Membership Catalog: Membership Catalog (#5) 
Student Dashboard: Dashboard (#7) 
Checkout Page: 报名课程 (#6) [
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: medium
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: optional
Checkout Email Confirmation: no
Open Registration: no
Registration Names: optional
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: hidden
Account Phone: hidden
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: MY
Currency: MYR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: 
Email From Name: 
Email Footer Text
Email Header Image: 594
Cert Bg Width: 794
Cert Bg Height: 1123
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

手动付款: Enabled
手动付款 Logging: 
手动付款 Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 256 MB
Php Memory Limit: 3072M
Php Post Max Size: 256M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.4.28
Software: LiteSpeed
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Kadence for Faqing
Version: 1.0.2
Themeuri: https://tutti.my/
Authoruri: https://tutti.my/
Template: kadence
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /home/runcloud/webapps/Faqing_academy-LDfzKd5l-staging/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /home/runcloud/webapps/Faqing_academy-LDfzKd5l-staging/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 Can you request error logs for the site? And error logging to be enabled on the staging site?

I've reviewed all the logs and all the updates are queued but they're not running

You noted this happened on a production site but the ticket's initial system report is a staging url.

It's possible that WP CRON isn't functioning well on the staging site and that could be preventing the updates from running. 

If you head to Tools -> Scheduled Actions and filter by "Pending" you'll see a few actions (unrelated to LifterLMS) that are missed (pending with a schedule date in the past)


![Screenshot_2022-03-10_16-16-55](https://user-images.githubusercontent.com/1290739/157771323-756c363b-bfc1-47e8-8948-bb8bed16549e.png)


When actions like this get missed it's a good sign that WP CRON is not working as expected and that could be what's going on here... Since our background updater is processed asynchronously using cron processes.

I can't prove that exactly though (and it's hard to prove).

I would like to rule out bugs and errors though so getting error logging enabled would be helpful and seeing if the user actually ran this in production (having the same issue) and if there are any existing error logs we can review.

**Comment by nrherron92** [comment]
@thomasplevy the user clarified he hasn't actually run the update on the live site yet.

The logs for staging are enabled, and I'm not seeing any errors. I went ahead and added WP Crontrol too and there's a bunch of old stalled CRON jobs not running. 

I think he should add WP Crontrol to the production site to see if this is also the case there then reach out to his host about fixing it?

**Comment by thomasplevy** [comment]
I think that advising to run on the live site knowing there could be a potential issue is not advisable at this time.

That said if there's a bunch of stalled crons on the staging site this is almost certainly the cause of the issue. If crons aren't running then crons.

![Screenshot_2022-03-11_08-49-42](https://user-images.githubusercontent.com/1290739/157901205-483e6520-38aa-45bf-a264-ba55eba9f73e.png)

The cron that needs to run to process the update is: `wp_llms_bg_updater_cron`

You can (or you can ask) the customer to trigger that. It'll need to run a couple of times probably and will keep popping back up until the process completes and the 6.0 welcome notice displays.

**Comment by thomasplevy** [comment]
I see that the host has stated that crons are running and the user has provided a bunch of logs to prove as much but the screen there (via WP Crontrol) is showing errors. I know we can't say the host is wrong exactly but in this case it's pretty clear that the *site itself* is saying that it's not functioning. The cron process *may* be running on the server (and likely is) but WordPress doesn't use real crons. It uses the pseudo WP CRON and it's obviously not working right based on what we're seeing here.

**Comment by thomasplevy** [comment]
@nrherron92 any movement here or need for us to look at something new?

**Comment by nrherron92** [comment]
@thomasplevy no, I haven't heard back. I'll close this for now and open again if he does follow up
