### ISSUE TITLE
Custom Sales Content Limit

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2065]
### Reproduction Steps

+ HS-189132
+ Create a course and use the custom sales content option
+ With long form content the sales content cuts off at around 8k words or 45k characters which prevents long form sales content. 
+ I have some example copy on myliftersite if needed

### Expected Behavior

+ All the content in the sales content box should show up

### Actual Behavior

+ The content is getting cut off

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Website

www.hollyswritingclasses.com

Admin Credentials

Email: help@lifterlms.com
Password:

System Report

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#4) [[removed]/blog/]
Page On Front: Welcome to HollysWritingClasses.com (#4172) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: The Writing Courses (#15) [[removed]/courses/]
Membership Catalog:(#16) []
Student Dashboard: Dashboard (#18) [[removed]/dashboard/]
Checkout Page: Purchase (#17) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength:
Terms Required: yes
Terms Page: TERMS OF USE (#6672) [[removed]/terms-of-use-2/]
Checkout Names:
Checkout Address:
Checkout Phone:
Checkout Email Confirmation: no
Open Registration: no
Registration Names:
Registration Address:
Registration Phone:
Registration Voucher:
Registration Email Confirmation: no
Account Names:
Account Address:
Account Phone:
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: You've received this email in relationship to your writing classes account at HollysWritingClasses.com. If you need help, please request assistance at our help desk HERE: https://novelwritingschool.com/support/
Email Header Image: 5869
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 1,000 MB
Php Memory Limit: 1000M
Php Post Max Size: 1000M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 900
Php Version: 7.4.28
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad
Version: 2.4.9
Themeuri: https://lifterlms.com/launchpad/
Authoruri: https://gocodebox.com
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Classic Editor: 1.6.2
Classic Widgets: 0.3
Code Snippets: 2.14.3
ConvertKit: 1.9.6.9
HurryTimer: 2.6.3
Import and export users and customers: 1.19.1.9
LifterLMS: 6.0.0
LifterLMS ConvertKit: 2.1.2
LifterLMS Custom Fields: 2.0.2
LifterLMS Customizations: 1.0.0
LifterLMS Groups: 1.0.0-beta.19
LifterLMS PDFs: 2.0.1
LifterLMS Social Learning: 1.5.0
Poll: 8.0.1
Tiger Technologies Plugin: 1.0
XFtoWP: 1.5 BETA


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: Yes
LifterLMS Groups: Yes
LifterLMS PDFs: Yes
LifterLMS Social Learning: Yes


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 We'll dig deeper into this but this is likely going to be a limitation of the database table size. We could institute a word count limit and notification to let users know what the limitations are.

In the meantime I think using the custom page option (in favor of the custom content option) would be an acceptable workaround.

**Comment by pondermatic** [comment]
@nrherron92, "Sales Page Custom Content" is stored in a WordPress database field that is limited to 64K bytes. Some characters use more than one byte, so the limit can be lower. For now, using a WordPress page as the sales page is a better option for long form sales content. WordPress pages can store up 4M bytes.

@gocodebox/engineering
"Sales Page Custom Content" is stored in `wp_posts.post_excerpt`, which WordPress defines as the 'text' type. The maximum number of characters that `text` fields can hold depends on the character set that the table uses and the types of characters stored in the field. Database column sizes are based on bytes, and some characters take up to 4 bytes to store. See MySQL [String Type Storage Requirements](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings).

In the best case scenario `text` can hold 2^16 - 2 characters, or about 64K.

`wp_postmeta.meta_value` and `wp_posts.post_content` use the `longtext` type, which can hold 2^32 - 4 bytes, or about 4M. Perhaps we should move where sales page custom content is stored?

**Comment by thomasplevy** [comment]
Thanks for looking into this @pondermatic 

I don't think we should endeavor to move the storage location at this time. I'd rather call this a known limitation and institute some level of validation on the field (client-side validation is probably sufficient).

@nrherron92 I'm going to move this to the backlog as a future improvement (to add validation) and let the customer know the cause of this issue, the limitation, and our (future) solution.

In the meantime, luckily, they can very easily copy/paste their content into a WP page and use the page in favor of the sales page content.
