### ISSUE TITLE
Username shows to logged in users on checkout form

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2071]
Reported in chat HS-189573
User found workaround by using a column and display conditions on the column to hide the block

### Reproduction Steps
1. Head to wp-admin < LifterLMS < Forms < Billing Information
2. Make sure you have a username field (aka User Login field) on your checkout form
3. Create a course with an access plan on your course
4. View the purchase link and you should see the Username field even though it should only show up to logged out users

<img width="1045" alt="Screen Shot 2022-03-20 at 10 28 22 AM" src="https://user-images.githubusercontent.com/76497148/159170032-9e19fe5d-fda2-4f65-a146-c66aaf19ec7c.png">

### Expected Behavior
The username field would not show up

### Actual Behavior
The username field shows up

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#2029) [[removed]/blog/]
Page On Front: Home (#1015) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Courses (#2202) [[removed]/courses/]
Membership Catalog: Membership Catalog (#2129) [[removed]/memberships/]
Student Dashboard: Dashboard (#2131) [[removed]/dashboard/]
Checkout Page: Purchase (#2130) [[removed]/purchase/]
Course Catalog Per Page: 30
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36


Theme
-------------------------------------------

Name: Kadence
Version: 1.1.14
Themeuri: https://www.kadencewp.com/kadence-theme/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ x] On a staging site
+ [ x] On a production website
+ [ x] With only LifterLMS and a default theme

**Comment by pondermatic** [comment]
The `llms_visibility` block attribute is not getting added to the form. If added manually to the form's post content in the database, the form is rendered correctly.

**Comment by pondermatic** [comment]
Developer Notes:
In the client-side block editor, when a block attribute value equals the default value, the attribute is **not** added to the post content. Since the user login block has only one allowable `llms_visibility` setting, `logged_out`, it is always the default and therefore never saved with the attribute.

Options:
1. ~Save the attribute even when it's the default.~ The WordPress serializer's [`getCommentAttributes()`](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/serializer.js#L233-L239) function prevents storing the attribute if its value is the default. There are no block filter hooks to easily change this.
2. ~Teach ? to use the default `llms_visibility` value from ? (not `schemas/llms-reusable-blocks.php`).~
    Add this code in one of these methods (in order of execution).
    ```php
	// Set the `user_login` field block's visibility to its default 'logged_out' if not set.
	// The WordPress serializer `getCommentAttributes()` function removes the attribute before being serialized
	// into `post_content` because the block's default is `logged_out` AND the only allowed value is `logged_out`.
	if ( 'llms/form-field-user-login' === $block['blockName'] && empty( $block['attrs']['llms_visibility'] ) ) {
		$block['attrs']['llms_visibility'] = 'logged_out';
	}
    ```
    1. [`LLMS_Forms::render_field_block()`](https://github.com/gocodebox/lifterlms/blob/6.2.0/includes/forms/class-llms-forms.php#L1163), this is the first bit of LifterLMS code to see the block.
    1. [`LLMS_Forms::block_to_field_settings()`](https://github.com/gocodebox/lifterlms/blob/6.2.0/includes/forms/class-llms-forms.php#L116)
    1. [`LLMS_Forms::is_block_visible_in_list()`](https://github.com/gocodebox/lifterlms/blob/6.2.0/includes/forms/class-llms-forms.php#L865)
    1. [`LLMS_Forms::is_block_visible()`](https://github.com/gocodebox/lifterlms/blob/6.2.0/includes/forms/class-llms-forms.php#L826)
    1. [`LLMS_Blocks_Visibility::maybe_filter_block()`](https://github.com/gocodebox/lifterlms-blocks/blob/2.4.1/includes/class-llms-blocks-visibility.php#L122)
3. Alter the `post_content` value when the post is saved. Ugh.

**Comment by thomasplevy** [comment]
It *might* be possible to do number one but the block APIs responsible for storing block attributes intentionally don't save default values. If 1 is the preffered solution someone's going to have to figure out how to do it because I don't know how.

**Comment by pondermatic** [comment]
@gocodebox/engineering , I'm leaning toward option 2.v since it is in the llms-blocks project. Does anybody have a preference?

**Comment by eri-trabiccolo** [comment]
@pondermatic I'm ok with 2.
