### ISSUE TITLE
Certificate Sequenced Id Error

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2076]
### Reproduction Steps

+ HS-188990
+ Create a template and set the sequenced id to, for example, 9
+ Award a user that certificate 
+ Go back in the certificate and update the id to a different number like 182, save and sync

### Expected Behavior

+ The certificates should readjust the numbers via the sync

### Actual Behavior

+ The number does not change on assigned certificates and template throws this error:

Updating failed. Invalid parameter(s): certificate_sequential_id

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: Yes
Debug Log: Yes
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#1758) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Course Catalog (#26) [[removed]/courses/]
Membership Catalog: Membership Catalog (#27) [[removed]/memberships/]
Student Dashboard: Dashboard (#29) [[removed]/dashboard/]
Checkout Page: Checkout (#8) [[removed]/checkout/]
Course Catalog Per Page: 16
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: KE
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: RizikiLearn, Upskill & Grow!
Email Header Image: 3393
Cert Bg Width: 922
Cert Bg Height: 713
Cert Legacy Compat: yes


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 64 MB
Php Memory Limit: 768M
Php Post Max Size: 64M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 180
Php Version: 7.4.28
Software: LiteSpeed
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-One
Version: 1.4
Themeuri: https://wordpress.org/themes/twentytwentyone/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@pondermatic I see you're looking into this but I wanted to note that once issued, the sequential ID of an awarded certificate *SHOULD NOT CHANGE*. If you adjust the "next sequential id" of the template it is NOT supposed to resequence all the certificates awarded from that certificate.

Additionally, the validation in place is meant so that users cannot accidentally reduce the next sequential ID to an ID lower than it's current ID. This is to prevent collisions. An ID must be unique, by nature of it being an ID. So if you choose to jump the sequence that's fine but you can't go back and issue ID 9 if it's already been issued (or skipped)

**Comment by nrherron92** [comment]
@pondermatic @thomasplevy would this mean as well say a user has the certificate set to 009 and they wanted to change it to just 9 they couldn't do this for the same reasons (and/or) would have to manually just change it on the assigned certificates?

**Comment by thomasplevy** [comment]
@nrherron92 009 and 9 are the same thing. When the sequential ID is output on the awarded certificate it's formatted to be (I think) 6 digits long. So it'll pad 9 to `000009` and 9000 will be come `009000` and 900000 would be the same thing.

When the certificate is awarded, the sequential ID merge code is merged and replaced with the (formatted) next sequential ID and the value is stored to the awarded certificate so that in the future if it's merged again the ID won't change. The template's "next sequential id" is incremented.

The fact that the sequential ID won't change is part of how an ID should work. For example, you can NEVER change the WordPress post ID of any post. Or a WordPRess user IDs. IDs should not change. So we did not construct a way to *change* the sequential ID of an awarded certificate for this reason.

**Comment by thomasplevy** [comment]
Also of note, if padding the sequential ID with zeros is not desired we have filters in place for you:

https://developer.lifterlms.com/reference/hooks/llms_certificate_sequential_id_format/

Then `length` property could be reduced to `1` (from `6`) to essentially disable the formatting

**Comment by pondermatic** [comment]
I agree that the certificate ID on awarded certs should never change. It is an identifier that is unique to that award.

There may be a bug  that allows the sequence ID to be set too low in the certificate template editor. I'm looking into that and will create a new issue if it is what I think it is.

**Comment by pondermatic** [comment]
What I have found may not be a bug, more of an enhancement, so I'll ask here in this issue.
1. Edit a certificate template.
2. Increment the "Next Sequential ID".
3. Click the "Update" button.
4. Decrement the "Next Sequential ID".

The number should not be allowed to go lower than the first updated value. When updated with this "too low" value, an admin notice is displayed: "Updating failed. Invalid parameter(s): certificate_sequential_id".

@thomasplevy, when the form is successfully posted to the REST API, the response includes the new `certificate_sequential_id` value. Does or can the client-side response handler change the `<input id="llms-certificate-title-control">`'s `min` attribute? Also, that ID attribute doesn't sound correct.

**Comment by pondermatic** [comment]
This appears to be the problem with that input's ID:
https://github.com/gocodebox/lifterlms/blob/trunk/src/js/admin-certificate-editor/plugin/sequential-id-control.js#L28

**Comment by thomasplevy** [comment]
@pondermatic this var should be managed by `useState()` to avoid the bug you're asking about:

https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/src/js/admin-certificate-editor/plugin/sequential-id-control.js#L19-L24

**Comment by pondermatic** [comment]
OK. I'll open a new issue and close this one.

**Comment by thomasplevy** [comment]
@pondermatic Let's let @nrherron92 determine if this should be closed or not please

**Comment by nrherron92** [comment]
@pondermatic @thomasplevy followed up with user on the filter. I'll close this out if he doesn't have anything else on this issue!

**Comment by nrherron92** [comment]
I think we're good to close this! I'll follow up if the user gets back to us further relating to this issue!
