### ISSUE TITLE
Buddypress member profile tab /courses/

### ISSUE THREAD

**Issue by oksodavid** [gocodebox/lifterlms#208]
on Buddypress members profile tab:
Courses In-Progress
You are not enrolled in any courses.

on same member login LifterLMS /my-courses/:
Courses In-Progress
Status: enrolled Course Started - Sep 20, 2016 Test Oak Course &
Status: Enrolled Course Started - Sep 05, 2016 2020 Coordinate Geometry

Note: Is this the member profile the only place where LifterLMS Buddypress integration should be visible? Could there also be LifterLMS activity updates in the group activity feed for 'Courses Achievements Certificates'?

**Comment by thomasplevy** [comment]
@oksodavid I will look into the reported issue ASAP

As far as additional features we have a few requested and will be doing a post 3.0 launch upgrade to the integration

see #164 
https://trello.com/c/uiWhDKOh/75-new-engagement-event-add-to-buddypress-group
https://trello.com/c/pkVYlKmF/98-buddypress-restrict-activity-members-and-group-pages-to-lifterlms-memberships

**Comment by thomasplevy** [comment]
resolved in beta.9

we will be addressing new buddypress features post 3.0 release
