### ISSUE TITLE
PHP Fatal error on Confirm Payment page with non-existing order

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#2093]
### Reproduction Steps

1. Go to your WordPress site, but change the URL path to `/purchase/confirm-payment/?order=order-DOES-NOT-EXIST`.

### Expected Behavior

+ A page should load with a message about the order not being found.

### Actual Behavior

+ A PHP Fatal error occurs.

### Error Messages / Logs

+ PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\wordpress-develop\src\wp-content\plugins\lifterlms\includes\shortcodes\class.llms.shortcode.checkout.php:257

### System and Environment Information

LifterLMS 6.2.0
LifterLMS PayPal Gateway 1.3.0
WordPress 5.9.1-src
Windows 10

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment]
@nrherron92 woops I didn't realize I had this assigned to you... Sorry!
