### ISSUE TITLE
Aosta missing from Italy Province List

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2098]
### Reproduction Steps

+ HS-190584
+ Set checkout to Italy
+ Check the province dropdown for Aosta

### Expected Behavior

+ It isn't technically a province according to some guy named Rocco but AO is used as a mailing code. 
+ The argument for adding this I think comes with WooCommerce using this in their dropdown as well, so it seems to be the standard?

### Actual Behavior

+ It's not a province so we didn't add it, but maybe we should. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by pondermatic** [comment]
Related to #1686 and [private issue 45](https://github.com/gocodebox/private-issues/issues/45).

**Comment by eri-trabiccolo** [comment]
The tricky thing with Aosta is that it's not in a province.
Basically Italy is divided in regions, and usually regions are divided in provinces, but there are some regions, like Val d'Aosta, that have a special statute.
In this very case, the Val d'Aosta region, has no provinces.
Although for all the cities/towns within this region we use to specify AO in the province field.
