### ISSUE TITLE
Comments are not enabled by default when creating a lesson with the Course builder

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#2099]
### Reproduction Steps

According to this: https://lifterlms.com/docs/discussion-and-commenting-in-courses-and-lessons/#global-settings if enabled, Lessons and courses should have comments enabled by default.

However, when creating a lesson with the course builder, it doesn't follow the setting in the URL above but if you create a lesson by going to Courses >> Lessons >> Add new then the comments are enabled by default.

Here is a video: https://www.loom.com/share/f3de8e4d362f41fda57fa021b81bc0f7

### Expected Behavior

Comments should be enabled by default irrespective of how the lesson was created.

### Actual Behavior

Comments are only enabled by default if you do not use the Course builder.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
N/A

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

HS-190654

**Comment by pondermatic** [comment]
[`LLMS_Lesson::get_creation_args()`](https://github.com/gocodebox/lifterlms/blob/6.2.0/includes/models/model.llms.lesson.php#L241) needs to use [`get_default_comment_status()`](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/comment.php#L277).

`LLMS_Post_Model::get_creation_args()` should probably updated as well.

**Comment by eri-trabiccolo** [comment]
@pondermatic good catch!
Although I don't think we should update `LLMS_Post_Model::get_creation_args()` as well. Basically we want the comments (and not pings, right?) settings follow the defaults only for the lessons.
