### ISSUE TITLE
6.3 BuddyBoss Conflict

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2110]
### Reproduction Steps

+ HS-190940
+ HS-191089
+ Enable LifterLMS 6.3
+ Enable BuddyBoss and their Platform
+ Go into LifterLMS->Settings->Integration and make sure BuddyPress is enabled with some menu options added
+ Go into Appearance->Menus and add the BuddyBoss profile to the menu:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/47434271/163047424-9610a8e2-46fe-4c67-a8b9-01406ff04417.png">
+ Then try to go to the BuddyBoss profile link either through the menu item or clicking on the user icon

### Expected Behavior

+ You get directed to the user profile

### Actual Behavior

+ There is a fatal error connected to LearnDash
+ You can get around this by removing the BuddyBoss menu profile link or by turning off the LifterLMS integration and/or removing all the menu options in the integration settings

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught Error: Class 'LearnDash_Custom_Label' not found in /home/karmagpi/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php:2949 Stack trace: #0 /home/karmagpi/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php(3090): bp_nav_menu_get_loggedin_pages() #1 /home/karmagpi/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-filters.php(774): bp_nav_menu_get_item_url('profile') #2 /home/karmagpi/public_html/wp-includes/class-wp-hook.php(307): bp_setup_nav_menu_item(Object(WP_Post)) #3 /home/karmagpi/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(Object(WP_Post), Array) #4 /home/karmagpi/public_html/wp-includes/nav-menu.php(1001): apply_filters('wp_setup_nav_me...', Object(WP_Post)) #5 [internal function]: wp_setup_nav_menu_item(Object(WP_Post)) #6 /home/karmagpi/public_html/wp-includes/nav-menu.php(764): array_map('wp_setup_nav_me...', Array) #7 /home/karmagpi/public_html/wp-includes/nav-menu-template.php(151): wp_get_nav_men in /home/karmagpi/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php on line 2949

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#1398) [https://natalie-test-site.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.3.0
Db Version: 6.3.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: IT
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.17
Software: Apache/2.4.53 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36


Theme
-------------------------------------------

Name: BuddyBoss Theme
Version: 1.8.9.1
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

BuddyBoss Platform: 1.9.3
BuddyBoss Platform Pro: 1.2.1
LifterLMS: 6.3.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.5.0)
achievements/loop.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/loop.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 4.11.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
loop/author.php (ver: 3.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 5.3.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)



```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
@nrherron92 can you let me know why this is something we should be investigating and fixing when the error message clearly comes from BuddyPress and states something about LD compatibility?

**Comment by nrherron92** [comment]
@thomasplevy It's a new issue that happens with LifterLMS 6.3 and seems to be tied to the update we made with LifterLMS tabs connecting to the BuddyBoss profile navigation.

When the BuddyPress integration is enabled with the tabs you want to link selected, this error is thrown. 

If you remove all tab options from the integration settings but leave it turned on then the fatal error goes away. 

However, I do think that this is BuddyBoss having some LearnDash specific coding related to their profile page that is causing the error when we try to hook into the profile page's navigation.  

I am reaching out to BuddyBoss too, but I still wanted to see if there was something on our end with the update we released that we could look into. 

That said, I'm totally cool with closing this and opening it back if I hear back something from BuddyBoss about something they think that we can/should do.

**Comment by thomasplevy** [comment]
@nrherron92 if this seems to be related to our recent update then we'll have a closer look, of course. Reading through your report it isn't clear that this seems connected to recent changes.

**Comment by eri-trabiccolo** [comment]
@thomasplevy
Under the conditions Natalie described, a BuddyBoss function (`bp_nav_menu_get_loggedin_pages()` customization of a BuddyPress function) that loops through all the menu items and does something based on the nav item slug.
E.g.
```php
				if ( 'my-courses' === $s_nav['slug'] ) {
					$sub_name = sprintf( __( 'My  %s', 'buddyboss' ), LearnDash_Custom_Label::get_label( 'courses' ) );
				}
```
Now it happens that, when the subnav slug for our Course tab is, by default, 'my-courses', and BuddyBoss in that case takes for granted that this means LearnDash plugin is active and that `my-courses` is a LearnDash endpoint.
[
@nrherron92 another workaround to avoid this is to change the View Courses endpoint slug in LifterLMS > Settings > Account to something different than `my-courses`
]

This didn't happen with LifterLMS 6.2- because the endpoint slugs were hardcoded and were: 'courses', 'memberships', 'achievements', 'certificates'.

This is basically not our direct fault, I think BuddyBoss guys should fix it, although maybe we want to 'prefix' our slugs to avoid conflicts?
Like prepending always `llms-` to any endpoint of the BuddyPress profile?
So that we'll have URLs like `https://example.org/members/admin/courses/llms-my-courses`, `https://example.org/members/admin/courses/llms-my-grades`... and so on.

It'll require some work but nothing impossible...
Let me know.

**Comment by nrherron92** [comment]
thanks for looking into this guys! I'll send this information over to BuddyBoss and see if they can get a fix for their expectation of LearnDash in the code! <3

**Comment by eri-trabiccolo** [comment]
@nrherron92 
any news on this?

**Comment by nrherron92** [comment]
@eri-trabiccolo it was sent to their dev team according to the support rep I spoke with

**Comment by eri-trabiccolo** [comment]
@nrherron92 thanks Natie, so I assign this to you.
I think we don't have to do anything on the dev side, for the moment at least.

**Comment by Snoepys** [comment]
Hi! I have reached without any lucky to Buddyboss forum as @thomasplevy ask me for in Slack 14 days ago. Is there any update with this issue? Have Buddyboss answer you, @nrherron92 ? Still can't be able to reorder courses tab. :(

**Comment by thomasplevy** [comment]
@Snoepys thanks for your patience on this.

As of this morning we don't have a firm timeline from BuddyBoss on when we can expect a resolution to this (or a few other minor BuddyBoss conflicts).

The issues we have encountered (like this one) have been relaid to their development team but we don't know when to expect a fix.

**Comment by Snoepys** [comment]
Hi! I have seen that today BuddyBoss have launch a new update: https://www.buddyboss.com/resources/buddyboss-platform-releases/2-0-3/
LifterLMS - Handled critical issue in the profile screen
I can't update yet but want to know if that update have fixed this issue.
Thanks!

**Comment by thomasplevy** [comment]
@Snoepys I'm not sure, we'll check into it and update this issue when we know more

**Comment by thomasplevy** [comment]
@nrherron92 I know we chatted about this earlier this week but if you get some time to check out the latest BB update and let us know if we have more nudging to do or what. Thanks <3

**Comment by nrherron92** [comment]
@thomasplevy yes! It looks like the critical error is fixed on their end, no more fatal error! Though, they still have not addressed the certificates issues. Good to close now I think?

**Comment by thomasplevy** [comment]
Thanks. Yes let's close it (we're tracking the certificate issue separately at #1940)
