### ISSUE TITLE
Since version 6.2.0 rolled out we can't use the theme builder of Elementor to design the course & membership archives.

### ISSUE THREAD

**Issue by SaeedMasri** [gocodebox/lifterlms#2111]
After the 6.2.0 version, the archive template doesn't apply to the course catalog page, and it goes like this:

![image](https://user-images.githubusercontent.com/44070679/163065033-37c4d81d-4b18-4ff7-abcd-6d86b09e66b3.png)

The issue also appear in the FaceBook community too, Will from your team face it here at 7:00 of the live video:

https://www.facebook.com/groups/lifterlmsvip/posts/5018034661598540/?__cft__[0]=AZUOD4KKXyhcttWRZYGNuIWrQcwckUtnvbBPNr9RKXoOSrM9_PbOhPqXqod9i1W2f_BMp-U4H9W35nlP54X0BlWTI6Bgf5uyJbm0RqpDfNdUMjVbe5f9r-_hCOy6BbHVBBcwW5RpXVNPvMMsLl5gEW5RWE8y8mCA-toxGoiVQ4GB8qgryu_jjF77UlW0JzBmaEA&__tn__=%2CO%2CP-R

Maybe this is what caused the issue: (From LifterLMS changelog)
"Added new filter llms_template_loader_priority to control the priority of the template_include hook callback used to load restricted content templates."

**Version 6.1.0 works just perfect with the theme builder, the issue started from 6.2.0 and above!**

### Reproduction Steps

+ Create a course archive in Elementor theme builder.
+ Assign it as a course archive from the conditions.
+ It doesn't apply the template to the course archive and the course archive got messed up. (See the loom video):
https://www.loom.com/share/4beb58adda0847508cbe7982ffe3e3f8

### Expected Behavior

+ The custom course archive template which was designed in Elementor theme builder, doesn't reflect on the course catalog page,

### Actual Behavior

+ The course archive got messed up after we assign the designed template in the theme builder condition.

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: http://localhost/demo
Site Url: http://localhost/demo
Login Url: http://localhost/demo/wp-login.php
Version: 5.9.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.3.0
Db Version: 6.3.0
Course Catalog: Course Catalog (#14) [http://localhost/demo/courses/]
Membership Catalog: Membership Catalog (#15) [http://localhost/demo/memberships/]
Student Dashboard: Dashboard (#17) [http://localhost/demo/dashboard/]
Checkout Page: Purchase (#16) [http://localhost/demo/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: demo@lifterlms.com
Email From Name: demo
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 40 MB
Php Memory Limit: 512M
Php Post Max Size: 40M
Php Soap: No
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.4.19
Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.7.9
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

Ele Custom Skin: 3.1.5
Elementor: 3.6.3
Elementor Pro: 3.6.5
JetSmartFilters: 2.3.11
LifterLMS: 6.3.0
LifterLMS Advanced Quizzes: 2.0.1
LifterLMS Advanced Videos: 1.0.0-beta.18
LifterLMS Assignments: 1.3.0
LifterLMS Helper: 3.4.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] With only LifterLMS and a default theme and Elementor & Elemetor pro.

### Browser, Device, and Operating System Information

+ Chrome Version 100.0.4896.75 (Official Build)
+ Windows 10  (64-bit)

**Comment by thomasplevy** [comment]
@SaeedMasri could you please edit your issue to provide us with the information requested in the issue template as found here: https://github.com/gocodebox/lifterlms/issues/new?assignees=&labels=&template=Bug_Report.md

Providing this information accelerates our ability to replicate issue. This is especially important when dealing with plugin and theme conflicts like the one you're raising.

After providing this information we'll take a closer look and let you know what we find.

**Comment by SaeedMasri** [comment]
Done, thanks.

**Comment by eri-trabiccolo** [comment]
@SaeedMasri 
thanks for reporting this.
Yes you're right, the issue is related to the recent changes in 6.2.0.
We decreased the priority (higher number) of our filter callback on `template_include` that takes care of loading the right template to fix an issue with the Divi theme builder.

You say:
> Maybe this is what caused the issue: (From LifterLMS changelog)
> "Added new filter llms_template_loader_priority to control the priority of the template_include hook callback used to load restricted content templates."

Actually we introduced that filter specifically to control the priority (that was changed from 10 to 100) of the callback, so that whoever had problems with the new priority could change it.
In order to revert the change introduced in 6.2.0 you can leverage that filter by adding the following to your child-theme functions.php or something.
```php
<?php // do not copy this line.
add_filter(
	'llms_template_loader_priority',
	function () {
		return 10;
	}
);
```

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I think we need to split our callback, and call the piece that regards to the single restrictions at priority 100 (or higher) because of https://github.com/gocodebox/lifterlms/issues/2063
and the other templates load at priority 10, so to allow theme builders overrides, but keeping the ability to restrict.
What do you think?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm not following exactly what you mean... Mostly I want things to work and I'm not interested in adding special compatibility with custom priorities for each builder, especially since they're liable to change their code leaving us looking like we broke something again

**Comment by SaeedMasri** [comment]
> 

@eri-trabiccolo Thanks, Rocco,
unfortunately, that snippet didn't fix the issue 😅

**Comment by eri-trabiccolo** [comment]
@SaeedMasri mmm weird.
May I ask you where did you place it?

**Comment by SaeedMasri** [comment]
@eri-trabiccolo In the functions.php file of my child theme,
Does this restriction/apply filter has a relation to what I'm doing and not reflecting on the course catalog?
https://github.com/gocodebox/lifterlms/blob/dev/includes/class.llms.template.loader.php#L55

**Comment by eri-trabiccolo** [comment]
Ohhh @SaeedMasri my bad. I told you you could add that snippet to your child-theme's functions.php but actually id wouldn't work since the filter hook is fired _before_ the child theme's functions.php is executed. What you need is to put it in a plugin or in a must use plugin. You can actually use our _customizations_ plugin and place the snippet there: https://lifterlms.com/docs/how-do-i-add-custom-code-to-lifterlms-or-lifterlms-launchpad/

> Does this restriction/apply filter has a relation to what I'm doing and not reflecting on the course catalog?

Well not exactly. 
Think it this way: if you use that snippet basically you make our templates loading acting as prior to LifterLMS 6.2.0.
Prior to 6.2.0, this line:
https://github.com/gocodebox/lifterlms/blob/ec76e2c9c5d14d16164a001766cbe9d9d41d0b9f/includes/class.llms.template.loader.php#L51
was just
`add_filter( 'template_include', array( $this, 'template_loader' ), 10 );`

and your catalogs worked fine, right?
Using that filter you reproduce that.

**Comment by SaeedMasri** [comment]
Yes, the snippet worked inside the customizations plugin, thanks @eri-trabiccolo you really rock/Rocco #AptlyNamed :)
