### ISSUE TITLE
LifterLMS conflict with Elementor

### ISSUE THREAD

**Issue by paaljoachim** [gocodebox/lifterlms#212]
Hey

Elementor is a very interesting Page Builder. I noticed an issue created in regards to it having a conflict with LifterLMS:

https://github.com/pojome/elementor/issues/612

**Comment by thomasplevy** [comment]
@paaljoachim based oh the issue in elementor's github it looks like they have resolved via changing the priority of their actions so I'm going to close this one out

thanks for the heads up though

**Comment by paaljoachim** [comment]
Your welcome..:)
