### ISSUE TITLE
Update documentation related to instructor's assistants

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#2138]
The documentation is wrong then:
https://lifterlms.com/docs/roles-and-capabilities/#instructors-assistant
> Instructor’s Assistants are similar to Instructors but they can only edit courses that are authored by the instructors they’ve been assigned to. 

_Originally posted by @eri-trabiccolo in https://github.com/gocodebox/lifterlms/issues/2122#issuecomment-1109934499_

The necessary change is that instructor's assistants *can be managed* by their instructor and they can only edit courses their instructor has assigned them to.

We've discussed changing the functionality to allow an assistant blanket access to any course an instructor has access to but if we were to do so this would mean that an instructor *could not* create multiple assistants with different permissions per course. The intention is that an instructor would create an assistant and assign them to the course(s) they wish them to assist with.

**Comment by magicemilymiddleton** [comment]
No problem - made that update
