### ISSUE TITLE
Course name error (beta 3.0) when processing with stripe

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#214]
## internal notes

- [ ] add `llms_trim_string()` around parameters sent to statement descriptor

## Brief summary of issue
An error is occurring when processing an order through stripe.

> The statement descriptor must be at most 22 characters. Her portable biz - Course is 25 characters long.

It's possible this is related to stripe testing

## Reproduction Steps
-Process order with stripe checkout
-Click 'buy now'

## Expected Behavior
Order processed, move on to course page (or thank you page)

## What I'm experiencing
Error message saying the course name is too many characters (see screenshot)
![image](https://cloud.githubusercontent.com/assets/4434724/18822449/dfe0ab14-8364-11e6-8b18-69ee15af9a5c.png)

The actual course name is "Automate Your Biz" (see screenshot)
![image](https://cloud.githubusercontent.com/assets/4434724/18822472/14153300-8365-11e6-8eb0-4945163421f7.png)

The website name is "Her Portable Biz" - is it possible that the checkout is pulling the site name and appending "course" at the end?

## Other notes
- It's possible this is related to stripe testing
- I was able to proceed to checkout when the course price plan was free ($0.00)
- possibly unrelated, but when I changed the price to on sale for $0.00 (as opposed to setting the course as a free course), the order doesn't process (see short gif)

https://goo.gl/pUAMdQ

- Student status is set to enrolled
![image](https://cloud.githubusercontent.com/assets/4434724/18823048/e10859c8-836a-11e6-939b-11de498afea8.png)

## Screenshots or video

Extra screenshot - with name of course listed on the checkout page
![image](https://cloud.githubusercontent.com/assets/4434724/18822654/10f2f17e-8367-11e6-8c30-44068bd16696.png)

## WordPress Environment

**LifterLMS Version:** 3.0.0-beta.9
**Wordpress Version:** 4.6.1

## Server Details

**Server Info:** Apache
**PHP Version:** 5.6.24
**PHP Max Post Size:** 64 MB
**Max Upload Size:** 64 MB
**PHP Time Limit:** 30
**PHP Max Input Vars:** 1000
**MySQL Version:** 5.5.48

## Browser, Device, and Operating System
**Browser:** Chrome 53
**Operating system:** Windows NT 10.0
**Javascript enabled** Yes
**Cookies enabled** Yes
**Flash version** 23.0.0
**Java version** Not installed

**Comment by thomasplevy** [comment]
thanks @Loralee know the issue and will get it resolved asap via some string cleanup on our side before sending data to stripe

in the meantime you can change the site title (under WP General settings) to be something so it passes stripes validation

**Comment by Loralee** [comment]
thanks @thomasplevy. Is there a place I can scan for known issues, so I don't waste time writing up bug reports?

**Comment by thomasplevy** [comment]
@Loralee i have a lot in my head but mostly everything is right here: https://github.com/gocodebox/lifterlms/issues

**Comment by thomasplevy** [comment]
resolved in stripe 4.0.0-rc1
