### ISSUE TITLE
Create documentation related to plain permalinks and WP Engine cache exclusions

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#2152]
@willmiddleton-lifterlms, a rough draft of a KB post about this issue is [here](https://lifterlms.com/?post_type=pp-doc&p=210802&preview=true). Please give it your magic touch.

_Originally posted by @pondermatic in https://github.com/gocodebox/lifterlms/pull/2128#discussion_r873912598_

**Comment by magicemilymiddleton** [comment]
Published: https://lifterlms.com/docs/wp-engine-cache-plain-permalinks-and-password-reset-form/
