### ISSUE TITLE
Woocommerce product options connection with course (beta 3.0.9)

### ISSUE THREAD

**Issue by Loralee** [gocodebox/lifterlms#216]
## Brief summary of issue
When adding a a woocommerce product to a lifterlms course (with matching sku) the product appears to be connected for a moment, and then disappears.

## Reproduction Steps
- open course that's not already connected to a woocommerce shop item
- choose the woocommerce shop item from the drop down menu
![image](https://cloud.githubusercontent.com/assets/4434724/18859212/e5ba131e-8426-11e6-8fb0-d9af5fe37e66.png)
- update the course
- view "product options" again - to see if the product has been added

## Expected Behavior
The product to be in the "Product options" tab, as an added item

##What I'm experiencing
When the update is complete, the item appears for a moment, and then the field empties again.
![lifterlms_woocommerce_add_product](https://cloud.githubusercontent.com/assets/4434724/18859175/8b4962cc-8426-11e6-9bcb-9e3ae44e7aa3.gif)

## Other notes 
There's a possibility it's related to my installation of divi & the select2 issue we've been dealing with. I can double check with another theme.

##Screenshots or video

## System Info
LifterLMS Version: 3.0.0-beta.9
Wordpress Version: 4.6.1

## Server Details
**Server Info:** Apache
**PHP Version:** 5.6.24
**PHP Max Post Size:** 64 MB
**Max Upload Size:** 64 MB
**PHP Time Limit:** 30
**PHP Max Input Vars:** 1000
**MySQL Version:** 5.5.51

## Browser, Device, and Operating System
**Browser:** Chrome 52
**Operating system:** Windows NT 10.0
**Javascript enabled** Yes
**Cookies enabled** Yes
**Flash version** 22.0.0
**Java version** Not installed
**Websockets supported** Yes
**Browser size** 1263 x 595
**Screen size** 1280 x 720 (Retina)
**Color depth** 24 bit

**Comment by thomasplevy** [comment]
@Loralee can you open your console and send screenshots of the console contents on page load please

**Comment by Loralee** [comment]
sorry for the delay @thomasplevy 
Here's the screencast:
https://goo.gl/SxhGkW

**Comment by thomasplevy** [comment]
resolved in wc rc

@Loralee it was a typo and thanks for the creds. I patched your test site via the very dangerous plugin editor functionality after resolving it so you can carry on without a new install
