### ISSUE TITLE
Implement new gateway feature: `modify_recurring_payments`

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#2173]
See related: https://github.com/gocodebox/lifterlms-gateway-paypal/issues/52

## Goal

Allow payment gateways to determine if recurring payment details (such as trial end date, next payment date, etc...) can be modified via the admin panel order UI.

The new gateway feature can be added to the [supports](https://github.com/gocodebox/lifterlms/blob/81b1fff19d7b8a97e6a5d2780f800212050c6e1f/includes/abstracts/abstract.llms.payment.gateway.php#L101-L109) interface for a new gateway feature, probably called "modify_recurring_payments".

I think that this feature should be enabled by default *when* `recurring_payments` is `true`. We don't currently have a concept of a conditional feature so we'll probably need to reengineer the existing supports/feature functionality to accommodate a conditional feature default.

Ideally this should be implemented in a way that *does not* mess with existing gateways (which can edit by default)

**Comment by eri-trabiccolo** [comment]
> I think that this feature should be enabled by default when recurring_payments is true. We don't currently have a concept of a conditional feature so we'll probably need to reengineer the existing supports/feature functionality to accommodate a conditional feature default.

Well in the constructor, we can check whether `modify_recurring_payments` feature is set, if so use its value, otherwise force `modify_recurring_payments` to be `true` when `recurring_payments` is `true` as well. And this would ensure also the following:

> Ideally this should be implemented in a way that does not mess with existing gateways (which can edit by default)

**Comment by thomasplevy** [comment]
@eri-trabiccolo yes but since the abstract payment gateway *does not* currently have a constructor the existing payment gateways generally don't call `parent::__construct()` in their constructor's. They *should* probably do that anyway but they don't. So doing this in the constructor is the logical way to do it but it might mean we need to edit other gateways (we can do our internal ones quite easily) but any external gateways might break...
