### ISSUE TITLE
[7.x] Add new data retention settings for orders and user accounts

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#2191]
Introduces a collection of admin settings designed to automatically delete abandoned orders from the database after a specified time period (days/weeks/months/years)

+ Inactive accounts - an account which has no enrollments
+ Pending orders - orders with then "llms-pending" status

When running the cron *pending orders* should be deleted first and then the inactive account check should be run.

The user settings should be a number input accepting any whole number greater than 0 and a select drop down to select the time period (days/weeks/months/years)

A cron should run for each setting to query orders/users that match the setting criteria and delete them accordingly.

The settings can be left blank (no number value) to disable the cron (the data is retained)

The default value of both settings should be blank

With 7.0 and gateways that subscribe to the new AJAX checkout flow (currently on PayPal CP) a pending order will *not* have an associated user account but with other gateways the user account will likely exist and be considered an "inactive" account. Deleting an order should *never* delete the user, instead the user should be deleted independently by the inactive account setting.

---

I think this should be added shortly after 7.0 release if not with the 7.0 release.

**Comment by thomasplevy** [comment]
![Screenshot_2022-07-14_09-27-27](https://user-images.githubusercontent.com/1290739/179031305-0fee9a71-fc73-4e8c-b9a9-4de9fac8b7bc.png)

@eri-trabiccolo thoughts on this?

+ making it just days because we don't have a combo field box for number input + dropdown
+ are descriptions clear enough?

**Comment by eri-trabiccolo** [comment]
@thomasplevy looks good.
I'm all for reducing the complexity and talk only about days.
Descriptions are clear enough yes.

This is a very good feature!

**Comment by brianhogg** [comment]
Closing to add as an idea and possible future cycle pitch.
