### ISSUE TITLE
[L321]  __  Missing text domain during build with gulp

### ISSUE THREAD

**Issue by TheBarzFR** [gocodebox/lifterlms#2224]
### Reproduction Steps

Error during building last release with gulp

### Expected Behavior

See below

### Error Messages / Logs

+ Include any relevant error messages or log files
```
gulp build
/opt/lifterlms/includes/admin/post-types/post-tables/class-llms-admin-post-table-awards.php
...
[L321]  __  Missing text domain
1 problem

```

### System and Environment Information

<details>
<summary>System Report</summary>

Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Components version:
npm: 8.5.1
nodejs: v12.22.9
PHP: 7.4.30

Gulp CLI version: 2.3.0
Local version: 4.0.2

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Comment by thomasplevy** [comment]
Thanks @TheBarzFR we'll get this cleaned up!
