### ISSUE TITLE
PHP Fatal error on Quick Edit Awarded Certificates

### ISSUE THREAD

**Issue by younes-dro** [gocodebox/lifterlms#2231]
[17-Aug-2022 14:12:09 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_user_id() on bool in C:\wamp64\www\expresstechsoftware\wp-content\plugins\lifterlms\includes\admin\post-types\post-tables\class-llms-admin-post-table-awards.php:232
Stack trace:
#0 C:\wamp64\www\expresstechsoftware\wp-content\plugins\lifterlms\includes\admin\post-types\post-tables\class-llms-admin-post-table-awards.php(194): LLMS_Admin_Post_Table_Awards->manage_cols_user(131)
#1 C:\wamp64\www\expresstechsoftware\wp-includes\class-wp-hook.php(307): LLMS_Admin_Post_Table_Awards->manage_cols('user', 131)
#2 C:\wamp64\www\expresstechsoftware\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 C:\wamp64\www\expresstechsoftware\wp-includes\plugin.php(476): WP_Hook->do_action(Array)
#4 C:\wamp64\www\expresstechsoftware\wp-admin\includes\class-wp-posts-list-table.php(1349): do_action('manage_llms_my_...', 'user', 131)
#5 C:\wamp64\www\expresstechsoftware\wp-admin\includes\class-wp-list-table.php(1450): WP_Posts_List_Table->column_default(Object(WP_Pos in C:\wamp64\www\expresstechsoftware\wp-content\plugins\lifterlms\includes\admin\post-types\post-tables\class-llms-admin-post-table-awards.php on line 232

**Comment by eri-trabiccolo** [comment]
Hi @younes-dro 
thanks for reporting this.
It happens when you click on the Update button from the quick edit form, right?

**Comment by younes-dro** [comment]
hello @eri-trabiccolo 

Yes.

![quick-update](https://user-images.githubusercontent.com/31171/185179500-989b199c-3e83-448b-9cef-c5e4f2814e3a.png)
