### ISSUE TITLE
[Reporting Feature] The text inside blue progress indicator is not readable

### ISSUE THREAD

**Issue by sekanderb** [gocodebox/lifterlms#2236]
If you look at the screenshot, you will see that the black text inside the blue progress bar is not readable. We can either make the font color white or change the background to make it readable.

In my personal opinion, the progress bar should not get much focus as it will get repeated in every row. Making it light gray (example: #dedede) could make things easy to read.

But if that's too much work, we can keep all the blue and make the font white.

<img width="1010" alt="Screen Shot 2022-08-20 at 11 19 09 AM" src="https://user-images.githubusercontent.com/3262638/185730613-3aa2ecaf-b76f-4bc2-a325-a1835ebd8b73.png">

**Comment by eri-trabiccolo** [comment]
This was actually fixed with the admin restyling shipped with 7.1
