### ISSUE TITLE
Course Progress Reporting Feature - Dummy Text

### ISSUE THREAD

**Issue by sekanderb** [gocodebox/lifterlms#2239]
Please have a look at the marked area. It says call to action. I guess we can change it to something relevant. When I clicked the button, I took me to lesson edit screen. So, I am not sure if this is the expected behavior.
<img width="1436" alt="Screen Shot 2022-08-21 at 8 48 05 PM" src="https://user-images.githubusercontent.com/3262638/185796944-3d73cf88-19f8-4bda-a901-f2eb70cef5dc.png">

**Comment by thomasplevy** [comment]
What's the behavior you're expecting?

**Comment by eri-trabiccolo** [comment]
@sekanderb 
_Call to action_ it's not a dummy text, it's the name of the last lesson completed by Kade and Margarita. If their last completed lesson was _Always look at the bright side of life_ that's the text you would see there, with the edit link to that very lesson.

**Comment by sekanderb** [comment]
@thomasplevy as the column name says last lesson, we could mention the name of the lesson.

From @eri-trabiccolo's comment, it seems that the problem was with the lesson name. I also went ahead and verified that indeed the lessons actual name was "call to action".

I am marking this as closed. I apologize for the inconvenience.
