### ISSUE TITLE
Spain missing Provinces

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2243]
### Reproduction Steps

+ HS-200045
+ User reported that several provinces and regions were either missing or wrong. Provided this as a list: https://public.opendatasoft.com/explore/dataset/provincias-espanolas/table/?sort=provincia

I'm not sure if there is a way to verify this is correct but we could maybe use it as a reference point?

### Expected Behavior

+ There should be more/separate provinces and regions

### Actual Behavior

+ Missing places

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
Ok, cool, thanks.
That link though doesn't give us any information about the province's code, like  B for Barcelona, CC for Cáceres, M for Madrid and so on.
I manually compared the list the customer provides us with, with the WooCommerce one:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/states.php#L552-L605

They match (except for the order, and the language, which is english for WooCommerce, of course).
So I'd say that we're gonna use the WooCommerce one.

**Comment by thomasplevy** [comment]
sounds good :+1:
