### ISSUE TITLE
Sidebar 404

### ISSUE THREAD

**Issue by oksodavid** [gocodebox/lifterlms#227]
Your theme does not declare support for LifterLMS Sidebars. Please see our integration guide or check out our LaunchPad theme which is designed specifically for use with LifterLMS

https://lifterlms.com/docs/lifterlms-sidebar-support/?utm_source=notice&utm_medium=product&utm_content=sidebarsupport&utm_campaign=lifterlmsplugin

results 404

**Comment by thomasplevy** [comment]
@oksodavid please see #178 -- documentation is coming
