### ISSUE TITLE
Integrations 404

### ISSUE THREAD

**Issue by oksodavid** [gocodebox/lifterlms#228]
Enable Integrations
Extend LifterLMS functionality to any of the following popular plugins
bbPress	bbPress Enable
Restrict forums and topics within forums to LifterLMS memberships. ***Learn More***
BuddyPress	BuddyPress Enable
Add LifterLMS information to BuddyPress profiles. ***Learn More***

***Learn More*** > results 404

**Comment by thomasplevy** [comment]
@oksodavid please see #178 -- i am far behind on my documentation but its a top priority for today
