### ISSUE TITLE
Instructor and Assistant Roles not able to update course content

### ISSUE THREAD

**Issue by robbiefarai** [gocodebox/lifterlms#2285]
Some thing happened where instructors and instructor assistants are not able to edit their courses any more. They must now be added the Role LMS Manager. However this enables them to edit and view the courses of other instructors.

**Comment by thomasplevy** [comment]
Hey @robbiefarai 

Could you provide some additional information about your issue:

Have a look at our issue template for a [bug report](https://github.com/gocodebox/lifterlms/issues/new?assignees=&labels=&template=Bug_Report.md)

I'd also like to know what the last version of LifterLMS you were using before you had this issue.

Thanks!

**Comment by thomasplevy** [comment]
@robbiefarai Can you update us with the requested information please!

**Comment by actuallyakash** [comment]
Hey @robbiefarai 

I've just tested this and it's working fine. Instructors and instructor assistants can see other courses but can only edit the courses made by them or which are assigned to them. Going to close the issue, you can always open it if something else arises.

Below docs can be helpful:

https://lifterlms.com/docs/roles-and-capabilities/
https://lifterlms.com/docs/how-do-i-change-the-instructor-of-a-course/
