### ISSUE TITLE
Illegal string error message from class.llms.admin.notices.php file

### ISSUE THREAD

**Issue by melissalove** [gocodebox/lifterlms#229]
Showing up throughout dashboard on a completely clean install of WordPress and Divi. No plugins or changes to functions.php.
![screenshot-siteschool thedesignspace co 2016-10-11 22-36-42](https://cloud.githubusercontent.com/assets/17326331/19289603/77e66994-9003-11e6-85fa-bf75745771d1.jpg)

**Comment by thomasplevy** [comment]
sorry about that melissa, I'll see what I can do to get that resolved...

**Comment by thomasplevy** [comment]
@melissalove has this gone away?

if it has, do you recall any button presses or clicks or actions taken immediately prior that could help me recreat the issue

thanks

**Comment by melissalove** [comment]
@thomasplevy Still there but I guess it won't go away until I update again? I can delete Lifter and reintall?

**Comment by melissalove** [comment]
Just so you know. Deleted, re-installed and still there.

**Comment by thomasplevy** [comment]
@melissalove can use the element inspector and find the "ID" of the element wrapping the warnings should be something like "llms-notices...."

I could track it down from there

thanks

**Comment by melissalove** [comment]
Inspect the error notices?

**Comment by melissalove** [comment]
I think it's llms-admin-notice and lms notice gateways.

**Comment by thomasplevy** [comment]
@melissalove can you send me the **full id** of the notice that the warnings are rendering inside of

**Comment by melissalove** [comment]
Sure. I'm not sure I'm looking in the right place though. Is it this?

<div class="notice notice-<br />
<b>Warning</b>:  Illegal string offset 'type' in <b>/home/thedes94/public_html/siteschool/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php</b> on line <b>181</b><br />
 llms-admin-notice" id="llms-noticeno-gateways">
				<br>
<b>Warning</b>:  Illegal string offset 'dismissible' in <b>/home/thedes94/public_html/siteschool/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php</b> on line <b>182</b><br>
				<br>
<b>Warning</b>:  Illegal string offset 'html' in <b>/home/thedes94/public_html/siteschool/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php</b> on line <b>187</b><br>
				<br>
<b>Warning</b>:  Illegal string offset 'remindable' in <b>/home/thedes94/public_html/siteschool/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.notices.php</b> on line <b>188</b><br>
			</div>

**Comment by thomasplevy** [comment]
resolved in 3.0.2 (pending release)
