### ISSUE TITLE
Does this Console Log Error have anything to do with LifterLMS?

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2296]
HS-208437

Console logs are something I currently have no understanding of, so I'm not sure how to answer this question or even how to correctly title/phrase the question:

We had a customer report Chrome console seems to be throwing up errors relating to the Vimeo player which is causing delays in their site load.

Just wondering if this might me a LifterLMS issue with the player we're using? or if there's even enough information below to glean valuable information from or if we should go ahead and request admin logins. (my Chrome console is not sending this information when I load a Vimeo video)

Here's a copy of the errors.

jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-test-impression?beacon=1 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
(anonymous) @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 568379559?color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 568379559?color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ba8758f1511867bfbcbb0bcb027b9ea6bb66436d1667732844 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
be @ player.module.js:2
_ @ vendor.module.js:2
Wa @ vendor.module.js:2
_e @ player.module.js:2
Promise.then (async)
Go @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 568379559?color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 568379559?color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-test-impression?beacon=1 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
(anonymous) @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ba2a3acae4bdd218128ffd97c0a60a5d3138c2b11667732844 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
be @ player.module.js:2
_ @ vendor.module.js:2
Wa @ vendor.module.js:2
_e @ player.module.js:2
Promise.then (async)
Go @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ba2a3acae4bdd218128ffd97c0a60a5d3138c2b11667732844 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
be @ player.module.js:2
_ @ vendor.module.js:2
logStartRequest @ vendor.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
(anonymous) @ player.module.js:2
performDelegateAction @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
play @ vendor.module.js:2
play @ vendor.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
ee @ player.module.js:2
(anonymous) @ player.module.js:2
setTimeout (async)
(anonymous) @ player.module.js:2
Promise.then (async)
vi @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://player-telemetry.vimeo.com/player-events/log/play 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
w @ player.module.js:2
m @ player.module.js:2
(anonymous) @ player.module.js:2
performDelegateAction @ player.module.js:2
E @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
play @ vendor.module.js:2
play @ vendor.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
ee @ player.module.js:2
(anonymous) @ player.module.js:2
setTimeout (async)
(anonymous) @ player.module.js:2
Promise.then (async)
vi @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ba2a3acae4bdd218128ffd97c0a60a5d3138c2b11667732844 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
be @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
t._handleEvent @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
Promise.then (async)
then @ vendor.module.js:2
n.loadManifest @ vendor.module.js:2
Promise.then (async)
n.setVideoSrc @ vendor.module.js:2
set @ vendor.module.js:2
t._updateCurrentFile @ vendor.module.js:2
set @ vendor.module.js:2
t._initScanner @ vendor.module.js:2
t._updateScanner @ vendor.module.js:2
set @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
c @ vendor.module.js:2
loadVideo @ vendor.module.js:2
J @ player.module.js:2
vi @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://player-telemetry.vimeo.com/player-events/log/partial 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
w @ player.module.js:2
m @ player.module.js:2
(anonymous) @ player.module.js:2
performDelegateAction @ player.module.js:2
E @ player.module.js:2
C @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
t._handleEvent @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
t._onPlayError @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
Promise.catch (async)
t.play @ vendor.module.js:2
n.play @ vendor.module.js:2
t.play @ vendor.module.js:2
play @ vendor.module.js:2
play @ vendor.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
ee @ player.module.js:2
(anonymous) @ player.module.js:2
setTimeout (async)
(anonymous) @ player.module.js:2
Promise.then (async)
vi @ player.module.js:2
(anonymous) @ player.module.js:2
W @ player.module.js:2
(anonymous) @ player.module.js:2
Promise.then (async)
init @ player.module.js:2
cd @ player.module.js:2
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
Promise.then (async)
(anonymous) @ 561721144?autoplay=1&color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0:1
vendor.module.js:2 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ba2a3acae4bdd218128ffd97c0a60a5d3138c2b11667732844 500
(anonymous) @ vendor.module.js:2
t @ vendor.module.js:2
log @ vendor.module.js:2
be @ player.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ player.module.js:2
e.fire @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
t._handleEvent @ vendor.module.js:2
(anonymous) @ vendor.module.js:2
e.fire @ vendor.module.js:2
n._handleStreamChange @ vendor.module.js:2
e.fire @ vendor.module.js:2
i._resolveSwitchComplete @ vendor.module.js:2
t._updateBufferEnd @ vendor.module.js:2
t._handleUpdateEnd @ vendor.module.js:2

**Comment by thomasplevy** [comment]
Hard to say... This looks like it's a telemetry related request but without looking at the actual network traffic it's difficult to pinpoint the origin.

Where does this happen?

Steps to recreate?

Does it happen with LifterLMS disabled? Only on LifterLMS screens?

Etc...?

Really can't say whats causing this based on this log alone.

**Comment by thomasplevy** [comment]
@willmiddleton-lifterlms I tried to login to get more information but the provided username/password doesn't work. I tried a password reset but I'm not getting an email back.

Maybe email doesn't work properly on the customer's server?

Please get credentials functioning and report back so we can dig in deeper.

Thanks!

**Comment by magicemilymiddleton** [comment]
Customer responded and said:

"I've done a little troubleshooting…. It seems that the issue was caused by my system-wide Adguard. Disabling it has removed the console errors. 🙄"

We do have admin logins if we care enough to investigate a LifterLMS + Adguard conflict, but I'd assume it's not widely used enough to be worth the effort in solving.

**Comment by thomasplevy** [comment]
Adblockers, among other things, kill telemetry calls. This is expected if you choose to use an ad blocker. There's no "conflict" here that we'd be able to do anything about anyway since extensions run in the browser's sandbox. There's no apis to integrate with or whatever... We'll close this out. The user should configure their adblocker to not run on their own site, that's the best bet.

FYI: I disable my adblockers on sites I manage (like LifterLMS.com).
