### ISSUE TITLE
Lifter login vs Buddypress

### ISSUE THREAD

**Issue by oksodavid** [gocodebox/lifterlms#230]
Just a small detail about consistency of user experience. My lifter login requires account email address, whereas Buddypress requires username. This creates confusion for users when in a mixed Buddypress Lifter setup. Can the Lifter login form have an option to accept username display, or have default WordPress 'Username or Email'?

**Comment by thomasplevy** [comment]
@oksodavid check your LifterLMS -> Settings -> Accounts and look for "Disable Usernames" under "General Information Field Settings"

![lifterlms_settings_ _local_ _wordpress](https://cloud.githubusercontent.com/assets/1290739/19319546/25c4f69e-9062-11e6-94e6-bdc5fe16d017.jpg)

**Comment by oksodavid** [comment]
thank you, and apologies.

**Comment by thomasplevy** [comment]
@oksodavid no apologies necessary!
