### ISSUE TITLE
Quiz doesn't start

### ISSUE THREAD

**Issue by saracomin96** [gocodebox/lifterlms#2300]
### Reproduction Steps

hi, if a user tries to take the quiz, the button doesn't work and generates this error:

llms-quiz.js:589 Uncaught TypeError: LLMS.l10n.translate is not a function
     at Object.load_ui_elements (llms-quiz.js:589:147)
     at Object.start_quiz (llms-quiz.js:373:9)
     at HTMLButtonElement.<anonymous> (llms-quiz.js:95:10)
     at HTMLButtonElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
     at v.handle (jquery.min.js?ver=3.6.0:2:41048)

Instead from admin this problem does not come out, from what can it be given?

### Expected Behavior

the quiz screen should open

### Actual Behavior

generates error:

llms-quiz.js:589 Uncaught TypeError: LLMS.l10n.translate is not a function
    at Object.load_ui_elements (llms-quiz.js:589:147)
    at Object.start_quiz (llms-quiz.js:373:9)
    at HTMLButtonElement.<anonymous> (llms-quiz.js:95:10)
    at HTMLButtonElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
llms-quiz.js:589 Uncaught TypeError: LLMS.l10n.translate is not a function
    at Object.load_ui_elements (llms-quiz.js:589:147)
    at Object.start_quiz (llms-quiz.js:373:9)
    at HTMLButtonElement.<anonymous> (llms-quiz.js:95:10)
    at HTMLButtonElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
 Wordpress
-------------------------------------------

Home Url: https://academy.bluenext.it
Site Url: https://academy.bluenext.it
Login Url: https://academy.bluenext.it/wp-login.php
Version: 6.0.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: it_IT
Multisite: No
Page For Posts: Not Set
Page On Front: Home Page (#1372) [https://academy.bluenext.it/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.0
Db Version: 7.0.0
Course Catalog: Catalogo Corsi (#16) [https://academy.bluenext.it/?page_id=16]
Membership Catalog: Catalogo Membership (#17) [https://academy.bluenext.it/?page_id=17]
Student Dashboard: Area Riservata (#1317) [https://academy.bluenext.it/area-riservata/]
Checkout Page: Acquisti (#18) [https://academy.bluenext.it/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: modifica-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: riscatta-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: formazione@bluenext.it
Email From Name: Bluenext Academy
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manuale: Disabled
Manuale Logging: no
Manuale Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.39
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 50 MB
Php Memory Limit: 512M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 3600
Php Version: 7.4.33
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad Child
Version: 1.1.0
Themeuri: https://lifterlms.com/product/launchpad/
Authoruri: https://lifterlms.com
Template: lifterlms-launchpad
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control: 4.1.1
Elementor: 3.8.0
Elementor Pro: 3.8.0
Events Widgets For Elementor And The Events Calendar: 1.6
FluentCRM - Marketing Automation For WordPress: 2.6.1
LifterLMS: 7.0.0
LifterLMS Blocks: 2.4.3
LifterLMS Custom Fields: 2.0.2
LifterLMS Labs: 1.6.0
LifterLMS Stripe Payment Gateway: 5.5.0
Login as User: 1.4.4
PublishPress Capabilities: 2.6.0
Simple Custom CSS and JS: 3.41
The Events Calendar: 6.0.3
Toolset Blocks: 1.6.3
Toolset Module Manager: 1.8.8
Toolset Types: 3.4.16
WP Engine Smart Plugin Manager: 5.12.21
WPForms: 1.7.7.2
WPForms User Registration: 2.1.0
WP Mail SMTP: 3.6.1
Yoast Duplicate Post: 4.5
Yoast SEO: 19.9


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 4.21.0)
checkout/form-checkout.php (ver: 5.0.0): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 5.0.0)
emails/header.php (ver: 3.16.15): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 3.16.15)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
Hey @saracomin96 you were asking on slack how to put a quiz on a custom page with a short code. Have you done that and is that customization possibly causing this problem?

**Comment by saracomin96** [comment]
hello, I didn't do anything special, I just created a button that refers to the quiz at the end. I noticed one thing: by deleting the cache I can take the quiz once but once I try again it gives me the same error. I have wpengine it might be a cache problem

**Comment by saracomin96** [comment]
it also gives me error for LLMS.Ajax

**Comment by thomasplevy** [comment]
> I just created a button that refers to the quiz at the end

Is this button a quiz start button (as seen on the default quiz page) which, when clicked, starts the quiz with an AJAX request?

Or is the button a link that takes you to the quiz page?

Is the problem happening when you click this button?

If you're trying to create a start quiz button that loads the quiz on a non-default screen you'll need to enqueue the JS resources that are expected to be loaded when the button is clicked (which are loaded, by default, on the quiz screen).

This script powers quiz functionality:

https://github.com/gocodebox/lifterlms/blob/488f8e6b131459f9b3aebf4c61c820e1b665d96c/includes/class.llms.frontend.assets.php#L200

If loaded out of default context I'm *not* 100% positive it will function. There may be CSS selectors used to power the JS events that may be necessary in order to make everything work. I'm not positive about that though.

**Comment by saracomin96** [comment]
Hi! in the end it was the cookie banner that blocked resources if cookies were not accepted, I corrected the types of cookies needed and now it works!
