### ISSUE TITLE
Manually recorded first transaction on an access plan with unpaid trial, is not recorded as trial transaction

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#2308]
### Reproduction Steps

+ Create an access plan with trial
+ as visitor, purchase the access plan with manual payment
+ as admin head on the order and manually record a transaction, ideally for the trial.

### Expected Behavior

+ I'd expect the transaction is recorded for the trial

### Actual Behavior

+ The transaction is actually recorded as a "normal" transaction, this also means that it if you have a plan with a trial and a recurring plan with 5 payments due, this transaction will decrease the number of remaining recurring transactions from 5 to 4.

### System and Environment Information

LifterLMS 7.0.1

### This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by brianhogg** [comment]
For an access plan with a free trial, it looks like the first $0 transaction on the Order is a `single` type when it probably should be `trial`.
