### ISSUE TITLE
Database question: Postgres or MariaDB as opposed to MySQL?

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2309]
We had a customer ask a question that I have no clue about the answer to. Is there any info you could help fill me in on about this:
_"I plan to use Postgres or MariaDB as opposed to MySQL, will that be an issue?"_

**Comment by eri-trabiccolo** [comment]
MariaDB is a fork of MySQL, so it's fine.
WordPress requires MySQL/MariaDB, doesn't natively support postgresql, there might be a plugin for that but I never used it.
See WordPress requirements here:
https://wordpress.org/about/requirements/
Although we require higher PHP:
https://github.com/gocodebox/lifterlms/blob/trunk/lifterlms.php#L22

**Comment by magicemilymiddleton** [comment]
Thanks!

**Comment by eri-trabiccolo** [comment]
@willmiddleton-lifterlms 
I'm closing this theb, feel free to re-open it if you need. ❤️
