### ISSUE TITLE
LifterLMS Add-ons screens pulling "hidden" products from the WooCommerce catalog on LifterLMS.com

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#2335]
### Reproduction Steps

+ Install LifterLMS 
+ View the "All" view
+ Noticed the Lifetime Deal products as an example. They shouldn't be there as they are set to "hidden" in the WooCommerce catalog visibility settings

### Expected Behavior

+ The All tab, and any other tab there that shows products from within our store should NOT show hidden products

### Actual Behavior

+ Hidden products display and they shouldn't

![LifterLMS_Add-ons__Courses__and_Resources_‹_LifterLMS_Academy_—_WordPress_and_Zoom](https://user-images.githubusercontent.com/12163552/216671697-ff6202f5-f7bc-4ef5-8c7d-10fc5019a2c3.png)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://soft-cherry.myliftersite.com
Site Url: https://soft-cherry.myliftersite.com
Login Url: https://soft-cherry.myliftersite.com/wp-login.php
Version: 6.1.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.1
Db Version: 7.0.1
Course Catalog: Course Catalog (#14) [https://soft-cherry.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#15) [https://soft-cherry.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#17) [https://soft-cherry.myliftersite.com/dashboard/]
Checkout Page: Purchase (#16) [https://soft-cherry.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.41
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.27
Software: Apache/2.4.55 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-Three
Version: 1.0
Themeuri: https://wordpress.org/themes/twentytwentythree
Authoruri: https://wordpress.org
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 7.0.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by chrisbadgett** [comment]
While we are here on this area, it would be nice to lead with "Bundles" in the first position and put "All" in the last position.

**Comment by chrisbadgett** [comment]
Products with catalog visibility set to hidden should not show up in the Add-ons and more view 
![Edit_product_“Infinity_Bundle_Lifetime_License_–_Payment_Plan__12_–_Pay_”_‹_LifterLMS_—_WordPress](https://user-images.githubusercontent.com/12163552/216707866-40ee4c58-9de1-47c4-a6cd-22aaa5673735.png)

**Comment by kimcoleman** [comment]
Looking into this - the Add-ons that are "hidden" seem to also pass the category as "uncategorized". If this is an ok check - without us having to update things to retrieve the hidden product property that isn't already in the addons code - we can update this function:
https://github.com/gocodebox/lifterlms/blob/dev/includes/admin/class.llms.admin.addons.php#L89

to also include a check like:

`// Exclude uncategorized Add-ons.
if ( array_key_exists( 'uncategorized', $addon['categories'] ) ) {
	unset( $this->data['items'][ $key ] );
}
`
