### ISSUE TITLE
Add filter for content displayed when no courses are available

### ISSUE THREAD

**Issue by seothemes** [gocodebox/lifterlms#2365]
A customer asked if it's possible to change the `You are not enrolled in any courses.` text that is displayed when no courses are available.

It would be nice to add a dedicated filter for this [here](https://github.com/gocodebox/lifterlms/blob/trunk/includes/functions/llms.functions.templates.dashboard.php#L196), and possibly an option somewhere to make it easier for users to add custom content.

Currently the only way to change this is with the use of the `gettext` (or `gettext_lifterlms`) filter, which is kind of a hack.

**Comment by jaedm97** [comment]
Hi @eri-trabiccolo 

I would like to implement this issue. We can provide both options for the users: 

- A filter for the developers to customize the content. 
- A new setting in `Settings > Membership` for non-tech users to customize the content. 

Let me know your opinion. Thanks.

**Comment by actuallyakash** [comment]
Hey @jaedm97 

Thank you for reaching out for your contribution. I didn't see your comment before working on this issue 😅 

Let me discuss with the team if we need a **setting in the backend for non-tech users** and then you can go ahead and make your contribution. Thanks.
