### ISSUE TITLE
Content Restricted Message not working

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#237]
Hi LifterLMS team,
I am working on a new site and I've noticed the even if I insert the Content Restricted Message the system is going to use the default one.

Just to be sure I've attached two images in this issue, the first one is the result on my frontend and the second one is from the course restrictions panel.

![frontend-restricted-message](https://cloud.githubusercontent.com/assets/190159/19418455/94875b70-93c4-11e6-858a-aead7d713db7.png)

![backend-restricted-message](https://cloud.githubusercontent.com/assets/190159/19418463/b415fb54-93c4-11e6-91b2-d80fd70fd46b.png)

Hope this can help.
Andrea

**Comment by thomasplevy** [comment]
hey @AndreaBarghigiani we're actually using this setting somewhere else but the description is misleading and this text probably should be displayed inside the tooltips

I'll get this updated in a future release, thanks for catching it <3

**Comment by thomasplevy** [comment]
@AndreaBarghigiani just wanted to hit you up and let you know that after a long time i've gotten this issue resolved, please see version 3.2.4 of LifterLMS!
