### ISSUE TITLE
Create consistent HTML markup for sections added to the LifterLMS My Dashboard

### ISSUE THREAD

**Issue by kimcoleman** [gocodebox/lifterlms#2378]
**Is your feature request related to a problem? Please describe.**
The HTML for the various tabs or "sections" on the LifterLMS My Dashboard (frontend page output by the shortcode [lifterlms_my_account]) has different HTML markup for each tab.

We should create a consistent HTML wrapping `<section>` just like the main sections for My Courses or My Memberships to help people themeing these pages or otherwise wanting to create a consistent style that targets for all "tabs"/views.

**Comment by brianhogg** [comment]
v7.8 added more consistency, will improve as needed for accessibility
