### ISSUE TITLE
Error when featured image file doesn't exist

### ISSUE THREAD

**Issue by seothemes** [gocodebox/lifterlms#2381]
### Reproduction Steps

Looks like it's happening when a course has a featured image set but the file doesn't exist.

Getting the error "Trying to access array offset on value of type bool"

From `llms_featured_img` function https://github.com/gocodebox/lifterlms/blob/trunk/includes/llms.template.functions.php#L810)

<img width="734" alt="featured image error" src="https://user-images.githubusercontent.com/24793388/224225626-71650c54-3446-498d-8298-a04c2e3fc342.png">

### Expected Behavior

Return empty string if `wp_get_attachment_image_src` is not set

### Actual Behavior

`wp_get_attachment_image_src` returns false because [0] is not set

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
Fixed, see https://github.com/gocodebox/lifterlms/pull/2392
