### ISSUE TITLE
Merge Codes for Certificates missing in 7.1.1

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2391]
### Reproduction Steps

+ Note: this will be fixed with Rocco's PR for issue #2386 (#2387) but this should be added to the changelogs.
+ Head into certificates
+ Add a bock and open the dropdown to open the merge code options

### Expected Behavior

+ The merge codes should be listed in the additional options drop down to copy and paste.

### Actual Behavior

+ The option is missing, only LifterLMS shortcodes are available. 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
Fixed, see https://github.com/gocodebox/lifterlms/pull/2392
