### ISSUE TITLE
All lessons completed 100% and course incomplete

### ISSUE THREAD

**Issue by saracomin96** [gocodebox/lifterlms#2395]
### Reproduction Steps

For each lesson the user has a button that sends to an external platform (costum), which has a video player, if the user watches the whole video, an api call (https://developer.lifterlms.com/rest-api/#tag/Student-Progress/paths/~1students~1{id}~1progress~1{post_id}/post) is made to update the "complete" lesson from previously accessed (via the button). The site has a lot of traffic and calls although they are successful and all the lessons of the course are completed, the course is not 100% completed, which is a problem because it precludes the possibility of earning certificates or awards.

I also point out that the call update student progress (https://developer.lifterlms.com/rest-api/#tag/Student-Progress/paths/~1students~1{id}~1progress~1{post_id}/post ), for a course if passed as 'complete' status, it does not complete it, it remains unchanged

### Expected Behavior

Upon completion of all lessons the course is 100% complete

### Actual Behavior

All lessons of a course completed but the course is not 100% complete

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Supporto
-------------------------------------------


WordPress
-------------------------------------------

Home Url: https://academy.assosoftware.it
Site Url: https://academy.assosoftware.it
Login Url: https://academy.assosoftware.it/wp-login.php
Version: 6.1.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: it_IT
Multisite: No
Page For Posts: Not Set
Page On Front: Home Page (#1372) [https://academy.assosoftware.it/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.1.1
Db Version: 7.1.1
Course Catalog: Catalogo Corsi (#16) [https://academy.assosoftware.it/?page_id=16]
Membership Catalog: Catalogo Membership (#17) [https://academy.assosoftware.it/?page_id=17]
Student Dashboard: Area Riservata (#1317) [https://academy.assosoftware.it/area-riservata/]
Checkout Page: Acquisti (#18) [https://academy.assosoftware.it/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: modifica-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: riscatta-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: academy@assosoftware.it
Email From Name: ASSOSOFTWARE
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manuale: Disabled
Manuale Logging: no
Manuale Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.40
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 50 MB
Php Memory Limit: 512M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 43300
Php Version: 8.0.28
Software: nginx
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad Child
Version: 1.1.0
Themeuri: https://lifterlms.com/product/launchpad/
Authoruri: https://lifterlms.com
Template: lifterlms-launchpad
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: 4.2.7
Elementor: 3.11.5
Elementor Pro: 3.11.6
Events Widgets For Elementor And The Events Calendar: 1.6.2
FluentCRM - Marketing Automation For WordPress: 2.7.40
LifterLMS: 7.1.1
LifterLMS Blocks: 2.4.3
LifterLMS Custom Fields: 2.0.2
LifterLMS Labs: 1.6.1
Login as User: 1.4.4
PublishPress Capabilities: 2.7.0
Simple Custom CSS and JS: 3.43
The Events Calendar: 6.0.11
Toolset Blocks: 1.6.5
Toolset Module Manager: 1.8.8
Toolset Types: 3.4.18
WP Crontrol: 1.15.2
WP Engine Smart Plugin Manager: 5.13.28
WPForms: 1.8.0.2
WPForms User Registration: 2.1.0
WP Mail SMTP Pro: 3.7.0
Yoast Duplicate Post: 4.5
Yoast SEO: 20.3


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /nas/content/live/assosoftware/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 4.21.0)
checkout/form-checkout.php (ver: 5.0.0): /nas/content/live/assosoftware/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 5.0.0)
emails/header.php (ver: 3.16.15): /nas/content/live/assosoftware/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 3.16.15)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by actuallyakash** [comment]
Hey @saracomin96 

I've tested this on my end and it seems to complete the course when completing all the lessons from API Endpoint (https://developer.lifterlms.com/rest-api/#tag/Student-Progress/paths/~1students~1%7Bid%7D~1progress~1%7Bpost_id%7D/post)

Can you provide a JSON export file of a course in which you're facing the issue? You can export a course by going to Courses > Hover over any course and you'll see an export button. Just attach the file here and we'll test it.

Thanks.

**Comment by saracomin96** [comment]
[coursejson.zip](https://github.com/gocodebox/lifterlms/files/11040770/coursejson.zip)

hello, I attach the file. However, the site has a lot of traffic and is overloaded

**Comment by actuallyakash** [comment]
Hey @saracomin96, thanks for providing the JSON file.

I can see that the course provided by you is also working fine (attached screenshot with progress bar). I've completed all four lessons via API endpoint and they're completing the course to 100%.

![image](https://user-images.githubusercontent.com/18614782/226940628-6ac02dc9-ec54-4bfb-9bad-582d060d5735.png)
![image](https://user-images.githubusercontent.com/18614782/226942461-590b0b44-41a9-4c02-a936-34b6964f5ef5.png)

I'm tagging @eri-trabiccolo for insights, and if I find something, I'll get back to you here.

**Comment by saracomin96** [comment]
Hi, do you have any news?
I'll give you more details, we have considerable traffic within the site (about 1000 registered users), a prize and a certificate are awarded for each completed lesson, often they fail and the lessons are not completed or the prize and the certificate are not assigned. Could it be given by these engagements?

**Comment by saracomin96** [comment]
in this table 'wp_lifterlms_user_postmeta', meta_value and meta_id are related to something else? at what?

<img width="573" alt="Screenshot_2023-03-27_alle_16 21 21" src="https://user-images.githubusercontent.com/109804671/227970961-aab8406d-e4de-42fb-9026-48f7dc180709.png">

I also have another question: several misalignments in a site where many users are attending courses, these misalignments mean that for completed lessons they are not awarded a certificate and related award, we would like to launch a query in the database to trigger these meta_key : _completion_trigger, _achievement_earned, _certificate_earned? is it possible?

thank you so much!

**Comment by eri-trabiccolo** [comment]
Hey @saracomin96 as said on slack

> `meta_id` is just the table auto-increment ID
> `meta_value` is the actual value of the row…
> see the table description here: https://lifterlms.com/docs/lifterlms-database-description/#table-wp_lifterlms_user_postmeta

> we would like to launch a query in the database to trigger these meta_key : _completion_trigger, _achievement_earned, _certificate_earned? is it possible?

You said that the completion was already there, why do you need to add a completion trigger?

Ideally yes you can but what would be the purpose of this? 
So that they would be able to see the certificates/achievements earned on their dashboard? 
In this case yes you can.
But you need to create the earned certificate and assignment too (whose ID will be the `meta_value` in the table above; `post_id` there is the lesson/course ecc which triggered the certificate awarding)

**Comment by saracomin96** [comment]
Hi, since there was server malfunction, certain triggers didn't fire, so there are certificates and rewards that weren't earned, since it's really a lot of users we need to do it in database, what query can be run?

**Comment by saracomin96** [comment]
HI,
the steps would be:

- Create an earned certificate assigned to the user

- Do an insert where the assigned certificate ID will be the meta_value in the table above; post_id there is the lesson/course etc which triggered the certificate awarding/award

If I need to enter thousands of assigned certificates and awards, how can I do it directly in the database with query?

**Comment by eri-trabiccolo** [comment]
Hi there,
well doing that with only SQL queries would be pretty complex, you'd need to create different records on different tables with a specific order, I wouldn't suggest that, nor we can provide you with the exact code - it's not trivial, and our software already does what should be done with PHP + queries.
If you really want to do that then I can only suggest you to do some manual tests and see what changes in the DB over different tables and reverse engineer the SQL code you need.

If the lessons are already marked as completed but the certificates and awards weren't created and assigned for many users I would rather suggest you to go through these users (loop over them) and:
- mark a completed course lesson as incomplete
- mark that lesson as complete
this will trigger the lesson and the course completion again, so triggering the engagement awarding.

Can this be an heavy task? Yeah, over many users it will, I suggest you then to run this in background 30 users at a time.
E.g. using this library: https://github.com/deliciousbrains/wp-background-processing

I'm going to close this issue unless you found  a bug in our code that needs to be addressed, in this case please feel free to re-open this adding a description of the bug. Thanks!
