### ISSUE TITLE
Problems on outline course inside dashboard after upgrading 3.0.1

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#241]
Hi LifterLMS team,
this is a minor thing but I would like to understand if it is only me or if is something that affects other users. Since I upgraded from the 3.0.1 I've noticed a strange alignment of the lessons. You can see from the image below what I mean.

![schermata 2016-10-20 alle 11 41 13](https://cloud.githubusercontent.com/assets/190159/19554856/bc7ff148-96ba-11e6-8a21-919b594044db.png)

I've already upgraded to 3.0.2 but nothing has changed. Can you please have a check? I am working on Firefox Developer Edition and I am creating a custom theme for Genesis, it souldn't be a poblem from my side but if is working well for you I am going to check even further.

Thank you,
Andrea

**Comment by thomasplevy** [comment]
@AndreaBarghigiani I'll take a look, thanks for the heads up

**Comment by thomasplevy** [comment]
found the issue but need to bump out of milestone
