### ISSUE TITLE
Add an option to include the number of lessons on course thumbnails in the course catalog and "My Courses".

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2434]
**Is your feature request related to a problem? Please describe.**
Currently, course thumbnails found in the course catalog and "My Courses" do not include the number of lessons as you can see [here](https://share.getcloudapp.com/9ZuK7wKg) and [here](https://share.getcloudapp.com/OAuo5ple).

**Describe the solution you'd like**
Course creators should have the option to show the number of lessons on each course's thumbnail, as you can see [here](https://share.getcloudapp.com/E0uXkDX0) and [here](https://share.getcloudapp.com/WnumOLZo).

**Describe alternatives you've considered**
At the moment, users can use [this plugin](https://drive.google.com/file/d/13WzGbrcwiuvNkmQKAtSaLUdVNISXSJmC/view?usp=sharing).

**Comment by actuallyakash** [comment]
If we're doing this for "My Courses" and "Course Catalog", I think we can also show the number of lessons inside the course under the difficulty paragraph. (Refer to Screenshot)
![image](https://github.com/gocodebox/lifterlms/assets/18614782/764c4c94-4629-4d51-a832-ca657ce1a02b)

Let me know your thoughts.

cc: @eri-trabiccolo

**Comment by eri-trabiccolo** [comment]
Not against, yeah go for it, not crucial though.
Also https://github.com/gocodebox/lifterlms/pull/2439 would require an update of the labs plugin so to allow users to disable that easily.

@actuallyakash
please don't start working on the block and on the labs yet, we need to define what should be the default behavior (show this new info by default or not?) both in catalogs and single courses. For the single courses we need to "unify" the behavior among the ones built with the classic editor and the one built with the block editor.
The idea would be to not show the lesson count by default on single courses, but show them on catalogs.
