### ISSUE TITLE
Course Builder button URL goes to 404: ignores website intalled subdirectory

### ISSUE THREAD

**Issue by OvidiuMaciuc** [gocodebox/lifterlms#2461]
On WordPress 6.2.2, Theme: Astra 4.1.5, LifterLMS 7.2.0
and PHP 7.4.33
The website is not installed on the main directory www.example.com
Instead, WP is installed on a subdirectory: www.example.com/today/

### Reproduction Steps

Login as admin. Go to any course page. Click Edit Course from top bar.
Click on the top button Launch Course Builder -> error.
On the sidebar: Course > Summary > click button Launch Course Builder -> same error.

### Expected Behavior
Open LifterLMS Course Builder page.

[website-name]/[subdirectory]/wp-admin/admin.php?page=llms-course-builder&course_id=1071

### Actual Behavior
Page not found when the button is clicked.

[website-name]/wp-admin/admin.php?page=llms-course-builder&course_id=1071

### Error Messages / Logs
404 Page not found

This should be a quick fix.

**Comment by eri-trabiccolo** [comment]
Hey @OvidiuMaciuc Thanks for reporting this, we're investigating into this issue!

**Comment by OvidiuMaciuc** [comment]
Quick response @eri-trabiccolo !
I can confirm the issue is fixed.

**Comment by eri-trabiccolo** [comment]
Thanks for the feedback!
