### ISSUE TITLE
Inline jQuery code should be moved at the footer to ensure that the code will run if jQuery is loaded after footer content.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2470]
### Reproduction Steps
This issue happens when theme load jQuery after the footer content, instead of `<head>`. An error like `$(...) is not a function` will be seen. This happens because we have **inline code** enclosed in `(functioin($){})(jQuery)` is running before jQuery is even loaded. As an example, consider using the Divi theme and then creating a LifterLMS quiz **with clarifications for each question**. Once you finish answering the quiz, the clarifications will not show up (you won't be able to toggle them) for your wrong answers because of the  `$(...) is not a function` error.

No configuration of the Divi theme is needed to replicate the issue, just leave the default settings for Divi as is without touching or changing them. However, fix the issue you can go to `WordPress Dashboard > Divi > Theme Options > General > Performance` and set `Defer jQuery And jQuery Migrate` and to `Disabled`. To bring the issue back again, just set it back to 'Enabled' (default).

### Expected Behavior
jQuery code should always run after jQuery is loaded.

### Actual Behavior
jQuery code should always runs before jQuery is loaded.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
Ok so this has an alternative.
I see this as an enhancement, thanks!
