### ISSUE TITLE
Line Height Issues

### ISSUE THREAD

**Issue by edent** [gocodebox/lifterlms#248]
I think there is an issue with how you've defined the line height in CSS.

Both
- https://github.com/gocodebox/lifterlms/blob/c68803c9c78e4d9a4902d542735e5f3dbb82cdfe/assets/css/admin.css#L2376
- https://github.com/gocodebox/lifterlms/blob/329ac490a03a1030cd317605f5fd2f94d27cf063/_private/scss/admin/modules/_llms-order-note.scss#L24

Say `line-hieght: 1.5l`

There are two issues here.
- It should be spelled `line-height`
- The `l` is not needed. 

See the specification for [CSS `line-height`](https://developer.mozilla.org/en/docs/Web/CSS/line-height) for more details.

**Comment by thomasplevy** [comment]
@edent thanks, these are typos (i am stupid from time to time)

I see your pr and I'll merge it early next week

take care
