### ISSUE TITLE
Add inputs edit user profile

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#252]
Hi LifterLMS Team,
I have a strange problem when I am trying to add few fields inside the edit profile page, the one located in `myaccount/form-edit-account.php`.

Since I would like to let my users add several information, like their social profiles and a description about themselves, I have run some tests with the latter but I've noticed that the new information are not updated.

I understand that is a form and LifterLMS needs to know which information will need to update in the database, but I am wondering... There is a way to tell the script to update also the bio and all the other information that I want to put inside? 

Because I do not want to expose my users to the backend of WordPress in order to do so.

*Update*
I thought that with a block of code it should be simplier to understand why I am seeing it as a strange behavior. I've created a new `<div>` to put the new informations and the description is inside this block:

```
<p class="form-textarea">
	<label for="description"><?php _e('Biographical Information', 'profile') ?></label>
	<textarea name="description" id="description" rows="3" cols="50"><?php the_author_meta( 'description', $current_user->ID ); ?></textarea>
</p>
```

As you can see I am usign the `name` as the same in the backend profile page, do you use a custom functions or you loop through all the $_POST values?

Thank you in advance for the future help and keep up with your amazing work!
Andrea

**Comment by AndreaBarghigiani** [comment]
@thomasplevy sorry il I push it but there are any news? Even a suggestion is welcome and if I solve the issue I can even send you a PR.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani this is currenty working off old apis and I missed updating this screen...

Added #260 to track the update to this screen

in the meantime you'll want to hook into the forum submission via this action: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.frontend.forms.php#L378

I'll make sure #260 is backwards compatible somehow

**Comment by Mte90** [comment]
As I can see there is the hook for the registration but not for the profile itself.
In the docs https://lifterlms.com/docs/how-to-add-custom-fields-to-lifterlms-registration/ is mentioned only registration but it's a problem because if I want to change or edit it is not possible.

**Comment by Mte90** [comment]
Ok I found the hook for add new profile fields `lifterlms_edit_account_form_end`

**Comment by Mte90** [comment]
And also the hook for save the data `lifterlms_save_account_details`

**Comment by thomasplevy** [comment]
see version 3.7.0 (pending) for API updates

**Comment by Mte90** [comment]
@thomasplevy as I can see the hook `lifterlms_save_account_details` not exist anymore so there is an alternative?
Usually the removing of hook is documented somewhere with alternatives, I am missing something?

**Comment by thomasplevy** [comment]
@Mte90 you're correct, I messed up and removed a hook by accident...

I've been trying to get this functionality ported over to our 3.x APIs for a really long time (this was all on my task list to get done in alignment with 3.x release -- that was 8 months ago -- and I got really tired of dealing with 2 sets of APIs because it made it damn near impossible to explain to even competent developers how it all works...

I don't have the capacity to write out a full tutorial today but all the functionality for updating accounts creating and updating users in LifterLMS now runs through the LLMS_Person_Handler class

If you can adjust your customizations to fire off a filter please use this function: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.person.handler.php#L707

if you need me to add that deprecated filter back in please open a new ticket (or submit a PR to add it back in somewhere that makes sense).

Yes, you're right I messed up here... I don't have any good excuses. I maintain too many codebases and I'm not a very good developer I guess...

**Comment by Mte90** [comment]
After my test I think that this class is not involved on the shortcode generated `lifterlms_my_account` on saving of the fields. The `update` method is not involved on saving of that page generated ;-/

**Comment by thomasplevy** [comment]
@Mte90 

```
add_action( 'lifterlms_before_user_update', function( $data, $screen ) {

	var_dump( $data, $screen ); die;

}, 10, 2 );
```

Does that not kill your update on forum submission?

Have you modified or overriden the edit account template?

**Comment by Mte90** [comment]
no :-/, i tried also altering the plugin code for update.
As I can see also that shortcode generate a only 3 fields but on the docs of that method they are not mentioned.

**Comment by thomasplevy** [comment]
@Mte90 the shortcode and this function are two different things -- the account shortcode doesn't handle the update but, instead, generates the form (as well as all the other account endpoints)

Can you give me a link where I can take a look at your site here? Post a system report? give me something. I'm happy to help debug this but everything is working from my perspective. It sounds to me like theres some amount of customization going awry here and I realize I removed a hook but I can't figure out what you're actually doing or what's going wrong on your end.

Thanks,

**Comment by thomasplevy** [comment]
actually @Mte90 let's open a new thread and track this as a new issue, I need some more information and recreation steps -- please head to https://github.com/gocodebox/lifterlms/issues/new and then follow the template -- provide me with as much of the info as possible

thanks

**Comment by Mte90** [comment]
My code is on https://pastebin.com/jbMwESfX and add few fields in the edit page of the account printed with the shortcode of lifter.
So I can create the profiles fields but they are actually not saved.

With your snippet the code is not executed :-/

**Comment by thomasplevy** [comment]
@Mte90 this is code adding checkout fields, not account edit fields. Please look to this tutorial: https://lifterlms.com/docs/add-custom-fields-lifterlms-checkout-open-registration/

**Comment by Mte90** [comment]
My fault the first part was another code, this is the right one https://pastebin.com/vajYA06N

**Comment by thomasplevy** [comment]
@Mte90,

How're you attaching the `lifterlms_before_user_update` hook? What's that code look like? It could be an issue with when you're attaching the hook (possibly too early or too late). Try a different priority maybe?

**Comment by thomasplevy** [comment]
@Mte90 maybe this gist will help: https://gist.github.com/thomasplevy/9df0fa48ea95c39cad2c078efb69e7d2

This is an example of adding a custom checkbox to all user reg/update fields (and saving it) using hooks and filters only.

This is real working code from a forthcoming official LifterLMS Add-On I'm working on

Maybe it'll help?

**Comment by Mte90** [comment]
I tried that code on my website in a plugin of one file but in the edit-account page printed with this shortcode there are no fields of that file.

**Comment by thomasplevy** [comment]
@Mte90 are you on the latest version of LifterLMS? Are you overriding our default templates?

**Comment by Mte90** [comment]
Yes, the 3.7.6.
AS I can see here the shortcode use different hooks: https://github.com/gocodebox/lifterlms/blob/0b12fe452d85b3a85714f568c4961c565f2f1b3b/includes/shortcodes/class.llms.shortcode.my.account.php#L41

So for print the fields I use `lifterlms_edit_account_form_end` and not the hook suggested, infact https://github.com/gocodebox/lifterlms/blob/584f5a1af652a0b12cbb4b07ce17c9089c6d2236/templates/myaccount/form-edit-account.php#L29 use different hooks to print the fields and inside use `lifterlms_get_person_fields` but is not printing.

This is my plugin code https://pastebin.com/6zUCDigQ, add some fields on all the profile editing or registration form, save it and show in the order box.

**Comment by thomasplevy** [comment]
@Mte90 the only issue I see here is that you're trying to save data using hooks that don't exist or are not designed to save data... the example I provided will work!

It outputs all the fields in the places you're expecting but it's not saving anything.

If you're not seeing your fields show up it's probably because you've overridden a template that's changed. Are you certain you're not overwriting any templates?

**Comment by thomasplevy** [comment]
FYI, I loaded your plugin up on my test site and removed the "die()" statement and the fields all output on checkout, reg, and update account.... Maybe you have a custom theme which is overriding templates? I've seen this happen where devs simply drop the entire templates folder into their theme and don't think they're overriding but they actually are.

**Comment by Mte90** [comment]
You was right!
My collegue added templates in the theme without alert me -.-'
