### ISSUE TITLE
Cloned Courses Enrollment and Open Message Shortcodes Are Not Replacing Origin Info ID with new info ID

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms#2520]
### Reproduction Steps

+ Clone or "Cohort Clone" any course with course enrollment and open start and end dates
![Edit_Course_“Fall_2023_Semester”_‹_A_LifterLMS_Sandbox_—_WordPress](https://github.com/gocodebox/lifterlms/assets/12163552/cf7269ae-3a87-4705-9390-f28355309e7e)

+ Notice how the new clone open or enrollment message does not display the dates

![Fall_2023_Semester_–_A_LifterLMS_Sandbox](https://github.com/gocodebox/lifterlms/assets/12163552/194f331d-0b43-4ab5-87c3-5c496437fc77)

### Expected Behavior

+ The cloned course would display the correct enrollment or open message with the dates in the restriction settings

### Actual Behavior

The new clone open or enrollment message does not display the dates from the settings. 

I believe the problem is the message shortcode references an id from the origin course instead of it's dates info id: 

This course closed on [lifterlms_course_info id="177" key="end_date"].

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Support
-------------------------------------------


WordPress
-------------------------------------------

Home Url: https://course-cohorts.myliftersite.com
Site Url: https://course-cohorts.myliftersite.com
Login Url: https://course-cohorts.myliftersite.com/wp-login.php
Version: 6.3.1
Debug Mode: Yes
Debug Log: Yes
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.4.0-beta.1
Db Version: 7.4.0-beta.1
Course Catalog: Course Catalog (#17) [https://course-cohorts.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#18) [https://course-cohorts.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#20) [https://course-cohorts.myliftersite.com/dashboard/]
Checkout Page: Purchase (#19) [https://course-cohorts.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.42
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.30
Software: Apache/2.4.57 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: Sky Pilot
Version: 1.3.0
Themeuri: https://lifterlms.com
Authoruri: https://lifterlms.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 7.4.0-beta.1
LifterLMS Course Cohorts: 1.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS Course Cohorts: Yes


Template Overrides
-------------------------------------------

loop/content.php (ver: 3.14.0): /srv/users/manager/apps/course-cohorts/public/wp-content/themes/sky-pilot/lifterlms/ (ver: 1.0.0)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ x] On a staging site
+ [ ] On a production website
+ [ x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@chrisbadgett 
Can you check the original course has the correct id in those shortcodes?
I feel they have the wrong ids there because of an old bug. If I am correct, fixing the id in the original shortcodes (which must match the original course) would fix the issue.

**Comment by chrisbadgett** [comment]
You are correct, if I start with a brand new course with restriction dates, it works perfectly in the original. And the cohort clone works perfectly as well with the restriction message with the new dates I put in the cohort wizard.

I also tested creating a new cohort from the previous cohort and it works as expected.

So as long as the original shortcode IDs are correct, it works as expected through multiple clones.

**Comment by eri-trabiccolo** [comment]
Thanks for the feedback.
Closing this, but feel free to re-open it if you think.
