### ISSUE TITLE
Strings in libraries/lifterlms-blocks/assets/js/llms-blocks.js do not translate.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2525]
### Reproduction Steps

1. Install and activate `Loco Translate`.
2. Go to `WordPress Dashboard > Loco Translate > Plugins > LifterLMS > New Language`. Set `Choose a language: > WordPress language:` to `English (United States)`. And set `Choose a location:` to `Custom`.
3. Translate "**Courses**" (`Admin menu name`), to "**My Courses**". This works as you can see in [this video](https://share.zight.com/04udkdg7).
4. Now, translate ""**Course Information Options**" to "**My Course Information Options Test**". This does not work, as you can see in [this video](https://share.zight.com/Z4upzpqY).

### Expected Behavior
""**Course Information Options**" must be translatable, as well as other strings in `libraries/lifterlms-blocks/assets/js/llms-blocks.js` (_e.g._, `Display Estimated Time`, `Display Difficulty`, `Display Tracks`, _etc_)..

### Actual Behavior
""**Course Information Options**" did not translate. Other strings in `libraries/lifterlms-blocks/assets/js/llms-blocks.js` also did not translate (_e.g._, `Display Estimated Time`, `Display Difficulty`, `Display Tracks`, _etc_).

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment]
@dominiquemariano thanks for reporting.
I can reproduce, gonna look into this when looking into the other language issues!

**Comment by brianhogg** [comment]
Removing the check for file existence seems to fix the translation string loading: https://github.com/gocodebox/lifterlms/pull/2593/commits/c35516effd34695bc7865b41c26cf43e5c0b9049 

In Loco Translate, the existing translation doesn't seem to be showing for me (ie. `es_ES`), but if I put a translation in and save, it now shows in the editor along with already translated strings:

<img width="1055" alt="Captura de pantalla 2024-02-16 a las 5 00 16 p  m" src="https://github.com/gocodebox/lifterlms/assets/627497/590dde24-c5e4-4b87-a2d6-859eb5e97869">

<img width="1491" alt="Captura de pantalla 2024-02-16 a las 4 59 57 p  m" src="https://github.com/gocodebox/lifterlms/assets/627497/edefb095-ca76-4bb6-9afa-bacdbd1d352c">

As a note to self, the Course Information Options block is disabled when trying to add it to an existing course.

We also may not need to try loading in all the directory options. From the [Block Editor documentation](https://developer.wordpress.org/block-editor/how-to-guides/internationalization/), it seems loading the plugin directory should be enough.
