### ISSUE TITLE
Analytics JS errors on Safari

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#255]
potentially also mobile safari (need to confirm)

<img width="1050" alt="screen shot 2016-11-04 at 7 12 29 pm" src="https://cloud.githubusercontent.com/assets/1290739/20026582/591f9584-a2ba-11e6-8dbf-f5d851120c1a.png">

**Comment by leftlane** [comment]
May not be isolated to Safari. Analytics also don't load on Chrome for iOS: https://www.dropbox.com/s/remecw2de75fp3a/File%20Nov%2004%2C%208%2023%2020%20PM.png?dl=0

**Comment by thomasplevy** [comment]
@leftlane 3.1.4 is available and fixes this issue

**Comment by leftlane** [comment]
Sadly, I still get nothing but the “loading...” spinner. 

Using LLMS 3.1.5 and Safari 10.0.2, Safari Technology Preview 10.1, and mobile Safari in iOS 10.2.

Safari error: 
<img width="987" alt="screen shot 2016-11-11 at 11 41 55 am" src="https://cloud.githubusercontent.com/assets/1584080/20224492/475f86de-a804-11e6-8882-2665b71558d7.png">

**Comment by thomasplevy** [comment]
@leftlane cleared your local browser caches?

**Comment by leftlane** [comment]
Doh. My bad. Force-reloaded, but didn't empty the cache. After doing so, analytics are loading now, so I'm getting my first look at them.

I notice that no legacy data is included in the analytics. No sales data from prior to the update. Is that correct?

Also, the filters don't appear to be working. When I filter by either of our memberships, I only see the # of sales. All the other tiles are zero, which is incorrect.

**Comment by thomasplevy** [comment]
see #254 

could you please open new issues if you're seeing other issues related to this screen, thanks

**Comment by thomasplevy** [comment]
@leftlane before reporting anything new checkout 3.1.6 (#254 is taking longer than I'd hoped but I had a typo that may have been causing the other notes above)
