### ISSUE TITLE
How to get parent course id of a lesson

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#259]
### 1. Reproduction Steps

Hi LifterLMS team,
I am working on the customization of a theme for my LMS project. I would like to have the name and the link of the parent course inside of a single page lesson. In order to do so I've created the `single-lesson.php` page template since I am using Genesis and I would like to use their hooks to add this kind of information.

Inside it I've added the following code:
```
$lesson = new LLMS_Lesson( $post->ID );
$parent_course_link = get_permalink( $lesson->get_parent_course() );
$parent_course_tit = get_the_title( $lesson->get_parent_course() );
```

### 2. Expected Behavior
Get the url and title of the parent course.

### 3. Actual Behavior
I get the name and the url of the page I am at. 

I've also tried to use the `get_course()` method found in `model.llms.lesson.php` but this give me a `false` value and I am not able to move forward.

### 4. Error Messages / Logs
I have no error messages but simply a unexpected behaviour. I am writing to you because I found in the source code the following @todo: *refactor to use new api after a migration is written*. Are you working on a new API?

### 5. System Report
Wordpress
-------------------------------------------

Home Url: http://newskam.dev
Site Url: http://newskam.dev
Version: 4.6.1
Debug Mode: Yes
Locale: it_IT
Multisite: No
Page For Posts: Blog (#87)
Page On Front: Home (#85)
Permalink Structure: /%year%/%monthnum%/%postname%/
Show On Front: page
Wp Cron: Yes

Settings
-------------------------------------------

Version: 3.1.5
Course Catalog: Corsi (#4)
Course Catalog Per Page: 10
Course Catalog Sorting: menu_order
Membership Catalog: Catalogo Membership (#5)
Membership Catalog Per Page: 10
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Student Dashboard: Bacheca (#7)
Courses Endpoint: visualizza-corsi
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: hidden
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Checkout Page: Fai il tuo acquisto e migliora le tue conoscenze (#6)
Confirmation Endpoint: conferma-pagamento
Force Ssl Checkout: no
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: admin@localhost.dev
Email From Name: newskam
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no

Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Enabled
PayPal Logging: yes
PayPal Order: 1
Manual: Disabled
Manual Logging: no
Manual Order: 1

Server
-------------------------------------------

Mysql Version: 5.5.44
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 1 GB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 5.5.9-1ubuntu4.11
Software: nginx/1.9.3
Wp Memory Limit: 40M

Theme
-------------------------------------------

Name: skillsAndMore '17
Version: 
Themeuri: 
Authoruri: 
Template: genesis
Child Theme: Yes
Llms Support: No

Plugins
-------------------------------------------

bbPress: 2.5.11
bbPress Genesis Extend: 1.1.1
Genesis Simple Share: 1.0.9
Glossary: 1.1.1
LifterLMS: 3.1.5
LifterLMS PayPal Gateway: 1.0.0-beta.1
Simply Show Hooks: 1.2.1
Skillsandmore Super Plugin: 1.0.0
WordPress Importer: 0.6.3
WordPress Rainbow Hilite: 1.0.6

Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: No

**Comment by AndreaBarghigiani** [comment]
My bad. I was sure to have called the `$post` object before to create the LLMS_Lesson object. Solved it!

**Comment by widevents** [comment]
Hi Andrea, I need to get the id of the course to which a lesson belongs to pass a value of an ACF custom field through a parameter. How do you think I could get that ID? I have read your article but my level is still not very high and I would appreciate it if you could help me with this problem by writing down the code.

Thank you!!

**Comment by thomasplevy** [comment]
@widevents,

If you're on a lesson page:

```php
$lesson = llms_get_post( get_the_ID() );
if ( $lesson ) {
   $course_id = $lesson-> get_parent_course();
}
```

If you need more help hop into the `#developers` channel at lifterlms.com/slack and we can look at your code more specifically to help you out, GitHub is best used for issues and bug reports, not help with custom code
