### ISSUE TITLE
State and country dropdowns are not in sync when a page using the [lifterslms_my_account] shortcode is not set as the official student dashboard page.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2616]
### Reproduction Steps

1. Install a fresh copy of WordPress and LifterLMS.
2. Make sure that you have completed setting up LifterLMS through the setup wizard. This will ensure that you have the "Dashboard" page.
3. Use themes like the Twenty Twenty Four theme, Sky Pilot, Astra, or Kadence.
4. Create a page named "My Student Account" and use the `[lifterslms_my_account]` shortcode on it.
5. View both the "Dashboard" page and  the "My Student Account" page on the front-end as a **non-logged in site visitor**.

### Expected Behavior
Both the "Dashboard" page and  the "My Student Account" page should display what you see in [this screenshot](https://share.zight.com/d5u2QeOo).

### Actual Behavior
Only the "Dashboard" page displays what you see in this screenshot. The "My Student Account" page that uses the displays [this screenshot](https://share.zight.com/X6uXGD8b).

### Why this happens.
The select2 JS and CSS files from LifterLMS are not being loaded when the page using the the `[lifterslms_my_account]` shortcode is also not set as the page in `WordPress Dashboard > LifterLMS > Settings > Accounts > Student Dashboard > Dashboard Page`.

**Comment by brianhogg** [comment]
This is expected behaviour. `[lifterlms_my_account]` is only designed to be used on the page marked as the Dashboard page in the LifterLMS settings, to avoid us needing to load our JS/CSS on every page or do a scan of the content on every page load.
