### ISSUE TITLE
lifterlms.js uses unload event, which is scheduled to be removed from chrome.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2620]
### Reproduction Steps

1. Create a new site with a fresh install of LifterLMS.
2. Analyze that site using [pagespeed.web.dev](https://pagespeed.web.dev/)
3. In the results page, navigate down to `General > Uses deprecated APIs`

### Expected Behavior
Shouldn't be using deprecated APIs that are scheduled to be removed from Chrome.

### Actual Behavior
1 deprecation warning for UnloadHandler, as you can see in [this screenshot](https://share.zight.com/YEuJ9gD4). See https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by brianhogg** [comment]
Looks like this might be removed from Chrome by the end of Q1 2025. May need to prioritize this a little higher.

**Comment by brianhogg** [comment]
https://developer.chrome.com/docs/web-platform/deprecating-unload

This appears to be related to the opt-in tracking script.
