### ISSUE TITLE
Duplicate query when using the [lifterlms_courses mine="enrolled"] shortcode.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2626]
### Reproduction Steps

1. Create a page. Call it `My Courses`.
2. Add this shortcode to that page:` [lifterlms_courses order="ASC" orderby="title" posts_per_page="9" mine="enrolled"] `.
3. Install the Query Monitor plugin.
4. View the `My Courses` page on the front-end.
5. From the admin toolbar, click on the Query Monitor results.
6. Navigate to `Query Monitor > Database Queries > Duplicate Queries`.

### Expected Behavior
You should not see a report for `SELECT SQL_CALC_FOUND_ROWS DISTINCT upm.post_id AS id`.

### Actual Behavior
You will see a report report for `SELECT SQL_CALC_FOUND_ROWS DISTINCT upm.post_id AS id`, as you can see in [this screenshot](https://share.zight.com/jkup2OJz).

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by brianhogg** [comment]
Closing as there's no functionality issues nor significant slowdown, and may not be something that can be eliminated without some kind of global caching system (which is likely beyond the scope of LifterLMS).

**Comment by dominiquemariano** [comment]
@brianhogg In some servers (see HS-241049) the query execution time due to the query in [this screenshot](https://share.zight.com/jkup2OJz) can reach average execution times above 4 seconds (see HS-241049). That is a least 8 seconds if the query gets called twice. So the issue here is not that is is fast on the server I used in [my screenshot](https://share.zight.com/jkup2OJz). The issue is also not that the customer's server is slow. 

The issue is that it **makes the situation worse in already challenged servers** that we are calling the query twice.
