### ISSUE TITLE
LifterLMS WP Plugin is conflicting with WP media - had to deactivate to restore site

### ISSUE THREAD

**Issue by lsweeney-dg** [gocodebox/lifterlms#2713]
### Reproduction Steps

Install LifterLMS plugin on Wordpress.com site. 
Wait about 1 minute.
Go to Media in WP admin - and none of it will be visible or loading.
Check live site - no images are loading.
Deactivate LifterLMS plugin.
Check WP admin Media and live site again - all media is back working / loading again as expected.

Wordpress.com - WP Business Plan
Assembler Theme
Gutenberg 18.8.0 (as managed by Wordpress)
LifterLMS plugin version the problem is on is 7.7.0. (Same version others on wordpress.org reported on)

I have reproduced on another WP site. Tried clearing cache on the sites. Tried switching themes on one site, it didn't resolve it. Theme doesn't appear related but the theme in use is Assembler.

Could not find any information about this across LifterLMS resources. Did see a notification about media and nginx in the LifterLMS dashboard but it directs to a 404 page on LifterLMS so i'm not sure if thats related.

Could not explore the LifterLMS settings much more as when its activated the site is broken, so have left it deactivated for now.

### Expected Behavior

LifterLMS plugin should not be conflicting with Wordpress media. Media should continue to work and load as expected.

### Actual Behavior

As soon as LifterLMS plugin is activated, all Wordpress media breaks so the site breaks. As soon as it is deactivated, media is restored.
2 other users have reported on wordpress.org too. One was told by Wordpress support they also found the issue was caused by LifterLMS and they disabled it, and referred them to LifterLMS too.

### Error Messages / Logs

Media disappears. Didn't notice any obvious errors.

### System and Environment Information

<details>
<summary>System Report</summary>

Wordpress.com - Assembler Theme - Business Plan - Gutenberg 18.8.0 (as managed by Wordpress)
LifterLMS plugin version the problem is on is 7.7.0. (Same version others reported on)

</details>

This issue has be recreated:
With only LifterLMS and a default theme (assembler)

### Browser, Device, and Operating System Information

N/A

**Comment by ideadude** [comment]
Thanks for the heads up.

Rolling back for now will fix the issue.

We will test on wp .com and update here when we have a fix.

**Comment by lsweeney-dg** [comment]
> Thanks for the heads up.
> 
> Rolling back for now will fix the issue.
> 
> We will test on wp .com and update here when we have a fix.

Hi - thanks so much for replying so quickly, i should have come to github first :) 

... unfortunately on wordpress.com (not wordpress.org) i don't see any way to roll back plugins to a previous version, that's why i didn't try it.  There is no visible options on the plugins page or inside the LifterLMS dashboard or settings. 

~~Wordpress.com users would have to go into the plugin files (Tools -> Plugin File Editor) and copy and paste each file from the Github repository's last version into each of the plugin files on wordpress.com... it would take a several hours to do and might cause an issue that i'm not aware of. On balance it's safer to just wait.~~

*Update - there is a plugin called WP Rollback that i didn't have on my new site, thats why i couldn't roll back. Have resintalled it now and can roll back.
