### ISSUE TITLE
Restricting pages by membership access working incorrectly

### ISSUE THREAD

**Issue by brianhogg** [gocodebox/lifterlms#2714]
### Reproduction Steps
1. Create a page.
2. On the page, use the Membership Access → Restrict this page → Enabled
3. Now add a membership. → After adding a membership,
4. Add a User to a membership, make sure you add the user to the membership that has already been added to restrict this page.
5. View the page. → You will be able to see the page.
6. Add another membership on the page(restrict this page) → Visit the page → You will encounter a warning,  "You must belong to one of the following memberships to access this content." Even if you already have one of the memberships.
7. After that, when you decide to remove the membership from the list and try to add the membership that you've already added, you will encounter the warning message again even if you belonged to that membership
8. After removing the membership from the restrict page, you will notice that an automatically added membership will be displayed as None. Even though there is no membership listed on the restrict page, you will encounter the same warning. [ The glitch occurred. ]

Screen Recording:
1. https://share.zight.com/jku02vJ4
2. https://share.zight.com/d5ujLNDX

### Expected Behavior

It should allow the user to see the page even if they're only added to one specific membership.

### Actual Behavior

The user was unable to access the page when there are multiple memberships and encounter a glitches when trying to edit or adding and removing the membership listed on the restrict this page member access.

### This issue has been recreated:
+ [x] Locally
+ [x] On a production website

### Related User Information

Ticket link:

HS-245705
HS-245718

**Comment by brianhogg** [comment]
I’m not able to replicate this. I added one membership as a restriction, then two, then three memberships. I created a free access plan on the one membership, signed up as a new student via that membership access plan, and I can view the restricted page.

[In this video](https://share.zight.com/d5ujLNDX) at 0:39 it only shows two of the three selected memberships that you need to be a part of to view the content, and I’m not sure why. Maybe the page settings didn’t finish saving? I’m not sure.

I can’t get the “None” to appear either on the wordpress.com or on the myliftersite hosting.

Admin or someone who can edit the page should probably always have access otherwise you do get a "restricted" message in the page editor which seems wrong.

**Comment by alextonio12** [comment]
Hi @brianhogg  have you tried removing the selected membership on the Restrict Page Access and then adding it again? It might make a difference. We receive many tickets related to page restrictions or member access issues.

**Comment by alextonio12** [comment]
Yesterday, I asked the customer to downgrade their LifterLMS plugin to version 7.6.3, and I received a response today that the issue was fixed on the 'Restrict this page' feature.

**Comment by brianhogg** [comment]
The clear all "X" seems to be causing the problem. When I click on it instead of the “X” beside the membership I get the “None” option and sometimes a membership of the page ID.

<img width="532" alt="Captura_de_pantalla_2024-08-12_a_las_5_46_29_a_ m_" src="https://github.com/user-attachments/assets/a01200d3-46bb-4a1d-b742-b76148727831">

The workaround is to not use that "X". If it was used, you may need to clear out all of the memberships, turn off restrict this page, save, refresh, then turn restrict back on and re-select the membership(s) you’d like.

**Comment by brianhogg** [comment]
The error happens if there is already invalid data in the "Memberships" array. A check is done to see if the student is enrolled in (say) an ID of `0` which always fails and restricts access to the page. This will filter that data out if found.

We might also want to check for membership IDs that don't exist, but keeping as-is for now. We likely don't want to suddenly give public access to content if a membership is deleted (for example) if someone forgets to update the membership that restricts it.
