### ISSUE TITLE
Add class to the current lesson in the Course Syllabus block

### ISSUE THREAD

**Issue by brianhogg** [gocodebox/lifterlms#2777]
**Is your feature request related to a problem? Please describe.**
In older themes, using the Course Syllabus widget would add a `current-lesson` class on the current lesson. This lets the lesson be styled (ie. bolded) to show the student what lesson they are on. In the newer Course Syllabus block however this class (or a similar class) is not added.

**Describe the solution you'd like**
Add a CSS class on the div for the lesson.

**Describe alternatives you've considered**
There is a `llms_get_preview_classes` filter we could possibly use, which only passes in the `$classes` already generated currently. Or, creating a custom version of the `lesson-preview.php` template.

**Comment by brianhogg** [comment]
For some reason the global `$post` is the Course rather than the Lesson when the course syllabus is generating, so you can't do a `if ( get_the_ID() === $this->get( 'id' ) )` within the `LLMS_Lesson::get_preview_classes` method.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
