### ISSUE TITLE
Quiz Resume

### ISSUE THREAD

**Issue by brianhogg** [gocodebox/lifterlms#2783]
* Ability to resume a new attempt on a quiz.
* Save question value when Previous Question is used.
* Resumes quiz on the question they exited on.
* Refreshing the page prompts about unsaved changes, since the current question may not have been saved before.
* Defaults to one day for resuming. See `llms_quiz_attempt_resume_time_period` filter to modify.

![CleanShot 2024-10-24 at 3  05 19@2x](https://github.com/user-attachments/assets/1c2d8ed2-3e64-49c8-a9bc-eb1ed489715e)
![CleanShot 2024-10-24 at 3  05 11@2x](https://github.com/user-attachments/assets/01a20a21-b35e-44f7-a68a-2dc77d0e86a4)
![CleanShot 2024-10-24 at 3  02 06@2x](https://github.com/user-attachments/assets/b23bc03b-c5d0-49cd-af6e-088ede4fec68)

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
