### ISSUE TITLE
Button says "Preview" Lesson, but "Previous" Lesson is meant

### ISSUE THREAD

**Issue by konradsroka** [gocodebox/lifterlms#286]
### 1. Reproduction Steps

- Go into a lesson 
- at the end there is two button links to next lesson or previous lesson 
- description to go to previous lesson says "PREVIEW Lesson" 

See screenshot here 
![image](https://cloud.githubusercontent.com/assets/636523/22150154/47b26d90-df63-11e6-8e16-9b113601d810.png) 

cheers

**Comment by thomasplevy** [comment]
@konradsroka according to our template/code and local reproduction it says "Previous"

Have you modified any templates and accidentally overwritten the text here?

Are you loading a translation file that might have mis-translated the string?

Thanks

**Comment by thomasplevy** [comment]
@konradsroka don't go dark on us man!

**Comment by irama** [comment]
Hi @thomasplevy I get it too. Using LocoTranslate I was able to fix it. It's possible it only appears in the Australian English translation (that's the one I use, I haven't checked any others).

**Comment by thomasplevy** [comment]
@irama it looks like both AU and NZ tranlations on glotpress say "Preview Lesson"

Just submitted translation suggestions for the locales: https://translate.wordpress.org/projects/wp-plugins/lifterlms

Thanks for the hint
