### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by ChristianRabenstein** [gocodebox/lifterlms#287]
Hello Thomas : )

I have installed your new pre release 3.3.0-rc1, but an error occurred while trying to activate the plugin. Maybe this information helps you to avoid possible problems for the final release.

Tested on a current WordPress 4.7.1 installation, Twenty Seventeen theme, without active plugins.

Error:
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected 'clone' (T_CLONE), expecting identifier (T_STRING) in /wp-content/plugins/lifterlms-3.3.0-rc1/includes/abstracts/abstract.llms.post.model.php on line 271 

Best
Christian

**Comment by thomasplevy** [comment]
@ChristianRabenstein 

Thanks for running an early and unstable version 👍 

Do me a favor and give me a bit of additional information (as per issue submission guidelines at: https://github.com/gocodebox/lifterlms/blob/master/.github/issue_template.md

What I really want is your PHP version you're running.

Thanks,

**Comment by thomasplevy** [comment]
i still want to know but apparently `clone` as a class method conflicts with php's magic `__clone` I was unaware...

Thanks for finding this for me

**Comment by ChristianRabenstein** [comment]
I have sent you an email with a link to my php data, hope you got it.
