### ISSUE TITLE
Fatal error due to model.llms.course.php on line 424

### ISSUE THREAD

**Issue by HammyHavoc** [gocodebox/lifterlms#300]
Hi!

Earlier today I went to login to /wp-admin/ and was met with a white screen, I'm assuming something broke in an update either with Lifter or elsewhere.

I disabled the plugin manually via SFTP, regained use of /wp-admin/ and reinstalled with the latest 3.4.5 build from your website, yet can't reactivate the plugin as I'm met with this error:

`Fatal error: Can't use method return value in write context in /var/www/vhosts/site/httpdocs/wp-content/plugins/lifterlms/includes/models/model.llms.course.php on line 424`

Any light you could shed on this would be hugely appreciated. :- )

All the best,
Hammy

**Comment by HammyHavoc** [comment]
Error isn't present on 3.3.0, so something seems to have broken since then.

**Comment by thomasplevy** [comment]
@HammyHavoc LifterLMS supports PHP 5.6 and higher, this error is evidence of PHP 5.5 or lower on your server.

You can see our system requirements at https://lifterlms.com/docs/minimum-system-requirements-lifterlms/

Please update your server to a supported version of PHP and enjoy both increased performance and security (5.5 and lower are at their EOL -- http://php.net/eol.php).

Take care
