### ISSUE TITLE
Unable to Activate Plugin, Fatal Error on model.llms.course.php

### ISSUE THREAD

**Issue by jayinpr** [gocodebox/lifterlms#307]
I'm able to install the plugin but can't activate it. It gives this error:

Fatal error: Can't use method return value in write context in /var/www/html/inet/wp-content/plugins/lifterlms/includes/models/model.llms.course.php on line 424

Using:
Wordpress: 4.7.3
Theme: Govintranet (https://github.com/helpful/govintranet)

I don't have problems at this moment with any other plugins I'm using on the site.

**Comment by thomasplevy** [comment]
@jayinpr this is evidence that you're running PHP version 5.5 or lower

While WP is endlessly backwards compatible LifterLMS is not!

Please see our system requirements at https://lifterlms.com/docs/minimum-system-requirements-lifterlms/

how to fix: upgrade your server to PHP 5.6 (or 7!)

Hope that helps

**Comment by jayinpr** [comment]
Thanks a lot! I'm running 5.4 but replicated the portal on a dev environment upgrading to php 7.1 and it worked great. I really appreciate your help.

**Comment by thomasplevy** [comment]
@jayinpr great!
