### ISSUE TITLE
mobile app login

### ISSUE THREAD

**Issue by petesavva** [gocodebox/lifterlms#313]
I am building a mobile app that will require user authentication through my lifterlms site. I can't find any documentation regarding API.
Can someone point me in the right direction please?
Thanks.

**Comment by thomasplevy** [comment]
hey @petesavva that's really cool that you're building a mobile app! Unfortunately LifterLMS doesn't currently have a rest API. I'd like to add rest API endpoints related course, lessons, students and so on but I haven't started the development of any of this stuff yet.

However, to be honest, I'm not sure we'll ever add endpoints for managing login via the rest api. The WordPress rest api itself doesn't have login endpoints ([see docs](https://developer.wordpress.org/rest-api/reference/)) and looking at what other plugins (WooCommerce for example) aren't implementing login endpoints either

That said, the WP rest api is really easy to use and extendable, I'd recommend you create a small plugin that adds a login endpoint that you can use for you app, you can then utilize either WP functions like [wp_signon()[(https://codex.wordpress.org/Function_Reference/wp_signon) or LifterLMS functions like [LLMS_Person_Handler::login()](https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.person.handler.php#L546)

Hope that helps!

**Comment by thomasplevy** [comment]
@petesavva any help needed here or can I close this question?
