### ISSUE TITLE
LifterLMS 3.8.0 Alpha/Beta Feedback General

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#317]
Thanks for participating in a pre-release period, your feedback is invaluable!

If you have general feedback about LifterLMS 3.8.0 alpha/beta releases please post them here.

Please include your pre-release version number with your feedback (eg: alpha.1)

If you would like to report a bug in the release please open a [new issue](https://github.com/gocodebox/lifterlms/issues/new) and follow the instructions for leaving reproduction steps and so on.

As always, this is not a place to post general support requests with production versions of LifterLMS or LifterLMS add-ons. Those belong in [tickets](https://lifterlms.com/my-account/my-tickets) or [the forums](https://wordpress.org/support/plugin/lifterlms).

**Comment by wonboyn** [comment]
Hi Thomas,

We use the existing engagements feature to notify students when a new batch of drip feed lessons have become available. This works well - except with courses that have a specified start date as there is no trigger event based on a course start date. Theoretically we could use lesson/section completion but we find that not all students are meticulous about the clicking the button!

Any chance you could expand the range of event triggers with these new notifications to include course start / end dates & even an ability to schedule emails for release on a frequency &/or at specified future date/times?

Thanks again.

Tim

**Comment by thomasplevy** [comment]
@wonboyn thanks for the feedback. We're not going to be adding this as a new notification trigger but we do already have this as a planned feature for engagements (eg: trigger a specific engagement when drip content becomes available).

It does make sense to add this to notifications but -- and this is the reason why we don't currently have the engagement trigger -- we need to to a bit of a hefty refactoring project in order to get drip-related data exposed in a way that makes attaching scheduled events to them simple. Currently the drip data is just dates stored in the database and when a student visits the lesson LifterLMS evaluates whether or not the content is available to them. We need to overhaul this so that lesson drip data is processed in the backend actively. Once we've done that it'll be trivial to add notifications and engagements based off drip availability.

I understand that this is certainly an important feature to you and that this is more than likely an important feature for LifterLMS at a whole but I'd be doing the 3.8 release a disservice by crowbaring yet another major feature into it. That means that I'll have to delay the release due to another significant overhaul. So this one's going to have to remain backlogged for the moment and I appreciate your patience and understanding in the matter.

You can see the feature request [here](https://trello.com/c/2UHFsCa1/150-engagement-trigger-to-send-emails-when-dripped-lessons-become-available) -- notifications will be added to the scope of that request once notifications are publicly available 

Thanks

**Comment by thomasplevy** [comment]
closing feedback
