### ISSUE TITLE
Typo in label on notifications

### ISSUE THREAD

**Issue by wonboyn** [gocodebox/lifterlms#321]
### 1. Reproduction Steps

1) Choose settings > notifications
2) Click on Email link against purchase receipt

![screen shot 2017-04-29 at 12 58 00 pm](https://cloud.githubusercontent.com/assets/8089290/25552388/c9f9c2d8-2cdb-11e7-9e9d-af9d7ff21343.png)

**Comment by thomasplevy** [comment]
fix pending, will be available in beta.3

thanks @wonboyn!
