### ISSUE TITLE
inefficient calls to get_the_post_thumbnail in various templates

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#322]
lesson / course thumbnails are calling get_the_post_thumbnail() where has_post_thumbnail() should be being used instead

this results in overall inefficent code but can cause issues when other plugins/themes add html to using filters attached to get_the_post_thumbnail()

WP Overlays plugin causes PHP timeout issues on courses with a large number of lessons as a result

**Comment by actual-saurabh** [comment]
This is limited to just one instance:
https://github.com/gocodebox/lifterlms/blob/master/templates/course/lesson-preview.php#L22-L25
