### ISSUE TITLE
Notifications does not use the Student Name

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#343]
### 1. Reproduction Steps

+ Insert into the notification the {{STUDENT_NAME}} 
+ trigger a specific notification

![schermata 2017-05-24 alle 18 10 28](https://cloud.githubusercontent.com/assets/190159/26413821/807c07f2-40ad-11e7-8826-2d013ad52c80.png)

### 2. Expected Behavior

+ Show the student name

### 3. Actual Behavior

+ Shows "You" or "you"

### 5. System Report

Wordpress
-------------------------------------------

Home Url: http://newskam.dev
Site Url: http://newskam.dev
Version: 4.7.5
Debug Mode: Yes
Locale: it_IT
Multisite: No
Page For Posts: Blog (#87)
Page On Front: Home (#85)
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes

Settings
-------------------------------------------

Version: 3.8.1
Db Version: 3.7.7
Course Catalog: Corsi (#4)
Course Catalog Per Page: 10
Course Catalog Sorting: menu_order
Membership Catalog: Catalogo Membership (#5)
Membership Catalog Per Page: 10
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Student Dashboard: Bacheca (#7)
Courses Endpoint: visualizza-corsi
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Termini e Condizioni (#17441)
Checkout Names: required
Checkout Address: required
Checkout Phone: hidden
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Checkout Page: Fai il tuo acquisto e migliora le tue conoscenze (#6)
Confirmation Endpoint: conferma-pagamento
Force Ssl Checkout: yes
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: andrea@skillsandmore.org
Email From Name: Andrea da skillsAndMore
Email Footer Text: 
Email Header Image: http://newskam.dev/wp-content/uploads/2017/04/green-logo.png
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no

Gateways
-------------------------------------------

Stripe: Disabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manuale: Disabled
Manuale Logging: no
Manuale Order: 1

Server
-------------------------------------------

Mysql Version: 5.6.33
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 1 GB
Php Memory Limit: -1
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 5.5.9-1ubuntu4.11
Software: nginx/1.9.3
Wp Memory Limit: 40M

Theme
-------------------------------------------

Name: skillsAndMore '17
Version: 
Themeuri: 
Authoruri: 
Template: genesis
Child Theme: Yes
Llms Support: No

Plugins
-------------------------------------------

Akismet Anti-Spam: 3.3.2
bbPress: 2.5.12
bbPress Genesis Extend: 1.1.1
CodePen oEmbed: 1.0
Elementor: 1.4.6
Elementor Addon Elements: 0.5
Genesis Translations: 2.4.1
Jetpack by WordPress.com: 4.9
JP bbPress Slack Integration: 0.3.1
LifterLMS: 3.8.1
LifterLMS Helper: 2.4.3
LifterLMS MailChimp Add-on: 2.2.0
LifterLMS Stripe Payment Gateway: 4.1.1
Popup Maker: 1.6.0
Redirection: 2.5
Skillsandmore Super Plugin: 1.1.0
WP Code Highlight.js: 0.5.18
WP Inspect: 1.0.0
Yoast SEO: 4.7.1

Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: No

### 6. Browser, Device, and Operating System

+ I'm on Mac and tested with Firefox and Chrome but I think is for a wrong PHP call.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani I see how this could potentially cause issues in translation... but this is actually intentional:

If you (the student) see a notification on screen about something you have just done you should see something directed at you instead of about you...

Perhaps I'm thinking about this the wrong way but the notifications identify the recipient of the notification and if it is about his/herself it switches "you" for their name... maybe I have a logic flaw here -- despite a month long testing period I didn't have many people actually use this other than our internal team and no one seemed to find a problem with this behavior, is this not working for you?

**Comment by thomasplevy** [comment]
also, i did not make "you" translatable, that was dumb... sorry, fixing that right now...

**Comment by AndreaBarghigiani** [comment]
Don't worry @thomasplevy, 
I couldn't test in depth the beta version because I was really busy and only now that you release it I had to test it out on the staging environment for my website.

Maybe is a misconception of mine, using the `{{STUDENT_NAME}}` to recall the name of the student I was thinking to use the proper name instead of 'You', at the end of the day, if I want to use 'You' I can always write it myself but if I want to use the proper name of the student dynamically is kind of difficult ;)

Probably is just a cultural thing, but from my point of view if someone gets a notification from a website it sounds weird to read "You Lesson Complete", from my point of view is better to read "Andrea, Lesson Complete".

Now that I wrote it in English I understand better why you choose this solution 😄 
Anyway, congrats for the hard work!

**Comment by thomasplevy** [comment]
@AndreaBarghigiani I see what you're saying here... i think that maybe this needs a little more work regardless because i see the confusion... i was considering trying to build a kind of dynamic fallback system EG

{{STUDENT_NAME SELF="YOU"}} but decided just to merge it in because that fallback would get kind of complicated...

I'll keep my eye on this and see if i have other issues here and adust accordingly.

Thanks for the feedback as always!
