### ISSUE TITLE
certificate previews don't let admins preview since closing security hole in 3.8

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#344]

**Comment by jdelta-RBS** [comment]
@thomasplevy What, by chance, was the security hole closed in 3.8.0? Nothing seems to point to this in https://github.com/gocodebox/lifterlms/releases/tag/3.8.0

**Comment by thomasplevy** [comment]
@jdelta-RBS 

> Earned certificates are only accessible by the student who earned the certificate
