### ISSUE TITLE
Randomizing Quiz Questions

### ISSUE THREAD

**Issue by larrygroebe** [gocodebox/lifterlms#368]
A couple of Lifter's competitors allow you to randomize the order in which quiz questions are presented. It would be useful for at least one of my clients if Lifter had this feature too. In a multiple-choice quiz it's not always possible or sufficient to randomize answers.

Fortunately, randomizing questions is simple to add.

In the model.llms.quiz.attempt.php file, there is a function called _get_new_questions_.
 Adding a couple lines provides reandomization that can be switched on or off for a given quiz by adding a custom field called "randomize"  A slightly more elaborate version would use another random setting field like LifterLMS now has for randomizing presentation of the answers. 

One simple further step would enable developers to present only n questions at random from the total set, simply by adding adding an _array_slice_ function after the _shuffle_ function

A working example of basic quiz randomization is below.

--Larry

```
private function get_new_questions( $quiz_id ) {
$qquiz = new LLMS_QQuiz( $quiz_id );
$questions = array();
foreach ( $qquiz->get_questions( 'ids' ) as $qid ) {
$questions[] = array(
'id' => absint( $qid ),
'points' => $qquiz->get_question_value( $qid ),
'answer' => null,
'correct' => null,
);
}

//lg 20180814 // optionally randomize the quiz question order.
$rnd =get_post_meta($quiz_id, 'randomize',true); //does this quiz have an extra field that says go ahead and randomize?
if ($rnd) {shuffle($questions);} // randomize them

return $questions;
}

```

**Comment by thomasplevy** [comment]
@larrygroebe coming soon, I'd like to give you a credit in the changelog, usually that comes in the form of "props to [name](link)" any requests there?

**Comment by larrygroebe** [comment]
Larry Groebe is just fine.
