### ISSUE TITLE
Clone ACF

### ISSUE THREAD

**Issue by kartavyi2013** [gocodebox/lifterlms#387]
### 1. Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced
+ Include screenshots where applicable
+ Record a video if possible

### 2. Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)

### 3. Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

### 4. Error Messages / Logs

+ Include any relevant error messages or log files

### 5. System Report

Many issues are the result of theme or plugin conflicts. Including information about your WordPress version, your plugins (and their versions), and your theme (and its version) will help us resolve conflicts.
We've created the [LifterLMS System Report](https://lifterlms.com/docs/how-to-use-the-lifterlms-system-report/) to help with this

### 6. Browser, Device, and Operating System

+ If the bug occurs in a specific browser, it is very useful in helping us track down the specifics using this information (as well as version numbers).

**Comment by kartavyi2013** [comment]
I cant clone cources with acf fields, is it possible?

**Comment by thomasplevy** [comment]
@kartavyi2013 I haven't built an ACF integration, #386 intends to allow 3rd parties to hook into our duplication methods

I plan to add support for ACF in the future but currently you're correct, course cloning does not pull in ACF fields (or any other plugin's post meta, for that matter)

**Comment by thomasplevy** [comment]
see #386
