### ISSUE TITLE
Hey Thomas and the Rest, I really enjoy working with your plugin. But those admin-ajax calls give me a headache

### ISSUE THREAD

**Issue by Papawhoop** [gocodebox/lifterlms#388]
Dear Developers of Lifter LMS,

I just dropped by to ask whether you found a way to lower the POST calls to ajax admin.php drastically. I already setup a heartbeat controle, but during peaktime ( as soon as many users are logged in - working on their courses ) the calls explode. In the LifterLMS use with WooCommerce I gathered so many uncacheable ajax calls that the sites TTFB really gets spookymooky. And by spookymooky I mean my host mailed me because he expected it to be a DDoS-attack...

I would be super-thankful for any kind of help on how to handle that issue.

Best,
Papa

**Comment by thomasplevy** [comment]
@Papawhoop please check out this duplicate issue and follow along there: https://github.com/gocodebox/lifterlms/issues/371

Closing this one because we're already working on this issue in that other issue.

Best,
