### ISSUE TITLE
“Lesson(s)” string is not useful for i18n

### ISSUE THREAD

**Issue by alvarogois** [gocodebox/lifterlms#391]
### 1. Reproduction Steps

Found on:
https://github.com/gocodebox/lifterlms/blob/master/assets/js/lifterlms.min.js
https://github.com/gocodebox/lifterlms/blob/master/includes/admin/post-types/post-tables/class.llms.admin.post.table.quizzes.php
https://github.com/gocodebox/lifterlms/blob/master/languages/lifterlms.pot

### 2. Expected Behavior

Singular and plural forms should be dealt with separately. In some languages, singular and plural forms are too different to be used in the same string, like you can do in English with Lesson(s).

Examples:
– Portuguese – lição (singular); lições (plural)
– Italian – lezione (singular); lezioni (plural)
– Spanish – lección (singular); lecciones (plural)
– Catalan – lliçó (singular) lliçons (plural)

### 3. Actual Behavior

One string for singular and plural forms.

**Comment by thomasplevy** [comment]
@alvarogois sorry for the delay. I was "out of the office" on vacation.

Thanks for the catch here. I'll fix this up in a future release!

**Comment by actual-saurabh** [comment]
This string doesn't exist anywhere anymore. Can be confirmed quickly by searching though https://github.com/gocodebox/lifterlms/blob/master/languages/lifterlms.pot. 

This issue can be closed safely.
