### ISSUE TITLE
View Order hooks doesn't have the order id

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#402]
Looking on https://github.com/gocodebox/lifterlms/blob/master/templates/myaccount/view-order.php#L29 seems that these filters doesn't give to the develop what is the order id to use.
The only way to get that value is to write: `$wp->query_vars['orders']`.

To simplify the development will be helpful to pass this as parameter in all the hook in that file.

Ps: I developed a tiny plugin https://github.com/CodeAtCode/lifterlms-attach-pdf that show a file uploaded on the backend of the order (we will use for invoice made manually). The code where I am using the filter https://github.com/CodeAtCode/lifterlms-attach-pdf/blob/master/public/LifterLMS_Attach_PDF.php#L57

**Comment by thomasplevy** [comment]
not a sexy solution and not perfect but is something like`global $post; $order_id = $post->ID;` unacceptable? 

I'll update this in a future release but you shouldn't be roadblocked to what you need to do because the order ID is the post ID

**Comment by Mte90** [comment]
In a page like `http://lifter.dev/dashboard/orders/57/` `get_the_ID()` print the id of the page dashboard and not the order.
Probably a global variable like that is a good alternative :-)

**Comment by thomasplevy** [comment]
my bad I thought you were looking at the admin side, yes, you're right...

Well I will def. add a fix for this in a future release. Just a heads up: I am terribly far behind on a major update related to quizzes and immediately following that I'm putting all of my efforts into the rest api/cpu issue (#371 ) so while this is a few lines of code I'm not getting into backlog pruning on low priority non-bugs like this one for at least a month or two. If you submit a PR for an update to the template I can include it in the next release I put together but if I'm working on myself it's going to probably be a while. I know it's a small add but I'm so backlogged I can't focus on that kind of thing for a while.

Thanks

**Comment by Mte90** [comment]
No worry, in the meantime I resolved and the plugin is working.
