### ISSUE TITLE
catalog quiries are inefficient, especially on sites with a large number of courses

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#403]
see #393 as related issue

**Comment by Mte90** [comment]
If you point me on the right method I can do something like for #466.

**Comment by thomasplevy** [comment]
This is the same issue -- essentially -- as #393 -- the get_progress method is called a bunch on catalogs but the get_progress method is the issues

**Comment by Mte90** [comment]
Ok so fixing that method everything will breathe better!

**Comment by thomasplevy** [comment]
see #474 and #393
