### ISSUE TITLE
Quiz Previous Question not working when set to random order

### ISSUE THREAD

**Issue by Sarah-p** [gocodebox/lifterlms#404]
I believe this is a bug.

I have created a quiz with 100 questions and set to randomize the questions when taken. But when a tester takes the quiz and needs to go back to a previous question the link does not go to the question they just answered but the previous question that was added in the quiz order. 

Example:
Questions are added to the quiz backend labeled 1-100
When a quiz is taken question 10 might be displayed as question 50. But when the previous question is hit then the displayed question 49 is not shown but question 09.

This makes it so that if someone is on question 99 and hits previous question, they could potentially be taken all the way back to the beginning with no way to get back to their last question.

**Comment by thomasplevy** [comment]
@Sarah-p thanks for catching this. I'm currently rewriting almost everything in LifterLMS related to quizzes and I'll be sure this gets fixed during the overhaul

**Comment by Sarah-p** [comment]
Sounds great! I'll just use non random question till it's fixed.

**Comment by thomasplevy** [comment]
resolved in 3.16.0 alphas (to be released in alpha.4 or beta.1)

**Comment by thomasplevy** [comment]
resolved in 3.16.0
