### ISSUE TITLE
[Reviews] Avoid use of Inline CSS.

### ISSUE THREAD

**Issue by dineshchouhan** [gocodebox/lifterlms#410]
Hello,

We are trying to make our theme compatible with LifterLMS but the problem is, you have used inline CSS at many places, like in Review List, Review Box etc., you can look at here: 
https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.review.php#L65
https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.review.php#L111

Used multiple style attribute in single tag: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.review.php#L66

In our theme, we are not able to override your inline CSS and we don't want to use `!important`.

I haven't checked your plugin fully but It may possible you used inline in other places, I'll suggest you to don't use inline CSS.

**Comment by thomasplevy** [comment]
@dineshchouhan I'll get this cleaned up in a future release. You're absolutely correct that this is a bad practice and I am sorry I haven't resolved this yet.

**Comment by thomasplevy** [comment]
FWIW I just wanted to note that as a rule we do not excessively inline and this is one of the oldest portions of the codebase before we put coding standards in place. Please don't let this one class prevent you from making your theme fully compatible as I can assure you 95% or more of our styles are in the CSS files as they should be

**Comment by thomasplevy** [comment]
@sujaypawar I'm currently working on our 3.16 release and a bit behind schedule. Every issue is important but I won't be able to get into this until mid to late February. My apologies

**Comment by sujaypawar** [comment]
No problem. All the best for 3.16 :)
