### ISSUE TITLE
My Courses Vs. My Account

### ISSUE THREAD

**Issue by sujaypawar** [gocodebox/lifterlms#416]
Just a small suggestion:

The default page title is My Courses and same is followed in other places like, settings. But, as LifterLMS offers memberships as well, should it be better called My Account?

**Comment by thomasplevy** [comment]
It should be called "Student Dashboard"

In version one it was called "My Courses" and we've changed our language to Student Dashboard but I've missed updating the page title. I'll change that default in a future release.

PS We want to avoid using My Account to avoid confusion between WooCommerce and LifterLMS when used together.

**Comment by thomasplevy** [comment]
This page should be called "Dashboard"

**Comment by philwp** [comment]
Do you want to make the slug `student-dashboard` or `dashboard`
https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.install.php#L241

**Comment by thomasplevy** [comment]
@philwp from an admin / course creators experience this is the student dashboard but from a student's experience it's just the dashboard -- so slug should be `dashboard` and title should be "Dashboard"

Thanks!
