### ISSUE TITLE
Inconsistent Headings in My Account

### ISSUE THREAD

**Issue by dineshchouhan** [gocodebox/lifterlms#425]
It would be better if headings were consistent in my account tabs. Some tabs have headings, while some not.

This video will explain what I mean - 
https://www.youtube.com/watch?v=sr8OusAVB8A

**Comment by thomasplevy** [comment]
video unavailable

please provide screenshots or specific examples of these inconsistencies and I'll clean them up in a future release.

Thanks

**Comment by thomasplevy** [comment]
@dineshchouhan screenshot please! That video is unavailable

**Comment by thomasplevy** [comment]
@dineshchouhan can you please follow up per my last comment. I'll be closing this if I can't get some more information from you!

**Comment by thomasplevy** [comment]
Need more information from @dineshchouhan. If you can provide requested information please respond and I'll reopen
