### ISSUE TITLE
Error at the end of Setup Wizard

### ISSUE THREAD

**Issue by sujaypawar** [gocodebox/lifterlms#426]
Just came across error at the end of Setup Wizard while importing the sample course:

```
The supplied file cannot be processed by the importer.
No generator supplied.
```

Screenshot - https://cloudup.com/cGwRnKCIlAf

Note - this is a multisite installation. Could that be the reason? Also the error message can be a bit elaborative.

**Comment by thomasplevy** [comment]
@sujaypawar can you give this another shot? I ran a good 25 imports today and saw no issuses.

We host the demo course on an S3 bucket via CloudFlare so it's possible that it was temporarily unavailable or something.

Let me know if you can come up with some reliable repro steps please!
