### ISSUE TITLE
Suggestion: Needs "Save & Close" and "Discard" button on Course Builder

### ISSUE THREAD

**Issue by dineshchouhan** [gocodebox/lifterlms#427]
Currently, it's a little bit confusing that how to save and go back to post edit mode. Needs "Save & Close" and "Discard" button and that should be always visible currently pencil button appears on mouse hover. 

Screenshot: https://goo.gl/meA6Dp

**Comment by thomasplevy** [comment]
sure I'll that add that in a future release

**Comment by thomasplevy** [comment]
see 3.16
