### ISSUE TITLE
Lesson and Course sidebars are not appearing in Customizer

### ISSUE THREAD

**Issue by dineshchouhan** [gocodebox/lifterlms#448]
As per Sidebar compatibility for LifterLMS document is implemented in Astra and it's working fine but the problem is when a user wants to add widget through Customizer in that case Lesson and Course sidebars are not appearing, even user is on Course or Lesson page, It's showing Main Sidebar instead of Lesson or Course sidebar.

Same Problem with all other themes which are natively compatible with LifterLMS. Example: Twenty Sixteen, Twenty Seventeen etc.

**Comment by thomasplevy** [comment]
I'll look into this along with other customizer issues your team has raised

**Comment by thomasplevy** [comment]
This may be resolved (possibly accidentally) in the latest version of Astra, we may still have issues with other themes. Need to do some research and information

**Comment by thomasplevy** [comment]
Because LifterLMS "hijacks" the theme's primary sidebar and replaces it with the widgets from the course / lesson sidebar this prevents the actual widget area from being rendered in the customizer sidebar where a user could edit the widgets in the sidebar.
