### ISSUE TITLE
How to add Quiz in latest version?

### ISSUE THREAD

**Issue by dineshchouhan** [gocodebox/lifterlms#449]
After the update of Latest version of LifterLMS, Quiz & Questions menu got disappeared. I'm not able to add or edit quizzes.
I got a notice about Quiz Builder but how to use that, no Idea.

Can you please help me out?

LifterLMS Version: 3.16.7

**Comment by thomasplevy** [comment]
https://lifterlms.com/docs/get-new-quiz-builder/
