### ISSUE TITLE
login and registration forms both use default "_wpnonce" for nonce field

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#451]
Results in duplicate IDs since the name & id are generated from the name param of `wp_nonce_field`

add unique names for each & update handler functions to check nonce on the new names

**Comment by thomasplevy** [comment]
Fix on [payment-controllers](https://github.com/gocodebox/lifterlms/tree/payment-controllers) branch

**Comment by actual-saurabh** [comment]
Close in favour of #593
