### ISSUE TITLE
Migrate My Course to Dashboard Section

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#455]
### 1. Reproduction Steps

* take old `my-courses.php`
* adapt the output dashboard-section.php

### 2. Expected Behavior
Before output
![3307398590-example-course-list](https://user-images.githubusercontent.com/403283/36500505-c1064aee-1744-11e8-9108-bdffed2f2ef0.png)

### 3. Actual Behavior
Actual output
![schermata 2018-01-12 alle 20 01 59](https://user-images.githubusercontent.com/403283/36500489-b634f3ae-1744-11e8-9907-decce36e5b87.jpg)

I want back the progress bar, there is an hook? Looking the code https://github.com/gocodebox/lifterlms/blob/2f416b359b828c4451cd3a20c5200943f1deac15/includes/functions/llms.functions.templates.dashboard.php#L76 seems that there are 2 filters.

**Comment by thomasplevy** [comment]
@Mte90 progress bar was not removed your screenshot shows a progress bar on the 3rd tile (Javascript)

**Comment by Mte90** [comment]
You are right but for the issue of `from theme archive course` in all the titles?

**Comment by thomasplevy** [comment]
@Mte90 

LifterLMS doesn't show "from theme archive course" anywhere in the codebase... could this be coming from a piece of custom code or plugin running on your site?

The HTML content is all still 100% customizable, take a look at the the loop templates:  https://github.com/gocodebox/lifterlms/tree/master/templates/loop

Also look at the hooks in the dashboard to remove content or add your own hooks to add other content: https://github.com/gocodebox/lifterlms/blob/master/includes/llms.template.hooks.php#L128-L147

We updated the dashboad to use the same loop template as the catalogs as this was something that we saw requests for over and over again from users. I know it's a big change and I apologize if you're not a fan.

Additionally, this allows more consistency for customization (there's fewer custom elements output by LifterLMS). If you want the catalogs to look different than the dashboard you can modify the templates and use conditionals to display alternate html:

`is_llms_account_page()` will return `true` on the dashboard and `false` on the catalogs

Hope that helps,

**Comment by Mte90** [comment]
You are right somehow someone made something wrong for that label -.-'
