### ISSUE TITLE
Remove reliance on session manager

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#462]
https://github.com/ericmann/wp-session-manager

**Comment by Mte90** [comment]
I saw today that my site had 330000 lines of sessions saved with less of 100 users.
So I think that something happening in the wrong way...
I see on https://wordpress.org/support/topic/i-have-a-massive-amount-of-sessions-in-wp-options/#post-9874736 that the new version of that library use a custom table, maybe the version used in lifter is not updated?

I am not sure if add a daily cronjob and the issues that can create but I think that is not good for my database.

**Comment by thomasplevy** [comment]
@Mte90 a few things here:

1. This library is used by a handful of other popular plugins. I've found a few issues when two installed plugins use this same plugin which causes a massive number of sessions to be created. I can't really figure out a way to avoid this from happening. The sessions are cleaned up automatically and in general other than being annoying they don't break websites. It's a bummer. It's underperformant, and it must be addressed but I don't currently have a perfect roadmap for fixing it other than removing the reliance entirely and building a custom session manager that doesn't conflict...

2. Caching could cause each page load to create a new session. You can disable the session manager entirely by adding this constant to your wp-config.php file: https://gist.github.com/thomasplevy/c442ea9c30416a9c3fab81e1d5480d00

3. I've considered upgrading to the latest version of the lib but since I'm planning to remove it anyway I haven't done so. The library does generally work with the above exceptions and while it may seem simple to click the update button I can assure you that it's not that simple. I don't have a high confidence level in upgrading it fixing either of the above too issues and my level of concern for it creating new issues outweighs this. For now, I'm keeping it where it is unless a contributor (maybe you) has the time to really weed out the potential issues that could result from an upgrade and assure me that it's going to be fine if it is upgraded.

4. Really it needs to be removed. The use of sessions for what we use it for is massive overkill and was more important in LifterLMS 1.0 but as we've improved the plugin we've been slowly removing the need. The last few areas that need cleanup are coupon usage and error / success notices. Both of these can be easily factored out but it's not high on my priority list currently.

As always I'm sorry that this is causing you issues and I welcome some assistance but it's not currently flagged as a priority for me to work on.

My apologies

**Comment by Mte90** [comment]
I disable the php session as you suggested, I will let you know if the situation improve :-)

**Comment by lukecav** [comment]
Any progress on updating LifterLMS to use the more current version of WP Session Manager?
https://github.com/ericmann/wp-session-manager/releases/tag/4.2.0

**Comment by thomasplevy** [comment]
@lukecav 

This is on our backlog still

**Comment by lukecav** [comment]
@thomasplevy 

Any ETA?

**Comment by thomasplevy** [comment]
@lukecav It's currently on the [future](https://github.com/gocodebox/lifterlms/milestone/18) milestone with no eta as it has not been prioritized.

It's been prioritized this way as we don't see a lot of issues resulting from the use of this library and, for those who do have problems it can easily be disabled with little impact (as noted [above](https://github.com/gocodebox/lifterlms/issues/462#issuecomment-407171508), see point 2).

My team is tiny. We cannot do all the things that we want and need to do. We have to prioritize according to impact and to my knowledge there's not a tremendous impact or need to update with this particular item.

It sounds like you have some information that I may not have; I'd appreciate if you'd share it here.

**Comment by lukecav** [comment]
WP Session Manager version 1.2.2 will only delete 1000 expired sessions every 12 hours so if a site has higher expired sessions then those will not be removed.

**Comment by thomasplevy** [comment]
@lukecav thanks for the information. Work has begun to remove the library, we've weighed the pros and cons of upgrading vs. removing and decided to build the functionality we require into the core and remove the 3rd-party dependency. Likely we're a few weeks out from a release in the core but work has begun.

**Comment by thomasplevy** [comment]
A few notes I don't want to lose:

1) The library hasn't been upgraded because there's been no security issues and it's been unclear to me until Monday that there was a clear scaling issues with the lib.
2) In determining how to resolve this issue, I found that the latest version of the library does not resolve this particular issue:

https://github.com/ericmann/wp-session-manager/blob/b5cafd9216241a53314f7e21b3888b8583f7784f/includes/DatabaseHandler.php#L264-L282

3) There is a filter that can be leveraged to run the garbage collector more frequently than hourly: 

https://github.com/ericmann/wp-session-manager/blob/b5cafd9216241a53314f7e21b3888b8583f7784f/wp-session-manager.php#L65

4) After testing the upgrade a not enormous but also not insignificant amount of core code needs to be rewritten to accommodate changes in the library

5) After testing the upgrade a substantial amount of code in the phpunit testing suite fails as a result of the load order of things -- the library "loads" after output in the testing suite. The best I could find was to conditionally disable the library in the testing suite, which is probably okay, but that also makes me feel like the integration tests are more frail and less reliable than running the integration tests with the integrations loaded.  

5) Knowing all of this, and the fact that we've wanted to remove the external dependency, it feels like a good time to write in our own session management that does exactly what we need it to do
