### ISSUE TITLE
 Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /lifterlms/lifterlms.php on line 29

### ISSUE THREAD

**Issue by misonessie** [gocodebox/lifterlms#469]
Plugin failed to be activated with an error message:
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /wp-content/plugins/lifterlms-0592bfd8b38d8afc7d3bd12e24c3442eaa9b2498/lifterlms.php on line 29

**Comment by thomasplevy** [comment]
@misonessie did you clone the GitHub repo and attempt to run it? If so please checkout our installing for development guide here: https://github.com/gocodebox/lifterlms#installing-for-development

As noted in the [readme](https://github.com/gocodebox/lifterlms#installing-for-development) "If you clone or download this repo directly it will not run as a plugin inside WordPress! Installable production releases are available in on the Releases tab. You can get the latest stable release from WordPress.org"

So if you're looking for a production-ready installable zip hit the "Releases" tab here in GitHub or head over to WordPress.org to grab the latest.

Best

**Comment by misonessie** [comment]
@thomasplevy Thank you.
