### ISSUE TITLE
Access plan editor doesn't load with visual editing disabled

### ISSUE THREAD

**Issue by pjeby** [gocodebox/lifterlms#470]
### 1. Reproduction Steps

* Install LifterLMS and have it install the example course
* Install and activate a plugin that replaces the default WP visual editor, like [Mark-It-Down WP](https://wordpress.org/plugins/mark-it-down-wp/) or [WP Markdown Editor](https://github.com/hoducha/wp-markdown-editor)  -- or go to your profile and disable the visual editor
* Edit the example course

### 2. Expected Behavior

* The "Product Options" section of the page should load and be editable, even if only with plain text fields

### 3. Actual Behavior

* The loading animation continues for an extended period, then stops
* The options area is cleared and replaced with the message "There was an error loading the necessary resources. Please try again."

**Comment by thomasplevy** [comment]
@pjeby any errors on the JS console that you're seeing here?

**Comment by pjeby** [comment]
Before the hundreds of "waiting" messages, there are two jqmigrate warnings:

* JQMIGRATE: 'ready' event is deprecated
* JQMIGRATE: jQuery.fn.attr('checked') might use property instead of attribute

Both traces list `LLMS.init`, but are unlikely to be a problem because they also appear when the visual editor is enabled and the product options section works normally.

Ironically, when the section works, there *is* an error in the console:

    tinymce.min.js Uncaught TypeError: Cannot set property 'onload' of null

Anyway, the most critical difference between the working and non-working conditions is that **when the visual editor is enabled**, there are `wp-includes/js/tinymce` scripts included on the page, and **when it is not, they are not**.

LLMS apparently requires the visual editor to be enabled, rather than falling back to plain textareas as wordpress itself does.  ISTM that it should either fall back gracefully in that case, or else force the needed scripts to be included.

It would appear that Wordpress has (since 4.8) some hooks that can be used to ensure that certain scripts are loaded after TinyMCE, so that might be an option for replacing the "check ten times a second for 30 seconds" approach to dependency ordering.

Alternately, simply having LLMS check whether the visual editor is even enabled in the first place and not having the dependency check take place could support the "fall back to plain text" approach.

**Comment by thomasplevy** [comment]
@pjeby I'll look into finding a better solution when the editor is disabled. Thanks
