### ISSUE TITLE
Wordpress Fatal Parse Error upon Activation: Fail

### ISSUE THREAD

**Issue by Anchorage42** [gocodebox/lifterlms#471]
Receive this message when trying to install and activate through wordpress dashboard:

Parse error: syntax error, unexpected '[' in /home/content/35/12510435/html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.database.store.php on line 110

I have tried looking for the unexpected bracket but found nothing in the file.

**Comment by thomasplevy** [comment]
@Anchorage42 LifterLMS is built to function on PHP 5.6 or later, we do not test against older versions of PHP which have reached their official [end of life](http://php.net/eol.php).

Minimum system requirements and recommendations can be found [here](https://lifterlms.com/docs/minimum-system-requirements-lifterlms/).

I haven't confirmed through a test case but my assumption is that the syntax we're using may not function on older versions of PHP.

Can you check your PHP version and let me know what it is so we can confirm this as a bug or as an issue on unsupported versions of PHP.

Thanks,

**Comment by Anchorage42** [comment]
It waw a PHP error. Was running 5.3.
Thank you

**Comment by Anchorage42** [comment]
Hey @thomasplevy, 
Updated PHP and got the install activated; now I get the following when I try to use the builder:

Fatal error: Call to undefined function wp_enqueue_editor() in /home/content/35/12510435/html/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.assets.php on line 232

**Comment by thomasplevy** [comment]
@Anchorage42 What version of WordPress are you using? This function has been part of the WordPress core for a while and I can't imagine why this would be occurring unless you were on a fairly old version of WordPress.

**Comment by Anchorage42** [comment]
Fixed. Thank you
