### ISSUE TITLE
Optimize call of get_enrollment_status/date

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#474]
![get_enrollment_status](https://user-images.githubusercontent.com/403283/37106874-21c37d22-2233-11e8-9b57-f2910b9a5c0c.png)

Looking at the [code](https://github.com/gocodebox/lifterlms/blob/master/includes/models/model.llms.student.php#L528) seems that the query is not cached but executed different time in the page for the same `$product_id`.
The best way will be to save in the class this value to avoid more query for the same data.

**Comment by Mte90** [comment]
![count](https://user-images.githubusercontent.com/403283/37107440-9e2ec014-2234-11e8-947a-50a9c140a82a.png)
Looking at Query monitor there are 99 call of this query, maybe otpimizing that with cache this value will save a lot.

**Comment by thomasplevy** [comment]
Will look into this in a future update

**Comment by Mte90** [comment]
![count](https://user-images.githubusercontent.com/403283/37107626-1629cc08-2235-11e8-97d8-4110bf865e87.png)
Looking at the [code](https://github.com/gocodebox/lifterlms/blob/student-progress/includes/models/model.llms.student.php#L492) this one is executed 28 times.

With caching this value we can save like 130 queries for page.

**Comment by Mte90** [comment]
I made this test with putting them in a array in the class in this pr https://github.com/gocodebox/lifterlms/pull/467

Maybe evaluate to implement something like that in the next update will be optimal. If you not have time explain me how to fix and I will try do it :-)

**Comment by thomasplevy** [comment]
@Mte90 I didn't love that solution. I'm sorry.

I'm considering all of this but I don't have the capacity to write all the code you need written (we have 7k users, a lot of support tickets, and a lot of issues to fix...)

You're always welcome to submit suggestions or write code but please understand that at the end of the day I am supporting this code base and have to answer to potential bugs and issues. It *may* fix your specific problems but I see issues with that PR (noted on the PR) and I'm not comfortable merging that in. I'm sorry...

**Comment by thomasplevy** [comment]
@Mte90 please have a look at student-progress branch -- I added a general caching mechanism to the `LLMS_Abstract_User_Data` abstract (used by `LLMS_Student` class) which can be used to add data to the WP core's object cache using `LLMS_Student->cache_set()` `LLMS_Student->cache_get()`and `LLMS_Student->cache_delete()`

I added caching for the functions identified in this issue which seems to cut down on duplicate queries you've identified here. This should help #461 as well. It looks to me like the largest offender is the `get_enrollment_status()` method that is called before adding links to lessons. Every lesson _requires_ enrollment in the course. Between the syllabus (at the bottom of a course) and the outline widget (if you have one) this is a stupidly unnecessary number of database calls (sorry...). This caching should reduce that significantly.

I'm sure there's other areas in the class that can utilize the same methods / strategies to optimize further. Let me know if you see another method that seems offensive and could benefit from this kind of caching.

**Comment by thomasplevy** [comment]
Aside: I did not thoroughly test this. I'm writing unit tests as I go and testing on a local site but I'm working pretty quickly here. I'm not ready to push to production yet and I'd appreciate any feedback you have on this... I feel like you're not testing any of this on a staging site and that's up to you but please know that I'm not calling this production ready!

**Comment by Mte90** [comment]
I am testing them and checking the code locally and later trying on production, so no worry for that :-D

I checked also this other commit and seems that do the magic.
I will test and will let you know!

**Comment by Mte90** [comment]
Trying locally seems that work a lot!
Same page switching only the branch is 333 vs 128 query!
Using only this branch!
You made an amazing job, if you update the branch with the master I will try that in production and I will give you more informations.
If you will go in Italy I have to offer to you a pizza (if this improvement arrive in an official release of course)!

**Comment by thomasplevy** [comment]
PR at #476

**Comment by thomasplevy** [comment]
Merged into master with PR #476
