### ISSUE TITLE
Actually clear sessions when clearing sessions via Status -> Tools

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#481]
This class doesn't exist in codebase and it doesn't clear sessions when the button is clicked

https://github.com/gocodebox/lifterlms/blob/master/includes/admin/class.llms.admin.page.status.php#L47

We should be using this method: https://github.com/ericmann/wp-session-manager/blob/master/includes/OptionsHandler.php#L137-L164

**Comment by actual-saurabh** [comment]
Related #462

**Comment by thomasplevy** [comment]
This bug is misidentified. LifterLMS loads an old version of the wp-session-manager lib and in that version this function does exist (and it does work).

Closing as invalid
