### ISSUE TITLE
Lesson page show status of an user

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#487]
On that page (https://skillsandmore.org/lezione/gerarchia-tema-wordpress/) as you can see that as not logged there is a pgress and course already marked.
I am using W3 Total cache so maybe there is something about it but I disabled for that pages.

I saw that on `lifterlms_course_progress_bar()` doing a check about `is_user_logged_in()` I can avoid that behaviour.
I am not sure what can I do to debug more that issue but seems that there is no check for an user logged on this pages.

**Comment by thomasplevy** [comment]
@Mte90 are you seeing this anywhere else? A quick local test doesn't show me this behavior but I'm afraid this is an issue resulting from all the additional caching added as a result of #474 

My biggest concern with that (and why I was having you test it) was that caching plugins would persist this data incorrectly across user sessions...

Are you certain that total cache is disabled for logged in users?

**Comment by Mte90** [comment]
Happen in other pages and in the past week we didn't noticed that issue.

We disabled the caching for logged users but I think that a check for logged users can simplify and avoid any kind of issue.

I can do test but I cannot think that I can disable W3 (for me is this the problem).

**Comment by thomasplevy** [comment]
Found the issue will have this patched in 3.17.2, testing updates now and will have released in the next several hours. Sorry about this...

**Comment by thomasplevy** [comment]
@Mte90 have you had a chance to see if [3.17.2](https://github.com/gocodebox/lifterlms/releases/tag/3.17.2) fixes this for you?

**Comment by Mte90** [comment]
The problem is fixed now :-)
