### ISSUE TITLE
Unminified versions missing from repository for some scripts

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#503]
I modified the build tasks to also include the unminified sources in the distribution in #484. 

However, these files don't seem to be using the default tasks:

- lifterlms.min.js #504 
- llms-attempt-grading.min.js #505 
- llms-lesson-locked.min.js
- llms-metabox-membership.min.js

I can't find these scripts in https://github.com/gocodebox/lifterlms/tree/470936afd2c503c14fef7b4925584f3106ebb4f0/_private/js

I have excluded course builder related files since it does make sense to process that separately.

**Comment by thomasplevy** [comment]
`llms-metabox-membership.min.js` script appears to be from LifterLMS 2.x and should have been removed during 3.x upgrade but is still present. Probably the _priv version was removed but the built asset was not

`llms-lesson-locked.min.js` was replaced by functionality in https://github.com/gocodebox/lifterlms/blob/master/_private/js/app/llms-lesson-preview.js

Both these scripts are built holdovers that should be removed. Yes.
