### ISSUE TITLE
Code improvement on BuddyPress detection

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#511]
![immagine](https://user-images.githubusercontent.com/403283/39398396-6ba9b08e-4b0d-11e8-924d-f218692b1918.png)

As I can see in every page there is this query, but there isn't Buddypress in my installation.

![immagine](https://user-images.githubusercontent.com/403283/39398553-ac56284a-4b0f-11e8-92d4-d8d23fafab5f.png)

AS I can see on https://github.com/gocodebox/lifterlms/blob/d824132daa0dd49347940a3b7c484c1e1f88960f/includes/class.llms.integrations.php#L52 
the class are defined maybe they are executed on every page.

There is the request https://github.com/gocodebox/lifterlms/blob/master/includes/abstracts/llms.abstract.integration.php#L125 maybe we can add a check in the classes with detect the plugin like for https://github.com/gocodebox/lifterlms/blob/0eb956847a57893aeca29794148c111462c4c565/includes/class.llms.widgets.php#L34 inside every class.
In the meantime we can disable with an hook and save a query in every page, in all the pages of the site.

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/39398833-2b29bf5c-4b14-11e8-9e3e-0a70fe7427b0.png)

I see that also this query run in all the pages on https://github.com/gocodebox/lifterlms/blob/2a36f219e5556dfede4dbc5d0ccff65014a488a1/includes/class.llms.query.php#L121 but this value is required in the code?

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/39398914-2fccd548-4b15-11e8-8a54-a73f5141591d.png)
This are the queries that happen in all the pages (in this case in the website homepage) maybe we can do something to do only when required?

**Comment by thomasplevy** [comment]
> This are the queries that happen in all the pages (in this case in the website homepage) maybe we can do something to do only when required?

Let's track this as a separate issue please

**Comment by thomasplevy** [comment]
> I see that also this query run in all the pages on
> 
> lifterlms/includes/class.llms.query.php
> 
> Line 121 in 2a36f21
> 
>  			'person-logout' => get_option( 'lifterlms_logout_endpoint', 'person-logout' ), 
> but this value is required in the code?

Please open this as a new issue as well please

**Comment by Mte90** [comment]
Opened other two tickets and cleaned this one

**Comment by thomasplevy** [comment]
> Opened other two tickets and cleaned this one

Thanks!

**Comment by thomasplevy** [comment]
@Mte90 check #515 for me please, this will flip the `is_installed()` and `is_enabled()` checks on integration classes which will prevent the DB call (made by `is_enabled()`) when the integration is loaded by first using `is_installed()` to check for the existence of the integration dependencies

With BuddyPress: https://github.com/gocodebox/lifterlms/blob/master/includes/integrations/class.llms.integration.buddypress.php#L108

With bbPress: https://github.com/gocodebox/lifterlms/blob/master/includes/integrations/class.llms.integration.bbpress.php#L229

Etc...

Let me know if that helps!
