### ISSUE TITLE
Option endpoint loaded in all the pages

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#513]
![immagine](https://user-images.githubusercontent.com/403283/39398833-2b29bf5c-4b14-11e8-9e3e-0a70fe7427b0.png)

I see that also this query run in all the pages on https://github.com/gocodebox/lifterlms/blob/2a36f219e5556dfede4dbc5d0ccff65014a488a1/includes/class.llms.query.php#L121 but this value is required in the code?

**Comment by thomasplevy** [comment]
I believe this may have been refactored out of the core but this particular line was lost. Will confirm and remove if possible

sorry

**Comment by Mte90** [comment]
no problem the important that we found :-D
