### ISSUE TITLE
PHP Warning: in_array() expects parameter 2 to be array, string given in /wp-content/plugins/lifterlms/includes/admin/class.llms.admin.user.custom.fields.php on line 233

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#516]
https://github.com/gocodebox/lifterlms/blob/master/includes/admin/class.llms.admin.user.custom.fields.php#L233

if `$selected` is empty, there's no array to run `in_array()` for. 

![screen shot 2018-04-30 at 4 42 04 pm](https://user-images.githubusercontent.com/1739834/39424790-f4df3fa2-4c95-11e8-8cd2-4d9ba74318db.png)

**Comment by thomasplevy** [comment]
@actual-saurabh 

Can you provide some more exact reproduction steps for this... the code here can run in a few different scenarios and I want to ensure I'm reproducing correctly to find a solution

thanks

**Comment by actual-saurabh** [comment]
I just found this inside the error_log of a site during a support cycle. I couldn't reproduce it or get any information that describes the context.

I raised it as a more generic idea of checking if expected variables are arrays before running iterations and array specific functions.

If not, we can keep this open till we encounter it again.
