### ISSUE TITLE
Incorrect parameter in access plan query

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#517]
In https://github.com/gocodebox/lifterlms/blob/b082d1410566f1147e88a90303f038ca679e444d/includes/models/model.llms.product.php#L45, `post_per_page` should be `posts_per_page`.

Without this, there is no parameter passed to the query. In a specific server that defaults the `posts_per_page` to 1 (instead of the usual -1), only 1 access plan shows up.

**Comment by thomasplevy** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/4a148723-fbbf-4972-8e6e-120148c5a497-ef52a266-6f48-460b-87a2-21f94f0c8a79-v1.png?transparent=1&palette=1&width=246)
