### ISSUE TITLE
Unpredictable JS load order creates undefined function type of errors

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#520]
![screen shot 2018-05-01 at 7 27 30 pm](https://user-images.githubusercontent.com/1739834/39475917-c836b56a-4d77-11e8-8378-31719f1b1f44.png)

This is the current order of the js files. Here's an ordered list for convenience:

1. assets/js/llms-admin-tables.min.js
2. assets/js/llms-admin.min.js
3. assets/js/llms-ajax.min.js
4. assets/select2/js/select2.min.js
5. assets/js/llms-metabox-students.min.js
6. assets/js/llms.min.js
7. assets/js/vendor/topModal.js
8. assets/js/llms-metabox-product.min.js
9. assets/js/llms-metabox-instructors.min.js
10. assets/js/llms-metabox-fields.min.js
11. assets/js/llms-metaboxes.min.js

Often because the `l10n` object is defined in `llms.min.js` but used in scripts loaded before that where it throws undefined errors.

By using the [`$dependecy` parameter of `wp_enqueue_script()`](https://developer.wordpress.org/reference/functions/wp_enqueue_script/#parameters) we could control this load order by adding scripts as dependencies of other scripts.

The final solution would involve deciding on a correct nested load order and then registering dependencies without explicitly enqueuing them.

This is because enqueueing the final script will surely enqueue scripts listed in the dependencies first.

**Comment by thomasplevy** [comment]
Related #146 & #484

**Comment by actual-saurabh** [comment]
I had a chance to review this more closely.

We should remove enqueue_inline_script() and related methods in favour of [wp_localize_script()](https://developer.wordpress.org/reference/functions/wp_localize_script/) calls. This way the l10n issues will go away if we attach the data to the main `'llms'` script. This will ensure that all data is available to the script that needs them.

Second, make `'llms'` a dependency of all the other scripts ensuring that all the lllms related objects are loaded and in place before any other scripts load.

This will halve the code in both the assets files and make a lot of issues go away. Also see: https://pippinsplugins.com/use-wp_localize_script-it-is-awesome/ for other benefits.
