### ISSUE TITLE
Blank account endpoint for achievements needs to remove dashboard main page summary section in addition to nav items

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#535]

**Comment by toyinogunseinde** [comment]
HS-117849 I feel once disabled from the endpoint, it shouldn't be in the dashboard as well(thereby using CSS to hide it). From the perspective of a customer, If i remove something from an endpoint, that means i don't need that feature. I do not need to use extra CSS to remove it

**Comment by thomasplevy** [comment]
Agreed, that's why we've added this is a bug @toyinogunseinde :-D
