### ISSUE TITLE
Post author for Quiz Assignments etc is hardcoded to 1 by default

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#542]
https://github.com/gocodebox/lifterlms/blob/master/includes/abstracts/abstract.llms.post.model.php#L534

If no post author is supplied when creating a new post of any type in LifterLMS, the default author is set to literal `1`.

This should pick up the current user by default, so that different authors can create different parts of the course, as well.

**Comment by thomasplevy** [comment]
PR #543
