### ISSUE TITLE
Expiry occurs 24 hours earlier than UX suggests

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#552]
https://github.com/gocodebox/lifterlms/blob/0b12fe452d85b3a85714f568c4961c565f2f1b3b/includes/models/model.llms.coupon.php#L219 checks if the current time is lesser than the saved expiry. However, the comparison is made by converting the expiry date (for example, 05/22/2018) into seconds which would turn out to be the timestamp for 00:00 Hrs on that day.

So, anyone trying to use the coupon **on** the date gets an error message that is slightly confusing because the date hasn't passed yet:

![screen shot 2018-05-22 at 6 48 12 pm](https://user-images.githubusercontent.com/1739834/40364810-d1c3267a-5df0-11e8-9ae3-3da135205ad6.png)

The UX also suggests that the coupon should still work on the expiry date:

![screen shot 2018-05-22 at 6 46 26 pm](https://user-images.githubusercontent.com/1739834/40364837-e1d629d6-5df0-11e8-8369-fd9b66c4975b.png)

Adding a day (24 hours) to expiry before this check would fix the issue.

**Comment by thomasplevy** [comment]
PR #553
