### ISSUE TITLE
Trial Price gets a strikethrough when there's a sale.

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#570]
https://github.com/gocodebox/lifterlms/blob/c645a1b641fb65498e11f686a8836f9697dd6001/templates/checkout/form-summary.php#L16

When there's a sale, the trial price is also struck through along with the regular price because of the markup similarity and CSS definitions.

To fix this, the trial price should have a class of its own and then excluded from the strikethrough styling.

**Comment by actual-saurabh** [comment]
https://github.com/gocodebox/lifterlms/blob/9e45174b74328a049fbafec0e93a81369a0ea6ed/assets/scss/frontend/_checkout.scss#L72-L75

**Comment by actual-saurabh** [comment]
https://github.com/gocodebox/lifterlms/pull/571

**Comment by BurlesonBrad** [comment]
thank you

**Comment by thomasplevy** [comment]
Fixed by #571
