### ISSUE TITLE
Notifications persist on Firefox (and reportedly Safari) over multiple steps

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#588]
### 1. Reproduction Steps

Open any course in Firefox and complete lessons.

### 2. Expected Behavior

Notification of completion shows up and clears automatically. Completing the next lesson should show only one new notification and the older ones should not visible anymore. Works as expected in Chrome.

### 3. Actual Behavior

In Firefox, notifications persist across multiple steps with a large number of notifications accumulating and clearing randomly:

![screen shot 2018-06-13 at 5 12 19 pm](https://user-images.githubusercontent.com/1739834/41349549-d8cec340-6f2d-11e8-8ce5-9b606edb365b.png)

Similar behaviour has been reported on Safari, but I haven't been able to test this yet. Chrome works just fine.

### 4. Error Messages / Logs

There are no errors in console. Nothing abnormal on the surface.

### 5. System Report

NA

### 6. Browser, Device, and Operating System

Firefox (tested), Safari (reported)

**Comment by thomasplevy** [comment]
These browsers don't seem to be obeying `onbeforeunload` JS events.... 

Some notifications used to redisplay until dismissed (like payment or cert notifications) but I had so many complaints about the differing behaviors that they're all set to only display once so really we don't need an AJAX dismissal handler (which is what the unload events do) anyway.

I'll adjust the scripts to record as viewed via the PHP functions called when displaying and then an unload event won't be required
