### ISSUE TITLE
LLMS Login & Registration doesn't accept apostrophes in Email local-part

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#591]
### 1. Reproduction Steps

Try using any email address with an apostrophe during signup.

### 2. Expected Behavior

Should be able to register.

### 3. Actual Behavior

The error here is displayed and registration fails: https://github.com/gocodebox/lifterlms/blob/d824132daa0dd49347940a3b7c484c1e1f88960f/includes/class.llms.person.handler.php#L979-L981

### 4. Notes
As per RFCs described here: https://en.wikipedia.org/wiki/Email_address#Local-part and issues raised in WP Core (https://core.trac.wordpress.org/ticket/18039 & https://core.trac.wordpress.org/ticket/34483), such emails are valid. Hence this was fixed and released in WP 4.8 via https://core.trac.wordpress.org/changeset/29966.

The same strategy used in the change-set above (`wp_unslash()` before running `is_email()` will fix this issue.

**Comment by actual-saurabh** [comment]
Same with login. This line needs to be fixed as well: https://github.com/gocodebox/lifterlms/blob/d824132daa0dd49347940a3b7c484c1e1f88960f/includes/class.llms.person.handler.php#L653

**Comment by thomasplevy** [comment]
I'm going to steal this from you and write some long-overdue unit tests for the person handler class in the process of fixing this. Thanks for the research on core tickets to find a simple solution here

**Comment by thomasplevy** [comment]
Login issue persists in 3.29.3: `$_POST` data isn't run through `wp_unslash` and therefore the email lookup fails to actually perform the login.
