### ISSUE TITLE
Nonce verification during Login & Registration doesn't affect processing

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#594]
The return value of nonce verification in https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.frontend.forms.php#L37 & https://github.com/gocodebox/lifterlms/blob/master/includes/controllers/class.llms.controller.registration.php#L56 isn't taken into account while processing the form at all.

That's a security issue since anyone would be send post data for login and registration using a stale or no nonce at all.

**Comment by thomasplevy** [comment]
Fixed via #605
