### ISSUE TITLE
core assets loaded with technically invalid URI

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#598]
Notice double slash in attached screencaps

![view-source_helpless-baboon_w5_wpsandbox_pro_wp-admin_admin_php_page_llms-course-builder_course_id_9_llms-action--edit-assignment](https://user-images.githubusercontent.com/1290739/41996450-cc992228-7a09-11e8-8d9b-2864aed1c98a.jpg)

![view-source_helpless-baboon_w5_wpsandbox_pro_wp-admin_admin_php_page_llms-course-builder_course_id_9_llms-action--edit-assignment](https://user-images.githubusercontent.com/1290739/41996480-e144eb80-7a09-11e8-8d80-1522615d4a00.jpg)

**Comment by actual-saurabh** [comment]
That's because `LLMS_PLUGIN_URL` has a trailing slash, so the assets enqueue scripts on admin need to be updated to remove the initial slash.
