### ISSUE TITLE
Logged in user already enrolled in a product should be redirected on checkout form

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#607]
### 1. Reproduction Steps

1. Enroll yourself into a product (course/membership).
1. Log out.
1. Click through the product to reach checkout page.
1. Use the login form to login.

### 2. Expected Behavior

Since you're already enrolled into the product, you should get redirected to the product and shouldn't be able to access the checkout form, at all.

### 3. Actual Behavior

Nothing happens, you end up on the same screen as a logged in user and can see all the checkout options. You only get the error after attempting to pay:

![screen shot 2018-07-04 at 6 20 59 pm](https://user-images.githubusercontent.com/1739834/42278037-102c8a5e-7fb7-11e8-8508-e07bf7cba6b4.png)

A visitor trying to buy the product has a better experience where they are redirected to the product page after finishing checkout

**Comment by actual-saurabh** [comment]
If a LifterLMS User object is initialised early with user_postmeta information (since the user is initialised way before queries are run), we could consolidate all permission and capabilities validations at one place before template load. (

For example, we could load ids of all the courses/memberships a particular user is enrolled in, right at the start.

So, if a user logs in _after_ landing on a checkout page, instead of performing a check on checkout attempt, we could know this immediately and display a message informing them of that (or straightaway redirect to the course/membership with the message).

**Comment by eri-trabiccolo** [comment]
Hi @actual-saurabh 
so what do we want to have here?
1) Display a message informing them of that
or
2) Straightaway redirect to the course/membership (or maybe better to the checkout redirect URL) + message.

I'm more for 1) to be honest as I don't like to be redirected eheh.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Validation takes place when the checkout form is submitted and displays an error message, this same behavior (message with link) should take place before checkout. The initialization of an object is a good idea but not necessary to solve this problem.

A simple enrollment check can be preformed within the checkout form shortcode logic.

**Comment by eri-trabiccolo** [comment]
@thomasplevy perfect for me, yeah I got where I should do the check, thanks for clarifying the expected behavior. :)
