### ISSUE TITLE
Course Drip generates warning when previewing as student (without actual enrollment)

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#620]
`Warning: A non-numeric value encountered in /path/wp-content/plugins/lifterlms/includes/models/model.llms.lesson.php on line 137`

In https://github.com/gocodebox/lifterlms/blob/a3c709f5bde0051cf898a710bba84735fda607a0/includes/models/model.llms.lesson.php#L137, the `$course->get_date( 'start_date', 'U' )` returns an empty string as per https://github.com/gocodebox/lifterlms/blob/master/includes/abstracts/abstract.llms.post.model.php#L414, when an unenrolled admin tries to preview the course.

So, maybe when the preview token is active, we could use the current date as the start date. Not sure whether the change should be made in the post abstract or in the lesson model.

**Comment by thomasplevy** [comment]
Have a customer report of this warning but I'm struggling to recreate...

**Comment by eri-trabiccolo** [comment]
Found the way.
Create a course with no "Course Time Period", or anyways with an empty start date.

Create a lesson of this course with a drip setting Method as "After course start date" and set e.g. 2 days.

Visit the course page as admin, but use the View manager to view it as student (non enrolled in that course).
Look at either the syllabus and/or your error log.

**Comment by thomasplevy** [comment]
Woooo thanks @eri-trabiccolo, patch incoming

**Comment by thomasplevy** [comment]
@eri-trabiccolo figured it out... I think this stems from the Lesson "Prerequisites" tab on the lesson options metabox from allowing users to choose the "Start Date" prereq settings for a lesson even when the course *does not have* a start date.

The course builder runs a check like this but the lesson metabox does not.

The above patch will prevent the warning for lessons already in this state but to prevent it from happening all together we should also fix the metabox:

https://github.com/gocodebox/lifterlms/blob/7f8db29cb999701c7fbaf85198d50d122eaf4637/includes/admin/post-types/meta-boxes/class.llms.meta.box.lesson.php#L54

This method for `start` should only be added to the dropdown when the course has an explicit start date.
