### ISSUE TITLE
Error Occur During Istallation of LifterLMS-master

### ISSUE THREAD

**Issue by Murtazaaaaa** [gocodebox/lifterlms#621]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\wp16\wp-content\plugins\lifterlms-master\lifterlms.php on line 29

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\wp16\wp-content\plugins\lifterlms-master\lifterlms.php on line 29

Please help me to resolve this issue. Thankyou

**Comment by thomasplevy** [comment]
duplicate of #622
