### ISSUE TITLE
Rror occur during Activation of LifterLMS 

### ISSUE THREAD

**Issue by Murtazaaaaa** [gocodebox/lifterlms#622]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\wp8\wp-content\plugins\lifterlms-master\lifterlms.php on line 29

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\wp8\wp-content\plugins\lifterlms-master\lifterlms.php on line 29

**Comment by thomasplevy** [comment]
@Murtazaaaaa the repo here is not an installable plugin so if you want to install for development from git please follow these instructions: https://github.com/gocodebox/lifterlms#installing-for-development

If you're looking for production-ready installable releases check the releases tab here on github or head to http://wordpress.org/plugins/lifterlms and click the "download" link for the latest stable release
