### ISSUE TITLE
BuddyPress profile doesn't have a LifterLMS "Notifications" tab

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#627]
![_62167_lifter_lms_notifications_to_be_listed_in_buddypress_area_-_science_cosmos](https://user-images.githubusercontent.com/1290739/44063452-5b7047e4-9f15-11e8-942a-7f2062afe4fc.jpg)

**Comment by yojance** [comment]
Submitted a PR for this #693
