### ISSUE TITLE
Unable to remove lifterlms_after_loop_item_title hooked enroll functions

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#630]
### 1. Reproduction Steps

Inject the following code in a page where there is the `[lifterlms_my_account]` and remove `lifterlms_template_loop_enroll_status` and `lifterlms_template_loop_enroll_date`.

Here is my code:
```php
remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_status', 25 );
remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_date', 30 );
```

As you can see I am following the same priority of those actions declared in `llms.functions.templates.dashboard.php:35,36,106,107`. 

By the way I do not understand why you're removing those later on in the code, in the lines `74,75,122,123` but I imagine you have your reasons to do so.

### 2. Expected Behavior

I would like to remove the enroll status and date of the course.

### 3. Actual Behavior

Even if I try to remove those functions the informations are still on the page. 

I am usign Genesis framework and I want to personalize the Student Dashboard page selecting the Template Page, [here's the code](https://gist.github.com/AndreaBarghigiani/083c0801a9055bfa68e209c22be0b301#file-template-bacheca-php) I am running in order to customize the page. 

### 4. Error Messages / Logs

There is no error message, the `remove_action` just doesn't work.

### 5. System Report

I've added the [System Report](https://gist.github.com/AndreaBarghigiani/083c0801a9055bfa68e209c22be0b301#file-system-report-txt).

### 6. Browser, Device, and Operating System

iMac 
macOS 10.13.6
Firefox 61.0.2

PS: I know that this is more a support request than a bug but since it is quite technical I preferred to publish here.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani try late initialization to remove actions... when removing from a plugin quite often the actions to remove end up running PRIOR to the actions to add in the LifterLMS core... this means that your code will never work...

try this:

```php
function my_late_init_func() {
   remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_status', 25 );
   remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_date', 30 );
}
add_action( 'init', 'my_late_init_func', 100 );
```

NOTE: closure used for ease of example... you should be okay with a closure but some people just really don't like them and I avoid them in production code

**Comment by AndreaBarghigiani** [comment]
Hi @thomasplevy and thanks for the quick reply. Actually I've tried your suggestion with this code:
```php
add_action( 'wp_head', 'remove_my_action' );
function remove_my_action(){
	remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_status', 25 );
	remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_date', 30 );
}```

And it wasn't working, unfortunately even the code you suggested on the `init` hook is working.

I've removed plenty of actions from LifterLMS in pages as `single-course.php` or `single-lesson.php` (following the Template Hierarchy) and with the files in the `template/` moving them into my theme.

Those are the only two hooks that I am not able to remove and I would prefer not to use the CSS in order to hide them.

**Comment by thomasplevy** [comment]
sorry i should have looked closer at the actions you're using...

try this

```php
add_action( 'lifterlms_before_loop', function() {
   if ( is_llms_account_page() ) {
      	remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_status', 25 );
	remove_action( 'lifterlms_after_loop_item_title', 'lifterlms_template_loop_enroll_date', 30 );
   } 
} );
```

these actions are added dynamically on the dashboard template function at https://github.com/gocodebox/lifterlms/blob/cdbee2b4b3bfabf3339bd6870f3d3af8e9227da0/includes/functions/llms.functions.templates.dashboard.php#L35

It's added this way because the loop function is shared between the dashboard and the catalogs and we don't want this information displayed on the catalogs... 

I wouldn't consider this a bug so much as a bit of a denser use case that requires more complicated code to remove the actions...

The above should work

**Comment by thomasplevy** [comment]
the `is_llms_account_page()` check actually probably isn't necessary now that I think about it

**Comment by AndreaBarghigiani** [comment]
Hi @thomasplevy,
I confirm that the code without the `is_llms_account_page()` is working just fine! Actually I do not know why this check isn'w working...

I've looked into my database and I found the `lifterlms_myaccount_page_id` with the correct ID in it but this check didn't return `true`.

Anyway this probably is a different problem and to be clear I didn't think of it as a bug, I was looking more for help than anything else and you helped me a lot solving my problem!

I am going to close this.

Thank you so much Thomas, is a pleasure use your product.

Talk you soon,
Andrea

**Comment by thomasplevy** [comment]
code should work with or without it `is_llms_account_page()` a quick tests results in my local test site and unit tests working properly when using this function... not sure why it wouldn't work on your site but if you want to explore that further please open a NEW issue with details on the bug.

Best
