### ISSUE TITLE
tests do not start

### ISSUE THREAD

**Issue by WhySpice** [gocodebox/lifterlms#634]
After creating and filling in the lessons, the created tests are no longer started. In the browser console I catch errors:

   ```
 Uncaught TypeError: Cannot read property 'ajaxurl' of undefined
    at llms.js:155
    at llms.js:15

content.js:150 Error: Cannot set user agent for iframe with location different to this page

llms-quiz.js:558 Uncaught TypeError: LLMS.l10n.translate is not a function
    at Object.load_ui_elements (llms-quiz.js:558)
    at Object.start_quiz (llms-quiz.js:355)
    at HTMLButtonElement.<anonymous> (llms-quiz.js:85)
    at HTMLButtonElement.dispatch (jquery.js?ver=1.12.4:2)
    at HTMLButtonElement.y.handle (jquery.js?ver=1.12.4:2)

```
What to do?

**Comment by thomasplevy** [comment]
@WhySpice 

At a glance it appears that assets are not being loaded in the correct order. I'm not sure why that would be happening. With the provided information I'm not going to be of much assistance to you. Could you please update your issue to include the information found in the issue template which was prefilled for you when you opened this issue. A copy of the template can be found here: https://github.com/gocodebox/lifterlms/blob/master/.github/issue_template.md

Please make sure you've ruled out plugin conflicts by disabling all plugins except LifterLMS and switching to a WP core theme (one of the "twenty").

Thanks

**Comment by thomasplevy** [comment]
@WhySpice bump!

**Comment by thomasplevy** [comment]
@WhySpice closing this information due to inactivity. Please respond with requested information and we'll reopen.
