### ISSUE TITLE
Docs directory for developer docs

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#641]
Create a `docs` directory in root that is excluded from the build & distribution. This will contain all the developer documentation in markdown. Such markdown can be utilised elsewaher, for example, imported into make.lifterlms.com. 

The purpose of keeping dev docs within the repository is to encourage developers to also contribute to the documentation either as standalone contributions or as a requirement for PRs. This will ensure that documentation is up-to-date and accurate.

This process will kickstart with #636 where the dev documentation is created before and alongside the actual code.

**Comment by actual-saurabh** [comment]
This would also be useful for maintaining developer documentation related issues alongside code changes since they need to be tightly aligned.

**Comment by thomasplevy** [comment]
see related #637 too
