### ISSUE TITLE
from where i can get the docementation to use it in wordpress and fix my notification issue

### ISSUE THREAD

**Issue by farrukh1321** [gocodebox/lifterlms#642]
i already have installed lifterlms in my wordpress website but the issue is that the engagements which i have set for the emails they working perfectly but the notification for the new user signup is not working fine. it sends the wordpress pre notification which i want to change with my lifterlms new user signup notification. The lifterlms team has said me to use these codes to fix the issue but i dont understant how i can use this code in my wordpress website.

https://github.com/gocodebox/lifterlms/blob/master/includes/notifications/controllers/class.llms.notification.controller.enrollment.php#L29-L32 

https://github.com/gocodebox/lifterlms/blob/master/includes/abstracts/llms.abstract.notification.controller.php#L118-L141

https://github.com/gocodebox/lifterlms/blob/master/includes/notifications/class.llms.notifications.php#L262

https://github.com/gocodebox/lifterlms/blob/master/includes/notifications/controllers/class.llms.notification.controller.enrollment.php#L34-L50

**Comment by farrukh1321** [comment]
yes i know this already. i dont find out how can i do this. i already have tried tons on things but nothing is working there. can you please little elaborate that how i can do it.

**Comment by thomasplevy** [comment]
@farrukh1321 the notification is sent by WordPress and nothing you modify in LifterLMS will change that... WPBeginner has an article on how to turn off this WP core notification: https://www.wpbeginner.com/plugins/how-to-disable-new-user-notifications-in-wordpress/

Again, NOTHING in LifterLMS will modify this notification... It's not coming from LifterLMS, it's part of the WordPress core.

**Comment by farrukh1321** [comment]
i already have tried all these things but no results.
and i know that it is a wordpress issue but every other mail is sending from the lms but this new user is the only mail which is sent from default.

**Comment by thomasplevy** [comment]
@farrukh1321,

I'm sorry that you're having issues here but this is not an issue we can help you with in this channel.

Our GitHub repo is for bug reports and issues related DIRECTLY to the LifterLMS core codebase. Check out our guidelines [here](https://github.com/gocodebox/lifterlms#getting-help-and-support-support). There are a number of ways to get general help and support with LifterLMS but GitHub is not one of them.

I realize that it may seem like the issue you're reporting is a LifterLMS bug but it's not. It's a notification from the WordPress core, and as such, while I'm sure our support team can help you're requesting assistance in the wrong place! Please understand that we WANT TO HELP but we want to help in the correct channels. Again, this is not a general support form. This is a place for bug reports and contributions to the core LifterLMS codebase ONLY!

Please check out that link above for ways to get general help and support with LifterLMS.

You could also check out the free WordPress.org forums. Here's the forum I think you may want to post in: https://wordpress.org/support/forum/how-to-and-troubleshooting/

You could also check out the general WordPress.org support page at https://wordpress.org/support/

Thanks for your cooperation and best of luck.
