### ISSUE TITLE
LMS Manager does not show up in Gutenberg author dropdown

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#643]
I understand that Gutenberg is not yet rolled out and probably you already know this problem but I would like to open this issue as well because I would like to know your opinion about it.

I am referring to a problem well known in the Gutenberg ecosystem and you can read all about it in [this issue](https://github.com/WordPress/gutenberg/issues/8526#issuecomment-424426981).

As you can read from [my comment](https://github.com/WordPress/gutenberg/issues/8526#issuecomment-414112862) I am not able to find my LMS Manager account in the author dropdown menu.

The people that partecipated in the discussion are telling me that this is because the REST API call that Gutenberg uses to list the authors is looking for a specific `user_level` instead of the proper capability to read and publish post.

I understood that this is more a REST API issue than a LifterLMS one but will be able to see the LMS Manager role (as well as the Instructor one) inside this dropdown menu in a future release of the plugin?

### 1. Reproduction Steps
* create any kind of content inside WordPress (post, page, lesson or course)
* open the Document sidebar in Gutenberg
* open the author dropdown menu

### 2. Expected Behavior
List all the user profiles able to edit/publish a post, especially LMS Manager and Instructor.

### 3. Actual Behavior
No custom role are showed in this dropdown, only the ones that have at least a `user_level` of 1 (at least I think it from reading this [Codex page](https://codex.wordpress.org/User_Levels#User_Level_1)).

### 4. Error Messages / Logs
No error messages or logs.

### 5. System Report
I will not include the System Report because this has nothing to do with my installation but in how LifterLMS creates the User Roles.

## Proposed Solution
Reading the [last comment](https://github.com/WordPress/gutenberg/issues/8526#issuecomment-424426981) in the discussion a user suggest to use the [`wp role reset`](https://developer.wordpress.org/cli/commands/role/reset/) WP CLI command but I am afraid that this could mess up the User Roles inside my installation.

Do you think this could be the right solution for the moment?

Thank you in advance for the support.
Andrea

**Comment by thomasplevy** [comment]
@AndreaBarghigiani 

Short answer: we might be able to make this possible.

Long answer: the "post author" is not what LifterLMS uses to output instructor information. The "proper" solution is not currently available. I know Gutenberg is expected in September but let's all be really honest: that's not happening.

We're working on putting together a list of Gutenberg features.

This was NOT on my radar but I will look into it.

For the meantime I hope you can understand that Gutenberg is NOT a stable or official part of WordPress so we are NOT officially supporting it or taking any real stance on what the final feature set with regards to LifterLMS is going to look like as SO MUCH of Gutenberg is still unstable / not quite yet ready.

Thanks!

**Comment by AndreaBarghigiani** [comment]
Hi @thomasplevy,
I completely understand and agree with your feelings about Gutenberg. As I wrote I open this issue just to let you know this kind of problem with the new "editor" that is not related only on your plugin.

Anyway I'm in the middle of a relocation but I hope to have time and work on some issues during the Hacktoberfest. I am also studying the creation of Gutenberg blocks so if you want to delegate some work in this field ill be more than happy to help you out.

I think one of the better way to start will be to convert the LifterLMS shortcodes keeping them for backward compatibility.

All the best,
Andrea

**Comment by thomasplevy** [comment]
This is resolved via https://github.com/gocodebox/lifterlms-blocks/issues/14
