### ISSUE TITLE
Convert Shortcodes to Gutenberg Blocks

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#661]
All blocks must be built using JSX/ES Next (not ES5!)

See prerequisite task in lifterlms-lib-tasks: https://github.com/gocodebox/lifterlms-lib-tasks/issues/3

Shortcodes should not be removed for now

**Comment by AndreaBarghigiani** [comment]
As discussed in #664 I will present here the copy of the first proposal for Gutenberg blocks:

Blocks for the course Gutenberg template:
- [x] Paragraph (done by Gutenberg)
- [ ] Course Info
- [ ] Course Instructor
- [ ] Access Plans 
- [ ] Course Syllabus (I think we'll be better if we merge into it also the Course Outline and let decide the users via the Gutenberg Inspector)

Beside them I think those are other useful blocks in the General use of LifterLMS (I took inspiration also from your [shortcode page](https://lifterlms.com/docs/shortcodes/):
- [ ] Access Plan Button
- [ ] Course CTA Section (to drop course information into any post)
- [ ] Course Prerequisites
- [ ] Course Reviews
- [ ] Hide Content Block 
- [ ] Pricing table (I am [experimenting with Gutenberg](https://github.com/skillsAndMore/sam-gutenberg) and this kind of block is on my list 😉)

**Comment by thomasplevy** [comment]
Moving to lifterlms-blocks: https://github.com/gocodebox/lifterlms-blocks/issues/2
