### ISSUE TITLE
Course Builder quiz editor "Total Points" area doesn't update when points value of questions change

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#673]
### 1. Reproduction Steps

+ Open any quiz in the course builder
+ Increase or decrease the points value of any question in the quiz

### 2. Expected Behavior

+ Total Points in header should update to reflect the new total

### 3. Actual Behavior

+ Total doesn't update

This appears to be a visual issue only. Total points and grading is unaffected when taking a quiz. Additionally when refreshing the builder and reopening the total points value reflects the new correct total.

**Comment by tthompson899** [comment]
I'd like to help out with this. New to the hacktoberfest so I'm sure how I would assign this issue to myself.

**Comment by tthompson899** [comment]
I may have overlooked it but are there instructions on getting this up and running locally? I saw where you install composer and gulp but was there anything else I need?

**Comment by thomasplevy** [comment]
@tthompson899 composer & gulp here: https://github.com/gocodebox/lifterlms#installing-for-development

You can refer to [lifterlms-lib-tasks](https://github.com/gocodebox/lifterlms-lib-tasks) for all the available gulp tasks you can use for development, see https://github.com/gocodebox/lifterlms-lib-tasks for a tasklist

**Comment by thomasplevy** [comment]
This appears resolved somehow (v3.26.3)
