### ISSUE TITLE
Documentation should contain build instructions

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#682]
Not sure if this should be in `Contributing.md` `./docs/` or the Wiki but the build process should be documented somewhere.

**Comment by thomasplevy** [comment]
Build process is at https://github.com/gocodebox/lifterlms#installing-for-development

Should be moved, you're correct. Will update in the future

**Comment by thomasplevy** [comment]
Build instructions now exist at https://github.com/gocodebox/lifterlms/blob/master/docs/installing.md
