### ISSUE TITLE
[Quiz] Backslashes added to Quotes that are present in answers (long answer)

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#685]
### 1. Reproduction Steps

Add a long answer question to a Quiz. Place some text in "double quotes" in the answer.

### 2. Expected Behavior

The attempt result should show the double quotes as expected.

### 3. Actual Behavior

The quotes end up with backslashes \"double quotes\".

![screen shot 2018-10-10 at 6 07 29 pm](https://user-images.githubusercontent.com/1739834/46738224-48f88f80-ccbb-11e8-84ea-ff911d266757.png)

### 4. Error Messages / Logs

NA

### 5. System Report

NA

### 6. Browser, Device, and Operating System

NA

**Comment by actual-saurabh** [comment]
This is a known behaviour where all request data gets slashed this way. To test, I modified the following line: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.ajax.handler.php#L564

```php
$answer = array_map( 'stripslashes_deep', isset( $request['answer'] ) ? $request['answer'] : array() );
```

This fixed the issue. However, I'm not sure how this affects other things and would test this more before attempting a proper fix.

**Comment by actual-saurabh** [comment]
This has now been reported for Fill in the Blanks, as well.

**Comment by thomasplevy** [comment]
Ensure `stripslashes_deep` doesn't strip line breaks like `\r` or `\n`
