### ISSUE TITLE
[Quiz] Multiple Choice Questions (MCQ) Options don't work as expected on iOS

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#686]
### 1. Reproduction Steps

Open an MCQ on an iOS device. Touch an option to select it.

### 2. Expected Behavior

The option should get selected on a single touch.

### 3. Actual Behavior

When attempting to select an option, a single tap wouldn't work and you have to tap again (or use a long touch) for the option to be actually selected).

### 4. Error Messages / Logs

NA

### 5. System Report

NA

### 6. Browser, Device, and Operating System

Any browser on any iOS device 

This happens because of a peculiarity of iOS. See: https://css-tricks.com/annoying-mobile-double-tap-link-issue/ and is related to https://github.com/gocodebox/lifterlms/blob/master/assets/scss/frontend/_llms-quizzes.scss#L211-L219

I'm not sure of a fix at this point. The easy way out seems to be removing the hover state altogether or find a way to remove it on iOS (or any mobile device).

Also see: https://codepen.io/chriscoyier/pen/yaoAaL (from the css-tricks article)

**Comment by thomasplevy** [comment]
@actual-saurabh can you please define MCQ for me

**Comment by thomasplevy** [comment]
thanks!

**Comment by thomasplevy** [comment]
I imagine this is in regard to a support request I've been dealing with and abandoned during my week away... I've been digging into this and doing and undoing the behavior and struggling all the while to find definitive solutions...

Please take a look at my most recent update to the quiz interface which attempts to fix this here: https://github.com/gocodebox/lifterlms/commit/9c41651956734a277e0a4ad714f4b8ec42d5d0ae

A while back this fix that's commented out was added to resolve this issue however this fix caused new issues:

1. Scrolling now selects an item if you touch an item to scroll
2. MCQs with multiple correct answers stopped functioning

I removed this code and tested on a simulator via BrowserStack (I don't have access to a physical iPone) and this fixed the new issues and the old issues I was no longer able to recreate.

I'm puzzled.

**Comment by thomasplevy** [comment]
@actual-saurabh does the fix from above help with this at all? Have you had a chance to take a look at it.

Thanks,
