### ISSUE TITLE
Add a "Display Name" field to student's profile information (privacy concern when commenting)

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#691]
**Is your feature request related to a problem? Please describe.**

Currently LifterLMS does not supply a `display_name` to `wp_insert_user()` when registering new users.

If account settings require (or allow) a name during registration the user's full name will be used and displayed publicly when commenting and the user will have no way to customize their name.

**Describe the solution you'd like**

Add a "Display Name" text field to the "Edit Account" area of the student dashboard so student's have the ability to choose their public display name.

LifterLMS Social Learning already implements this solution. If we add this to the core we should remove it from Social Learning to ensure there's no duplicate fields when using the add-on

**Comment by LiamBailey** [comment]
Would it be ok for me to tackle this?

**Comment by thomasplevy** [comment]
@LiamBailey absolutely, any questions let us know
