### ISSUE TITLE
get_current_screen() errors in PHP logs

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#698]
### 1. Reproduction Steps

I have a customer site with Yoast SEO Premium and LifterLMS and I've noticed several 500 errors. Digging around I've come to a counclusion that is not LifterLMS fault but I would like to let you know that I found my `php_errorlog` full of the same error.

### 2. Expected Behavior

No error.

### 3. Actual Behavior

I found `php_errorlog` full of errors.

### 4. Error Messages / Logs

```
[22-Oct-2018 08:34:14 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /home/cannab73/public_html/wp-content/plugins/lifterlms/includes/class.llms.playnice.php:78
Stack trace:
#0 /home/cannab73/public_html/wp-includes/class-wp-hook.php(286): LLMS_PlayNice->wp_seo_premium_redirects(false)
#1 /home/cannab73/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(false, Array)
#2 /home/cannab73/public_html/wp-content/plugins/wordpress-seo-premium/premium/classes/post-watcher.php(98): apply_filters('wpseo_premium_p...', false)
#3 /home/cannab73/public_html/wp-includes/class-wp-hook.php(286): WPSEO_Post_Watcher->detect_slug_change(590, Object(WP_Post), Object(WP_Post))
#4 /home/cannab73/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/cannab73/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /home/cannab73/public_html/wp-includes/post.php(3647): do_action('post_updated', 590, Object(WP_Post), Object(WP_Post))
#7 /home/cannab73/public_html/wp-incl in /home/cannab73/public_html/wp-content/plugins/lifterlms/includes/class.llms.playnice.php on line 78
```

### Advised solution

As you can read form the [WordPress Codex](https://codex.wordpress.org/Function_Reference/get_current_screen), this function should be called with the `current_screen` hook but instead is fired inside the `wp_seo_premium_redirects()` via the `wpseo_premium_post_redirect_slug_change` filter hook.

I am sorry but I do not have time to debug it deeper.

All the best!

**Comment by moorscode** [comment]
Bumped into this issue during Hacktoberfest.

Looking at the code it requires a bunch of crazy, undesired things to solve this problem, _unless_ the filter in Yoast SEO provides additional context.

I have created an issue on the Premium repository to add `$post_id`, `$post`, `$post_before`.
