### ISSUE TITLE
PHP: Unit & Integration Tests

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#699]
The test coverage for the codebase is currently at an embarrassing 22%: https://codeclimate.com/github/gocodebox/lifterlms

Unit & Integration tests will improve this! We have a testing framework already built: https://github.com/gocodebox/lifterlms/tree/master/tests

Anything that doesn't already have a test should be tested! In the hacktoberfest spirit I'm opening this issue for anyone interested in contributing tests!

**Comment by unt01d** [comment]
I'm up for helping with this @thomasplevy.  Can you point me in the direction of a good candidate to start off with?

**Comment by thomasplevy** [comment]
@unt01d 

most of the currency functions in this file don't have tests of any kind: https://github.com/gocodebox/lifterlms/blob/master/includes/functions/llms.functions.currency.php
