### ISSUE TITLE
This is where you can add new courses.

### ISSUE THREAD

**Issue by BurlesonBrad** [gocodebox/lifterlms#710]
### 1. Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced
Activate LifterLMS _(yep, that's about all 'ya gotta do)_
+ Include screenshots where applicable
![image](https://user-images.githubusercontent.com/6208757/47929893-5f4bd280-de98-11e8-9345-a4d5da17a547.png)
![image](https://user-images.githubusercontent.com/6208757/47929910-670b7700-de98-11e8-9ec0-7a1f54e21774.png)
+ Record a video if possible
I've got enough videos to clog a Panasonic Camcorder from 1988. Pretty sure the screenshots are enough.

### 2. Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)
I would expect that message to not appear on the front end of the site

### 3. Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)
Message Shows 👍 is what actually happens.  

### 4. Error Messages / Logs

+ Include any relevant error messages or log files
Line 254 👍

**Comment by eri-trabiccolo** [comment]
Hi there,
my 2 cents:

This doesn't seem to be a LifterLMS 'issue', but more something related to the theme.

Your OceanWP theme prints [the archive description](https://developer.wordpress.org/reference/functions/get_the_archive_description/) for what it calls "the page subheading", which, for the post type archives (as the Courses is), is the post type description set, as you pointed out, here:
https://github.com/gocodebox/lifterlms/blob/3.24.2/includes/class.llms.post-types.php#L254

Out of curiosity I've tested, how that theme behaves with the WooCommerce shop "page", which is the WooCommerce product post type archive, whose description is, similarly, defined here:
https://github.com/woocommerce/woocommerce/blob/3.5.1/includes/class-wc-post-types.php#L328
and I got exactly the same result.

We can discuss about how good "This is where you can add new courses" is :), or about whether the description is meant for front or back end, but I think that, unless the post type descriptions become customizable, high are the chances that, whatever the LifterLMS devs choose, they won't match the taste of all people. 
The problem, IMHO, is that that info should not be displayed there, and this is about the theme.
I think you should report this to the theme author, as that very theme is responsible for displaying that information there.

Having said that...
You can alter the theme page subheading. Here's a code snippet referring to the WooCommerce shop from the theme documentation:
https://docs.oceanwp.org/article/482-alter-the-shop-page-subheading

Using `is_post_type_archive( 'course' )` in place of `is_shop()` will contextualize it for LifterLMS course post type archive.


Alternatively you can always filter the LifterLMS course post type args, before the course post type is registered, clearing its description, e.g.
```php
function my_alter_llms_post_type_course_description( $course_data ) {
	unset( $course_data[ 'description' ] );

	// or set a custom description	
	// if ( is_array( $course_data ) ) {
	// 	$course_data[ 'description' ] = __( 'My course description', 'mytextdomain' );
	// }
	
	return $course_data;
}
add_filter( 'lifterlms_register_post_type_course',  'my_alter_llms_post_type_course_description' );
```

end of my 2 cents.

**Comment by thomasplevy** [comment]
@BurlesonBrad,

I've taken a look through the WordPress core documentation on the description field of custom post types. It's pretty unclear whether this description is supposed to ever be displayed on the frontend of a site or not. 

> **description**
> (string) (optional) A short descriptive summary of what the post type is.
> Default: blank

[Source](https://codex.wordpress.org/Function_Reference/register_post_type)

Digging a bit further into how OceanWP outputs this information, it seems there's a lot of functions in the WordPress core which seem to lean towards using this on the frontend instead of as admin-facing description of the post type.

So I think I'd recommend as an immediate action taking @eri-trabiccolo's code snippet to remove or customize the description.

I'm not sure there's any string I'll be able to come up with that everyone would be happy with for a forward facing description of courses. I think as a next step in the core we'll simply remove the description field since it is optional. Additionally, on these archive pages you can already add your own description information via the WYSIWYG editor on the page selected for your catalog.

Thanks for bringing it to our attention.

**Comment by toyinogun** [comment]
HS-174795

**Comment by mikesimpson416** [comment]
This issue is still relevant in 2022. I have just installed WordPress, Kadence theme and Lifter LMS and I get this on my course catalogue page.

It looks so unprofessional to have a bit of text like this appearing and it doesn't seem editable.

**Comment by BurlesonBrad** [comment]
> This issue is still relevant in 2022. I have just installed WordPress, Kadence theme and Lifter LMS and I get this on my course catalogue page.
> 
> It looks so unprofessional to have a bit of text like this appearing and it doesn't seem editable.

@mikesimpson416 : It is 'editable' 🤷‍♀️🤷‍♂️ .....mostly

It's over here on line 390:
https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.post-types.php#L390

Edit it however you'd like, but .... at least now 'ya know where it is ;-)

**Comment by thomasplevy** [comment]
@nrherron92 is this a recent change in Kadence or has this existed in Kadence for a while?

**Comment by nrherron92** [comment]
Hey all!

This setting can be turned off in Kadence by going into Appearance->Customize->LifterLMS->Course Archive and hiding the description setting for Course Archives

![image](https://user-images.githubusercontent.com/47434271/148800278-f992309d-18d9-4a6b-b0a4-ed3eb3c4f873.png)

**Comment by chrisbadgett** [comment]
I've noticed this on Kadence for a while and have used Natalie's method to hide it in the past.

**Comment by BurlesonBrad** [comment]
> I've noticed this on Kadence for a while and have used Natalie's method to hide it in the past.

Right.  But that is not a programmatic and practical solution.

Site authors should always be able to utilize their 'Course Description'.  _(much in the same way WC store owners would as well)_  The whole point is that there should not be some type of "not-removeable-for-the-average-consumer" text that magically appears in the description.

Many people use that area to display anything from SEO data to descriptive text and much more.

- Displaying the phrase "Cooking Classes" instead of having it hidden
- Adding a CTA button to the "Join" page instead of it being entirely hidden
- H1 + H2 + h3 keyword & text

So, regardless of theme, the default text should not ever be displayed - at all.
