### ISSUE TITLE
PHP Fatal error:  Uncaught DOMException: Not Found Error in .../wp-content/plugins/lifterlms/includes/class.llms.certificates.php:215

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#711]
I'm not sure why it happens but this has been reported by a couple of users while it seems to be just fine with others:

PHP Fatal error:  Uncaught DOMException: Not Found Error in /nas/content/live/missouricb/wp-content/plugins/lifterlms/includes/class.llms.certificates.php:215

The error seems to be *Raised if oldnode is not a child of this node.* according to the documentation. Which means that there are probably `<link>` tags that are attempted to be replaced that aren't children of the header tag.

Using this logic and the fact that all the `<link>` tags are removed anyway at https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.certificates.php#L219-L222, I simply removed the replacement code and simply appended the `<style>` tag.

This fixes the fatal error without affecting the functionality!

The code here: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.certificates.php#L182-L216 becomes

```
			// inline stylesheets
			foreach ( $links as $link ) {

				// only proceed for stylesheets
				if ( 'stylesheet' !== $link->getAttribute( 'rel' ) ) {
					continue;
				}

				// save href for use later
				$href = $link->getAttribute( 'href' );

				// only include local stylesheets
				// this means that external fonts (google, for example) are excluded from the download
				// sorry... (kind of)
				if ( 0 !== strpos( $href, get_site_url() ) ) {
					continue;
				}

				// get the actual CSS
				$stylepath = strtok( str_replace( get_site_url(), untrailingslashit( ABSPATH ), $href ), '?' );
				$raw = file_get_contents( $stylepath );

				// add it to be inlined late
				$tag = $dom->createElement( 'style', $raw );
				$dom->appendChild( $tag );
			}
```

**Comment by actual-saurabh** [comment]
I have had the opportunity to see this happen on more sites. In each of these, at least one `<link>` tag seems to output outside `<head>`. I'm not sure why but many themes and plugins seem to be doing that and adding `<link>' tag at the end of `body`.

**Comment by actual-saurabh** [comment]
According to MDN here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link,

>A `<link>` element can occur either in the `<head>` or `<body>` element, depending on whether it has a **link type** that is *body-ok*. For example, the `stylesheet` link type is body-ok, and therefore `<link rel="stylesheet">` is permitted in the body. However, this isn't a good practice to follow; it makes more sense to separate your `<link>` elements from your body content, putting them in the `<head>`.

**Comment by thomasplevy** [comment]
so the issue is here: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.certificates.php#L213-L216

Easy fix (I think)
