### ISSUE TITLE
[i18n] Make Course and Membership archive strings translatable

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#712]
The fallback for the has_archive parameter is a string which should be translatable. See https://github.com/gocodebox/lifterlms/blob/42b79e169f9a0d5b74b34c37b014891b93fcc51b/includes/class.llms.post-types.php#L270 and https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.post-types.php#L454 where `courses` and `memberships` are strings that aren't i18n'ed. 

Contrast with the slug for single course/membership here https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.post-types.php#L264 and here https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.post-types.php#L448.

**Comment by caban13** [comment]
I am very happy with this issue, it's a very good improvement! Thanks.
