### ISSUE TITLE
Fatal error on Launchpad Activation through LifterLMS > Settings > Addons

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#717]
### 1. Reproduction Steps

Activate Launchpad from Addons section.

### 2. Expected Behavior

Theme should get activated, no errors

### 3. Actual Behavior

Fatal error because the variable `$addon` isn't defined here: https://github.com/gocodebox/lifterlms/blob/3b0a831c6de3f02de6eeda69440afea53725122d/includes/models/model.llms.add-on.php#L80

### 4. Error Messages / Logs

`Uncaught Error: Call to a member function get() on null in /path/to/wp/wp-content/plugins/lifterlms/includes/models/model.llms.add-on.php:80`

### 5. System Report

NA

### 6. Browser, Device, and Operating System

NA

**Comment by thomasplevy** [comment]
Should be `$this->get()`
