### ISSUE TITLE
Enrollment visibility in block settings doesn't save properly.

### ISSUE THREAD

**Issue by SaeedMasri** [gocodebox/lifterlms#718]
Hi guys, 
When I add a new LifterLMS's block, say the course syllabus block and change the visibility to "enrolled users", sometimes it doesn't save that after I update the course, especially when you add a new block and not editing the visibility for a previously added one.
I figured out that changing the option from the drop-down menu"Enrolled In" to something else and come back to "in this course" make it work and save after I update the course. I hope I made it clear and sorry if it's already previously submitted/on your bugs radar.

Cheers

**Comment by thomasplevy** [comment]
@SaeedMasri 

I'm trying to reproduce this issue but I'm not finding a way to get the visibility data to _not save_ in any capacity. In all of my tests it's saving every time no matter how hard I try to break them.

Can you check out the issue template [here](https://raw.githubusercontent.com/gocodebox/lifterlms/master/.github/ISSUE_TEMPLATE/Bug_Report.md) and add a comment with all the information in the template.

Thanks

**Comment by SaeedMasri** [comment]
@thomasplevy 

### 1. Reproduction Steps

First step in the video shows the bug, and then my work around which I mentioned in the previous comment in order to make it save the visibility condition.

https://www.youtube.com/watch?v=Kyxfv7lVmXc

### 2. Expected Behavior

It doesn't save the enrollment visibility for enrolled students only.

### 3. Actual Behavior

After saving, It shows the block to everyone!

### 4. Error Messages / Logs

No error messages!

### 5. System Report

Wordpress
-------------------------------------------

Home Url: https://liftrademo.pilvia.site
Site Url: https://liftrademo.pilvia.site
Login Url: https://liftrademo.pilvia.site/wp-login.php
Version: 5.0
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#103) [https://liftrademo.pilvia.site/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.25.0
Db Version: 3.25.0
Course Catalog: Course Catalog (#18) [https://liftrademo.pilvia.site/courses/]
Membership Catalog: Membership Catalog (#19) [https://liftrademo.pilvia.site/memberships/]
Student Dashboard: Custom Dashboard (#513) [https://liftrademo.pilvia.site/custom-dashboard/]
Checkout Page: Purchase (#20) [https://liftrademo.pilvia.site/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: sallory@gmail.com
Email From Name: Astra Demo
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 256 MB
Php Memory Limit: 128M
Php Post Max Size: 256M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.1.17
Software: nginx/1.12.2
Wp Memory Limit: 128M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Nineteen
Version: 1.0
Themeuri: https://github.com/WordPress/twentynineteen
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Astra Pro: 1.6.6.1
Easy Theme and Plugin Upgrades: 2.0.1
Elementor: 2.3.5
Elementor Extras: 1.9.15
Elementor Pro: 2.1.10
Envato Elements - Template Kits (Beta): 0.1.2
LifterLMS: 3.25.0
LifterLMS Helper: 3.0.2
LifterLMS MailChimp Add-on: 3.1.0
Loco Translate: 2.2.0
User Menus: 1.1.2
Webcraftic Disable Admin Notices Individually: 1.0.6


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS MailChimp: No


Template Overrides
-------------------------------------------



Another fellow in LifterLMS's facebook  group experienced the same issue:

https://www.facebook.com/groups/lifterlmsvip/permalink/1966609180074452/?comment_id=1967992833269420&reply_comment_id=1968203213248382&comment_tracking=%7B%22tn%22%3A%22R%22%7D


Cheers

**Comment by thomasplevy** [comment]
Thanks @SaeedMasri 

This actually appears to be a bug in the "View as" functionality which I haven't spend a second of time looking at since 5.0 was announced. Can you help confirm -- if you view that same course with those settings in a private browsing session the syllabus should be hidden.

**Comment by thomasplevy** [comment]
Fix coming in LifterLMS Blocks 1.1 / LifterLMS core 3.25.1
