### ISSUE TITLE
lifterlms_lesson_completed is not returning the course ID

### ISSUE THREAD

**Issue by mjugger** [gocodebox/lifterlms#719]
### 1. Reproduction Steps

When adding my function to an action listener for the `lifterlms_lesson_completed` action I only get the ID of the user that completed the course but not the ID of the course that was just completed.

### 2. Expected Behavior

```php
add_action( 'lifterlms_course_completed', 'my_fn' );
function my_fn($user_id, $course_id) {
    var_dump($course_id); // should be the ID of the course that was completed (i.e. 4033)
}

```

### 3. Actual Behavior
```php
add_action( 'lifterlms_course_completed', 'my_fn' );
function my_fn($user_id, $course_id) {
    var_dump($course_id); // is null
}

```

**Comment by eri-trabiccolo** [comment]
Hi mjugger,
you need to specify the number of args you intend to pass to the action callback, which by default is 1, hence only the first callback argument ($user_id) has a value.
See: https://developer.wordpress.org/reference/functions/add_action/

So in your case, you should use:
```php
add_action( 'lifterlms_course_completed', 'my_fn', 10, 2 );
```

Does this fix the issue for you?

**Comment by mjugger** [comment]
@eri-trabiccolo 
Yes, it does fix it. man I feel dumb (been a long week lol)
Thanks @eri-trabiccolo
