### ISSUE TITLE
Get posts by rest api

### ISSUE THREAD

**Issue by trananhvinh** [gocodebox/lifterlms#721]
I have an ios app and I want to get posts from wordpress website (post in LifterLMS). How can I use your api to do it?

**Comment by thomasplevy** [comment]
@trananhvinh unfortunately we haven't constructed a rest API yet. It's on our roadmap and we realize the importance of having a rest api in these times but we just don't have one yet. 

That said it is fully possible to use our internal APIs to retrieve data about courses and so on. You could construct your own API endpoints in a custom plugin to pull that data.
