### ISSUE TITLE
Lesson prereq not set when prerequisite is toggled "on" for a lesson

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#724]
### 1. Reproduction Steps

+ Create at least 2 lessons in the course builder
+ Enable a prerequisite for lesson 2 by toggling the prereq on for the lesson settings

### 2. Expected Behavior

+ Lesson one (the default and only available lesson for the prerequisite options) will be the selected prerequisite for the lesson

### 3. Actual Behavior

+ Prerequisite will *show* as enabled but the value stored in the DB for lesson 2's prereq will be `0` instead of the ID of lesson 1
+ This is occurring because the "change" event on the select box doesn't fire when enabling the prereq

**Comment by JeremyGruver** [comment]
Was this ever fixed or addressed? Currently, a course in the latest LifterLMS, the lesson pre-req doesn't work. I can go to a lesson below it and mark it as complete.

**Comment by thomasplevy** [comment]
@JeremyGruver 

This issue doesn't have much to do with behavior of prereqs on the frontend of the site. This particular issue was preventing data from being saved properly. And yes, this issue was addressed.

If you're encountering a different bug please report it as such. Please pay attention to the issue report template and take a look at the readme first: https://github.com/gocodebox/lifterlms#reporting-a-bug. Remember that GitHub is for developers and contributors. It's __not__ a support forum. If you need help and support with LifterLMS as a user there's a ton of options for you (but not GitHub): https://github.com/gocodebox/lifterlms#getting-help-and-support-support

Before you do anything else though: make sure you're not trying to "test" prerequisite functionality as an administrator or a course instructor. These roles *automatically* bypass prerequisites so that you can easily edit and review your content despite the presence of a prereq!
