### ISSUE TITLE
Sales reporting chart shows "Net Sales" as a bar if "Net Sales" returns it's data last in the series of metrics

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#740]
### 1. Reproduction Steps

+ In `LLMS_Analytics_Sold_Widget` add a `sleep( 3 )` in the `format_response()` method to force the query to take a while.
+ View the sales reporting tab

### 2. Expected Behavior

+ Net sales should always be a line graph

### 3. Actual Behavior

+ Net sales will be the last returned metric and will display as a bar chart instead of a line chart

### 4. Error Messages / Logs

+ N/A

### 5. System Report

+ Latest

It looks like the series data is being assigned numerically instead of being linked to the actual data type

**Comment by eri-trabiccolo** [comment]
Really weird issue.
I've reproduce the issue following the described steps, and I get different charts mostly anytime I refresh the page:
- take 1 (note that also the axis are wrong):
![Schermata 2019-06-05 alle 21 39 15](https://user-images.githubusercontent.com/7689242/58985078-d2c11400-87da-11e9-9af3-0900fda2d3ac.png)

- take 2:
![Schermata 2019-06-05 alle 21 43 00](https://user-images.githubusercontent.com/7689242/58985163-0603a300-87db-11e9-9657-bedec3c818d8.png)

- take 4:
![Schermata 2019-06-05 alle 21 44 47](https://user-images.githubusercontent.com/7689242/58985258-33e8e780-87db-11e9-9cb1-085cdefa3cec.png)

anyway I get wrong/inconsistent charts, even if more rarely and I don't know why, also without adding the `sleep( 3 )` see:
![Schermata 2019-06-05 alle 21 49 27](https://user-images.githubusercontent.com/7689242/58985543-d86b2980-87db-11e9-9cde-c3a1e04d27fe.png)
