### ISSUE TITLE
Division by zero error for quizzes with 0 total possible points

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#750]
`includes/admin/reporting/class.llms.admin.reporting.php on line 410`

**Comment by pondermatic** [comment]
`( $args['data'] - $args['data_compare'] ) / $args['data'] * 100` will never be evaluated if `$args['data']` equals `0`, `'0'`, `''`, `null` or `false`.

**Comment by thomasplevy** [comment]
This shouldn't be possible. Closing
