### ISSUE TITLE
[Shortcodes] Course shortcode with "mine" parameter displays all courses if a student isn't enrolled in any

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#769]
https://github.com/gocodebox/lifterlms/blob/cdbee2b4b3bfabf3339bd6870f3d3af8e9227da0/includes/shortcodes/class.llms.shortcode.courses.php#L66 returns all courses if no enrolled ids are returned. 

Instead, it should return the same message as displayed on Dashboard > My Courses (https://github.com/gocodebox/lifterlms/blob/3bed5622fcd12da6a3a2e42397b0dbab6720e5b4/includes/functions/llms.functions.templates.dashboard.php#L118)

**Comment by thomasplevy** [comment]
@nrherron92 give us that PR please <3
