### ISSUE TITLE
LLMS_Order->unschedule_expiration() uses deprecated WooCommerce functions

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#770]
### 1. Reproduction Steps

+ Define `WP_DEBUG` to `true` in `wp-config.php`.
`define('WP_DEBUG', true);`
+ Enroll in a course.

### 2. Expected Behavior

+ The course information page is displayed with a "Get Started" button.

### 3. Actual Behavior

+ `Notice: wc_next_scheduled_action is <strong>deprecated</strong> since version 2.1.0! Use as_next_scheduled_action() instead. in /wordpress/src/wp-includes/functions.php on line 3923`
+ `Warning: Cannot modify header information - headers already sent by (output started at /wordpress/src/wp-includes/functions.php:3923) in /wordpress/src/wp-includes/pluggable.php on line 1223`

### 4. Error Messages / Logs

+ See "Actual Behavior".

### 5. System Report

WordPress 5.0.3
WooCommerce 3.5.5
LifterLMS 3.28.3

**Comment by thomasplevy** [comment]
@pondermatic,

You're right. WooCommerce recently bundled in the [Action Scheduler Library](https://github.com/Prospress/action-scheduler) developed by Prospress (the team behind WooCommerce Subscriptions). We're using a slightly outdated version of the library which is what's causing this warning to pop when using LifterLMS and WooCommerce on the same sites.

We'll be reworking all this as per issue #737. Currently I'm planning to include this in a release that will include a few other payment and library related updates, you can see the milestone here: https://github.com/gocodebox/lifterlms/milestone/30

If these are affecting a production website please disabled WP_DEBUG_DISPLAY which will prevent these warnings from __displaying__ the deprecation notices.

**Comment by pondermatic** [comment]
Thanks @thomasplevy ! Sounds like a good plan.

I noticed this issue on my development website.
