### ISSUE TITLE
Unable to edit Plan Description

### ISSUE THREAD

**Issue by RajeebTheGreat** [gocodebox/lifterlms#771]
### 1. Reproduction Steps

- Install WordPress 5.1
- Install LifterLMS 3.29.0-beta.1
- Go to Courses - Add Course - Access Plans - Add New 

![screen shot 2019-02-21 at 8 26 08 pm](https://user-images.githubusercontent.com/4414610/53213554-6cdbc280-3617-11e9-8945-d464edd0bdbf.png)

### 2. Expected Behavior

- Expected the TinyMCE to load properly and be able to add content to the Plan description

### 3. Actual Behavior

- Plan Description field is not unclickable. TinyMCE buttons do not show up.
- It does work when you delete the first Access Plan added and add a new one. 

### 5. System Report

Wordpress
-------------------------------------------

Home Url: http://localhost/llms
Site Url: http://localhost/llms
Login Url: http://localhost/llms/wp-login.php
Version: 5.1
Debug Mode: Yes
Debug Log: Yes
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes

Settings
-------------------------------------------

Version: 3.29.0-beta.1
Db Version: 3.29.0-beta.1
Course Catalog: Course Catalog (#5) [http://localhost/llms/courses/]
Membership Catalog: Membership Catalog (#6) [http://localhost/llms/memberships/]
Student Dashboard: Dashboard (#8) [http://localhost/llms/dashboard/]
Checkout Page: Purchase (#7) [http://localhost/llms/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: rajeebthegreat+lifterlms@gmail.com
Email From Name: LifterLMS
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no

Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1

Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 128 MB
Php Memory Limit: 20480M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.1
Software: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.1 mod_perl/2.0.8-dev Perl/v5.16.3
Wp Memory Limit: 20480M

Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

Theme
-------------------------------------------

Name: LifterLMS LaunchPad
Version: 2.4.6
Themeuri: https://lifterlms.com/launchpad/
Authoruri: https://gocodebox.com
Template: 
Child Theme: No
Llms Support: No

Plugins
-------------------------------------------

LifterLMS: 3.29.0-beta.1

Integrations
-------------------------------------------

BbPress: No
BuddyPress: No

Template Overrides
-------------------------------------------

### 6. Browser, Device, and Operating System

Tested on Chrome, MacBook Air, MacOS Mojave 10.14.3

**Comment by thomasplevy** [comment]
@RajeebTheGreat,

Struggling over here to recreate this can you check a few things for me:

Was this a brand new LifterLMS site or did you upgrade to the beta? 

If it was an upgrade, I'm wondering if I forgot to bump a version somewhere that may have prevented cache busting on static assets which could cause the interface issues I'm seeing as well as the tinyMCE issues identified in this issue

Also, are you seeing any JS errors in the console

Can you also check out this temp site and let me know if you're seeing the issue there: 

http://lonely-oyster.w5.poopy.life/wp-admin/post-new.php?post_type=course
user: `demo`
pass: `ZyS8gH2yG59h`

This temp site will self destruct in 7 days

**Comment by thomasplevy** [comment]
@RajeebTheGreat any update on this?

**Comment by RajeebTheGreat** [comment]
Hi @thomasplevy,

I was unable to replicate this on the temp site. I did reset my local installation and tested again. The issue persists but I think this might have something to do with my local setup.

You can close this issue.
