### ISSUE TITLE
[Access Plan] JS Access Plan Limit error

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#780]
```
Uncaught TypeError: Cannot read property 'access_plan_limit' of undefined
    at window.llms.metabox_product.has_plan_limit_been_reached (llms-metabox-product.js:484)
    at llms-metabox-product.js:113
```

The window.llms.product object is getting set late because of which the access plan limit isn't found until later and this throws an error. 

FYI, it doesn't affect saving or any other functionality.

**Comment by thomasplevy** [comment]
@actual-saurabh saw this once and closed, I saw it once and reopened, neither of us have seen it again since. If we can't get more reports of it by the May scrub we'll close this.

**Comment by eri-trabiccolo** [comment]
Ah yeah, I've recently bumped into this, and I've been able to reproduce it when activating the Yoast SEO plugin, for example, not sure exactly why.

Anyway a simple PR to fix this is coming.
As admin scripts are printed at `admin_print_footer_scripts` with priority 10, would be enough to fire `localize_js` here:
https://github.com/gocodebox/lifterlms/blob/3.30.2/includes/admin/post-types/meta-boxes/class.llms.meta.box.product.php#L37
 at 9
