### ISSUE TITLE
[Templates] [Checkout] Empty field value generates PHP Notice

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#782]
On https://github.com/gocodebox/lifterlms/blob/master/templates/checkout/form-confirm-payment.php#L40, if a field has an empty value, the following notice is displayed:

**Notice**: Undefined index: value in **/path/to/wp-content/plugins/lifterlms/templates/checkout/form-confirm-payment.php** on line **40**

Changing this line to the following fixes this:

```php
<span class="llms-field-display <?php echo $field['id']; ?>"><?php echo ! empty($field['value']) ? $field['value']: ''; ?></span><?php echo $field['last_column'] ? '<br>' : ' '; ?>
```

**Comment by thomasplevy** [comment]
@nrherron92 submit that PR please!
