### ISSUE TITLE
Upload media image background color issue in customizer

### ISSUE THREAD

**Issue by Swapnildhanrale** [gocodebox/lifterlms#784]
### 1. Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced
+ Include screenshots where applicable
+ Record a video if possible

### 2. Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)

### 3. Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

### 4. Error Messages / Logs

+ Include any relevant error messages or log files

### 5. System Report

Many issues are the result of theme or plugin conflicts. Including information about your WordPress version, your plugins (and their versions), and your theme (and its version) will help us resolve conflicts.
We've created the [LifterLMS System Report](https://lifterlms.com/docs/how-to-use-the-lifterlms-system-report/) to help with this

### 6. Browser, Device, and Operating System

+ If the bug occurs in a specific browser, it is very useful in helping us track down the specifics using this information (as well as version numbers).

**Comment by Swapnildhanrale** [comment]
Steps to Reproduce:
1. Add lifterLMS plugin
2. Go to customize in Astra theme
3. Got in layout >Header>Site Identity
4. you can see the color issue
As shown in the screenshot below.
Screenshot Url - http://tinyurl.com/y2lg23ar

**Comment by thomasplevy** [comment]
@Swapnildhanrale sorry for the delay here and thanks for reporting this. This is resolved and you'll see the fix in 3.30.1.
