### ISSUE TITLE
Advance Quizzes Reorder sorted Alphanumerically 

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#794]
Advance Quizzes Reorder sorted Alphanumerically 

EDIT: Redacted private URL

**Comment by thomasplevy** [comment]
### Recreation Steps

+ Create a reorder question with 10+ choices
+ Reorder them
+ Reload the builder 

### Expectation

+ Will be displayed in the saved order

### Actual

+ Choices will be visually ordered by their iterator as 1, 10, 11, 2, 3, etc...

### Issue

+ Core sorts choices alphabetically b/c the core choice iterators are alpha characters (A,B,C,...)
+ AQ customizes the iterator to be numeric (1,2,3...) but does not customize the sorting functionality

**Comment by thomasplevy** [comment]
Problem line: https://github.com/gocodebox/lifterlms/blob/master/includes/models/model.llms.question.php#L204
