### ISSUE TITLE
gulp task file names contain ":" colon character

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#816]
Some of the file names in `/gulpfile.js/tasks/` contain the `:` colon character, which is not allowed in a file name on Windows OS. Can we use `-`, `_` or `~` instead?

The following characters can not be used in file or directory names on Windows:
`/ ? < > \ : * | "`

I would be happy to make the changes and submit a pull request.

**Comment by thomasplevy** [comment]
@pondermatic I was not aware of this sorry

I'd prefer to use the hyphen `-` as the separator for task and file names here and will welcome the PR

However, I've been working on refactoring gulp tasks out of the core and into an package [lifterlms-lib-tasks](https://github.com/gocodebox/lifterlms-lib-tasks).

This has been done to simplify structures and tasks across all LifterLMS projects (add-ons and the handful of other free plugins we have). A number of the tasks used in the core builds are tasks from that package. I'll open another issue over there as well to help fully resolve this.

Thanks

**Comment by thomasplevy** [comment]
closed by #904
