### ISSUE TITLE
PHP_CodeSniffer progress

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#822]
**Is your feature request related to a problem? Please describe.**
If it takes a long time for PHP_CodeSniffer to run (on a slow machine), it can look like it is hung up because it defaults to running quietly.

**Describe the solution you'd like.**
PHP_CodeSniffer can show its progress, much like PHPUnit does. There are two different ways to enable this feature:

1. change the default behavior `phpcs --config-set show_progress 1`
2. enable in command line with the `-p` argument

I would be happy to may one of these changes to `composer.json` and submit a pull request.

**Comment by thomasplevy** [comment]
Command line on the composer command is probably simplest (and will start working immediately without having to run an `composer update`
