### ISSUE TITLE
Allow restricting\binding Coupons\Vouchers for 'draft' of 'future' posts

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#831]
**Problem I face.**
I have a course in draft, or that is scheduled to be published e.g. tomorrow, but I cannot setup a coupon for it until it'll become published.

**Solution I'd like**
I want to be able to set-up a coupon and restrict it to a "future" course (draft or scheduled),
so that it'll be available as soon as the course it'll be published.

It might happen that you need a course to be published in the future, e.g. tomorrow, but you still want to set up coupons and vouchers related to it now, so that when it'll be the time to launch your new course you don't need to also go to create/restrict a coupon, or create/bind a voucher to it, you just have to create your course - or you just have to do nothing if you scheduled the course publication.

**Aalternatives I've considered**
As an alternative one can always publish the course, then set-up coupons and vouchers to it related and then put back the course in draft or schedule it.

**Comment by eri-trabiccolo** [comment]
I've proposed a possible implementation in #832

**Comment by thomasplevy** [comment]
I see the problem and I like your solution in #832 (with a few adjustments I've requested on the PR to make the changes more generally useful for other future situations where we may want to use a post lookup for other post statuses).
Thanks!
