### ISSUE TITLE
LifterLMS will keep engagement e-mails after a refund

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#839]
### Expected Behavior

+ After refund, email engagements for that student stop. 

### Actual Behavior

+ LifterLMS keeps engagement e-mails after a refund

**Comment by thomasplevy** [comment]
Related #290

**Comment by thomasplevy** [comment]
Ticket needs follow up upon resolution: HS#85934

**Comment by nrherron92** [comment]
HS-133558
