### ISSUE TITLE
Extensible Methods in Shortcode Classes

### ISSUE THREAD

**Issue by andrewvaughan** [gocodebox/lifterlms#841]
Hey all,

As a practice, it's generally better to use `protected` in classes rather than `private` to allow for extensibility.  In this particular case, I need to extend the `[lifterlms_courses]` shortcode [class](https://github.com/gocodebox/lifterlms/blob/master/includes/shortcodes/class.llms.shortcode.courses.php) to provide better/more flexible taxonomy queries.

While some methods are `protected`, importantly, the `get_tax_query` method is private, preventing me from extending the shortcode's functionality.

This is an easy fix, and I will follow this up immediately with a PR.  Please consider reviewing your standards for `private` vs. `protected` to empower your customers to extend classes for their needs!

**Comment by thomasplevy** [comment]
I'll merge this in for our next release.

I'm not going to go through and start refactoring every class to exclusively use protected methods over private, however, I see your point and will take this into consideration for new code in the future. If you find a private method you need to overload or use just let us know or open a new PR and we'll handle them as needed.

Thanks
