### ISSUE TITLE
Student Dashboard endpoints (lost password, order history, & edit account) 404 with WooCommerce 3.6 or later

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#849]
### Reproduction Steps

+ Install LifterLMS and WooCommerce 3.6 or later
+ Access the "lost password" endpoint on the LifterLMS student dashboard

### Expected Behavior

+ Should be able to reset password via the password reset form

### Actual Behavior

+ A 404 page is encountered

### Error Messages / Logs

N/A

### System Information

LifterLMS (any version) and WooCommerce 3.6 or later

**Comment by thomasplevy** [comment]
Due to changes in WC 3.6 ([commit](https://github.com/woocommerce/woocommerce/commit/a0f47fb429266e1d55fbe5f77db928e478682973)) any WC endpoint accessed outside of the WC account page will 404.

Shared LifterLMS endpoints will no longer be accessible as a result

**Comment by thomasplevy** [comment]
Above commit resolves this in a somewhat acceptable manner. I'd really like a filter in WC that would allow us to not lie to WC via the `woocommerce_is_account_page` filter.

Will adjust this based on results of this issue in the WC GitHub: https://github.com/woocommerce/woocommerce/issues/23622

**Comment by eri-trabiccolo** [comment]
This PR of yours @thomasplevy has been accepted:
https://github.com/woocommerce/woocommerce/pull/23660

that's the filter we actually needed, and it will also solve #1037!
