### ISSUE TITLE
Fix spelling error in LLMS_Database_Query abstract method `preprare_query()`

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#859]
The abstract method `preprare_query` should be spelled `prepare_query`

We cannot simply rename the function without causing potential with add-ons (known and unknown).

We cannot deprecate it by replacing the abstract method with a concrete method that calls a replacement abstract method as per the comment here: https://github.com/gocodebox/lifterlms/pull/722#issuecomment-446750779

I'm not entirely certain how to fix this issue long term or even short term.

See discussion in closed PR #722

**Comment by BurlesonBrad** [comment]
sending beer 🍺

**Comment by yojance** [comment]
@thomasplevy 

Would something like this work?

```php
<?php

class LLMS_Database_Query {

	// Magic method.
	public function __call( $name, $arguments ) {

		// Misspelled method.
		if ( 'preprare_query' === $name ) {
			return call_user_func_array( [ $this, 'prepare_query' ], $arguments );
		}
	}

	// Renamed method.
	public function prepare_query( $param ) {}
}

**Comment by thomasplevy** [comment]
@yojance I believe it might, good thinking!
