### ISSUE TITLE
[Reporting] Student courses table is sortable by completion date in UI but no sorting logic exists

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#892]
The completion date column is sortable in UI here https://github.com/gocodebox/lifterlms/blob/3.33.2/includes/admin/reporting/tables/llms.table.course.students.php#L400-L404 but there's no code to support sorting by enrollment here: https://github.com/gocodebox/lifterlms/blob/3.33.2/includes/admin/reporting/tables/llms.table.course.students.php#L273-L307

**Comment by thomasplevy** [comment]
Duplicate of #760
