### ISSUE TITLE
Should LLMS_Post_Model property update return false if the previous value equals the new one?

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#909]
At the moment when updating an llms post model property which **is** a post_meta, if the new value equals the old value the `set` method return `false` (`set_bulk` can return a `WP_Error`).

This desn't happen if we update a model property which **is not** a post_meta, e.g. the `content` or the `title`. This is not consistent given the fact that we use the same "interface".

Ideally I should be able to use that method without concerning about the internal structure of that model, and I would expect a consistent behavior.

What do you think if we still return `true` when there was nothing to update?

**Comment by thomasplevy** [comment]
> At the moment when updating an llms post model property which is a post_meta, if the new value equals the old value the set method return false (set_bulk can return a WP_Error).

This stems from using `update_post_meta()`:

> returns true on success and false on failure. NOTE: If the meta_value passed to this function is the same as the value that is already in the database, this function returns false.

Source: https://codex.wordpress.org/Function_Reference/update_post_meta

> This desn't happen if we update a model property which is not a post_meta, e.g. the content or the title. This is not consistent given the fact that we use the same "interface".
> 
> Ideally I should be able to use that method without concerning about the internal structure of that model, and I would expect a consistent behavior.

This inconsistency is an oversight. Regardless of the database table or update function used it should have the same behavior. You're correct.

> What do you think if we still return true when there was nothing to update?

I think that we should make this change however the `LLMS_Abstract_Post_Model` class is used by almost every add-on and the `set()` method from the class is used all over the core (and add-ons). If we had 100% test coverage across every codebase it'd be pretty trivial to weigh the consequences of this change. But we don't have 100% test coverage so we'll need to ensure that we don't break anything by changing this by inspecting the codebase (and add-ons) manually.

My (kind of educated) guess is that this wouldn't really affect much at all but I don't know that for certain.

This is really a question concerning the REST API than anything else and for now I think devs implementing post updates through the REST API need to know this is how it works and adjust their integrations accordingly (which shouldn't be too complicated for them to do).

We'll tackle this over time.

**Comment by eri-trabiccolo** [comment]
wip in https://github.com/eri-trabiccolo/lifterlms/tree/issue/909
