### ISSUE TITLE
Bootstrap 4 navbar mobile misbehaving when lifterLms is active

### ISSUE THREAD

**Issue by Guillaume-Tnk** [gocodebox/lifterlms#922]
Bug with mobile menu, not staying open when lifterlms is active with understrap theme

### Reproduction Steps

- Install understrap theme [https://understrap.com/](url)
- Install and activate understrap child theme [https://understrap.com/understrap-child-themes/](url)
- Create some pages
- Create a menu and ad pages to it
- Install and activate lifterLms
- view website in mobile view with dev tools
- Click menu toggle

### Expected Behavior

menu to open/close on click on mobile as it should

### Actual Behavior

Menu rapidly close on mobile when clicked

View video below
[https://youtu.be/O0DpAmoZz_c](url)

**Comment by thomasplevy** [comment]
@Guillaume-Tnk any idea what piece of LifterLMS code is causing the issue?

**Comment by Guillaume-Tnk** [comment]
Unfortunately no, I just know it's coming from LifterLms because when I deactivate the lifterLms plugin, the problem disappears.
To be sure, I set a new WordPress install with just the theme and lifterLms nothing else as you can see from my video and the problem is there.

**Comment by eri-trabiccolo** [comment]
@thomasplevy collapse(.min).js

**Comment by Guillaume-Tnk** [comment]
Any quick fix to get the menu to behave appropriately?

**Comment by thomasplevy** [comment]
@Guillaume-Tnk 

You could try de-enqueing the offending conflicts in your child theme's functions.php file.

I don't have a timeline for fixing a theme conflict I've just been made aware of but I'd be very happy to have your help working on this.

Otherwise you'll have to wait until my and @eri-trabiccolo capacity becomes freed up to start slogging away on this issue backlog, which realistically won't be until Q1 2020. Sorry :-(

**Comment by cryptexvinci** [comment]
@Guillaume-Tnk 

You can insert this snippet to dequeue the collapse js

`add_action( 'wp_enqueue_scripts', 'um_theme_remove_collapse_js', 100 );

if ( ! function_exists( 'um_theme_remove_collapse_js' ) ) {
    function um_theme_remove_collapse_js() {
       wp_dequeue_script( 'collapse' );
    }
}`

**Comment by Guillaume-Tnk** [comment]
This is working! Thank you very much.

**Comment by eri-trabiccolo** [comment]
https://wordpress.org/support/topic/lifterlms-incompatible-with-arilewp-theme/

**Comment by eri-trabiccolo** [comment]
@thomasplevy maybe candidate for v4?

**Comment by thomasplevy** [comment]
Yea good idea, I'll have a look at this later today or tomorrow.
