### ISSUE TITLE
The new update of Google Chrome cause a glitch in the course edit page.

### ISSUE THREAD

**Issue by SaeedMasri** [gocodebox/lifterlms#927]
Hello,
I think the new update of Google Chrome cause a glitch in the course edit page. It happens when you open more than tab of the course settings or with a long content in your course page, an overlapping occurs like the screen shot:

![bug](https://user-images.githubusercontent.com/44070679/64900986-4655a580-d695-11e9-8250-dd6aa8c112a8.png)

Chrome version 77.0.3865.75 (Official Build) (64-bit).
The overlapping issue doesn't present in Firefox browser.
Also see:
https://wordpress.org/support/topic/several-trouble-after-updating/

**Comment by thomasplevy** [comment]
@SaeedMasri This isn't actually a bug in LifterLMS, it's a bug in Chrome (from what I can find).

Here's the Chrome bugs: 

https://bugs.chromium.org/p/chromium/issues/detail?id=1003556
https://bugs.chromium.org/p/chromium/issues/detail?id=1002969

And he's the issue in the Gutenberg project: https://github.com/WordPress/gutenberg/issues/17406

There's a potential workaround with a bit of PHP / CSS that could solve this for you immediately.

I'm not going to attempt to resolve this within LifterLMS but thanks for bringing it to my attention.

**Comment by thomasplevy** [comment]
@SaeedMasri it looks like this is actually already fixed with the Gutenberg plugin. You can install the latest plugin to fix as a holdover to what I imagine will be included in a future WP release. It looks like the Chrome bugs are already fixed on Chrome 78 (dev) and slated for release on Oct 22

**Comment by SaeedMasri** [comment]
I'm using Firefox until then, thanks!
