### ISSUE TITLE
[Membership Restriction] Membership restriction IDs don't save

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#938]
Saving Membership on restrictions doesn't work. On refreshing the editor, the `_llms_is_restricted` field saves but not the membership IDs at `_llms_restricted_levels`.

I tested this and found that this line sets the value to `false`

https://github.com/gocodebox/lifterlms/blob/09c3353aaeb2a8785868f2cf1cf67c4146e94068/includes/abstracts/abstract.llms.admin.metabox.php#L398

Since membership IDs are arrays, the filter input validation rejects the value. Changing it to:

```
$val = llms_filter_input( INPUT_POST, $field['id'], FILTER_DEFAULT, FILTER_REQUIRE_ARRAY );
```
saves the restrictions but breaks other stuff.

**Comment by actual-saurabh** [comment]
Maybe, the filter could be set conditionally based on the type of field?

**Comment by eri-trabiccolo** [comment]
Yeah, something similar to what I did here -> https://github.com/gocodebox/lifterlms/pull/923/files#diff-fe4c4aca8d1a4c6fbfc2abba17ef7309R402

maybe we can generalize it better, introducing two fields 'params' such as:
`filter_input` (default to `FILTER_SANITIZE_STRING`)
`filter_input_flags` (default to `array()`)
