### ISSUE TITLE
Modify to accommodate WP 5.0 and earlier

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#942]
https://github.com/gocodebox/lifterlms/blob/09c3353aaeb2a8785868f2cf1cf67c4146e94068/includes/abstracts/abstract.llms.post.model.php#L1097

See discussion in Slack: https://teamcodebox.slack.com/archives/C05476CSR/p1569299100013500

We can pretty easily modify to use pre 5.1 functions instead of bumping support to WP 5.1 or later

**Comment by eri-trabiccolo** [comment]
Let's go with `if ( ! empty( $error->errors ) )` then.

**Comment by eri-trabiccolo** [comment]
We actually have occurrences of `has_errors()` in the rest-api code too.
I'm going to make a PR there too, and update those PRs which make use of it: I guess we have to support the same WP version throughout the codebase...
