### ISSUE TITLE
Sales Reporting page does not hold filter specification

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#956]
### Reproduction Steps

+ Go to LifterLMS->Reporting->Sales
+ Select Toggle Filters
+ Choose to sort by either a Student, Membership, or Course and Apply Filter
+ Statistics do not change from total sales
+The bar graph sometimes changes color and date but does not reflect correct pricing.

No Filter: https://imgur.com/ruaR7SJ
Filter by Course: https://imgur.com/r92p62f
Filtered by Course: https://imgur.com/h3JEnFx (no change)

### Expected Behavior

+ Sales information should correctly reflect sales for the month, week, year, of filtered courses or memberships.

### Actual Behavior

+ The numbered statistics above the bar graph remain the same. The bar graph changes based on filter but only date and bar color.

### Error Messages / Logs

+ Include any relevant error messages or log files

PHP Warning:  Invalid argument supplied for foreach() in wp-content/plugins/lifterlms/templates/admin/reporting/nav-filters.php on line 82

**Comment by thomasplevy** [comment]
@nrherron92 I believe we have an open support request about this issue. Could you update the user and let them know this is resolved in 3.36.3 (now available)
