### ISSUE TITLE
Conflict with CartFlows (which requires WooCommerce): visiting a CartFlows checkout page results in 404.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#976]
### Reproduction Steps

+ Install and activate WooCommerce and create a product;
+ Install and activate CartFlows (https://wordpress.org/plugins/cartflows/);
+ Create a flow;
+ Setup CartFlows Step Checkout (Woo) so to bind it to a WooCommerce product;
+ Visit the just created checkout page.

### Expected Behavior

I should see the checkout page I've just created.

### Actual Behavior

I'm brought to the 404 page.

### Error Messages / Logs

n/a

### System Information
<details>

```
--- THEME ---
Name: LifterLMS LaunchPad
Version: 2.4.6
Themeuri: https://lifterlms.com/launchpad/
Authoruri: https://gocodebox.com
Template:
Child Theme: No

--- PLUGINS ---
CartFlows: 1.3.0

LifterLMS: 3.36.3

WooCommerce: 3.7.1
  
```

</details>

### SOME OTHER INFO/THOUGHS

This issue has been introduced with:
https://github.com/gocodebox/lifterlms/commit/c7e7cc1d5e76323e9a92b945e822be6985f1a59a

That plugin runs its query alteration at priority 10.
Before the commit above, the CartFlows callback ran after our one, as you can image, now, it runs before. The issue, although, **doesn't regard our query alteration** as, in CartFlows checkout pages, none of our conditions to alter the query are matched.

I've actually found the main responsible of this issue to be this line:
https://github.com/gocodebox/lifterlms/blob/3.36.3/includes/class.llms.query.php#L238

My guess is that the callbacks re-sorting, which follows a callback removal, when called from within the callback to be removed (hence **within the same hook execution**) is the cause of the issue. Although I've been not able to track 

I guess the reason for that is to avoid altering the query twice?!
So instead of removing the callback we can use a static variable to be sure we perform the actual callback logic only once.

I'm going to propose a PR following this logic.

**Comment by eri-trabiccolo** [comment]
Reported also here:
https://wordpress.org/support/topic/issue-due-to-priority-added-to-pre_get_posts/

**Comment by thomasplevy** [comment]
Fix one conflict create 5 new ones. Programming is fun.
