### ISSUE TITLE
Add a filter to allow customization of the frequency of `LLMS_Sessions::end_idle_sessions()`

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#988]
**Code in question**

https://github.com/gocodebox/lifterlms/blob/914f43d5857348216022c3e838cfbe265410fd0d/includes/class-llms-sessions.php#L59-L62

**Is your feature request related to a problem? Please describe.**

Currently it's not possible to customize the frequency with this cleanup action is run on a background process.

**Describe the solution you'd like**

Add a filter to the "every_five_mins" cron interval so that a custom interval could be used in its place.

**Describe alternatives you've considered**

Removing the action and re-adding it on a different hook but this is kind of wonky and may not actually work since the action is added via a class method instead using `array( $this, ... )`. I didn't setup a test case but I don't think it'll work.

**Comment by thomasplevy** [comment]
See ticket # 104523

**Comment by eri-trabiccolo** [comment]
Why shouldn't it? That's a singleton, so 
`remove_action( 'llms_end_idle_sessions', array( LLMS_Sessions::instance(), 'end_idle_sessions' ) );`
will remove the action, and it can be added to another hook, of course the removal must happen after the `LLMS_Sessions` has been instantiated. Am I wrong?

**Comment by thomasplevy** [comment]
@eri-trabiccolo ah yea... I think you're right that probably would work. I looked at that solution real quick. It still needs as a filter anyway though. It'll be far less customization code to filter it than to remove the action and add it back in. There will still be a weird cronjob running to that'll trigger a non-action if you go the removal route. Adding a filter needs to happen regardless, I think.

**Comment by eri-trabiccolo** [comment]
Ah yeah the filter hook way is better, I thought you meant the `remove/add` thing as a temporary workaround to provide while we implement and deploy the filter solution.
