### ISSUE TITLE
Some (most of) client side events are not tracked when using some themes, e.g. LaunchPad

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#992]
### Reproduction Steps
This can be reproduced with a lot of client side events, e.g. page.exit, addon event e.g. video.*, but it's much more evident whit av events.

+ Activate the LaunchPad theme
+ av addon enabled
+ As logged in student visit e.g. a lesson with a video
+ play a video, pause the video, do whatever you know should log an event
+ complete the video
+ complete the lesson (with the mark complete button)

### Expected Behavior
+ I'd expect the lesson to show as completed
+ I'd expect the reporting screen user/lesson showing the video progression at 100%

### Actual Behavior

+ Lesson is not set as completed
+ Video progression is 0%

I've spent quite a lot time trying to figure out what was happening there.
The thing is "quite" simple, once you know it :P 
First of all with a proper tool, e.g. chrome dev tools -> Application -> Cookies, but even better, in this case, Firefox dev tools -> Storage -> Cookies (better json readability), you can see that as soon as you load the page the `llms-tracking` cookie is set, but it immediately disappears (a). Then when a client side event occurs, and is "stored" in the cookie, the `llms-tracking` cookie of course "re-appears" but this time without the `nonce` item set. That's because the `nonce` is ONLY set into the cookie at init:
https://github.com/gocodebox/lifterlms/blob/3.37.1/assets/js/app/llms-tracking.js#L26

So that when the cookie is evaluated by the event recorder the `nonce` field is not there anymore and it doesn't record anything
https://github.com/gocodebox/lifterlms/blob/3.37.1/includes/class-llms-events.php#L416

although it clears the cookie:
https://github.com/gocodebox/lifterlms/blob/3.37.1/includes/class-llms-events.php#L430

(a) With the LaunchPad theme I've found that the reason for the cookie disappearing is due to a request sent to the server, after the tracking class has been init via js. I've analyzed the `$_SERVER` in the method `LLMS_Events::store_cookie()` when the issue occurred and found this to be the "responsible" request `[REQUEST_URI] => /wp-content/themes/lifterlms-launchpad/assets/public/css/style.css.map`.
(in fact if I remove `/*# sourceMappingURL=style.css.map */` from the LaunchPad style I fix this issue for the LaunchPad theme)
This "partial" cookie is stored here:
https://github.com/gocodebox/lifterlms/blob/3.37.1/includes/class-llms-events.php#L424
and then cleared here (as aforementioned):
https://github.com/gocodebox/lifterlms/blob/3.37.1/includes/class-llms-events.php#L430

### Solution
@thomasplevy
Since I don't think we can keep track of all the client-server communication and exclude this or this other I think we just have to make sure the `nonce` is always an `llms-tracking` cookie field. E.g. we could store the nonce (`store.set( 'nonce', settings.nonce );`) every time an event is added:
https://github.com/gocodebox/lifterlms/blob/3.37.1/assets/js/app/llms-tracking.js#L64

### Error Messages / Logs

n/a

### System Information

LifterLMS 3.37.1
LifterLMS Advanced Videos 1.0.0-beta.6

### Browser, Device, and Operating System Information
n/a

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Thanks for the research and finally figuring out what's actually going on here.

As far as the SiteGround staging issue is concerned please let me know what the results of the communication with them are regarding the support conversations you've had separately (or here, whatever).

As to fix the issue, since it is a LP issue I'd be hesitant to fix it in the core but you've also identified the issue being caused by a separate plugin as well. So I believe your proposed solution:

> E.g. we could store the nonce (store.set( 'nonce', settings.nonce );) every time an event is added

Is pretty solid. Do you want to write and submit the PR?

**Comment by eri-trabiccolo** [comment]
Yes it's not an LP issue, to me it's a llms issue that LP highlights.
I'm going to submit a PR.
