### ISSUE TITLE
Twenty Twenty: Theme header and footer displayed in the single certificates

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#999]
### Reproduction Steps

+ Visit a single certificate page using the Twenty Twenty theme

### Expected Behavior

+ I expect to see the certificate with no theme header and footer.

### Actual Behavior

+ I see the certificate page with the theme header and footer 

Also, do you think that even the body background should be "stripped" in the single certificate?
I think so... 

### Error Messages / Logs

n/a

### System Information

n/a

### Browser, Device, and Operating System Information

n/a

**Comment by thomasplevy** [comment]
Header and footer can be hidden with CSS `display:none;` I wish there was a better way but I haven't found one since there's no simple standardized way to to add footers and headers to a theme.

> Also, do you think that even the body background should be "stripped" in the single certificate?

Yes, we should override it to white if possible.
